// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: provider/envvars/v1/envvars.proto

package envvarsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v11 "github.com/ocelhq/ocel/pkg/proto/common/bindings/v1"
	v1 "github.com/ocelhq/ocel/pkg/proto/common/environment/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Coordinate) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Coordinate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Coordinate) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ValueMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinate    *Coordinate            `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Target        *Coordinate            `protobuf:"bytes,5,opt,name=target,proto3,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueMetadata) Reset() {
	*x = ValueMetadata{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueMetadata) ProtoMessage() {}

func (x *ValueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueMetadata.ProtoReflect.Descriptor instead.
func (*ValueMetadata) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{1}
}

func (x *ValueMetadata) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *ValueMetadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ValueMetadata) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ValueMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ValueMetadata) GetTarget() *Coordinate {
	if x != nil {
		return x.Target
	}
	return nil
}

type VersionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionEntry) Reset() {
	*x = VersionEntry{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionEntry) ProtoMessage() {}

func (x *VersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionEntry.ProtoReflect.Descriptor instead.
func (*VersionEntry) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{2}
}

func (x *VersionEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VersionEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SetValueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tier            v1.Tier                `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Coordinate      *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Value           string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpectedVersion *int64                 `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{3}
}

func (x *SetValueRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *SetValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *SetValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetValueRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type SetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueResponse) Reset() {
	*x = SetValueResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResponse) ProtoMessage() {}

func (x *SetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResponse.ProtoReflect.Descriptor instead.
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{4}
}

func (x *SetValueResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          v1.Tier                `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValuesRequest) Reset() {
	*x = ListValuesRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValuesRequest) ProtoMessage() {}

func (x *ListValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValuesRequest.ProtoReflect.Descriptor instead.
func (*ListValuesRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{5}
}

func (x *ListValuesRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *ListValuesRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ListValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ValueMetadata       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValuesResponse) Reset() {
	*x = ListValuesResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValuesResponse) ProtoMessage() {}

func (x *ListValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValuesResponse.ProtoReflect.Descriptor instead.
func (*ListValuesResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{6}
}

func (x *ListValuesResponse) GetValues() []*ValueMetadata {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          v1.Tier                `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Reveal        bool                   `protobuf:"varint,3,opt,name=reveal,proto3" json:"reveal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{7}
}

func (x *GetValueRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *GetValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *GetValueRequest) GetReveal() bool {
	if x != nil {
		return x.Reveal
	}
	return false
}

type GetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      *ValueMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{8}
}

func (x *GetValueResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetValueResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RevealValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          v1.Tier                `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Cells         []*Coordinate          `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealValuesRequest) Reset() {
	*x = RevealValuesRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealValuesRequest) ProtoMessage() {}

func (x *RevealValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealValuesRequest.ProtoReflect.Descriptor instead.
func (*RevealValuesRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{9}
}

func (x *RevealValuesRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *RevealValuesRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *RevealValuesRequest) GetCells() []*Coordinate {
	if x != nil {
		return x.Cells
	}
	return nil
}

type RevealValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*RevealedValue       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealValuesResponse) Reset() {
	*x = RevealValuesResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealValuesResponse) ProtoMessage() {}

func (x *RevealValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealValuesResponse.ProtoReflect.Descriptor instead.
func (*RevealValuesResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{10}
}

func (x *RevealValuesResponse) GetValues() []*RevealedValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type RevealedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealedValue) Reset() {
	*x = RevealedValue{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealedValue) ProtoMessage() {}

func (x *RevealedValue) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealedValue.ProtoReflect.Descriptor instead.
func (*RevealedValue) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{11}
}

func (x *RevealedValue) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RevealedValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteValueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tier            v1.Tier                `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Coordinate      *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	ExpectedVersion *int64                 `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteValueRequest) Reset() {
	*x = DeleteValueRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueRequest) ProtoMessage() {}

func (x *DeleteValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteValueRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteValueRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *DeleteValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *DeleteValueRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type DeleteValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValueResponse) Reset() {
	*x = DeleteValueResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueResponse) ProtoMessage() {}

func (x *DeleteValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueResponse.ProtoReflect.Descriptor instead.
func (*DeleteValueResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteValueResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SetReferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          v1.Tier                `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Target        *Coordinate            `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReferenceRequest) Reset() {
	*x = SetReferenceRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceRequest) ProtoMessage() {}

func (x *SetReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceRequest.ProtoReflect.Descriptor instead.
func (*SetReferenceRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{14}
}

func (x *SetReferenceRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *SetReferenceRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *SetReferenceRequest) GetTarget() *Coordinate {
	if x != nil {
		return x.Target
	}
	return nil
}

type SetReferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReferenceResponse) Reset() {
	*x = SetReferenceResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceResponse) ProtoMessage() {}

func (x *SetReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceResponse.ProtoReflect.Descriptor instead.
func (*SetReferenceResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{15}
}

func (x *SetReferenceResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListReferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          v1.Tier                `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferencesRequest) Reset() {
	*x = ListReferencesRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferencesRequest) ProtoMessage() {}

func (x *ListReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferencesRequest.ProtoReflect.Descriptor instead.
func (*ListReferencesRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{16}
}

func (x *ListReferencesRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *ListReferencesRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

type ListReferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	References    []*Coordinate          `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferencesResponse) Reset() {
	*x = ListReferencesResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferencesResponse) ProtoMessage() {}

func (x *ListReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferencesResponse.ProtoReflect.Descriptor instead.
func (*ListReferencesResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{17}
}

func (x *ListReferencesResponse) GetReferences() []*Coordinate {
	if x != nil {
		return x.References
	}
	return nil
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          v1.Tier                `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{18}
}

func (x *ListVersionsRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *ListVersionsRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*VersionEntry        `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{19}
}

func (x *ListVersionsResponse) GetVersions() []*VersionEntry {
	if x != nil {
		return x.Versions
	}
	return nil
}

type SetBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Tier          v1.Tier                `protobuf:"varint,2,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Binding       *v11.Binding           `protobuf:"bytes,4,opt,name=binding,proto3" json:"binding,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBindingRequest) Reset() {
	*x = SetBindingRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBindingRequest) ProtoMessage() {}

func (x *SetBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBindingRequest.ProtoReflect.Descriptor instead.
func (*SetBindingRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{20}
}

func (x *SetBindingRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SetBindingRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *SetBindingRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SetBindingRequest) GetBinding() *v11.Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *SetBindingRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type SetBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBindingResponse) Reset() {
	*x = SetBindingResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBindingResponse) ProtoMessage() {}

func (x *SetBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBindingResponse.ProtoReflect.Descriptor instead.
func (*SetBindingResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{21}
}

func (x *SetBindingResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RemoveBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Tier          v1.Tier                `protobuf:"varint,2,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBindingRequest) Reset() {
	*x = RemoveBindingRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBindingRequest) ProtoMessage() {}

func (x *RemoveBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBindingRequest.ProtoReflect.Descriptor instead.
func (*RemoveBindingRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveBindingRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *RemoveBindingRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *RemoveBindingRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RemoveBindingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBindingResponse) Reset() {
	*x = RemoveBindingResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBindingResponse) ProtoMessage() {}

func (x *RemoveBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBindingResponse.ProtoReflect.Descriptor instead.
func (*RemoveBindingResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveBindingResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListBindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Tier          v1.Tier                `protobuf:"varint,2,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindingsRequest) Reset() {
	*x = ListBindingsRequest{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindingsRequest) ProtoMessage() {}

func (x *ListBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListBindingsRequest) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{24}
}

func (x *ListBindingsRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ListBindingsRequest) GetTier() v1.Tier {
	if x != nil {
		return x.Tier
	}
	return v1.Tier(0)
}

func (x *ListBindingsRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ListBindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*BindingSummary      `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindingsResponse) Reset() {
	*x = ListBindingsResponse{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindingsResponse) ProtoMessage() {}

func (x *ListBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListBindingsResponse) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{25}
}

func (x *ListBindingsResponse) GetBindings() []*BindingSummary {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type BindingSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          v11.BindingType        `protobuf:"varint,2,opt,name=type,proto3,enum=common.bindings.v1.BindingType" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Properties    []*PropertyShape       `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindingSummary) Reset() {
	*x = BindingSummary{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingSummary) ProtoMessage() {}

func (x *BindingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindingSummary.ProtoReflect.Descriptor instead.
func (*BindingSummary) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{26}
}

func (x *BindingSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BindingSummary) GetType() v11.BindingType {
	if x != nil {
		return x.Type
	}
	return v11.BindingType(0)
}

func (x *BindingSummary) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BindingSummary) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BindingSummary) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BindingSummary) GetProperties() []*PropertyShape {
	if x != nil {
		return x.Properties
	}
	return nil
}

type PropertyShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JsonType      string                 `protobuf:"bytes,2,opt,name=json_type,json=jsonType,proto3" json:"json_type,omitempty"`
	List          bool                   `protobuf:"varint,3,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyShape) Reset() {
	*x = PropertyShape{}
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyShape) ProtoMessage() {}

func (x *PropertyShape) ProtoReflect() protoreflect.Message {
	mi := &file_provider_envvars_v1_envvars_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyShape.ProtoReflect.Descriptor instead.
func (*PropertyShape) Descriptor() ([]byte, []int) {
	return file_provider_envvars_v1_envvars_proto_rawDescGZIP(), []int{27}
}

func (x *PropertyShape) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropertyShape) GetJsonType() string {
	if x != nil {
		return x.JsonType
	}
	return ""
}

func (x *PropertyShape) GetList() bool {
	if x != nil {
		return x.List
	}
	return false
}

var File_provider_envvars_v1_envvars_proto protoreflect.FileDescriptor

const file_provider_envvars_v1_envvars_proto_rawDesc = "" +
	"\n" +
	"!provider/envvars/v1/envvars.proto\x12\x13provider.envvars.v1\x1a\x1bbuf/validate/validate.proto\x1a'common/environment/v1/environment.proto\x1a!common/bindings/v1/bindings.proto\"\xee\x03\n" +
	"\n" +
	"Coordinate\x125\n" +
	"\x04slug\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12\xca\x01\n" +
	"\x06folder\x18\x02 \x01(\tB\xb1\x01\xbaH\xad\x01\xba\x01\x90\x01\n" +
	"\x1eenvvars.coordinate.folder.root\x12a\"/\" is the project root, which is what an unbound app already reads; leave the folder off instead\x1a\vthis != '/'r\x172\x15^(/[^/#[:cntrl:]]+)*$R\x06folder\x12+\n" +
	"\x03key\x18\x03 \x01(\tB\x19\xbaH\x16r\x14\x10\x012\x10^[^#[:cntrl:]]*$R\x03key\x12\xae\x01\n" +
	"\venvironment\x18\x04 \x01(\tB\x8b\x01\xbaH\x87\x01\xba\x01p\n" +
	"\x1eenvvars.environment.class_wide\x129\"*\" is reserved: it names the value that binds class-wide\x1a\x13!this.contains('*')r\x122\x10^[^#[:cntrl:]]*$R\venvironment\"\xe6\x01\n" +
	"\rValueMetadata\x12?\n" +
	"\n" +
	"coordinate\x18\x01 \x01(\v2\x1f.provider.envvars.v1.CoordinateR\n" +
	"coordinate\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12<\n" +
	"\x06target\x18\x05 \x01(\v2\x1f.provider.envvars.v1.CoordinateH\x00R\x06target\x88\x01\x01B\t\n" +
	"\a_target\"[\n" +
	"\fVersionEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xf5\x01\n" +
	"\x0fSetValueRequest\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x12G\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x1f.provider.envvars.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tB\x03\x80\x01\x01R\x05value\x12.\n" +
	"\x10expected_version\x18\x04 \x01(\x03H\x00R\x0fexpectedVersion\x88\x01\x01B\x13\n" +
	"\x11_expected_version\"R\n" +
	"\x10SetValueResponse\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".provider.envvars.v1.ValueMetadataR\bmetadata\"\x85\x01\n" +
	"\x11ListValuesRequest\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x125\n" +
	"\x04slug\x18\x02 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\"P\n" +
	"\x12ListValuesResponse\x12:\n" +
	"\x06values\x18\x01 \x03(\v2\".provider.envvars.v1.ValueMetadataR\x06values\"\xad\x01\n" +
	"\x0fGetValueRequest\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x12G\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x1f.provider.envvars.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\x12\x16\n" +
	"\x06reveal\x18\x03 \x01(\bR\x06reveal\"\x83\x01\n" +
	"\x10GetValueResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\".provider.envvars.v1.ValueMetadataR\bmetadata\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tB\x03\x80\x01\x01R\x05value\"\xbe\x01\n" +
	"\x13RevealValuesRequest\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x125\n" +
	"\x04slug\x18\x02 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x125\n" +
	"\x05cells\x18\x03 \x03(\v2\x1f.provider.envvars.v1.CoordinateR\x05cells\"R\n" +
	"\x14RevealValuesResponse\x12:\n" +
	"\x06values\x18\x01 \x03(\v2\".provider.envvars.v1.RevealedValueR\x06values\"j\n" +
	"\rRevealedValue\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".provider.envvars.v1.ValueMetadataR\bmetadata\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tB\x03\x80\x01\x01R\x05value\"\xdd\x01\n" +
	"\x12DeleteValueRequest\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x12G\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x1f.provider.envvars.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\x12.\n" +
	"\x10expected_version\x18\x03 \x01(\x03H\x00R\x0fexpectedVersion\x88\x01\x01B\x13\n" +
	"\x11_expected_version\"/\n" +
	"\x13DeleteValueResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xda\x01\n" +
	"\x13SetReferenceRequest\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x12G\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x1f.provider.envvars.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\x12?\n" +
	"\x06target\x18\x03 \x01(\v2\x1f.provider.envvars.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\x06target\"V\n" +
	"\x14SetReferenceResponse\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".provider.envvars.v1.ValueMetadataR\bmetadata\"\x9b\x01\n" +
	"\x15ListReferencesRequest\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x12G\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x1f.provider.envvars.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\"Y\n" +
	"\x16ListReferencesResponse\x12?\n" +
	"\n" +
	"references\x18\x01 \x03(\v2\x1f.provider.envvars.v1.CoordinateR\n" +
	"references\"\x99\x01\n" +
	"\x13ListVersionsRequest\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x12G\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x1f.provider.envvars.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\"U\n" +
	"\x14ListVersionsResponse\x12=\n" +
	"\bversions\x18\x01 \x03(\v2!.provider.envvars.v1.VersionEntryR\bversions\"\xac\x04\n" +
	"\x11SetBindingRequest\x125\n" +
	"\x04slug\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12\xd9\x01\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x1b.common.environment.v1.TierB\xa7\x01\xbaH\xa3\x01\xba\x01\x9f\x01\n" +
	"\x14envvars.binding.tier\x12wa binding is published to an ocel coordinate, never to a stage or a stack name: name the preview or the production tier\x1a\x0ethis in [1, 2]R\x04tier\x12\xae\x01\n" +
	"\venvironment\x18\x03 \x01(\tB\x8b\x01\xbaH\x87\x01\xba\x01p\n" +
	"\x1eenvvars.environment.class_wide\x129\"*\" is reserved: it names the value that binds class-wide\x1a\x13!this.contains('*')r\x122\x10^[^#[:cntrl:]]*$R\venvironment\x12=\n" +
	"\abinding\x18\x04 \x01(\v2\x1b.common.bindings.v1.BindingB\x06\xbaH\x03\xc8\x01\x01R\abinding\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\".\n" +
	"\x12SetBindingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"\x89\x04\n" +
	"\x14RemoveBindingRequest\x125\n" +
	"\x04slug\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12\xd9\x01\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x1b.common.environment.v1.TierB\xa7\x01\xbaH\xa3\x01\xba\x01\x9f\x01\n" +
	"\x14envvars.binding.tier\x12wa binding is published to an ocel coordinate, never to a stage or a stack name: name the preview or the production tier\x1a\x0ethis in [1, 2]R\x04tier\x12\xae\x01\n" +
	"\venvironment\x18\x03 \x01(\tB\x8b\x01\xbaH\x87\x01\xba\x01p\n" +
	"\x1eenvvars.environment.class_wide\x129\"*\" is reserved: it names the value that binds class-wide\x1a\x13!this.contains('*')r\x122\x10^[^#[:cntrl:]]*$R\venvironment\x12-\n" +
	"\x04name\x18\x04 \x01(\tB\x19\xbaH\x16r\x14\x10\x012\x10^[^#[:cntrl:]]*$R\x04name\"1\n" +
	"\x15RemoveBindingResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"\xd9\x03\n" +
	"\x13ListBindingsRequest\x125\n" +
	"\x04slug\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12\xd9\x01\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x1b.common.environment.v1.TierB\xa7\x01\xbaH\xa3\x01\xba\x01\x9f\x01\n" +
	"\x14envvars.binding.tier\x12wa binding is published to an ocel coordinate, never to a stage or a stack name: name the preview or the production tier\x1a\x0ethis in [1, 2]R\x04tier\x12\xae\x01\n" +
	"\venvironment\x18\x03 \x01(\tB\x8b\x01\xbaH\x87\x01\xba\x01p\n" +
	"\x1eenvvars.environment.class_wide\x129\"*\" is reserved: it names the value that binds class-wide\x1a\x13!this.contains('*')r\x122\x10^[^#[:cntrl:]]*$R\venvironment\"W\n" +
	"\x14ListBindingsResponse\x12?\n" +
	"\bbindings\x18\x01 \x03(\v2#.provider.envvars.v1.BindingSummaryR\bbindings\"\xe5\x01\n" +
	"\x0eBindingSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.common.bindings.v1.BindingTypeR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x12B\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2\".provider.envvars.v1.PropertyShapeR\n" +
	"properties\"T\n" +
	"\rPropertyShape\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tjson_type\x18\x02 \x01(\tR\bjsonType\x12\x12\n" +
	"\x04list\x18\x03 \x01(\bR\x04list2\xc9\b\n" +
	"\x0eEnvVarsService\x12W\n" +
	"\bSetValue\x12$.provider.envvars.v1.SetValueRequest\x1a%.provider.envvars.v1.SetValueResponse\x12]\n" +
	"\n" +
	"ListValues\x12&.provider.envvars.v1.ListValuesRequest\x1a'.provider.envvars.v1.ListValuesResponse\x12W\n" +
	"\bGetValue\x12$.provider.envvars.v1.GetValueRequest\x1a%.provider.envvars.v1.GetValueResponse\x12c\n" +
	"\fRevealValues\x12(.provider.envvars.v1.RevealValuesRequest\x1a).provider.envvars.v1.RevealValuesResponse\x12`\n" +
	"\vDeleteValue\x12'.provider.envvars.v1.DeleteValueRequest\x1a(.provider.envvars.v1.DeleteValueResponse\x12c\n" +
	"\fSetReference\x12(.provider.envvars.v1.SetReferenceRequest\x1a).provider.envvars.v1.SetReferenceResponse\x12i\n" +
	"\x0eListReferences\x12*.provider.envvars.v1.ListReferencesRequest\x1a+.provider.envvars.v1.ListReferencesResponse\x12c\n" +
	"\fListVersions\x12(.provider.envvars.v1.ListVersionsRequest\x1a).provider.envvars.v1.ListVersionsResponse\x12]\n" +
	"\n" +
	"SetBinding\x12&.provider.envvars.v1.SetBindingRequest\x1a'.provider.envvars.v1.SetBindingResponse\x12f\n" +
	"\rRemoveBinding\x12).provider.envvars.v1.RemoveBindingRequest\x1a*.provider.envvars.v1.RemoveBindingResponse\x12c\n" +
	"\fListBindings\x12(.provider.envvars.v1.ListBindingsRequest\x1a).provider.envvars.v1.ListBindingsResponseB@Z>github.com/ocelhq/ocel/pkg/proto/provider/envvars/v1;envvarsv1b\x06proto3"

var (
	file_provider_envvars_v1_envvars_proto_rawDescOnce sync.Once
	file_provider_envvars_v1_envvars_proto_rawDescData []byte
)

func file_provider_envvars_v1_envvars_proto_rawDescGZIP() []byte {
	file_provider_envvars_v1_envvars_proto_rawDescOnce.Do(func() {
		file_provider_envvars_v1_envvars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_envvars_v1_envvars_proto_rawDesc), len(file_provider_envvars_v1_envvars_proto_rawDesc)))
	})
	return file_provider_envvars_v1_envvars_proto_rawDescData
}

var file_provider_envvars_v1_envvars_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_provider_envvars_v1_envvars_proto_goTypes = []any{
	(*Coordinate)(nil),             // 0: provider.envvars.v1.Coordinate
	(*ValueMetadata)(nil),          // 1: provider.envvars.v1.ValueMetadata
	(*VersionEntry)(nil),           // 2: provider.envvars.v1.VersionEntry
	(*SetValueRequest)(nil),        // 3: provider.envvars.v1.SetValueRequest
	(*SetValueResponse)(nil),       // 4: provider.envvars.v1.SetValueResponse
	(*ListValuesRequest)(nil),      // 5: provider.envvars.v1.ListValuesRequest
	(*ListValuesResponse)(nil),     // 6: provider.envvars.v1.ListValuesResponse
	(*GetValueRequest)(nil),        // 7: provider.envvars.v1.GetValueRequest
	(*GetValueResponse)(nil),       // 8: provider.envvars.v1.GetValueResponse
	(*RevealValuesRequest)(nil),    // 9: provider.envvars.v1.RevealValuesRequest
	(*RevealValuesResponse)(nil),   // 10: provider.envvars.v1.RevealValuesResponse
	(*RevealedValue)(nil),          // 11: provider.envvars.v1.RevealedValue
	(*DeleteValueRequest)(nil),     // 12: provider.envvars.v1.DeleteValueRequest
	(*DeleteValueResponse)(nil),    // 13: provider.envvars.v1.DeleteValueResponse
	(*SetReferenceRequest)(nil),    // 14: provider.envvars.v1.SetReferenceRequest
	(*SetReferenceResponse)(nil),   // 15: provider.envvars.v1.SetReferenceResponse
	(*ListReferencesRequest)(nil),  // 16: provider.envvars.v1.ListReferencesRequest
	(*ListReferencesResponse)(nil), // 17: provider.envvars.v1.ListReferencesResponse
	(*ListVersionsRequest)(nil),    // 18: provider.envvars.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),   // 19: provider.envvars.v1.ListVersionsResponse
	(*SetBindingRequest)(nil),      // 20: provider.envvars.v1.SetBindingRequest
	(*SetBindingResponse)(nil),     // 21: provider.envvars.v1.SetBindingResponse
	(*RemoveBindingRequest)(nil),   // 22: provider.envvars.v1.RemoveBindingRequest
	(*RemoveBindingResponse)(nil),  // 23: provider.envvars.v1.RemoveBindingResponse
	(*ListBindingsRequest)(nil),    // 24: provider.envvars.v1.ListBindingsRequest
	(*ListBindingsResponse)(nil),   // 25: provider.envvars.v1.ListBindingsResponse
	(*BindingSummary)(nil),         // 26: provider.envvars.v1.BindingSummary
	(*PropertyShape)(nil),          // 27: provider.envvars.v1.PropertyShape
	(v1.Tier)(0),                   // 28: common.environment.v1.Tier
	(*v11.Binding)(nil),            // 29: common.bindings.v1.Binding
	(v11.BindingType)(0),           // 30: common.bindings.v1.BindingType
}
var file_provider_envvars_v1_envvars_proto_depIdxs = []int32{
	0,  // 0: provider.envvars.v1.ValueMetadata.coordinate:type_name -> provider.envvars.v1.Coordinate
	0,  // 1: provider.envvars.v1.ValueMetadata.target:type_name -> provider.envvars.v1.Coordinate
	28, // 2: provider.envvars.v1.SetValueRequest.tier:type_name -> common.environment.v1.Tier
	0,  // 3: provider.envvars.v1.SetValueRequest.coordinate:type_name -> provider.envvars.v1.Coordinate
	1,  // 4: provider.envvars.v1.SetValueResponse.metadata:type_name -> provider.envvars.v1.ValueMetadata
	28, // 5: provider.envvars.v1.ListValuesRequest.tier:type_name -> common.environment.v1.Tier
	1,  // 6: provider.envvars.v1.ListValuesResponse.values:type_name -> provider.envvars.v1.ValueMetadata
	28, // 7: provider.envvars.v1.GetValueRequest.tier:type_name -> common.environment.v1.Tier
	0,  // 8: provider.envvars.v1.GetValueRequest.coordinate:type_name -> provider.envvars.v1.Coordinate
	1,  // 9: provider.envvars.v1.GetValueResponse.metadata:type_name -> provider.envvars.v1.ValueMetadata
	28, // 10: provider.envvars.v1.RevealValuesRequest.tier:type_name -> common.environment.v1.Tier
	0,  // 11: provider.envvars.v1.RevealValuesRequest.cells:type_name -> provider.envvars.v1.Coordinate
	11, // 12: provider.envvars.v1.RevealValuesResponse.values:type_name -> provider.envvars.v1.RevealedValue
	1,  // 13: provider.envvars.v1.RevealedValue.metadata:type_name -> provider.envvars.v1.ValueMetadata
	28, // 14: provider.envvars.v1.DeleteValueRequest.tier:type_name -> common.environment.v1.Tier
	0,  // 15: provider.envvars.v1.DeleteValueRequest.coordinate:type_name -> provider.envvars.v1.Coordinate
	28, // 16: provider.envvars.v1.SetReferenceRequest.tier:type_name -> common.environment.v1.Tier
	0,  // 17: provider.envvars.v1.SetReferenceRequest.coordinate:type_name -> provider.envvars.v1.Coordinate
	0,  // 18: provider.envvars.v1.SetReferenceRequest.target:type_name -> provider.envvars.v1.Coordinate
	1,  // 19: provider.envvars.v1.SetReferenceResponse.metadata:type_name -> provider.envvars.v1.ValueMetadata
	28, // 20: provider.envvars.v1.ListReferencesRequest.tier:type_name -> common.environment.v1.Tier
	0,  // 21: provider.envvars.v1.ListReferencesRequest.coordinate:type_name -> provider.envvars.v1.Coordinate
	0,  // 22: provider.envvars.v1.ListReferencesResponse.references:type_name -> provider.envvars.v1.Coordinate
	28, // 23: provider.envvars.v1.ListVersionsRequest.tier:type_name -> common.environment.v1.Tier
	0,  // 24: provider.envvars.v1.ListVersionsRequest.coordinate:type_name -> provider.envvars.v1.Coordinate
	2,  // 25: provider.envvars.v1.ListVersionsResponse.versions:type_name -> provider.envvars.v1.VersionEntry
	28, // 26: provider.envvars.v1.SetBindingRequest.tier:type_name -> common.environment.v1.Tier
	29, // 27: provider.envvars.v1.SetBindingRequest.binding:type_name -> common.bindings.v1.Binding
	28, // 28: provider.envvars.v1.RemoveBindingRequest.tier:type_name -> common.environment.v1.Tier
	28, // 29: provider.envvars.v1.ListBindingsRequest.tier:type_name -> common.environment.v1.Tier
	26, // 30: provider.envvars.v1.ListBindingsResponse.bindings:type_name -> provider.envvars.v1.BindingSummary
	30, // 31: provider.envvars.v1.BindingSummary.type:type_name -> common.bindings.v1.BindingType
	27, // 32: provider.envvars.v1.BindingSummary.properties:type_name -> provider.envvars.v1.PropertyShape
	3,  // 33: provider.envvars.v1.EnvVarsService.SetValue:input_type -> provider.envvars.v1.SetValueRequest
	5,  // 34: provider.envvars.v1.EnvVarsService.ListValues:input_type -> provider.envvars.v1.ListValuesRequest
	7,  // 35: provider.envvars.v1.EnvVarsService.GetValue:input_type -> provider.envvars.v1.GetValueRequest
	9,  // 36: provider.envvars.v1.EnvVarsService.RevealValues:input_type -> provider.envvars.v1.RevealValuesRequest
	12, // 37: provider.envvars.v1.EnvVarsService.DeleteValue:input_type -> provider.envvars.v1.DeleteValueRequest
	14, // 38: provider.envvars.v1.EnvVarsService.SetReference:input_type -> provider.envvars.v1.SetReferenceRequest
	16, // 39: provider.envvars.v1.EnvVarsService.ListReferences:input_type -> provider.envvars.v1.ListReferencesRequest
	18, // 40: provider.envvars.v1.EnvVarsService.ListVersions:input_type -> provider.envvars.v1.ListVersionsRequest
	20, // 41: provider.envvars.v1.EnvVarsService.SetBinding:input_type -> provider.envvars.v1.SetBindingRequest
	22, // 42: provider.envvars.v1.EnvVarsService.RemoveBinding:input_type -> provider.envvars.v1.RemoveBindingRequest
	24, // 43: provider.envvars.v1.EnvVarsService.ListBindings:input_type -> provider.envvars.v1.ListBindingsRequest
	4,  // 44: provider.envvars.v1.EnvVarsService.SetValue:output_type -> provider.envvars.v1.SetValueResponse
	6,  // 45: provider.envvars.v1.EnvVarsService.ListValues:output_type -> provider.envvars.v1.ListValuesResponse
	8,  // 46: provider.envvars.v1.EnvVarsService.GetValue:output_type -> provider.envvars.v1.GetValueResponse
	10, // 47: provider.envvars.v1.EnvVarsService.RevealValues:output_type -> provider.envvars.v1.RevealValuesResponse
	13, // 48: provider.envvars.v1.EnvVarsService.DeleteValue:output_type -> provider.envvars.v1.DeleteValueResponse
	15, // 49: provider.envvars.v1.EnvVarsService.SetReference:output_type -> provider.envvars.v1.SetReferenceResponse
	17, // 50: provider.envvars.v1.EnvVarsService.ListReferences:output_type -> provider.envvars.v1.ListReferencesResponse
	19, // 51: provider.envvars.v1.EnvVarsService.ListVersions:output_type -> provider.envvars.v1.ListVersionsResponse
	21, // 52: provider.envvars.v1.EnvVarsService.SetBinding:output_type -> provider.envvars.v1.SetBindingResponse
	23, // 53: provider.envvars.v1.EnvVarsService.RemoveBinding:output_type -> provider.envvars.v1.RemoveBindingResponse
	25, // 54: provider.envvars.v1.EnvVarsService.ListBindings:output_type -> provider.envvars.v1.ListBindingsResponse
	44, // [44:55] is the sub-list for method output_type
	33, // [33:44] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_provider_envvars_v1_envvars_proto_init() }
func file_provider_envvars_v1_envvars_proto_init() {
	if File_provider_envvars_v1_envvars_proto != nil {
		return
	}
	file_provider_envvars_v1_envvars_proto_msgTypes[1].OneofWrappers = []any{}
	file_provider_envvars_v1_envvars_proto_msgTypes[3].OneofWrappers = []any{}
	file_provider_envvars_v1_envvars_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_envvars_v1_envvars_proto_rawDesc), len(file_provider_envvars_v1_envvars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_envvars_v1_envvars_proto_goTypes,
		DependencyIndexes: file_provider_envvars_v1_envvars_proto_depIdxs,
		MessageInfos:      file_provider_envvars_v1_envvars_proto_msgTypes,
	}.Build()
	File_provider_envvars_v1_envvars_proto = out.File
	file_provider_envvars_v1_envvars_proto_goTypes = nil
	file_provider_envvars_v1_envvars_proto_depIdxs = nil
}
