// generated by `ocel link generate` from production; do not edit
import "@ocel/provider-aws/transform";

declare module "@ocel/provider-aws/transform" {
  interface LinksGenerated {
    generated: true;
  }

  interface Links {
  }
}
