// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common/environment/v1/environment.proto

package environmentv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tier int32

const (
	Tier_TIER_UNSPECIFIED Tier = 0
	Tier_TIER_PREVIEW     Tier = 1
	Tier_TIER_PRODUCTION  Tier = 2
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_PREVIEW",
		2: "TIER_PRODUCTION",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"TIER_PREVIEW":     1,
		"TIER_PRODUCTION":  2,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_common_environment_v1_environment_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_common_environment_v1_environment_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_common_environment_v1_environment_proto_rawDescGZIP(), []int{0}
}

type Lifecycle int32

const (
	Lifecycle_LIFECYCLE_UNSPECIFIED Lifecycle = 0
	Lifecycle_LIFECYCLE_EPHEMERAL   Lifecycle = 1
	Lifecycle_LIFECYCLE_PERSISTENT  Lifecycle = 2
)

// Enum value maps for Lifecycle.
var (
	Lifecycle_name = map[int32]string{
		0: "LIFECYCLE_UNSPECIFIED",
		1: "LIFECYCLE_EPHEMERAL",
		2: "LIFECYCLE_PERSISTENT",
	}
	Lifecycle_value = map[string]int32{
		"LIFECYCLE_UNSPECIFIED": 0,
		"LIFECYCLE_EPHEMERAL":   1,
		"LIFECYCLE_PERSISTENT":  2,
	}
)

func (x Lifecycle) Enum() *Lifecycle {
	p := new(Lifecycle)
	*p = x
	return p
}

func (x Lifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_common_environment_v1_environment_proto_enumTypes[1].Descriptor()
}

func (Lifecycle) Type() protoreflect.EnumType {
	return &file_common_environment_v1_environment_proto_enumTypes[1]
}

func (x Lifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lifecycle.Descriptor instead.
func (Lifecycle) EnumDescriptor() ([]byte, []int) {
	return file_common_environment_v1_environment_proto_rawDescGZIP(), []int{1}
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          Tier                   `protobuf:"varint,1,opt,name=tier,proto3,enum=common.environment.v1.Tier" json:"tier,omitempty"`
	Lifecycle     Lifecycle              `protobuf:"varint,2,opt,name=lifecycle,proto3,enum=common.environment.v1.Lifecycle" json:"lifecycle,omitempty"`
	Identity      string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_common_environment_v1_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_common_environment_v1_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_common_environment_v1_environment_proto_rawDescGZIP(), []int{0}
}

func (x *Environment) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *Environment) GetLifecycle() Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return Lifecycle_LIFECYCLE_UNSPECIFIED
}

func (x *Environment) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

var File_common_environment_v1_environment_proto protoreflect.FileDescriptor

const file_common_environment_v1_environment_proto_rawDesc = "" +
	"\n" +
	"'common/environment/v1/environment.proto\x12\x15common.environment.v1\x1a\x1bbuf/validate/validate.proto\"\xae\x01\n" +
	"\vEnvironment\x129\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x1b.common.environment.v1.TierB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04tier\x12H\n" +
	"\tlifecycle\x18\x02 \x01(\x0e2 .common.environment.v1.LifecycleB\b\xbaH\x05\x82\x01\x02\x10\x01R\tlifecycle\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity*C\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTIER_PREVIEW\x10\x01\x12\x13\n" +
	"\x0fTIER_PRODUCTION\x10\x02*Y\n" +
	"\tLifecycle\x12\x19\n" +
	"\x15LIFECYCLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13LIFECYCLE_EPHEMERAL\x10\x01\x12\x18\n" +
	"\x14LIFECYCLE_PERSISTENT\x10\x02BFZDgithub.com/ocelhq/ocel/pkg/proto/common/environment/v1;environmentv1b\x06proto3"

var (
	file_common_environment_v1_environment_proto_rawDescOnce sync.Once
	file_common_environment_v1_environment_proto_rawDescData []byte
)

func file_common_environment_v1_environment_proto_rawDescGZIP() []byte {
	file_common_environment_v1_environment_proto_rawDescOnce.Do(func() {
		file_common_environment_v1_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_environment_v1_environment_proto_rawDesc), len(file_common_environment_v1_environment_proto_rawDesc)))
	})
	return file_common_environment_v1_environment_proto_rawDescData
}

var file_common_environment_v1_environment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_environment_v1_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_environment_v1_environment_proto_goTypes = []any{
	(Tier)(0),           // 0: common.environment.v1.Tier
	(Lifecycle)(0),      // 1: common.environment.v1.Lifecycle
	(*Environment)(nil), // 2: common.environment.v1.Environment
}
var file_common_environment_v1_environment_proto_depIdxs = []int32{
	0, // 0: common.environment.v1.Environment.tier:type_name -> common.environment.v1.Tier
	1, // 1: common.environment.v1.Environment.lifecycle:type_name -> common.environment.v1.Lifecycle
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_environment_v1_environment_proto_init() }
func file_common_environment_v1_environment_proto_init() {
	if File_common_environment_v1_environment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_environment_v1_environment_proto_rawDesc), len(file_common_environment_v1_environment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_environment_v1_environment_proto_goTypes,
		DependencyIndexes: file_common_environment_v1_environment_proto_depIdxs,
		EnumInfos:         file_common_environment_v1_environment_proto_enumTypes,
		MessageInfos:      file_common_environment_v1_environment_proto_msgTypes,
	}.Build()
	File_common_environment_v1_environment_proto = out.File
	file_common_environment_v1_environment_proto_goTypes = nil
	file_common_environment_v1_environment_proto_depIdxs = nil
}
