// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common/bindings/v1/bindings.proto

package bindingsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindingType int32

const (
	BindingType_BINDING_TYPE_UNSPECIFIED BindingType = 0
	BindingType_BINDING_TYPE_POSTGRES    BindingType = 1
	BindingType_BINDING_TYPE_BUCKET      BindingType = 2
	BindingType_BINDING_TYPE_CUSTOM      BindingType = 3
	BindingType_BINDING_TYPE_TOPIC       BindingType = 4
	BindingType_BINDING_TYPE_TASK        BindingType = 5
	BindingType_BINDING_TYPE_KV          BindingType = 6
	BindingType_BINDING_TYPE_REALTIME    BindingType = 7
)

// Enum value maps for BindingType.
var (
	BindingType_name = map[int32]string{
		0: "BINDING_TYPE_UNSPECIFIED",
		1: "BINDING_TYPE_POSTGRES",
		2: "BINDING_TYPE_BUCKET",
		3: "BINDING_TYPE_CUSTOM",
		4: "BINDING_TYPE_TOPIC",
		5: "BINDING_TYPE_TASK",
		6: "BINDING_TYPE_KV",
		7: "BINDING_TYPE_REALTIME",
	}
	BindingType_value = map[string]int32{
		"BINDING_TYPE_UNSPECIFIED": 0,
		"BINDING_TYPE_POSTGRES":    1,
		"BINDING_TYPE_BUCKET":      2,
		"BINDING_TYPE_CUSTOM":      3,
		"BINDING_TYPE_TOPIC":       4,
		"BINDING_TYPE_TASK":        5,
		"BINDING_TYPE_KV":          6,
		"BINDING_TYPE_REALTIME":    7,
	}
)

func (x BindingType) Enum() *BindingType {
	p := new(BindingType)
	*p = x
	return p
}

func (x BindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_bindings_v1_bindings_proto_enumTypes[0].Descriptor()
}

func (BindingType) Type() protoreflect.EnumType {
	return &file_common_bindings_v1_bindings_proto_enumTypes[0]
}

func (x BindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindingType.Descriptor instead.
func (BindingType) EnumDescriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{0}
}

type PostgresTlsMode int32

const (
	PostgresTlsMode_POSTGRES_TLS_MODE_UNSPECIFIED PostgresTlsMode = 0
	PostgresTlsMode_POSTGRES_TLS_MODE_REQUIRE     PostgresTlsMode = 1
	PostgresTlsMode_POSTGRES_TLS_MODE_VERIFY_FULL PostgresTlsMode = 2
)

// Enum value maps for PostgresTlsMode.
var (
	PostgresTlsMode_name = map[int32]string{
		0: "POSTGRES_TLS_MODE_UNSPECIFIED",
		1: "POSTGRES_TLS_MODE_REQUIRE",
		2: "POSTGRES_TLS_MODE_VERIFY_FULL",
	}
	PostgresTlsMode_value = map[string]int32{
		"POSTGRES_TLS_MODE_UNSPECIFIED": 0,
		"POSTGRES_TLS_MODE_REQUIRE":     1,
		"POSTGRES_TLS_MODE_VERIFY_FULL": 2,
	}
)

func (x PostgresTlsMode) Enum() *PostgresTlsMode {
	p := new(PostgresTlsMode)
	*p = x
	return p
}

func (x PostgresTlsMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostgresTlsMode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_bindings_v1_bindings_proto_enumTypes[1].Descriptor()
}

func (PostgresTlsMode) Type() protoreflect.EnumType {
	return &file_common_bindings_v1_bindings_proto_enumTypes[1]
}

func (x PostgresTlsMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostgresTlsMode.Descriptor instead.
func (PostgresTlsMode) EnumDescriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{1}
}

type RealtimeTransport int32

const (
	RealtimeTransport_REALTIME_TRANSPORT_UNSPECIFIED    RealtimeTransport = 0
	RealtimeTransport_REALTIME_TRANSPORT_APPSYNC_EVENTS RealtimeTransport = 1
	RealtimeTransport_REALTIME_TRANSPORT_OCEL_GATEWAY   RealtimeTransport = 2
)

// Enum value maps for RealtimeTransport.
var (
	RealtimeTransport_name = map[int32]string{
		0: "REALTIME_TRANSPORT_UNSPECIFIED",
		1: "REALTIME_TRANSPORT_APPSYNC_EVENTS",
		2: "REALTIME_TRANSPORT_OCEL_GATEWAY",
	}
	RealtimeTransport_value = map[string]int32{
		"REALTIME_TRANSPORT_UNSPECIFIED":    0,
		"REALTIME_TRANSPORT_APPSYNC_EVENTS": 1,
		"REALTIME_TRANSPORT_OCEL_GATEWAY":   2,
	}
)

func (x RealtimeTransport) Enum() *RealtimeTransport {
	p := new(RealtimeTransport)
	*p = x
	return p
}

func (x RealtimeTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RealtimeTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_common_bindings_v1_bindings_proto_enumTypes[2].Descriptor()
}

func (RealtimeTransport) Type() protoreflect.EnumType {
	return &file_common_bindings_v1_bindings_proto_enumTypes[2]
}

func (x RealtimeTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RealtimeTransport.Descriptor instead.
func (RealtimeTransport) EnumDescriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{2}
}

type Binding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Properties:
	//
	//	*Binding_Postgres
	//	*Binding_Bucket
	//	*Binding_Custom
	//	*Binding_Topic
	//	*Binding_Task
	//	*Binding_Kv
	//	*Binding_Realtime
	Properties    isBinding_Properties `protobuf_oneof:"properties"`
	Grants        []*Grant             `protobuf:"bytes,4,rep,name=grants,proto3" json:"grants,omitempty"`
	Source        string               `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{0}
}

func (x *Binding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Binding) GetProperties() isBinding_Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Binding) GetPostgres() *PostgresProperties {
	if x != nil {
		if x, ok := x.Properties.(*Binding_Postgres); ok {
			return x.Postgres
		}
	}
	return nil
}

func (x *Binding) GetBucket() *BucketProperties {
	if x != nil {
		if x, ok := x.Properties.(*Binding_Bucket); ok {
			return x.Bucket
		}
	}
	return nil
}

func (x *Binding) GetCustom() *structpb.Struct {
	if x != nil {
		if x, ok := x.Properties.(*Binding_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

func (x *Binding) GetTopic() *TopicProperties {
	if x != nil {
		if x, ok := x.Properties.(*Binding_Topic); ok {
			return x.Topic
		}
	}
	return nil
}

func (x *Binding) GetTask() *TaskProperties {
	if x != nil {
		if x, ok := x.Properties.(*Binding_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *Binding) GetKv() *KvProperties {
	if x != nil {
		if x, ok := x.Properties.(*Binding_Kv); ok {
			return x.Kv
		}
	}
	return nil
}

func (x *Binding) GetRealtime() *RealtimeProperties {
	if x != nil {
		if x, ok := x.Properties.(*Binding_Realtime); ok {
			return x.Realtime
		}
	}
	return nil
}

func (x *Binding) GetGrants() []*Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *Binding) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type isBinding_Properties interface {
	isBinding_Properties()
}

type Binding_Postgres struct {
	Postgres *PostgresProperties `protobuf:"bytes,2,opt,name=postgres,proto3,oneof"`
}

type Binding_Bucket struct {
	Bucket *BucketProperties `protobuf:"bytes,3,opt,name=bucket,proto3,oneof"`
}

type Binding_Custom struct {
	Custom *structpb.Struct `protobuf:"bytes,6,opt,name=custom,proto3,oneof"`
}

type Binding_Topic struct {
	Topic *TopicProperties `protobuf:"bytes,7,opt,name=topic,proto3,oneof"`
}

type Binding_Task struct {
	Task *TaskProperties `protobuf:"bytes,8,opt,name=task,proto3,oneof"`
}

type Binding_Kv struct {
	Kv *KvProperties `protobuf:"bytes,9,opt,name=kv,proto3,oneof"`
}

type Binding_Realtime struct {
	Realtime *RealtimeProperties `protobuf:"bytes,10,opt,name=realtime,proto3,oneof"`
}

func (*Binding_Postgres) isBinding_Properties() {}

func (*Binding_Bucket) isBinding_Properties() {}

func (*Binding_Custom) isBinding_Properties() {}

func (*Binding_Topic) isBinding_Properties() {}

func (*Binding_Task) isBinding_Properties() {}

func (*Binding_Kv) isBinding_Properties() {}

func (*Binding_Realtime) isBinding_Properties() {}

type PostgresProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	TlsMode       PostgresTlsMode        `protobuf:"varint,7,opt,name=tls_mode,json=tlsMode,proto3,enum=common.bindings.v1.PostgresTlsMode" json:"tls_mode,omitempty"`
	TlsCa         string                 `protobuf:"bytes,8,opt,name=tls_ca,json=tlsCa,proto3" json:"tls_ca,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostgresProperties) Reset() {
	*x = PostgresProperties{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostgresProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresProperties) ProtoMessage() {}

func (x *PostgresProperties) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresProperties.ProtoReflect.Descriptor instead.
func (*PostgresProperties) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{1}
}

func (x *PostgresProperties) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PostgresProperties) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PostgresProperties) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *PostgresProperties) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PostgresProperties) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PostgresProperties) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PostgresProperties) GetTlsMode() PostgresTlsMode {
	if x != nil {
		return x.TlsMode
	}
	return PostgresTlsMode_POSTGRES_TLS_MODE_UNSPECIFIED
}

func (x *PostgresProperties) GetTlsCa() string {
	if x != nil {
		return x.TlsCa
	}
	return ""
}

type BucketProperties struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bucket          string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	PublicBaseUrl   string                 `protobuf:"bytes,2,opt,name=public_base_url,json=publicBaseUrl,proto3" json:"public_base_url,omitempty"`
	Public          bool                   `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	Endpoint        string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region          string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	PathStyle       bool                   `protobuf:"varint,6,opt,name=path_style,json=pathStyle,proto3" json:"path_style,omitempty"`
	Prefix          string                 `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,8,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,9,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BucketProperties) Reset() {
	*x = BucketProperties{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketProperties) ProtoMessage() {}

func (x *BucketProperties) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketProperties.ProtoReflect.Descriptor instead.
func (*BucketProperties) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{2}
}

func (x *BucketProperties) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *BucketProperties) GetPublicBaseUrl() string {
	if x != nil {
		return x.PublicBaseUrl
	}
	return ""
}

func (x *BucketProperties) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *BucketProperties) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *BucketProperties) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *BucketProperties) GetPathStyle() bool {
	if x != nil {
		return x.PathStyle
	}
	return false
}

func (x *BucketProperties) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *BucketProperties) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *BucketProperties) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

type TopicProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicProperties) Reset() {
	*x = TopicProperties{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicProperties) ProtoMessage() {}

func (x *TopicProperties) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicProperties.ProtoReflect.Descriptor instead.
func (*TopicProperties) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{3}
}

type TaskProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProperties) Reset() {
	*x = TaskProperties{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProperties) ProtoMessage() {}

func (x *TaskProperties) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProperties.ProtoReflect.Descriptor instead.
func (*TaskProperties) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{4}
}

type KvProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Tls           bool                   `protobuf:"varint,5,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvProperties) Reset() {
	*x = KvProperties{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvProperties) ProtoMessage() {}

func (x *KvProperties) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvProperties.ProtoReflect.Descriptor instead.
func (*KvProperties) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{5}
}

func (x *KvProperties) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *KvProperties) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *KvProperties) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *KvProperties) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *KvProperties) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

type RealtimeProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     RealtimeTransport      `protobuf:"varint,1,opt,name=transport,proto3,enum=common.bindings.v1.RealtimeTransport" json:"transport,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	SigningKey    []byte                 `protobuf:"bytes,4,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	VerifyKey     []byte                 `protobuf:"bytes,5,opt,name=verify_key,json=verifyKey,proto3" json:"verify_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealtimeProperties) Reset() {
	*x = RealtimeProperties{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeProperties) ProtoMessage() {}

func (x *RealtimeProperties) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeProperties.ProtoReflect.Descriptor instead.
func (*RealtimeProperties) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{6}
}

func (x *RealtimeProperties) GetTransport() RealtimeTransport {
	if x != nil {
		return x.Transport
	}
	return RealtimeTransport_REALTIME_TRANSPORT_UNSPECIFIED
}

func (x *RealtimeProperties) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RealtimeProperties) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RealtimeProperties) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

func (x *RealtimeProperties) GetVerifyKey() []byte {
	if x != nil {
		return x.VerifyKey
	}
	return nil
}

type Grant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []string               `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	Resources     []string               `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Conditions    []*GrantCondition      `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{7}
}

func (x *Grant) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Grant) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Grant) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Grant) GetConditions() []*GrantCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type GrantCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantCondition) Reset() {
	*x = GrantCondition{}
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantCondition) ProtoMessage() {}

func (x *GrantCondition) ProtoReflect() protoreflect.Message {
	mi := &file_common_bindings_v1_bindings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantCondition.ProtoReflect.Descriptor instead.
func (*GrantCondition) Descriptor() ([]byte, []int) {
	return file_common_bindings_v1_bindings_proto_rawDescGZIP(), []int{8}
}

func (x *GrantCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *GrantCondition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GrantCondition) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_common_bindings_v1_bindings_proto protoreflect.FileDescriptor

const file_common_bindings_v1_bindings_proto_rawDesc = "" +
	"\n" +
	"!common/bindings/v1/bindings.proto\x12\x12common.bindings.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa0\x04\n" +
	"\aBinding\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12D\n" +
	"\bpostgres\x18\x02 \x01(\v2&.common.bindings.v1.PostgresPropertiesH\x00R\bpostgres\x12>\n" +
	"\x06bucket\x18\x03 \x01(\v2$.common.bindings.v1.BucketPropertiesH\x00R\x06bucket\x121\n" +
	"\x06custom\x18\x06 \x01(\v2\x17.google.protobuf.StructH\x00R\x06custom\x12;\n" +
	"\x05topic\x18\a \x01(\v2#.common.bindings.v1.TopicPropertiesH\x00R\x05topic\x128\n" +
	"\x04task\x18\b \x01(\v2\".common.bindings.v1.TaskPropertiesH\x00R\x04task\x122\n" +
	"\x02kv\x18\t \x01(\v2 .common.bindings.v1.KvPropertiesH\x00R\x02kv\x12D\n" +
	"\brealtime\x18\n" +
	" \x01(\v2&.common.bindings.v1.RealtimePropertiesH\x00R\brealtime\x121\n" +
	"\x06grants\x18\x04 \x03(\v2\x19.common.bindings.v1.GrantR\x06grants\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06sourceB\f\n" +
	"\n" +
	"properties\"\x83\x02\n" +
	"\x12PostgresProperties\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tB\x03\x80\x01\x01R\bpassword\x12\x15\n" +
	"\x03url\x18\x06 \x01(\tB\x03\x80\x01\x01R\x03url\x12>\n" +
	"\btls_mode\x18\a \x01(\x0e2#.common.bindings.v1.PostgresTlsModeR\atlsMode\x12\x15\n" +
	"\x06tls_ca\x18\b \x01(\tR\x05tlsCa\"\xaa\x02\n" +
	"\x10BucketProperties\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12&\n" +
	"\x0fpublic_base_url\x18\x02 \x01(\tR\rpublicBaseUrl\x12\x16\n" +
	"\x06public\x18\x03 \x01(\bR\x06public\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"path_style\x18\x06 \x01(\bR\tpathStyle\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12\"\n" +
	"\raccess_key_id\x18\b \x01(\tR\vaccessKeyId\x12/\n" +
	"\x11secret_access_key\x18\t \x01(\tB\x03\x80\x01\x01R\x0fsecretAccessKey\"\x11\n" +
	"\x0fTopicProperties\"\x10\n" +
	"\x0eTaskProperties\"\x85\x01\n" +
	"\fKvProperties\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tB\x03\x80\x01\x01R\bpassword\x12\x10\n" +
	"\x03tls\x18\x05 \x01(\bR\x03tls\"\xc4\x01\n" +
	"\x12RealtimeProperties\x12C\n" +
	"\ttransport\x18\x01 \x01(\x0e2%.common.bindings.v1.RealtimeTransportR\ttransport\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12$\n" +
	"\vsigning_key\x18\x04 \x01(\fB\x03\x80\x01\x01R\n" +
	"signingKey\x12\x1d\n" +
	"\n" +
	"verify_key\x18\x05 \x01(\fR\tverifyKey\"\x99\x01\n" +
	"\x05Grant\x12\x18\n" +
	"\aactions\x18\x01 \x03(\tR\aactions\x12\x1c\n" +
	"\tresources\x18\x02 \x03(\tR\tresources\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12B\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2\".common.bindings.v1.GrantConditionR\n" +
	"conditions\"V\n" +
	"\x0eGrantCondition\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values*\xd7\x01\n" +
	"\vBindingType\x12\x1c\n" +
	"\x18BINDING_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BINDING_TYPE_POSTGRES\x10\x01\x12\x17\n" +
	"\x13BINDING_TYPE_BUCKET\x10\x02\x12\x17\n" +
	"\x13BINDING_TYPE_CUSTOM\x10\x03\x12\x16\n" +
	"\x12BINDING_TYPE_TOPIC\x10\x04\x12\x15\n" +
	"\x11BINDING_TYPE_TASK\x10\x05\x12\x13\n" +
	"\x0fBINDING_TYPE_KV\x10\x06\x12\x19\n" +
	"\x15BINDING_TYPE_REALTIME\x10\a*v\n" +
	"\x0fPostgresTlsMode\x12!\n" +
	"\x1dPOSTGRES_TLS_MODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19POSTGRES_TLS_MODE_REQUIRE\x10\x01\x12!\n" +
	"\x1dPOSTGRES_TLS_MODE_VERIFY_FULL\x10\x02*\x83\x01\n" +
	"\x11RealtimeTransport\x12\"\n" +
	"\x1eREALTIME_TRANSPORT_UNSPECIFIED\x10\x00\x12%\n" +
	"!REALTIME_TRANSPORT_APPSYNC_EVENTS\x10\x01\x12#\n" +
	"\x1fREALTIME_TRANSPORT_OCEL_GATEWAY\x10\x02B@Z>github.com/ocelhq/ocel/pkg/proto/common/bindings/v1;bindingsv1b\x06proto3"

var (
	file_common_bindings_v1_bindings_proto_rawDescOnce sync.Once
	file_common_bindings_v1_bindings_proto_rawDescData []byte
)

func file_common_bindings_v1_bindings_proto_rawDescGZIP() []byte {
	file_common_bindings_v1_bindings_proto_rawDescOnce.Do(func() {
		file_common_bindings_v1_bindings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_bindings_v1_bindings_proto_rawDesc), len(file_common_bindings_v1_bindings_proto_rawDesc)))
	})
	return file_common_bindings_v1_bindings_proto_rawDescData
}

var file_common_bindings_v1_bindings_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_bindings_v1_bindings_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_bindings_v1_bindings_proto_goTypes = []any{
	(BindingType)(0),           // 0: common.bindings.v1.BindingType
	(PostgresTlsMode)(0),       // 1: common.bindings.v1.PostgresTlsMode
	(RealtimeTransport)(0),     // 2: common.bindings.v1.RealtimeTransport
	(*Binding)(nil),            // 3: common.bindings.v1.Binding
	(*PostgresProperties)(nil), // 4: common.bindings.v1.PostgresProperties
	(*BucketProperties)(nil),   // 5: common.bindings.v1.BucketProperties
	(*TopicProperties)(nil),    // 6: common.bindings.v1.TopicProperties
	(*TaskProperties)(nil),     // 7: common.bindings.v1.TaskProperties
	(*KvProperties)(nil),       // 8: common.bindings.v1.KvProperties
	(*RealtimeProperties)(nil), // 9: common.bindings.v1.RealtimeProperties
	(*Grant)(nil),              // 10: common.bindings.v1.Grant
	(*GrantCondition)(nil),     // 11: common.bindings.v1.GrantCondition
	(*structpb.Struct)(nil),    // 12: google.protobuf.Struct
}
var file_common_bindings_v1_bindings_proto_depIdxs = []int32{
	4,  // 0: common.bindings.v1.Binding.postgres:type_name -> common.bindings.v1.PostgresProperties
	5,  // 1: common.bindings.v1.Binding.bucket:type_name -> common.bindings.v1.BucketProperties
	12, // 2: common.bindings.v1.Binding.custom:type_name -> google.protobuf.Struct
	6,  // 3: common.bindings.v1.Binding.topic:type_name -> common.bindings.v1.TopicProperties
	7,  // 4: common.bindings.v1.Binding.task:type_name -> common.bindings.v1.TaskProperties
	8,  // 5: common.bindings.v1.Binding.kv:type_name -> common.bindings.v1.KvProperties
	9,  // 6: common.bindings.v1.Binding.realtime:type_name -> common.bindings.v1.RealtimeProperties
	10, // 7: common.bindings.v1.Binding.grants:type_name -> common.bindings.v1.Grant
	1,  // 8: common.bindings.v1.PostgresProperties.tls_mode:type_name -> common.bindings.v1.PostgresTlsMode
	2,  // 9: common.bindings.v1.RealtimeProperties.transport:type_name -> common.bindings.v1.RealtimeTransport
	11, // 10: common.bindings.v1.Grant.conditions:type_name -> common.bindings.v1.GrantCondition
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_common_bindings_v1_bindings_proto_init() }
func file_common_bindings_v1_bindings_proto_init() {
	if File_common_bindings_v1_bindings_proto != nil {
		return
	}
	file_common_bindings_v1_bindings_proto_msgTypes[0].OneofWrappers = []any{
		(*Binding_Postgres)(nil),
		(*Binding_Bucket)(nil),
		(*Binding_Custom)(nil),
		(*Binding_Topic)(nil),
		(*Binding_Task)(nil),
		(*Binding_Kv)(nil),
		(*Binding_Realtime)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_bindings_v1_bindings_proto_rawDesc), len(file_common_bindings_v1_bindings_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_bindings_v1_bindings_proto_goTypes,
		DependencyIndexes: file_common_bindings_v1_bindings_proto_depIdxs,
		EnumInfos:         file_common_bindings_v1_bindings_proto_enumTypes,
		MessageInfos:      file_common_bindings_v1_bindings_proto_msgTypes,
	}.Build()
	File_common_bindings_v1_bindings_proto = out.File
	file_common_bindings_v1_bindings_proto_goTypes = nil
	file_common_bindings_v1_bindings_proto_depIdxs = nil
}
