import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

import { clientEnv, EnvClientError } from "./client.js";
import { EnvClientError as EnvClientErrorFromEdge } from "./edge.js";
import { EnvClientError as EnvClientErrorFromEnv } from "./index.js";

const SCHEMA_MODULE = resolve("src/env/schema.ts");

const DECLARATIONS = `import { envSchema } from ${JSON.stringify(SCHEMA_MODULE)};
export const schema = envSchema({
  NEXT_PUBLIC_SITE_URL: { class: "plain", client: true },
  NEXT_PUBLIC_PORT: { class: "plain", client: true, schema: z.coerce.number() },
  STRIPE_API_KEY: { class: "sensitive" },
});
`;

const GENERATED = `// Generated by ocel. Do not edit.
import { declared, inlined, type ClientValue } from ${JSON.stringify(SCHEMA_MODULE)};
import * as source0 from "./env.schema.ts";

const schema = { ...declared(source0), };

export const clientEnv: {
  readonly NEXT_PUBLIC_PORT: ClientValue<typeof schema, "NEXT_PUBLIC_PORT">;
  readonly NEXT_PUBLIC_SITE_URL: ClientValue<typeof schema, "NEXT_PUBLIC_SITE_URL">;
} = {
  NEXT_PUBLIC_PORT: inlined(schema, "NEXT_PUBLIC_PORT", process.env.NEXT_PUBLIC_PORT),
  NEXT_PUBLIC_SITE_URL: inlined(schema, "NEXT_PUBLIC_SITE_URL", process.env.NEXT_PUBLIC_SITE_URL),
};
`;

const BUILD_ENV = {
  NEXT_PUBLIC_SITE_URL: "https://example.com",
  NEXT_PUBLIC_PORT: "8080",
  STRIPE_API_KEY: "sk_live_server_only",
};

const restore: Array<() => void> = [];

function withBuildEnv(env: Record<string, string>): void {
  for (const [name, value] of Object.entries(env)) {
    const previous = process.env[name];
    restore.push(() => {
      if (previous === undefined) delete process.env[name];
      else process.env[name] = previous;
    });
    process.env[name] = value;
  }
}

async function load(source: string): Promise<{ clientEnv: Record<string, unknown> }> {
  const dir = mkdtempSync(join(tmpdir(), "ocel-env-client-"));
  writeFileSync(join(dir, "env.schema.ts"), `import { z } from "zod";\n` + DECLARATIONS);
  const file = join(dir, "env-client.ts");
  writeFileSync(file, source);
  return import(pathToFileURL(file).href);
}

afterEach(() => {
  while (restore.length > 0) restore.pop()?.();
});

describe("the generated client accessor", () => {
  it("reads a client-accessible value from the build environment", async () => {
    withBuildEnv(BUILD_ENV);

    const { clientEnv } = await load(GENERATED);

    expect(clientEnv.NEXT_PUBLIC_SITE_URL).toBe("https://example.com");
  });

  it("exposes no server-only value from a build environment holding one", async () => {
    withBuildEnv(BUILD_ENV);

    const { clientEnv } = await load(GENERATED);

    expect(Object.keys(clientEnv)).toEqual(["NEXT_PUBLIC_PORT", "NEXT_PUBLIC_SITE_URL"]);
    expect(JSON.stringify(clientEnv)).not.toContain("sk_live_server_only");
  });

  it("reads each value under the name it was declared with, and no other", () => {
    const reads = GENERATED.match(/process\.env\.[A-Z0-9_]*/g) ?? [];

    expect(reads).toEqual(["process.env.NEXT_PUBLIC_PORT", "process.env.NEXT_PUBLIC_SITE_URL"]);
  });

  it("names no environment entry a server-only value could arrive under", () => {
    expect(GENERATED).not.toContain("STRIPE_API_KEY");
  });

  it("freezes what it read, so a later value does not reach it", async () => {
    withBuildEnv(BUILD_ENV);
    const { clientEnv } = await load(GENERATED);

    process.env.NEXT_PUBLIC_SITE_URL = "https://rotated.example.com";

    expect(clientEnv.NEXT_PUBLIC_SITE_URL).toBe("https://example.com");
  });

  it("refuses to load when a value was never inlined, naming the key", async () => {
    await expect(load(GENERATED)).rejects.toThrow(/NEXT_PUBLIC_PORT/);
    await expect(load(GENERATED)).rejects.toThrow(/inlined/i);
  });

  it("hands back a schema'd value as its schema's output, as the server would", async () => {
    withBuildEnv(BUILD_ENV);

    const { clientEnv } = await load(GENERATED);

    expect(clientEnv.NEXT_PUBLIC_PORT).toBe(8080);
  });

  it("refuses to load a value its schema rejects, naming the key and the complaint", async () => {
    withBuildEnv({ ...BUILD_ENV, NEXT_PUBLIC_PORT: "eighty" });

    await expect(load(GENERATED)).rejects.toThrow(EnvClientError);
    await expect(load(GENERATED)).rejects.toThrow(/NEXT_PUBLIC_PORT/);
    await expect(load(GENERATED)).rejects.toThrow(/number/i);
  });
});

describe("ocel/env/client with no accessor generated", () => {
  it("refuses a read rather than yielding undefined", () => {
    expect(() => clientEnv.PUBLIC_SITE_URL).toThrow(EnvClientError);
    expect(() => clientEnv.PUBLIC_SITE_URL).toThrow(/PUBLIC_SITE_URL/);
    expect(() => clientEnv.PUBLIC_SITE_URL).toThrow(/env-client/);
  });

  it("names both commands that generate the accessor, and names it per app", () => {
    expect(() => clientEnv.PUBLIC_SITE_URL).toThrow(/ocel dev/);
    expect(() => clientEnv.PUBLIC_SITE_URL).toThrow(/ocel deploy/);
    expect(() => clientEnv.PUBLIC_SITE_URL).toThrow(/this app/);
  });

  it("says a config ocel cannot write into is refused, not silently skipped", () => {
    expect(() => clientEnv.PUBLIC_SITE_URL).toThrow(/refuses/);
    expect(() => clientEnv.PUBLIC_SITE_URL).toThrow(/by hand/);
  });

  it("is the same error class `ocel/env` exports, on both node and edge", () => {
    expect(EnvClientErrorFromEnv).toBe(EnvClientError);
    expect(EnvClientErrorFromEdge).toBe(EnvClientError);
  });

  it("answers a runtime's symbol probes, because inspecting is not reading", () => {
    expect(clientEnv[Symbol.toPrimitive as unknown as string]).toBeUndefined();
  });
});
