packages:
  - www
  - console/*
  - cli/node
  - packages/*
  - pkg/transformkit
  - ui/*
  - frameworks/*/*
  - platform/aws/functions/*
  - platform/aws/runtime
  - platform/aws/provider/edges/cloudfront/resolver
  - platform/aws/provider/payloads
  - platform/gcp/provider/payloads
  - platform/gcp/provider/suite
  - platform/vps/provider/host
  - platform/edge/contract
  - platform/edge/cloudflare/workers/*
  - platform/edge/cloudflare/lib/*
  - scripts/*
  - tests/fixtures/*/*
  - tests/fixtures/*/*/apps/*
  - tests/*

catalog:
  next: 16.2.10
  react: 19.2.8
  react-dom: 19.2.8

allowBuilds:
  '@bufbuild/buf': true
  aws-sdk: false
  better-sqlite3: true
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
  workerd: true

linkWorkspacePackages: true

autoInstallPeers: false
