packages:
  - console/*
  - cli/node
  - packages/*
  - frameworks/*/*
  - platform/aws/functions/*
  - platform/edge/contract
  - platform/edge/cloudflare/workers/*
  - platform/edge/cloudflare/lib/*
  - packages/native-lib/*
  - tools/*
  - scripts/*
  - examples/*
  - tests/*

allowBuilds:
  '@bufbuild/buf': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

linkWorkspacePackages: true

autoInstallPeers: false
