// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/resources/v1/variables.proto

package resourcesv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariableClass int32

const (
	VariableClass_VARIABLE_CLASS_UNSPECIFIED VariableClass = 0
	VariableClass_VARIABLE_CLASS_PLAIN       VariableClass = 1
	VariableClass_VARIABLE_CLASS_SENSITIVE   VariableClass = 2
	VariableClass_VARIABLE_CLASS_SECRET      VariableClass = 3
	VariableClass_VARIABLE_CLASS_DERIVED     VariableClass = 4
)

// Enum value maps for VariableClass.
var (
	VariableClass_name = map[int32]string{
		0: "VARIABLE_CLASS_UNSPECIFIED",
		1: "VARIABLE_CLASS_PLAIN",
		2: "VARIABLE_CLASS_SENSITIVE",
		3: "VARIABLE_CLASS_SECRET",
		4: "VARIABLE_CLASS_DERIVED",
	}
	VariableClass_value = map[string]int32{
		"VARIABLE_CLASS_UNSPECIFIED": 0,
		"VARIABLE_CLASS_PLAIN":       1,
		"VARIABLE_CLASS_SENSITIVE":   2,
		"VARIABLE_CLASS_SECRET":      3,
		"VARIABLE_CLASS_DERIVED":     4,
	}
)

func (x VariableClass) Enum() *VariableClass {
	p := new(VariableClass)
	*p = x
	return p
}

func (x VariableClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariableClass) Descriptor() protoreflect.EnumDescriptor {
	return file_app_resources_v1_variables_proto_enumTypes[0].Descriptor()
}

func (VariableClass) Type() protoreflect.EnumType {
	return &file_app_resources_v1_variables_proto_enumTypes[0]
}

func (x VariableClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariableClass.Descriptor instead.
func (VariableClass) EnumDescriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{0}
}

type VariableProblem_Kind int32

const (
	VariableProblem_KIND_UNSPECIFIED VariableProblem_Kind = 0
	VariableProblem_KIND_MISSING     VariableProblem_Kind = 1
	VariableProblem_KIND_INVALID     VariableProblem_Kind = 2
)

// Enum value maps for VariableProblem_Kind.
var (
	VariableProblem_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_MISSING",
		2: "KIND_INVALID",
	}
	VariableProblem_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_MISSING":     1,
		"KIND_INVALID":     2,
	}
)

func (x VariableProblem_Kind) Enum() *VariableProblem_Kind {
	p := new(VariableProblem_Kind)
	*p = x
	return p
}

func (x VariableProblem_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariableProblem_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_app_resources_v1_variables_proto_enumTypes[1].Descriptor()
}

func (VariableProblem_Kind) Type() protoreflect.EnumType {
	return &file_app_resources_v1_variables_proto_enumTypes[1]
}

func (x VariableProblem_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariableProblem_Kind.Descriptor instead.
func (VariableProblem_Kind) EnumDescriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{4, 0}
}

type VariableDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Class            VariableClass          `protobuf:"varint,2,opt,name=class,proto3,enum=app.resources.v1.VariableClass" json:"class,omitempty"`
	ClientAccessible bool                   `protobuf:"varint,3,opt,name=client_accessible,json=clientAccessible,proto3" json:"client_accessible,omitempty"`
	Required         bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Folders          []string               `protobuf:"bytes,5,rep,name=folders,proto3" json:"folders,omitempty"`
	Source           string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	// The module that holds the declaration's schemas without calling defineEnv,
	// when one does; empty when the schemas live beside the call.
	SchemaSource  string `protobuf:"bytes,7,opt,name=schema_source,json=schemaSource,proto3" json:"schema_source,omitempty"`
	HasSchema     bool   `protobuf:"varint,8,opt,name=has_schema,json=hasSchema,proto3" json:"has_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableDefinition) Reset() {
	*x = VariableDefinition{}
	mi := &file_app_resources_v1_variables_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableDefinition) ProtoMessage() {}

func (x *VariableDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_app_resources_v1_variables_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableDefinition.ProtoReflect.Descriptor instead.
func (*VariableDefinition) Descriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{0}
}

func (x *VariableDefinition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VariableDefinition) GetClass() VariableClass {
	if x != nil {
		return x.Class
	}
	return VariableClass_VARIABLE_CLASS_UNSPECIFIED
}

func (x *VariableDefinition) GetClientAccessible() bool {
	if x != nil {
		return x.ClientAccessible
	}
	return false
}

func (x *VariableDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *VariableDefinition) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *VariableDefinition) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *VariableDefinition) GetSchemaSource() string {
	if x != nil {
		return x.SchemaSource
	}
	return ""
}

func (x *VariableDefinition) GetHasSchema() bool {
	if x != nil {
		return x.HasSchema
	}
	return false
}

type DeclareEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definitions   []*VariableDefinition  `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareEnvRequest) Reset() {
	*x = DeclareEnvRequest{}
	mi := &file_app_resources_v1_variables_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareEnvRequest) ProtoMessage() {}

func (x *DeclareEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_resources_v1_variables_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareEnvRequest.ProtoReflect.Descriptor instead.
func (*DeclareEnvRequest) Descriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{1}
}

func (x *DeclareEnvRequest) GetDefinitions() []*VariableDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

type VariableCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableCell) Reset() {
	*x = VariableCell{}
	mi := &file_app_resources_v1_variables_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableCell) ProtoMessage() {}

func (x *VariableCell) ProtoReflect() protoreflect.Message {
	mi := &file_app_resources_v1_variables_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableCell.ProtoReflect.Descriptor instead.
func (*VariableCell) Descriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{2}
}

func (x *VariableCell) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VariableCell) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *VariableCell) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeclareEnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*VariableCell        `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareEnvResponse) Reset() {
	*x = DeclareEnvResponse{}
	mi := &file_app_resources_v1_variables_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareEnvResponse) ProtoMessage() {}

func (x *DeclareEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_resources_v1_variables_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareEnvResponse.ProtoReflect.Descriptor instead.
func (*DeclareEnvResponse) Descriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{3}
}

func (x *DeclareEnvResponse) GetCells() []*VariableCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type VariableProblem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Kind          VariableProblem_Kind   `protobuf:"varint,3,opt,name=kind,proto3,enum=app.resources.v1.VariableProblem_Kind" json:"kind,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableProblem) Reset() {
	*x = VariableProblem{}
	mi := &file_app_resources_v1_variables_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableProblem) ProtoMessage() {}

func (x *VariableProblem) ProtoReflect() protoreflect.Message {
	mi := &file_app_resources_v1_variables_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableProblem.ProtoReflect.Descriptor instead.
func (*VariableProblem) Descriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{4}
}

func (x *VariableProblem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VariableProblem) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *VariableProblem) GetKind() VariableProblem_Kind {
	if x != nil {
		return x.Kind
	}
	return VariableProblem_KIND_UNSPECIFIED
}

func (x *VariableProblem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ReportEnvProblemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problems      []*VariableProblem     `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEnvProblemsRequest) Reset() {
	*x = ReportEnvProblemsRequest{}
	mi := &file_app_resources_v1_variables_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEnvProblemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEnvProblemsRequest) ProtoMessage() {}

func (x *ReportEnvProblemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_resources_v1_variables_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEnvProblemsRequest.ProtoReflect.Descriptor instead.
func (*ReportEnvProblemsRequest) Descriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{5}
}

func (x *ReportEnvProblemsRequest) GetProblems() []*VariableProblem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type ReportEnvProblemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEnvProblemsResponse) Reset() {
	*x = ReportEnvProblemsResponse{}
	mi := &file_app_resources_v1_variables_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEnvProblemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEnvProblemsResponse) ProtoMessage() {}

func (x *ReportEnvProblemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_resources_v1_variables_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEnvProblemsResponse.ProtoReflect.Descriptor instead.
func (*ReportEnvProblemsResponse) Descriptor() ([]byte, []int) {
	return file_app_resources_v1_variables_proto_rawDescGZIP(), []int{6}
}

var File_app_resources_v1_variables_proto protoreflect.FileDescriptor

const file_app_resources_v1_variables_proto_rawDesc = "" +
	"\n" +
	" app/resources/v1/variables.proto\x12\x10app.resources.v1\x1a\x1bbuf/validate/validate.proto\"\xe6\x02\n" +
	"\x12VariableDefinition\x12+\n" +
	"\x03key\x18\x01 \x01(\tB\x19\xbaH\x16r\x14\x10\x012\x10^[^#[:cntrl:]]*$R\x03key\x12?\n" +
	"\x05class\x18\x02 \x01(\x0e2\x1f.app.resources.v1.VariableClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x12+\n" +
	"\x11client_accessible\x18\x03 \x01(\bR\x10clientAccessible\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12=\n" +
	"\afolders\x18\x05 \x03(\tB#\xbaH \x92\x01\x1d\x18\x01\"\x19r\x172\x15^(/[^/#[:cntrl:]]+)+$R\afolders\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12#\n" +
	"\rschema_source\x18\a \x01(\tR\fschemaSource\x12\x1d\n" +
	"\n" +
	"has_schema\x18\b \x01(\bR\thasSchema\"[\n" +
	"\x11DeclareEnvRequest\x12F\n" +
	"\vdefinitions\x18\x01 \x03(\v2$.app.resources.v1.VariableDefinitionR\vdefinitions\"\x87\x01\n" +
	"\fVariableCell\x12+\n" +
	"\x03key\x18\x01 \x01(\tB\x19\xbaH\x16r\x14\x10\x012\x10^[^#[:cntrl:]]*$R\x03key\x124\n" +
	"\x06folder\x18\x02 \x01(\tB\x1c\xbaH\x19r\x172\x15^(/[^/#[:cntrl:]]+)*$R\x06folder\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"J\n" +
	"\x12DeclareEnvResponse\x124\n" +
	"\x05cells\x18\x01 \x03(\v2\x1e.app.resources.v1.VariableCellR\x05cells\"\xf9\x01\n" +
	"\x0fVariableProblem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x06folder\x18\x02 \x01(\tB\x1c\xbaH\x19r\x172\x15^(/[^/#[:cntrl:]]+)*$R\x06folder\x12D\n" +
	"\x04kind\x18\x03 \x01(\x0e2&.app.resources.v1.VariableProblem.KindB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04kind\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"@\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fKIND_MISSING\x10\x01\x12\x10\n" +
	"\fKIND_INVALID\x10\x02\"Y\n" +
	"\x18ReportEnvProblemsRequest\x12=\n" +
	"\bproblems\x18\x01 \x03(\v2!.app.resources.v1.VariableProblemR\bproblems\"\x1b\n" +
	"\x19ReportEnvProblemsResponse*\x9e\x01\n" +
	"\rVariableClass\x12\x1e\n" +
	"\x1aVARIABLE_CLASS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14VARIABLE_CLASS_PLAIN\x10\x01\x12\x1c\n" +
	"\x18VARIABLE_CLASS_SENSITIVE\x10\x02\x12\x19\n" +
	"\x15VARIABLE_CLASS_SECRET\x10\x03\x12\x1a\n" +
	"\x16VARIABLE_CLASS_DERIVED\x10\x04B?Z=github.com/ocelhq/ocel/pkg/proto/app/resources/v1;resourcesv1b\x06proto3"

var (
	file_app_resources_v1_variables_proto_rawDescOnce sync.Once
	file_app_resources_v1_variables_proto_rawDescData []byte
)

func file_app_resources_v1_variables_proto_rawDescGZIP() []byte {
	file_app_resources_v1_variables_proto_rawDescOnce.Do(func() {
		file_app_resources_v1_variables_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_resources_v1_variables_proto_rawDesc), len(file_app_resources_v1_variables_proto_rawDesc)))
	})
	return file_app_resources_v1_variables_proto_rawDescData
}

var file_app_resources_v1_variables_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_resources_v1_variables_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_resources_v1_variables_proto_goTypes = []any{
	(VariableClass)(0),                // 0: app.resources.v1.VariableClass
	(VariableProblem_Kind)(0),         // 1: app.resources.v1.VariableProblem.Kind
	(*VariableDefinition)(nil),        // 2: app.resources.v1.VariableDefinition
	(*DeclareEnvRequest)(nil),         // 3: app.resources.v1.DeclareEnvRequest
	(*VariableCell)(nil),              // 4: app.resources.v1.VariableCell
	(*DeclareEnvResponse)(nil),        // 5: app.resources.v1.DeclareEnvResponse
	(*VariableProblem)(nil),           // 6: app.resources.v1.VariableProblem
	(*ReportEnvProblemsRequest)(nil),  // 7: app.resources.v1.ReportEnvProblemsRequest
	(*ReportEnvProblemsResponse)(nil), // 8: app.resources.v1.ReportEnvProblemsResponse
}
var file_app_resources_v1_variables_proto_depIdxs = []int32{
	0, // 0: app.resources.v1.VariableDefinition.class:type_name -> app.resources.v1.VariableClass
	2, // 1: app.resources.v1.DeclareEnvRequest.definitions:type_name -> app.resources.v1.VariableDefinition
	4, // 2: app.resources.v1.DeclareEnvResponse.cells:type_name -> app.resources.v1.VariableCell
	1, // 3: app.resources.v1.VariableProblem.kind:type_name -> app.resources.v1.VariableProblem.Kind
	6, // 4: app.resources.v1.ReportEnvProblemsRequest.problems:type_name -> app.resources.v1.VariableProblem
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_app_resources_v1_variables_proto_init() }
func file_app_resources_v1_variables_proto_init() {
	if File_app_resources_v1_variables_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_resources_v1_variables_proto_rawDesc), len(file_app_resources_v1_variables_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_resources_v1_variables_proto_goTypes,
		DependencyIndexes: file_app_resources_v1_variables_proto_depIdxs,
		EnumInfos:         file_app_resources_v1_variables_proto_enumTypes,
		MessageInfos:      file_app_resources_v1_variables_proto_msgTypes,
	}.Build()
	File_app_resources_v1_variables_proto = out.File
	file_app_resources_v1_variables_proto_goTypes = nil
	file_app_resources_v1_variables_proto_depIdxs = nil
}
