package clientenv

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/ocelhq/ocel/cli/internal/manifestbuilder"
	resourcesv1 "github.com/ocelhq/ocel/pkg/proto/app/resources/v1"
	"github.com/ocelhq/ocel/pkg/providerkit"
)

const specifier = "ocel/env/client"

var accessorPath = filepath.Join(".ocel", "env-client.ts")

var configFiles = []string{"tsconfig.json", "jsconfig.json"}

var recordPath = filepath.Join(".ocel", "output", "client-digests.json")

type App struct {
	Name      string
	Dir       string
	Variables []manifestbuilder.Variable
}

type Key struct {
	Name   string
	Source string
}

func Generate(apps []App) error {
	for _, app := range apps {
		keys, err := Keys(app.Variables)
		if err != nil {
			return err
		}
		if err := GenerateKeys(app.Dir, keys); err != nil {
			return err
		}
	}
	return nil
}

func GenerateKeys(dir string, keys []Key) error {
	path := filepath.Join(dir, accessorPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(accessorPath), err)
	}
	if err := os.WriteFile(path, []byte(accessor(filepath.Dir(path), keys)), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", accessorPath, err)
	}
	return mapSpecifier(dir)
}

const schemaSpecifier = "ocel/env/schema"

func accessor(from string, keys []Key) string {
	sources := sources(keys)
	var b strings.Builder
	b.WriteString("// Generated by ocel. Do not edit.\n")
	if len(sources) == 0 {
		b.WriteString("import { inlined, type ClientValue } from \"" + schemaSpecifier + "\";\n")
	} else {
		b.WriteString("import { declared, inlined, type ClientValue } from \"" + schemaSpecifier + "\";\n")
	}
	for i, source := range sources {
		fmt.Fprintf(&b, "import * as source%d from %q;\n", i, specifierFor(from, source))
	}
	b.WriteString("\nconst schema = {")
	for i := range sources {
		fmt.Fprintf(&b, " ...declared(source%d),", i)
	}
	b.WriteString(" };\n\nexport const clientEnv: {\n")
	for _, key := range keys {
		fmt.Fprintf(&b, "  readonly %s: ClientValue<typeof schema, %q>;\n", key.Name, key.Name)
	}
	b.WriteString("} = {\n")
	for _, key := range keys {
		fmt.Fprintf(&b, "  %s: inlined(schema, %q, process.env.%s),\n", key.Name, key.Name, key.Name)
	}
	b.WriteString("};\n")
	return b.String()
}

func sources(keys []Key) []string {
	var out []string
	for _, key := range keys {
		if key.Source != "" && !slices.Contains(out, key.Source) {
			out = append(out, key.Source)
		}
	}
	slices.Sort(out)
	return out
}

func specifierFor(from, source string) string {
	rel, err := filepath.Rel(from, source)
	if err != nil {
		rel = source
	}
	rel = filepath.ToSlash(strings.TrimSuffix(rel, filepath.Ext(rel)))
	if !strings.HasPrefix(rel, ".") {
		rel = "./" + rel
	}
	return rel
}

func mapSpecifier(dir string) error {
	for _, name := range configFiles {
		path := filepath.Join(dir, name)
		source, err := os.ReadFile(path)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}

		updated, err := withMapping(path, string(source))
		if err != nil {
			return err
		}
		if updated == string(source) {
			return nil
		}
		if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
		return nil
	}
	return nil
}

type buildRecord struct {
	Digests map[string]map[string]string `json:"digests,omitempty"`
}

func Record(projectDir string, apps []App) error {
	record := buildRecord{Digests: make(map[string]map[string]string, len(apps))}
	for _, app := range apps {
		record.Digests[app.Name] = digests(app)
	}
	return writeRecord(projectDir, record)
}

func writeRecord(projectDir string, record buildRecord) error {
	data, err := json.Marshal(record)
	if err != nil {
		return err
	}
	path := filepath.Join(projectDir, recordPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func CheckFresh(projectDir string, apps []App) error {
	record, err := readRecord(projectDir)
	if err != nil {
		return err
	}

	var missing, changed []string
	for _, app := range apps {
		recorded := record.Digests[app.Name]
		for key, digest := range digests(app) {
			built, ok := recorded[key]
			switch {
			case !ok:
				missing = append(missing, key)
			case built != digest:
				changed = append(changed, key)
			}
		}
	}
	if len(missing) == 0 && len(changed) == 0 {
		return nil
	}
	slices.Sort(missing)
	slices.Sort(changed)

	var causes []string
	if len(missing) > 0 {
		causes = append(causes, fmt.Sprintf(
			"%s %s never inlined — either not client-accessible when .ocel/output was built, or built by `ocel build`, which resolves no values",
			strings.Join(missing, ", "), were(missing),
		))
	}
	if len(changed) > 0 {
		causes = append(causes, fmt.Sprintf("the client-accessible value of %s changed since .ocel/output was built", strings.Join(changed, ", ")))
	}
	return fmt.Errorf(
		"--prebuilt cannot deploy this build: %s. "+
			"A client value is inlined into the browser bundle at build time, so this deploy would serve browsers something other than what its server holds. "+
			"Deploy without --prebuilt to build with the values this deploy resolved",
		strings.Join(causes, ", and "),
	)
}

func were(keys []string) string {
	if len(keys) == 1 {
		return "was"
	}
	return "were"
}

func readRecord(projectDir string) (buildRecord, error) {
	data, err := os.ReadFile(filepath.Join(projectDir, recordPath))
	if errors.Is(err, fs.ErrNotExist) {
		return buildRecord{}, nil
	}
	if err != nil {
		return buildRecord{}, err
	}
	var record buildRecord
	if err := json.Unmarshal(data, &record); err != nil {
		return buildRecord{}, fmt.Errorf("read %s: %w", recordPath, err)
	}
	return record, nil
}

func Keys(variables []manifestbuilder.Variable) ([]Key, error) {
	keys := make([]Key, 0, len(variables))
	for _, v := range variables {
		if !isClient(v) {
			continue
		}
		key, err := key(v.Key, v.Source, v.SchemaSource, v.Schema)
		if err != nil {
			return nil, err
		}
		keys = append(keys, key)
	}
	return withBuiltIn(keys), nil
}

func key(name, source, schemaSource string, schema bool) (Key, error) {
	if schemaSource != "" && schemaSource != source {
		return Key{Name: name, Source: schemaSource}, nil
	}
	if schema {
		return Key{}, fmt.Errorf(
			"%s is client-accessible and declared with a schema in %s, which calls defineEnv. "+
				"A browser bundle cannot import that module for the schema without the server's environment coming with it: "+
				"declare the variables with envSchema from '%s' in a module of their own, and hand that module's export to defineEnv",
			name, sourceOrUnknown(source), schemaSpecifier)
	}
	return Key{Name: name}, nil
}

func sourceOrUnknown(source string) string {
	if source == "" {
		return "the module calling defineEnv"
	}
	return source
}

func withBuiltIn(keys []Key) []Key {
	keys = append(keys, Key{Name: providerkit.ClientURLEnvName})
	slices.SortFunc(keys, func(a, b Key) int { return strings.Compare(a.Name, b.Name) })
	return slices.CompactFunc(keys, func(a, b Key) bool { return a.Name == b.Name })
}

func isClient(v manifestbuilder.Variable) bool {
	return v.ClientAccessible && v.Class == resourcesv1.VariableClass_VARIABLE_CLASS_PLAIN
}

func Declared(definitions []*resourcesv1.VariableDefinition) ([]Key, error) {
	var keys []Key
	for _, definition := range definitions {
		if !definition.GetClientAccessible() || definition.GetClass() != resourcesv1.VariableClass_VARIABLE_CLASS_PLAIN {
			continue
		}
		key, err := key(definition.GetKey(), definition.GetSource(), definition.GetSchemaSource(), definition.GetHasSchema())
		if err != nil {
			return nil, err
		}
		keys = append(keys, key)
	}
	return withBuiltIn(keys), nil
}

func digests(app App) map[string]string {
	out := map[string]string{}
	for _, v := range app.Variables {
		if !isClient(v) {
			continue
		}
		sum := sha256.Sum256([]byte(v.Value))
		out[v.Key] = hex.EncodeToString(sum[:])
	}
	return out
}
