package clientenv

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/ocelhq/ocel/cli/internal/manifestbuilder"
	resourcesv1 "github.com/ocelhq/ocel/pkg/proto/app/resources/v1"
)

const specifier = "ocel/env/client"

var accessorPath = filepath.Join(".ocel", "env-client.ts")

var configFiles = []string{"tsconfig.json", "jsconfig.json"}

var recordPath = filepath.Join(".ocel", "output", "client-values.json")

type App struct {
	Name      string
	Dir       string
	Variables []manifestbuilder.Variable
}

func Generate(apps []App) error {
	for _, app := range apps {
		if err := GenerateKeys(app.Dir, clientKeys(app)); err != nil {
			return err
		}
	}
	return nil
}

func GenerateKeys(dir string, keys []string) error {
	path := filepath.Join(dir, accessorPath)
	if len(keys) == 0 {
		if _, err := os.Stat(path); errors.Is(err, fs.ErrNotExist) {
			return nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create %s: %w", filepath.Dir(accessorPath), err)
	}
	if err := os.WriteFile(path, []byte(accessor(keys)), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", accessorPath, err)
	}
	return mapSpecifier(dir)
}

const inlinedHelper = `const inlined = (key: string, value: string | undefined): string => {
  if (value !== undefined) return value;
  const error = new Error(
    "'" + key + "' is client-accessible, but no value was inlined into this bundle. A bundler inlines only the names matching its own public convention (NEXT_PUBLIC_* under Next, VITE_* under Vite); rename the variable to one of those, or read it on the server instead."
  );
  error.name = "EnvClientError";
  throw error;
};
`

func accessor(keys []string) string {
	var b strings.Builder
	b.WriteString("// Generated by ocel. Do not edit.\n")
	if len(keys) > 0 {
		b.WriteString(inlinedHelper + "\n")
	}
	b.WriteString("export const clientEnv = {\n")
	for _, key := range keys {
		b.WriteString("  " + key + `: inlined("` + key + `", process.env.` + key + "),\n")
	}
	b.WriteString("};\n")
	return b.String()
}

func mapSpecifier(dir string) error {
	for _, name := range configFiles {
		path := filepath.Join(dir, name)
		source, err := os.ReadFile(path)
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}

		updated, err := withMapping(path, string(source))
		if err != nil {
			return err
		}
		if updated == string(source) {
			return nil
		}
		if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
		return nil
	}
	return nil
}

type buildRecord struct {
	Resolved bool                         `json:"resolved"`
	Inlined  map[string]map[string]string `json:"inlined,omitempty"`
}

func Record(projectDir string, apps []App) error {
	record := buildRecord{Resolved: true, Inlined: make(map[string]map[string]string, len(apps))}
	for _, app := range apps {
		record.Inlined[app.Name] = digests(app)
	}
	return writeRecord(projectDir, record)
}

func RecordUnresolved(projectDir string) error {
	return writeRecord(projectDir, buildRecord{})
}

func writeRecord(projectDir string, record buildRecord) error {
	data, err := json.Marshal(record)
	if err != nil {
		return err
	}
	path := filepath.Join(projectDir, recordPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func CheckFresh(projectDir string, apps []App) error {
	record, err := readRecord(projectDir)
	if err != nil {
		return err
	}

	var missing, changed []string
	for _, app := range apps {
		inlined := record.Inlined[app.Name]
		for key, digest := range digests(app) {
			built, ok := inlined[key]
			switch {
			case !record.Resolved || !ok:
				missing = append(missing, key)
			case built != digest:
				changed = append(changed, key)
			}
		}
	}
	if len(missing) == 0 && len(changed) == 0 {
		return nil
	}
	slices.Sort(missing)
	slices.Sort(changed)

	var causes []string
	if len(missing) > 0 {
		cause := "it was not client-accessible when .ocel/output was built"
		if !record.Resolved {
			cause = "`ocel build` resolves no values"
		}
		causes = append(causes, fmt.Sprintf("%s %s never inlined — %s", strings.Join(missing, ", "), were(missing), cause))
	}
	if len(changed) > 0 {
		causes = append(causes, fmt.Sprintf("the client-accessible value of %s changed since .ocel/output was built", strings.Join(changed, ", ")))
	}
	return fmt.Errorf(
		"--prebuilt cannot deploy this build: %s. "+
			"A client value is inlined into the browser bundle at build time, so this deploy would serve browsers something other than what its server holds. "+
			"Deploy without --prebuilt to build with the values this deploy resolved",
		strings.Join(causes, ", and "),
	)
}

func were(keys []string) string {
	if len(keys) == 1 {
		return "was"
	}
	return "were"
}

func readRecord(projectDir string) (buildRecord, error) {
	data, err := os.ReadFile(filepath.Join(projectDir, recordPath))
	if errors.Is(err, fs.ErrNotExist) {
		return buildRecord{}, nil
	}
	if err != nil {
		return buildRecord{}, err
	}
	var record buildRecord
	if err := json.Unmarshal(data, &record); err != nil {
		return buildRecord{}, fmt.Errorf("read %s: %w", recordPath, err)
	}
	return record, nil
}

func clientKeys(app App) []string {
	keys := make([]string, 0, len(app.Variables))
	for _, v := range app.Variables {
		if isClient(v) {
			keys = append(keys, v.Key)
		}
	}
	slices.Sort(keys)
	return keys
}

func isClient(v manifestbuilder.Variable) bool {
	return v.ClientAccessible && v.Class == resourcesv1.VariableClass_VARIABLE_CLASS_PLAIN
}

func DeclaredKeys(definitions []*resourcesv1.VariableDefinition) []string {
	var keys []string
	for _, definition := range definitions {
		if definition.GetClientAccessible() && definition.GetClass() == resourcesv1.VariableClass_VARIABLE_CLASS_PLAIN {
			keys = append(keys, definition.GetKey())
		}
	}
	slices.Sort(keys)
	return keys
}

func digests(app App) map[string]string {
	out := map[string]string{}
	for _, v := range app.Variables {
		if !isClient(v) {
			continue
		}
		sum := sha256.Sum256([]byte(v.Value))
		out[v.Key] = hex.EncodeToString(sum[:])
	}
	return out
}
