package clientenv

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ocelhq/ocel/cli/internal/manifestbuilder"
	resourcesv1 "github.com/ocelhq/ocel/pkg/proto/app/resources/v1"
)

func clientVar(key, value string) manifestbuilder.Variable {
	return manifestbuilder.Variable{
		Key:              key,
		Class:            resourcesv1.VariableClass_VARIABLE_CLASS_PLAIN,
		Value:            value,
		ClientAccessible: true,
	}
}

func serverVar(key, value string) manifestbuilder.Variable {
	return manifestbuilder.Variable{
		Key:   key,
		Class: resourcesv1.VariableClass_VARIABLE_CLASS_SENSITIVE,
		Value: value,
	}
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func appDir(t *testing.T) string {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "tsconfig.json"), "{\n  \"compilerOptions\": {\n    \"strict\": true\n  },\n  \"include\": [\"**/*.ts\"]\n}\n")
	return dir
}

func TestGenerate(t *testing.T) {
	t.Parallel()

	t.Run("writes the accessor the SDK pins", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)

		if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("NEXT_PUBLIC_SITE_URL", "https://example.com")}}}); err != nil {
			t.Fatalf("Generate: %v", err)
		}

		want := "// Generated by ocel. Do not edit.\n" +
			"import { inlined, type ClientValue } from \"ocel/env/schema\";\n" +
			"\n" +
			"const schema = { };\n" +
			"\n" +
			"export const clientEnv: {\n" +
			"  readonly NEXT_PUBLIC_OCEL_URL: ClientValue<typeof schema, \"NEXT_PUBLIC_OCEL_URL\">;\n" +
			"  readonly NEXT_PUBLIC_SITE_URL: ClientValue<typeof schema, \"NEXT_PUBLIC_SITE_URL\">;\n" +
			"} = {\n" +
			"  NEXT_PUBLIC_OCEL_URL: inlined(schema, \"NEXT_PUBLIC_OCEL_URL\", process.env.NEXT_PUBLIC_OCEL_URL),\n" +
			"  NEXT_PUBLIC_SITE_URL: inlined(schema, \"NEXT_PUBLIC_SITE_URL\", process.env.NEXT_PUBLIC_SITE_URL),\n" +
			"};\n"
		if got := read(t, filepath.Join(dir, ".ocel", "env-client.ts")); got != want {
			t.Errorf("accessor =\n%q\nwant\n%q", got, want)
		}
	})

	t.Run("reaches a schema through the module that declares it without defineEnv", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)
		schemaModule := filepath.Join(dir, "src", "env.schema.ts")
		envModule := filepath.Join(dir, "src", "env.ts")
		port := clientVar("NEXT_PUBLIC_PORT", "8080")
		port.Source, port.SchemaSource, port.Schema = envModule, schemaModule, true
		site := clientVar("NEXT_PUBLIC_SITE_URL", "https://example.com")
		site.Source, site.SchemaSource = envModule, schemaModule

		if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{site, port}}}); err != nil {
			t.Fatalf("Generate: %v", err)
		}

		want := "// Generated by ocel. Do not edit.\n" +
			"import { declared, inlined, type ClientValue } from \"ocel/env/schema\";\n" +
			"import * as source0 from \"../src/env.schema\";\n" +
			"\n" +
			"const schema = { ...declared(source0), };\n" +
			"\n" +
			"export const clientEnv: {\n" +
			"  readonly NEXT_PUBLIC_OCEL_URL: ClientValue<typeof schema, \"NEXT_PUBLIC_OCEL_URL\">;\n" +
			"  readonly NEXT_PUBLIC_PORT: ClientValue<typeof schema, \"NEXT_PUBLIC_PORT\">;\n" +
			"  readonly NEXT_PUBLIC_SITE_URL: ClientValue<typeof schema, \"NEXT_PUBLIC_SITE_URL\">;\n" +
			"} = {\n" +
			"  NEXT_PUBLIC_OCEL_URL: inlined(schema, \"NEXT_PUBLIC_OCEL_URL\", process.env.NEXT_PUBLIC_OCEL_URL),\n" +
			"  NEXT_PUBLIC_PORT: inlined(schema, \"NEXT_PUBLIC_PORT\", process.env.NEXT_PUBLIC_PORT),\n" +
			"  NEXT_PUBLIC_SITE_URL: inlined(schema, \"NEXT_PUBLIC_SITE_URL\", process.env.NEXT_PUBLIC_SITE_URL),\n" +
			"};\n"
		if got := read(t, filepath.Join(dir, ".ocel", "env-client.ts")); got != want {
			t.Errorf("accessor =\n%s\nwant\n%s", got, want)
		}
	})

	t.Run("imports every module keys were declared in, once each, wherever it lives", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)
		shared := filepath.Join(filepath.Dir(dir), "packages", "env", "index.ts")
		local := filepath.Join(dir, "env.schema.tsx")
		a, b, c := clientVar("PUBLIC_A", "1"), clientVar("PUBLIC_B", "2"), clientVar("PUBLIC_C", "3")
		a.SchemaSource, a.Schema = shared, true
		b.SchemaSource, b.Schema = local, true
		c.SchemaSource = shared

		if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{a, b, c}}}); err != nil {
			t.Fatalf("Generate: %v", err)
		}

		accessor := read(t, filepath.Join(dir, ".ocel", "env-client.ts"))
		for _, want := range []string{
			" from \"../../packages/env/index\";\n",
			" from \"../env.schema\";\n",
			"const schema = { ...declared(source0), ...declared(source1), };\n",
		} {
			if !strings.Contains(accessor, want) {
				t.Errorf("accessor =\n%s\nwant it to contain %q", accessor, want)
			}
		}
		if n := strings.Count(accessor, "import * as source"); n != 2 {
			t.Errorf("accessor imports %d modules, want one per module keys were declared in", n)
		}
	})

	t.Run("refuses a schema'd client key declared beside defineEnv, naming the way out", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)
		for _, tc := range []struct {
			name   string
			source string
			schema string
		}{
			{name: "declared inline", source: "/app/src/env.ts"},
			{name: "envSchema in the defineEnv module", source: "/app/src/env.ts", schema: "/app/src/env.ts"},
		} {
			t.Run(tc.name, func(t *testing.T) {
				port := clientVar("NEXT_PUBLIC_PORT", "8080")
				port.Source, port.SchemaSource, port.Schema = tc.source, tc.schema, true

				err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{port}}})
				if err == nil {
					t.Fatal("Generate = nil, want a refusal: the browser bundle has no side-effect-free module to take the schema from")
				}
				for _, want := range []string{"NEXT_PUBLIC_PORT", "/app/src/env.ts", "envSchema", "ocel/env/schema"} {
					if !strings.Contains(err.Error(), want) {
						t.Errorf("error = %q, want it to mention %q", err, want)
					}
				}
			})
		}
	})

	t.Run("reads each key under its declared name", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)

		err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{
			clientVar("NEXT_PUBLIC_APP_ID", "app_1"),
			clientVar("VITE_APP_ID", "app_2"),
		}}})
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}

		accessor := read(t, filepath.Join(dir, ".ocel", "env-client.ts"))
		for _, want := range []string{"process.env.NEXT_PUBLIC_APP_ID", "process.env.VITE_APP_ID"} {
			if !strings.Contains(accessor, want) {
				t.Errorf("accessor =\n%s\nwant a read of %s", accessor, want)
			}
		}
		if strings.Contains(accessor, "NEXT_PUBLIC_VITE_APP_ID") {
			t.Errorf("accessor =\n%s\nwant no prefix added to a declared name", accessor)
		}
	})

	t.Run("names no server-only value", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)

		err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{
			clientVar("PUBLIC_SITE_URL", "https://example.com"),
			serverVar("STRIPE_API_KEY", "sk-live"),
		}}})
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}

		accessor := read(t, filepath.Join(dir, ".ocel", "env-client.ts"))
		if strings.Contains(accessor, "STRIPE_API_KEY") {
			t.Errorf("accessor names a server-only value:\n%s", accessor)
		}
		if strings.Contains(accessor, "sk-live") {
			t.Errorf("accessor carries a resolved value; it must name the environment entry only:\n%s", accessor)
		}
	})

	t.Run("points the import specifier at the generated file", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)

		if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}); err != nil {
			t.Fatalf("Generate: %v", err)
		}

		tsconfig := read(t, filepath.Join(dir, "tsconfig.json"))
		if !strings.Contains(tsconfig, `"ocel/env/client": ["./.ocel/env-client.ts"]`) {
			t.Errorf("tsconfig does not map the specifier at the generated file:\n%s", tsconfig)
		}
		if !strings.Contains(tsconfig, `"strict": true`) || !strings.Contains(tsconfig, `"include"`) {
			t.Errorf("tsconfig lost what the user wrote:\n%s", tsconfig)
		}
	})

	t.Run("keeps what the user wrote around it", func(t *testing.T) {
		t.Parallel()

		dir := t.TempDir()
		source := "{\n  // the compiler options this project has always had\n  \"compilerOptions\": {\n    \"paths\": {\n      \"@/*\": [\"./src/*\"] // app aliases\n    }\n  }\n}\n"
		write(t, filepath.Join(dir, "tsconfig.json"), source)

		if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}); err != nil {
			t.Fatalf("Generate: %v", err)
		}

		tsconfig := read(t, filepath.Join(dir, "tsconfig.json"))
		for _, want := range []string{
			"// the compiler options this project has always had",
			"// app aliases",
			`"@/*": ["./src/*"]`,
			`"ocel/env/client": ["./.ocel/env-client.ts"]`,
		} {
			if !strings.Contains(tsconfig, want) {
				t.Errorf("tsconfig lost %q:\n%s", want, tsconfig)
			}
		}
	})

	t.Run("leaves every starting shape parseable", func(t *testing.T) {
		t.Parallel()

		for name, source := range map[string]string{
			"empty":              "{}\n",
			"no compilerOptions": "{\n  \"include\": [\"**/*.ts\"]\n}\n",
			"empty paths":        "{\n  \"compilerOptions\": {\n    \"paths\": {}\n  }\n}\n",
		} {
			t.Run(name, func(t *testing.T) {
				t.Parallel()

				dir := t.TempDir()
				write(t, filepath.Join(dir, "tsconfig.json"), source)

				if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}); err != nil {
					t.Fatalf("Generate: %v", err)
				}

				updated := read(t, filepath.Join(dir, "tsconfig.json"))
				var parsed struct {
					CompilerOptions struct {
						Paths map[string][]string `json:"paths"`
					} `json:"compilerOptions"`
				}
				if err := json.Unmarshal([]byte(updated), &parsed); err != nil {
					t.Fatalf("tsconfig is no longer parseable (%v):\n%s", err, updated)
				}
				want, err := accessorTarget("")
				if err != nil {
					t.Fatal(err)
				}
				if got := parsed.CompilerOptions.Paths[specifier]; len(got) != 1 || got[0] != want {
					t.Errorf("paths[%q] = %v, want [%q]\n%s", specifier, got, want, updated)
				}
			})
		}
	})

	t.Run("twice leaves the same files", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)
		apps := []App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}

		if err := Generate(apps); err != nil {
			t.Fatalf("Generate: %v", err)
		}
		first := read(t, filepath.Join(dir, "tsconfig.json"))
		accessor := read(t, filepath.Join(dir, ".ocel", "env-client.ts"))

		if err := Generate(apps); err != nil {
			t.Fatalf("Generate again: %v", err)
		}
		if got := read(t, filepath.Join(dir, "tsconfig.json")); got != first {
			t.Errorf("tsconfig changed on a second run:\n%s\nwant\n%s", got, first)
		}
		if got := read(t, filepath.Join(dir, ".ocel", "env-client.ts")); got != accessor {
			t.Errorf("accessor changed on a second run:\n%s", got)
		}
	})

	t.Run("gives a project with no client values the built-in one anyway", func(t *testing.T) {
		t.Parallel()

		dir := appDir(t)

		if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{serverVar("STRIPE_API_KEY", "sk-live")}}}); err != nil {
			t.Fatalf("Generate: %v", err)
		}

		got := read(t, filepath.Join(dir, ".ocel", "env-client.ts"))
		if !strings.Contains(got, "NEXT_PUBLIC_OCEL_URL: inlined(schema, \"NEXT_PUBLIC_OCEL_URL\", process.env.NEXT_PUBLIC_OCEL_URL)") {
			t.Errorf("accessor =\n%s\nwant the deployment url every app is handed, declared or not", got)
		}
		if strings.Contains(got, "STRIPE_API_KEY") {
			t.Errorf("accessor =\n%s\nwant no server value in a browser bundle", got)
		}
	})

	t.Run("gives each app its own accessor", func(t *testing.T) {
		t.Parallel()

		store, admin := appDir(t), appDir(t)

		err := Generate([]App{
			{Name: "storefront", Dir: store, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://store.example.com")}},
			{Name: "admin", Dir: admin, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_ADMIN_URL", "https://admin.example.com")}},
		})
		if err != nil {
			t.Fatalf("Generate: %v", err)
		}

		if got := read(t, filepath.Join(store, ".ocel", "env-client.ts")); !strings.Contains(got, "process.env.PUBLIC_SITE_URL") || strings.Contains(got, "ADMIN") {
			t.Errorf("storefront accessor = %q, want its own key only", got)
		}
		if got := read(t, filepath.Join(admin, ".ocel", "env-client.ts")); !strings.Contains(got, "process.env.PUBLIC_ADMIN_URL") || strings.Contains(got, "SITE_URL") {
			t.Errorf("admin accessor = %q, want its own key only", got)
		}
	})
}

func TestCheckFresh(t *testing.T) {
	t.Parallel()

	t.Run("refuses a bundle that predates the value it carries", func(t *testing.T) {
		t.Parallel()

		root := t.TempDir()
		built := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}
		if err := Record(root, built, true); err != nil {
			t.Fatalf("Record: %v", err)
		}

		rotated := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://rotated.example.com")}}}
		err := CheckFresh(root, rotated)
		if err == nil {
			t.Fatal("CheckFresh = nil for a build that predates the value, want a refusal")
		}
		if !strings.Contains(err.Error(), "PUBLIC_SITE_URL") {
			t.Errorf("error = %q, want it to name the changed key", err)
		}
		if !strings.Contains(err.Error(), "--prebuilt") {
			t.Errorf("error = %q, want it to name the flag being refused", err)
		}
	})

	t.Run("allows a bundle built with the same values", func(t *testing.T) {
		t.Parallel()

		root := t.TempDir()
		built := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{
			clientVar("PUBLIC_SITE_URL", "https://example.com"),
			serverVar("STRIPE_API_KEY", "sk-live"),
		}}}
		if err := Record(root, built, true); err != nil {
			t.Fatalf("Record: %v", err)
		}

		rotated := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{
			clientVar("PUBLIC_SITE_URL", "https://example.com"),
			serverVar("STRIPE_API_KEY", "sk-rotated"),
		}}}
		if err := CheckFresh(root, rotated); err != nil {
			t.Errorf("CheckFresh = %v, want a vars-only deploy of a server value to proceed", err)
		}
	})

	t.Run("refuses an ocel build output for what it is", func(t *testing.T) {
		t.Parallel()

		root := t.TempDir()
		if err := Record(root, []App{{Name: "storefront"}}, false); err != nil {
			t.Fatalf("Record: %v", err)
		}

		err := CheckFresh(root, []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}})
		if err == nil {
			t.Fatal("CheckFresh = nil for an output that inlined no client value, want a refusal")
		}
		for _, want := range []string{"PUBLIC_SITE_URL", "never inlined", "`ocel build` resolves no values"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("error = %q, want it to state %q", err, want)
			}
		}
		if strings.Contains(err.Error(), "changed since") {
			t.Errorf("error = %q, want it not to claim the value changed; it was never inlined", err)
		}
	})

	t.Run("refuses a key a build never knew about", func(t *testing.T) {
		t.Parallel()

		root := t.TempDir()
		if err := Record(root, []App{{Name: "storefront", Variables: []manifestbuilder.Variable{serverVar("STRIPE_API_KEY", "sk-live")}}}, true); err != nil {
			t.Fatalf("Record: %v", err)
		}

		err := CheckFresh(root, []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}})
		if err == nil {
			t.Fatal("CheckFresh = nil for a key the build never inlined, want a refusal")
		}
		for _, want := range []string{"PUBLIC_SITE_URL", "never inlined", "not client-accessible when"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("error = %q, want it to state %q", err, want)
			}
		}
	})

	t.Run("says nothing about a project with no client values", func(t *testing.T) {
		t.Parallel()

		root := t.TempDir()

		apps := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{serverVar("STRIPE_API_KEY", "sk-live")}}}
		if err := CheckFresh(root, apps); err != nil {
			t.Errorf("CheckFresh = %v, want nothing to check", err)
		}
	})
}

func TestRecord(t *testing.T) {
	t.Parallel()

	t.Run("holds no plaintext", func(t *testing.T) {
		t.Parallel()

		root := t.TempDir()

		err := Record(root, []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}, true)
		if err != nil {
			t.Fatalf("Record: %v", err)
		}

		if got := read(t, filepath.Join(root, ".ocel", "output", "client-digests.json")); strings.Contains(got, "https://example.com") {
			t.Errorf("record carries the value itself: %s", got)
		}
	})
}
