package clientenv

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ocelhq/ocel/cli/internal/manifestbuilder"
	resourcesv1 "github.com/ocelhq/ocel/pkg/proto/resources/v1"
)

func clientVar(key, value string) manifestbuilder.Variable {
	return manifestbuilder.Variable{
		Key:              key,
		Class:            resourcesv1.VariableClass_VARIABLE_CLASS_PLAIN,
		Value:            value,
		ClientAccessible: true,
	}
}

func serverVar(key, value string) manifestbuilder.Variable {
	return manifestbuilder.Variable{
		Key:   key,
		Class: resourcesv1.VariableClass_VARIABLE_CLASS_SENSITIVE,
		Value: value,
	}
}

func write(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func read(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func appDir(t *testing.T) string {
	dir := t.TempDir()
	write(t, filepath.Join(dir, "tsconfig.json"), "{\n  \"compilerOptions\": {\n    \"strict\": true\n  },\n  \"include\": [\"**/*.ts\"]\n}\n")
	return dir
}

func TestGenerate_WritesTheAccessorTheSDKPins(t *testing.T) {
	dir := appDir(t)

	if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("NEXT_PUBLIC_SITE_URL", "https://example.com")}}}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	want := "// Generated by ocel. Do not edit.\n" +
		"const inlined = (key: string, value: string | undefined): string => {\n" +
		"  if (value !== undefined) return value;\n" +
		"  const error = new Error(\n" +
		"    \"'\" + key + \"' is client-accessible, but no value was inlined into this bundle. A bundler inlines only the names matching its own public convention (NEXT_PUBLIC_* under Next, VITE_* under Vite); rename the variable to one of those, or read it on the server instead.\"\n" +
		"  );\n" +
		"  error.name = \"EnvClientError\";\n" +
		"  throw error;\n" +
		"};\n" +
		"\n" +
		"export const clientEnv = {\n" +
		"  NEXT_PUBLIC_SITE_URL: inlined(\"NEXT_PUBLIC_SITE_URL\", process.env.NEXT_PUBLIC_SITE_URL),\n" +
		"};\n"
	if got := read(t, filepath.Join(dir, ".ocel", "env-client.ts")); got != want {
		t.Errorf("accessor =\n%q\nwant\n%q", got, want)
	}
}

func TestGenerate_ReadsEachKeyUnderItsDeclaredName(t *testing.T) {
	dir := appDir(t)

	err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{
		clientVar("NEXT_PUBLIC_APP_ID", "app_1"),
		clientVar("VITE_APP_ID", "app_2"),
	}}})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	accessor := read(t, filepath.Join(dir, ".ocel", "env-client.ts"))
	for _, want := range []string{"process.env.NEXT_PUBLIC_APP_ID", "process.env.VITE_APP_ID"} {
		if !strings.Contains(accessor, want) {
			t.Errorf("accessor =\n%s\nwant a read of %s", accessor, want)
		}
	}
	if strings.Contains(accessor, "NEXT_PUBLIC_VITE_APP_ID") {
		t.Errorf("accessor =\n%s\nwant no prefix added to a declared name", accessor)
	}
}

func TestGenerate_NamesNoServerOnlyValue(t *testing.T) {
	dir := appDir(t)

	err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{
		clientVar("PUBLIC_SITE_URL", "https://example.com"),
		serverVar("STRIPE_API_KEY", "sk-live"),
	}}})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	accessor := read(t, filepath.Join(dir, ".ocel", "env-client.ts"))
	if strings.Contains(accessor, "STRIPE_API_KEY") {
		t.Errorf("accessor names a server-only value:\n%s", accessor)
	}
	if strings.Contains(accessor, "sk-live") {
		t.Errorf("accessor carries a resolved value; it must name the environment entry only:\n%s", accessor)
	}
}

func TestGenerate_PointsTheImportSpecifierAtTheGeneratedFile(t *testing.T) {
	dir := appDir(t)

	if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	tsconfig := read(t, filepath.Join(dir, "tsconfig.json"))
	if !strings.Contains(tsconfig, `"ocel/env/client": ["./.ocel/env-client.ts"]`) {
		t.Errorf("tsconfig does not map the specifier at the generated file:\n%s", tsconfig)
	}
	if !strings.Contains(tsconfig, `"strict": true`) || !strings.Contains(tsconfig, `"include"`) {
		t.Errorf("tsconfig lost what the user wrote:\n%s", tsconfig)
	}
}

func TestGenerate_KeepsWhatTheUserWroteAroundIt(t *testing.T) {
	dir := t.TempDir()
	source := "{\n  // the compiler options this project has always had\n  \"compilerOptions\": {\n    \"paths\": {\n      \"@/*\": [\"./src/*\"] // app aliases\n    }\n  }\n}\n"
	write(t, filepath.Join(dir, "tsconfig.json"), source)

	if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	tsconfig := read(t, filepath.Join(dir, "tsconfig.json"))
	for _, want := range []string{
		"// the compiler options this project has always had",
		"// app aliases",
		`"@/*": ["./src/*"]`,
		`"ocel/env/client": ["./.ocel/env-client.ts"]`,
	} {
		if !strings.Contains(tsconfig, want) {
			t.Errorf("tsconfig lost %q:\n%s", want, tsconfig)
		}
	}
}

func TestGenerate_LeavesEveryStartingShapeParseable(t *testing.T) {
	for name, source := range map[string]string{
		"empty":              "{}\n",
		"no compilerOptions": "{\n  \"include\": [\"**/*.ts\"]\n}\n",
		"empty paths":        "{\n  \"compilerOptions\": {\n    \"paths\": {}\n  }\n}\n",
	} {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			write(t, filepath.Join(dir, "tsconfig.json"), source)

			if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}); err != nil {
				t.Fatalf("Generate: %v", err)
			}

			updated := read(t, filepath.Join(dir, "tsconfig.json"))
			var parsed struct {
				CompilerOptions struct {
					Paths map[string][]string `json:"paths"`
				} `json:"compilerOptions"`
			}
			if err := json.Unmarshal([]byte(updated), &parsed); err != nil {
				t.Fatalf("tsconfig is no longer parseable (%v):\n%s", err, updated)
			}
			want, err := accessorTarget("")
			if err != nil {
				t.Fatal(err)
			}
			if got := parsed.CompilerOptions.Paths[specifier]; len(got) != 1 || got[0] != want {
				t.Errorf("paths[%q] = %v, want [%q]\n%s", specifier, got, want, updated)
			}
		})
	}
}

func TestGenerate_TwiceLeavesTheSameFiles(t *testing.T) {
	dir := appDir(t)
	apps := []App{{Dir: dir, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}

	if err := Generate(apps); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	first := read(t, filepath.Join(dir, "tsconfig.json"))
	accessor := read(t, filepath.Join(dir, ".ocel", "env-client.ts"))

	if err := Generate(apps); err != nil {
		t.Fatalf("Generate again: %v", err)
	}
	if got := read(t, filepath.Join(dir, "tsconfig.json")); got != first {
		t.Errorf("tsconfig changed on a second run:\n%s\nwant\n%s", got, first)
	}
	if got := read(t, filepath.Join(dir, ".ocel", "env-client.ts")); got != accessor {
		t.Errorf("accessor changed on a second run:\n%s", got)
	}
}

func TestGenerate_LeavesAProjectWithNoClientValuesAlone(t *testing.T) {
	dir := appDir(t)
	before := read(t, filepath.Join(dir, "tsconfig.json"))

	if err := Generate([]App{{Dir: dir, Variables: []manifestbuilder.Variable{serverVar("STRIPE_API_KEY", "sk-live")}}}); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, ".ocel", "env-client.ts")); !os.IsNotExist(err) {
		t.Errorf("an accessor was generated for a project with no client-accessible value (err = %v)", err)
	}
	if got := read(t, filepath.Join(dir, "tsconfig.json")); got != before {
		t.Errorf("tsconfig was edited:\n%s", got)
	}
}

func TestGenerate_GivesEachAppItsOwnAccessor(t *testing.T) {
	store, admin := appDir(t), appDir(t)

	err := Generate([]App{
		{Name: "storefront", Dir: store, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://store.example.com")}},
		{Name: "admin", Dir: admin, Variables: []manifestbuilder.Variable{clientVar("PUBLIC_ADMIN_URL", "https://admin.example.com")}},
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if got := read(t, filepath.Join(store, ".ocel", "env-client.ts")); !strings.Contains(got, "process.env.PUBLIC_SITE_URL") || strings.Contains(got, "ADMIN") {
		t.Errorf("storefront accessor = %q, want its own key only", got)
	}
	if got := read(t, filepath.Join(admin, ".ocel", "env-client.ts")); !strings.Contains(got, "process.env.PUBLIC_ADMIN_URL") || strings.Contains(got, "SITE_URL") {
		t.Errorf("admin accessor = %q, want its own key only", got)
	}
}

func TestCheckFresh_RefusesABundleThatPredatesTheValueItCarries(t *testing.T) {
	root := t.TempDir()
	built := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}}
	if err := Record(root, built); err != nil {
		t.Fatalf("Record: %v", err)
	}

	rotated := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://rotated.example.com")}}}
	err := CheckFresh(root, rotated)
	if err == nil {
		t.Fatal("CheckFresh = nil for a build that predates the value, want a refusal")
	}
	if !strings.Contains(err.Error(), "PUBLIC_SITE_URL") {
		t.Errorf("error = %q, want it to name the changed key", err)
	}
	if !strings.Contains(err.Error(), "--prebuilt") {
		t.Errorf("error = %q, want it to name the flag being refused", err)
	}
}

func TestCheckFresh_AllowsABundleBuiltWithTheSameValues(t *testing.T) {
	root := t.TempDir()
	built := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{
		clientVar("PUBLIC_SITE_URL", "https://example.com"),
		serverVar("STRIPE_API_KEY", "sk-live"),
	}}}
	if err := Record(root, built); err != nil {
		t.Fatalf("Record: %v", err)
	}

	rotated := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{
		clientVar("PUBLIC_SITE_URL", "https://example.com"),
		serverVar("STRIPE_API_KEY", "sk-rotated"),
	}}}
	if err := CheckFresh(root, rotated); err != nil {
		t.Errorf("CheckFresh = %v, want a vars-only deploy of a server value to proceed", err)
	}
}

func TestCheckFresh_RefusesAnOcelBuildOutputForWhatItIs(t *testing.T) {
	root := t.TempDir()
	if err := RecordUnresolved(root); err != nil {
		t.Fatalf("RecordUnresolved: %v", err)
	}

	err := CheckFresh(root, []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}})
	if err == nil {
		t.Fatal("CheckFresh = nil for an output that inlined no client value, want a refusal")
	}
	for _, want := range []string{"PUBLIC_SITE_URL", "never inlined", "`ocel build` resolves no values"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error = %q, want it to state %q", err, want)
		}
	}
	if strings.Contains(err.Error(), "changed since") {
		t.Errorf("error = %q, want it not to claim the value changed; it was never inlined", err)
	}
}

func TestCheckFresh_RefusesAKeyABuildNeverKnewAbout(t *testing.T) {
	root := t.TempDir()
	if err := Record(root, []App{{Name: "storefront", Variables: []manifestbuilder.Variable{serverVar("STRIPE_API_KEY", "sk-live")}}}); err != nil {
		t.Fatalf("Record: %v", err)
	}

	err := CheckFresh(root, []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}})
	if err == nil {
		t.Fatal("CheckFresh = nil for a key the build never inlined, want a refusal")
	}
	for _, want := range []string{"PUBLIC_SITE_URL", "never inlined", "not client-accessible when"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error = %q, want it to state %q", err, want)
		}
	}
}

func TestCheckFresh_SaysNothingAboutAProjectWithNoClientValues(t *testing.T) {
	root := t.TempDir()

	apps := []App{{Name: "storefront", Variables: []manifestbuilder.Variable{serverVar("STRIPE_API_KEY", "sk-live")}}}
	if err := CheckFresh(root, apps); err != nil {
		t.Errorf("CheckFresh = %v, want nothing to check", err)
	}
}

func TestRecord_HoldsNoPlaintext(t *testing.T) {
	root := t.TempDir()

	err := Record(root, []App{{Name: "storefront", Variables: []manifestbuilder.Variable{clientVar("PUBLIC_SITE_URL", "https://example.com")}}})
	if err != nil {
		t.Fatalf("Record: %v", err)
	}

	if got := read(t, filepath.Join(root, ".ocel", "output", "client-values.json")); strings.Contains(got, "https://example.com") {
		t.Errorf("record carries the value itself: %s", got)
	}
}
