// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: env/v1/vars.proto

package envv1

import (
	v1 "github.com/ocelhq/ocel/pkg/proto/deployments/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Coordinate addresses exactly one cell. Its four components are the only
// axes a value varies along, and every one of them is part of the store's key
// structure rather than an attribute, so each operation is a point read or a
// single prefix query.
type Coordinate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// slug is the owning project. Cross-project references name another
	// project's slug here, which is why it travels per operation rather than
	// per session.
	Slug string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	// folder is the app-divergence axis, a leading-slash path ("/checkout").
	// Empty means the project root. Nesting is organisation only: a folder is
	// addressed exactly, never as a parent of the folders under it.
	Folder string `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	// key is the variable's name as application code declares it.
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// environment is the named-environment override axis: the identity of one
	// preview environment. Empty means the value that binds class-wide, which is
	// the only kind production has.
	Environment   string `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_env_v1_vars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Coordinate) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Coordinate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Coordinate) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// ValueMetadata is everything about a value except the value: what a listing
// shows, and what a reveal adds the plaintext to.
type ValueMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Coordinate *Coordinate            `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	// version is the value's current version number, counting from one. It is
	// what a subsequent write passes as expected_version.
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// updated_at is when this version was written, epoch seconds.
	UpdatedAt int64 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// size is the plaintext's length in bytes, so a listing can show that a
	// value is present and roughly how big without disclosing it.
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// target is the cell this one references, and is absent for a cell holding
	// a value of its own. The other fields stay this row's own either way: what
	// a reference borrows is the plaintext, not the row, so its version is the
	// one a write against the pointer must expect and its size is zero.
	Target        *Coordinate `protobuf:"bytes,5,opt,name=target,proto3,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueMetadata) Reset() {
	*x = ValueMetadata{}
	mi := &file_env_v1_vars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueMetadata) ProtoMessage() {}

func (x *ValueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueMetadata.ProtoReflect.Descriptor instead.
func (*ValueMetadata) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{1}
}

func (x *ValueMetadata) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *ValueMetadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ValueMetadata) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ValueMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ValueMetadata) GetTarget() *Coordinate {
	if x != nil {
		return x.Target
	}
	return nil
}

// VersionEntry is one entry of a cell's change history. It carries no
// plaintext: history records that a value changed, not what it was.
type VersionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionEntry) Reset() {
	*x = VersionEntry{}
	mi := &file_env_v1_vars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionEntry) ProtoMessage() {}

func (x *VersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionEntry.ProtoReflect.Descriptor instead.
func (*VersionEntry) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{2}
}

func (x *VersionEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VersionEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SetValueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// options is always UTF-8 JSON bytes: `{}` when the provider was given no
	// options, never absent and never an empty string. The CLI never inspects
	// this field; only the provider unmarshals it.
	Options []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// protocol_version pins the wire contract so a provider can reject a
	// request it can't speak.
	ProtocolVersion string `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// class selects the substrate, and with it the table and the key the value
	// encrypts under. Preview and production ciphertext are encrypted under
	// different keys, so this is not a filter — it is which store is opened.
	Class      v1.Environment_Class `protobuf:"varint,3,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate *Coordinate          `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Value      string               `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// expected_version is the version the writer believes is current: absent
	// for a blind write, zero to require that no value exists yet. A write whose
	// expectation no longer holds is rejected rather than applied, so two people
	// editing at once cannot silently lose one edit. A blind write still loses
	// to a writer that commits between its read and its own commit. The
	// rejection is FAILED_PRECONDITION and nothing else: that code is how a
	// caller tells a lost race from a store it could not reach, so a provider
	// spending it on anything but a broken expectation tells a user their value
	// changed when it did not.
	ExpectedVersion *int64 `protobuf:"varint,6,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{3}
}

func (x *SetValueRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SetValueRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *SetValueRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *SetValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *SetValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetValueRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type SetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueResponse) Reset() {
	*x = SetValueResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResponse) ProtoMessage() {}

func (x *SetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResponse.ProtoReflect.Descriptor instead.
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{4}
}

func (x *SetValueResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListValuesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Options         []byte                 `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Class           v1.Environment_Class   `protobuf:"varint,3,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	// slug is the project whose values to enumerate. Resolution — which of them
	// an app actually reads — happens on the CLI side; the provider returns raw
	// cells.
	Slug          string `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValuesRequest) Reset() {
	*x = ListValuesRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValuesRequest) ProtoMessage() {}

func (x *ListValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValuesRequest.ProtoReflect.Descriptor instead.
func (*ListValuesRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{5}
}

func (x *ListValuesRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListValuesRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ListValuesRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *ListValuesRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ListValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ValueMetadata       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValuesResponse) Reset() {
	*x = ListValuesResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValuesResponse) ProtoMessage() {}

func (x *ListValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValuesResponse.ProtoReflect.Descriptor instead.
func (*ListValuesResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{6}
}

func (x *ListValuesResponse) GetValues() []*ValueMetadata {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetValueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Options         []byte                 `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Class           v1.Environment_Class   `protobuf:"varint,3,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate      *Coordinate            `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	// reveal asks for the plaintext. Without it the provider never decrypts.
	Reveal        bool `protobuf:"varint,5,opt,name=reveal,proto3" json:"reveal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{7}
}

func (x *GetValueRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GetValueRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *GetValueRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *GetValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *GetValueRequest) GetReveal() bool {
	if x != nil {
		return x.Reveal
	}
	return false
}

type GetValueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// found distinguishes an unset cell from a set one, so a caller never has to
	// read "no value" out of an empty string.
	Found    bool           `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata *ValueMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// value is populated only when the request asked to reveal.
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{8}
}

func (x *GetValueResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetValueResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RevealValuesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Options         []byte                 `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Class           v1.Environment_Class   `protobuf:"varint,3,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	// slug is the project the cells belong to. cells name them within it.
	Slug          string  `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Cells         []*Cell `protobuf:"bytes,5,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealValuesRequest) Reset() {
	*x = RevealValuesRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealValuesRequest) ProtoMessage() {}

func (x *RevealValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealValuesRequest.ProtoReflect.Descriptor instead.
func (*RevealValuesRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{9}
}

func (x *RevealValuesRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *RevealValuesRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *RevealValuesRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *RevealValuesRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *RevealValuesRequest) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

// Cell addresses one value inside a project already named. It is Coordinate
// without the slug: a batched read carries the project once for the whole
// request, so there is no second place for it to be stated and no way for two
// cells of one request to disagree about which project they belong to.
type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_env_v1_vars_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{10}
}

func (x *Cell) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Cell) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Cell) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type RevealValuesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values carries only the named cells that hold one. An unset cell is absent
	// rather than empty, which is the distinction GetValue.found draws.
	Values        []*RevealedValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealValuesResponse) Reset() {
	*x = RevealValuesResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealValuesResponse) ProtoMessage() {}

func (x *RevealValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealValuesResponse.ProtoReflect.Descriptor instead.
func (*RevealValuesResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{11}
}

func (x *RevealValuesResponse) GetValues() []*RevealedValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type RevealedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealedValue) Reset() {
	*x = RevealedValue{}
	mi := &file_env_v1_vars_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealedValue) ProtoMessage() {}

func (x *RevealedValue) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealedValue.ProtoReflect.Descriptor instead.
func (*RevealedValue) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{12}
}

func (x *RevealedValue) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RevealedValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteValueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Options         []byte                 `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Class           v1.Environment_Class   `protobuf:"varint,3,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate      *Coordinate            `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	// expected_version is the version the deleter believes is current: absent
	// for a blind delete, zero to require that no value is set — which an unset
	// cell already satisfies, so a repeat of a delete that already landed stays
	// idempotent rather than becoming a conflict. A delete whose expectation no
	// longer holds is rejected rather than applied, so a page showing a value
	// somebody has since replaced cannot destroy the replacement. Like a write,
	// the rejection is FAILED_PRECONDITION and nothing else.
	ExpectedVersion *int64 `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteValueRequest) Reset() {
	*x = DeleteValueRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueRequest) ProtoMessage() {}

func (x *DeleteValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteValueRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteValueRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *DeleteValueRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *DeleteValueRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *DeleteValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *DeleteValueRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type DeleteValueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deleted is false when there was nothing to delete. Deleting is idempotent
	// either way.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValueResponse) Reset() {
	*x = DeleteValueResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueResponse) ProtoMessage() {}

func (x *DeleteValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueResponse.ProtoReflect.Descriptor instead.
func (*DeleteValueResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteValueResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SetReferenceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Options         []byte                 `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Class           v1.Environment_Class   `protobuf:"varint,3,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	// coordinate is the cell that will hold the reference; target is the cell it
	// will read. target names its own slug, which is how a value owned by
	// another project is consumed, and it addresses that project's class-wide
	// value: a named environment belongs to the project holding it, and means
	// nothing in the target's namespace.
	Coordinate *Coordinate `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Target     *Coordinate `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	// expected_version is read exactly as SetValue reads it, against the cell
	// that will hold the reference — the pointer's own version, never the
	// target's.
	ExpectedVersion *int64 `protobuf:"varint,6,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetReferenceRequest) Reset() {
	*x = SetReferenceRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceRequest) ProtoMessage() {}

func (x *SetReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceRequest.ProtoReflect.Descriptor instead.
func (*SetReferenceRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{15}
}

func (x *SetReferenceRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SetReferenceRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *SetReferenceRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *SetReferenceRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *SetReferenceRequest) GetTarget() *Coordinate {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SetReferenceRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type SetReferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReferenceResponse) Reset() {
	*x = SetReferenceResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceResponse) ProtoMessage() {}

func (x *SetReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceResponse.ProtoReflect.Descriptor instead.
func (*SetReferenceResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{16}
}

func (x *SetReferenceResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListReferencesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Options         []byte                 `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Class           v1.Environment_Class   `protobuf:"varint,3,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	// coordinate is the value being asked about, not the reference: the answer
	// is what points here.
	Coordinate    *Coordinate `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferencesRequest) Reset() {
	*x = ListReferencesRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferencesRequest) ProtoMessage() {}

func (x *ListReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferencesRequest.ProtoReflect.Descriptor instead.
func (*ListReferencesRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{17}
}

func (x *ListReferencesRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListReferencesRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ListReferencesRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *ListReferencesRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

type ListReferencesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// references are the cells reading this value, sorted. It is the whole
	// answer: a reference may only point at a value, so nothing sits behind one
	// of these reading the same value at a second remove.
	References    []*Coordinate `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferencesResponse) Reset() {
	*x = ListReferencesResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferencesResponse) ProtoMessage() {}

func (x *ListReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferencesResponse.ProtoReflect.Descriptor instead.
func (*ListReferencesResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{18}
}

func (x *ListReferencesResponse) GetReferences() []*Coordinate {
	if x != nil {
		return x.References
	}
	return nil
}

type ListVersionsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Options         []byte                 `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Class           v1.Environment_Class   `protobuf:"varint,3,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate      *Coordinate            `protobuf:"bytes,4,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{19}
}

func (x *ListVersionsRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ListVersionsRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ListVersionsRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *ListVersionsRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

type ListVersionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// versions are newest first.
	Versions      []*VersionEntry `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{20}
}

func (x *ListVersionsResponse) GetVersions() []*VersionEntry {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_env_v1_vars_proto protoreflect.FileDescriptor

const file_env_v1_vars_proto_rawDesc = "" +
	"\n" +
	"\x11env/v1/vars.proto\x12\x06env.v1\x1a deployments/v1/deployments.proto\"l\n" +
	"\n" +
	"Coordinate\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\"\xcc\x01\n" +
	"\rValueMetadata\x122\n" +
	"\n" +
	"coordinate\x18\x01 \x01(\v2\x12.env.v1.CoordinateR\n" +
	"coordinate\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12/\n" +
	"\x06target\x18\x05 \x01(\v2\x12.env.v1.CoordinateH\x00R\x06target\x88\x01\x01B\t\n" +
	"\a_target\"h\n" +
	"\fVersionEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04sizeJ\x04\b\x04\x10\x05R\x05value\"\x9e\x02\n" +
	"\x0fSetValueRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x05class\x18\x03 \x01(\x0e2!.deployments.v1.Environment.ClassR\x05class\x122\n" +
	"\n" +
	"coordinate\x18\x04 \x01(\v2\x12.env.v1.CoordinateR\n" +
	"coordinate\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12.\n" +
	"\x10expected_version\x18\x06 \x01(\x03H\x00R\x0fexpectedVersion\x88\x01\x01B\x13\n" +
	"\x11_expected_version\"E\n" +
	"\x10SetValueResponse\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.env.v1.ValueMetadataR\bmetadata\"\xa5\x01\n" +
	"\x11ListValuesRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x05class\x18\x03 \x01(\x0e2!.deployments.v1.Environment.ClassR\x05class\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\"C\n" +
	"\x12ListValuesResponse\x12-\n" +
	"\x06values\x18\x01 \x03(\v2\x15.env.v1.ValueMetadataR\x06values\"\xdb\x01\n" +
	"\x0fGetValueRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x05class\x18\x03 \x01(\x0e2!.deployments.v1.Environment.ClassR\x05class\x122\n" +
	"\n" +
	"coordinate\x18\x04 \x01(\v2\x12.env.v1.CoordinateR\n" +
	"coordinate\x12\x16\n" +
	"\x06reveal\x18\x05 \x01(\bR\x06reveal\"q\n" +
	"\x10GetValueResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.env.v1.ValueMetadataR\bmetadata\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xcb\x01\n" +
	"\x13RevealValuesRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x05class\x18\x03 \x01(\x0e2!.deployments.v1.Environment.ClassR\x05class\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\"\n" +
	"\x05cells\x18\x05 \x03(\v2\f.env.v1.CellR\x05cells\"R\n" +
	"\x04Cell\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\"E\n" +
	"\x14RevealValuesResponse\x12-\n" +
	"\x06values\x18\x01 \x03(\v2\x15.env.v1.RevealedValueR\x06values\"X\n" +
	"\rRevealedValue\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.env.v1.ValueMetadataR\bmetadata\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8b\x02\n" +
	"\x12DeleteValueRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x05class\x18\x03 \x01(\x0e2!.deployments.v1.Environment.ClassR\x05class\x122\n" +
	"\n" +
	"coordinate\x18\x04 \x01(\v2\x12.env.v1.CoordinateR\n" +
	"coordinate\x12.\n" +
	"\x10expected_version\x18\x05 \x01(\x03H\x00R\x0fexpectedVersion\x88\x01\x01B\x13\n" +
	"\x11_expected_version\"/\n" +
	"\x13DeleteValueResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xb8\x02\n" +
	"\x13SetReferenceRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x05class\x18\x03 \x01(\x0e2!.deployments.v1.Environment.ClassR\x05class\x122\n" +
	"\n" +
	"coordinate\x18\x04 \x01(\v2\x12.env.v1.CoordinateR\n" +
	"coordinate\x12*\n" +
	"\x06target\x18\x05 \x01(\v2\x12.env.v1.CoordinateR\x06target\x12.\n" +
	"\x10expected_version\x18\x06 \x01(\x03H\x00R\x0fexpectedVersion\x88\x01\x01B\x13\n" +
	"\x11_expected_version\"I\n" +
	"\x14SetReferenceResponse\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.env.v1.ValueMetadataR\bmetadata\"\xc9\x01\n" +
	"\x15ListReferencesRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x05class\x18\x03 \x01(\x0e2!.deployments.v1.Environment.ClassR\x05class\x122\n" +
	"\n" +
	"coordinate\x18\x04 \x01(\v2\x12.env.v1.CoordinateR\n" +
	"coordinate\"L\n" +
	"\x16ListReferencesResponse\x122\n" +
	"\n" +
	"references\x18\x01 \x03(\v2\x12.env.v1.CoordinateR\n" +
	"references\"\xd5\x01\n" +
	"\x13ListVersionsRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x127\n" +
	"\x05class\x18\x03 \x01(\x0e2!.deployments.v1.Environment.ClassR\x05class\x122\n" +
	"\n" +
	"coordinate\x18\x04 \x01(\v2\x12.env.v1.CoordinateR\n" +
	"coordinateJ\x04\b\x05\x10\x06R\x06reveal\"H\n" +
	"\x14ListVersionsResponse\x120\n" +
	"\bversions\x18\x01 \x03(\v2\x14.env.v1.VersionEntryR\bversions2\xcd\x04\n" +
	"\x0eEnvVarsService\x12=\n" +
	"\bSetValue\x12\x17.env.v1.SetValueRequest\x1a\x18.env.v1.SetValueResponse\x12C\n" +
	"\n" +
	"ListValues\x12\x19.env.v1.ListValuesRequest\x1a\x1a.env.v1.ListValuesResponse\x12=\n" +
	"\bGetValue\x12\x17.env.v1.GetValueRequest\x1a\x18.env.v1.GetValueResponse\x12I\n" +
	"\fRevealValues\x12\x1b.env.v1.RevealValuesRequest\x1a\x1c.env.v1.RevealValuesResponse\x12F\n" +
	"\vDeleteValue\x12\x1a.env.v1.DeleteValueRequest\x1a\x1b.env.v1.DeleteValueResponse\x12I\n" +
	"\fSetReference\x12\x1b.env.v1.SetReferenceRequest\x1a\x1c.env.v1.SetReferenceResponse\x12O\n" +
	"\x0eListReferences\x12\x1d.env.v1.ListReferencesRequest\x1a\x1e.env.v1.ListReferencesResponse\x12I\n" +
	"\fListVersions\x12\x1b.env.v1.ListVersionsRequest\x1a\x1c.env.v1.ListVersionsResponseB/Z-github.com/ocelhq/ocel/pkg/proto/env/v1;envv1b\x06proto3"

var (
	file_env_v1_vars_proto_rawDescOnce sync.Once
	file_env_v1_vars_proto_rawDescData []byte
)

func file_env_v1_vars_proto_rawDescGZIP() []byte {
	file_env_v1_vars_proto_rawDescOnce.Do(func() {
		file_env_v1_vars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_env_v1_vars_proto_rawDesc), len(file_env_v1_vars_proto_rawDesc)))
	})
	return file_env_v1_vars_proto_rawDescData
}

var file_env_v1_vars_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_env_v1_vars_proto_goTypes = []any{
	(*Coordinate)(nil),             // 0: env.v1.Coordinate
	(*ValueMetadata)(nil),          // 1: env.v1.ValueMetadata
	(*VersionEntry)(nil),           // 2: env.v1.VersionEntry
	(*SetValueRequest)(nil),        // 3: env.v1.SetValueRequest
	(*SetValueResponse)(nil),       // 4: env.v1.SetValueResponse
	(*ListValuesRequest)(nil),      // 5: env.v1.ListValuesRequest
	(*ListValuesResponse)(nil),     // 6: env.v1.ListValuesResponse
	(*GetValueRequest)(nil),        // 7: env.v1.GetValueRequest
	(*GetValueResponse)(nil),       // 8: env.v1.GetValueResponse
	(*RevealValuesRequest)(nil),    // 9: env.v1.RevealValuesRequest
	(*Cell)(nil),                   // 10: env.v1.Cell
	(*RevealValuesResponse)(nil),   // 11: env.v1.RevealValuesResponse
	(*RevealedValue)(nil),          // 12: env.v1.RevealedValue
	(*DeleteValueRequest)(nil),     // 13: env.v1.DeleteValueRequest
	(*DeleteValueResponse)(nil),    // 14: env.v1.DeleteValueResponse
	(*SetReferenceRequest)(nil),    // 15: env.v1.SetReferenceRequest
	(*SetReferenceResponse)(nil),   // 16: env.v1.SetReferenceResponse
	(*ListReferencesRequest)(nil),  // 17: env.v1.ListReferencesRequest
	(*ListReferencesResponse)(nil), // 18: env.v1.ListReferencesResponse
	(*ListVersionsRequest)(nil),    // 19: env.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),   // 20: env.v1.ListVersionsResponse
	(v1.Environment_Class)(0),      // 21: deployments.v1.Environment.Class
}
var file_env_v1_vars_proto_depIdxs = []int32{
	0,  // 0: env.v1.ValueMetadata.coordinate:type_name -> env.v1.Coordinate
	0,  // 1: env.v1.ValueMetadata.target:type_name -> env.v1.Coordinate
	21, // 2: env.v1.SetValueRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 3: env.v1.SetValueRequest.coordinate:type_name -> env.v1.Coordinate
	1,  // 4: env.v1.SetValueResponse.metadata:type_name -> env.v1.ValueMetadata
	21, // 5: env.v1.ListValuesRequest.class:type_name -> deployments.v1.Environment.Class
	1,  // 6: env.v1.ListValuesResponse.values:type_name -> env.v1.ValueMetadata
	21, // 7: env.v1.GetValueRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 8: env.v1.GetValueRequest.coordinate:type_name -> env.v1.Coordinate
	1,  // 9: env.v1.GetValueResponse.metadata:type_name -> env.v1.ValueMetadata
	21, // 10: env.v1.RevealValuesRequest.class:type_name -> deployments.v1.Environment.Class
	10, // 11: env.v1.RevealValuesRequest.cells:type_name -> env.v1.Cell
	12, // 12: env.v1.RevealValuesResponse.values:type_name -> env.v1.RevealedValue
	1,  // 13: env.v1.RevealedValue.metadata:type_name -> env.v1.ValueMetadata
	21, // 14: env.v1.DeleteValueRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 15: env.v1.DeleteValueRequest.coordinate:type_name -> env.v1.Coordinate
	21, // 16: env.v1.SetReferenceRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 17: env.v1.SetReferenceRequest.coordinate:type_name -> env.v1.Coordinate
	0,  // 18: env.v1.SetReferenceRequest.target:type_name -> env.v1.Coordinate
	1,  // 19: env.v1.SetReferenceResponse.metadata:type_name -> env.v1.ValueMetadata
	21, // 20: env.v1.ListReferencesRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 21: env.v1.ListReferencesRequest.coordinate:type_name -> env.v1.Coordinate
	0,  // 22: env.v1.ListReferencesResponse.references:type_name -> env.v1.Coordinate
	21, // 23: env.v1.ListVersionsRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 24: env.v1.ListVersionsRequest.coordinate:type_name -> env.v1.Coordinate
	2,  // 25: env.v1.ListVersionsResponse.versions:type_name -> env.v1.VersionEntry
	3,  // 26: env.v1.EnvVarsService.SetValue:input_type -> env.v1.SetValueRequest
	5,  // 27: env.v1.EnvVarsService.ListValues:input_type -> env.v1.ListValuesRequest
	7,  // 28: env.v1.EnvVarsService.GetValue:input_type -> env.v1.GetValueRequest
	9,  // 29: env.v1.EnvVarsService.RevealValues:input_type -> env.v1.RevealValuesRequest
	13, // 30: env.v1.EnvVarsService.DeleteValue:input_type -> env.v1.DeleteValueRequest
	15, // 31: env.v1.EnvVarsService.SetReference:input_type -> env.v1.SetReferenceRequest
	17, // 32: env.v1.EnvVarsService.ListReferences:input_type -> env.v1.ListReferencesRequest
	19, // 33: env.v1.EnvVarsService.ListVersions:input_type -> env.v1.ListVersionsRequest
	4,  // 34: env.v1.EnvVarsService.SetValue:output_type -> env.v1.SetValueResponse
	6,  // 35: env.v1.EnvVarsService.ListValues:output_type -> env.v1.ListValuesResponse
	8,  // 36: env.v1.EnvVarsService.GetValue:output_type -> env.v1.GetValueResponse
	11, // 37: env.v1.EnvVarsService.RevealValues:output_type -> env.v1.RevealValuesResponse
	14, // 38: env.v1.EnvVarsService.DeleteValue:output_type -> env.v1.DeleteValueResponse
	16, // 39: env.v1.EnvVarsService.SetReference:output_type -> env.v1.SetReferenceResponse
	18, // 40: env.v1.EnvVarsService.ListReferences:output_type -> env.v1.ListReferencesResponse
	20, // 41: env.v1.EnvVarsService.ListVersions:output_type -> env.v1.ListVersionsResponse
	34, // [34:42] is the sub-list for method output_type
	26, // [26:34] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_env_v1_vars_proto_init() }
func file_env_v1_vars_proto_init() {
	if File_env_v1_vars_proto != nil {
		return
	}
	file_env_v1_vars_proto_msgTypes[1].OneofWrappers = []any{}
	file_env_v1_vars_proto_msgTypes[3].OneofWrappers = []any{}
	file_env_v1_vars_proto_msgTypes[13].OneofWrappers = []any{}
	file_env_v1_vars_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_env_v1_vars_proto_rawDesc), len(file_env_v1_vars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_env_v1_vars_proto_goTypes,
		DependencyIndexes: file_env_v1_vars_proto_depIdxs,
		MessageInfos:      file_env_v1_vars_proto_msgTypes,
	}.Build()
	File_env_v1_vars_proto = out.File
	file_env_v1_vars_proto_goTypes = nil
	file_env_v1_vars_proto_depIdxs = nil
}
