// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: env/v1/vars.proto

package envv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/ocelhq/ocel/pkg/proto/deployments/v1"
	v11 "github.com/ocelhq/ocel/pkg/proto/links/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_env_v1_vars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Coordinate) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Coordinate) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Coordinate) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ValueMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinate    *Coordinate            `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Target        *Coordinate            `protobuf:"bytes,5,opt,name=target,proto3,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueMetadata) Reset() {
	*x = ValueMetadata{}
	mi := &file_env_v1_vars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueMetadata) ProtoMessage() {}

func (x *ValueMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueMetadata.ProtoReflect.Descriptor instead.
func (*ValueMetadata) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{1}
}

func (x *ValueMetadata) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *ValueMetadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ValueMetadata) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ValueMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ValueMetadata) GetTarget() *Coordinate {
	if x != nil {
		return x.Target
	}
	return nil
}

type VersionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionEntry) Reset() {
	*x = VersionEntry{}
	mi := &file_env_v1_vars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionEntry) ProtoMessage() {}

func (x *VersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionEntry.ProtoReflect.Descriptor instead.
func (*VersionEntry) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{2}
}

func (x *VersionEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VersionEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SetValueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Class           v1.Environment_Class   `protobuf:"varint,1,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate      *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Value           string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ExpectedVersion *int64                 `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{3}
}

func (x *SetValueRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *SetValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *SetValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetValueRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type SetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueResponse) Reset() {
	*x = SetValueResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResponse) ProtoMessage() {}

func (x *SetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResponse.ProtoReflect.Descriptor instead.
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{4}
}

func (x *SetValueResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         v1.Environment_Class   `protobuf:"varint,1,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValuesRequest) Reset() {
	*x = ListValuesRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValuesRequest) ProtoMessage() {}

func (x *ListValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValuesRequest.ProtoReflect.Descriptor instead.
func (*ListValuesRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{5}
}

func (x *ListValuesRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *ListValuesRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ListValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ValueMetadata       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValuesResponse) Reset() {
	*x = ListValuesResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValuesResponse) ProtoMessage() {}

func (x *ListValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValuesResponse.ProtoReflect.Descriptor instead.
func (*ListValuesResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{6}
}

func (x *ListValuesResponse) GetValues() []*ValueMetadata {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         v1.Environment_Class   `protobuf:"varint,1,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Reveal        bool                   `protobuf:"varint,3,opt,name=reveal,proto3" json:"reveal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{7}
}

func (x *GetValueRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *GetValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *GetValueRequest) GetReveal() bool {
	if x != nil {
		return x.Reveal
	}
	return false
}

type GetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Metadata      *ValueMetadata         `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{8}
}

func (x *GetValueResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetValueResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RevealValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         v1.Environment_Class   `protobuf:"varint,1,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Cells         []*Cell                `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealValuesRequest) Reset() {
	*x = RevealValuesRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealValuesRequest) ProtoMessage() {}

func (x *RevealValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealValuesRequest.ProtoReflect.Descriptor instead.
func (*RevealValuesRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{9}
}

func (x *RevealValuesRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *RevealValuesRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *RevealValuesRequest) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_env_v1_vars_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{10}
}

func (x *Cell) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Cell) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Cell) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type RevealValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*RevealedValue       `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealValuesResponse) Reset() {
	*x = RevealValuesResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealValuesResponse) ProtoMessage() {}

func (x *RevealValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealValuesResponse.ProtoReflect.Descriptor instead.
func (*RevealValuesResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{11}
}

func (x *RevealValuesResponse) GetValues() []*RevealedValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type RevealedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealedValue) Reset() {
	*x = RevealedValue{}
	mi := &file_env_v1_vars_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealedValue) ProtoMessage() {}

func (x *RevealedValue) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealedValue.ProtoReflect.Descriptor instead.
func (*RevealedValue) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{12}
}

func (x *RevealedValue) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RevealedValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteValueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Class           v1.Environment_Class   `protobuf:"varint,1,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate      *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	ExpectedVersion *int64                 `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteValueRequest) Reset() {
	*x = DeleteValueRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueRequest) ProtoMessage() {}

func (x *DeleteValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteValueRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteValueRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *DeleteValueRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *DeleteValueRequest) GetExpectedVersion() int64 {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return 0
}

type DeleteValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValueResponse) Reset() {
	*x = DeleteValueResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueResponse) ProtoMessage() {}

func (x *DeleteValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueResponse.ProtoReflect.Descriptor instead.
func (*DeleteValueResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteValueResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SetReferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         v1.Environment_Class   `protobuf:"varint,1,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Target        *Coordinate            `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReferenceRequest) Reset() {
	*x = SetReferenceRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceRequest) ProtoMessage() {}

func (x *SetReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceRequest.ProtoReflect.Descriptor instead.
func (*SetReferenceRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{15}
}

func (x *SetReferenceRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *SetReferenceRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *SetReferenceRequest) GetTarget() *Coordinate {
	if x != nil {
		return x.Target
	}
	return nil
}

type SetReferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ValueMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReferenceResponse) Reset() {
	*x = SetReferenceResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReferenceResponse) ProtoMessage() {}

func (x *SetReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReferenceResponse.ProtoReflect.Descriptor instead.
func (*SetReferenceResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{16}
}

func (x *SetReferenceResponse) GetMetadata() *ValueMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListReferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         v1.Environment_Class   `protobuf:"varint,1,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferencesRequest) Reset() {
	*x = ListReferencesRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferencesRequest) ProtoMessage() {}

func (x *ListReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferencesRequest.ProtoReflect.Descriptor instead.
func (*ListReferencesRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{17}
}

func (x *ListReferencesRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *ListReferencesRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

type ListReferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	References    []*Coordinate          `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReferencesResponse) Reset() {
	*x = ListReferencesResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReferencesResponse) ProtoMessage() {}

func (x *ListReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReferencesResponse.ProtoReflect.Descriptor instead.
func (*ListReferencesResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{18}
}

func (x *ListReferencesResponse) GetReferences() []*Coordinate {
	if x != nil {
		return x.References
	}
	return nil
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         v1.Environment_Class   `protobuf:"varint,1,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Coordinate    *Coordinate            `protobuf:"bytes,2,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{19}
}

func (x *ListVersionsRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *ListVersionsRequest) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*VersionEntry        `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{20}
}

func (x *ListVersionsResponse) GetVersions() []*VersionEntry {
	if x != nil {
		return x.Versions
	}
	return nil
}

type SetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Class         v1.Environment_Class   `protobuf:"varint,2,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Link          *v11.Link              `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLinkRequest) Reset() {
	*x = SetLinkRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLinkRequest) ProtoMessage() {}

func (x *SetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLinkRequest.ProtoReflect.Descriptor instead.
func (*SetLinkRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{21}
}

func (x *SetLinkRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SetLinkRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *SetLinkRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SetLinkRequest) GetLink() *v11.Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *SetLinkRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type SetLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLinkResponse) Reset() {
	*x = SetLinkResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLinkResponse) ProtoMessage() {}

func (x *SetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLinkResponse.ProtoReflect.Descriptor instead.
func (*SetLinkResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{22}
}

func (x *SetLinkResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RemoveLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Class         v1.Environment_Class   `protobuf:"varint,2,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLinkRequest) Reset() {
	*x = RemoveLinkRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLinkRequest) ProtoMessage() {}

func (x *RemoveLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveLinkRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveLinkRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *RemoveLinkRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *RemoveLinkRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RemoveLinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLinkResponse) Reset() {
	*x = RemoveLinkResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLinkResponse) ProtoMessage() {}

func (x *RemoveLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLinkResponse.ProtoReflect.Descriptor instead.
func (*RemoveLinkResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveLinkResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Class         v1.Environment_Class   `protobuf:"varint,2,opt,name=class,proto3,enum=deployments.v1.Environment_Class" json:"class,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_env_v1_vars_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{25}
}

func (x *ListLinksRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ListLinksRequest) GetClass() v1.Environment_Class {
	if x != nil {
		return x.Class
	}
	return v1.Environment_Class(0)
}

func (x *ListLinksRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkSummary         `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_env_v1_vars_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{26}
}

func (x *ListLinksResponse) GetLinks() []*LinkSummary {
	if x != nil {
		return x.Links
	}
	return nil
}

type LinkSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          v11.LinkType           `protobuf:"varint,2,opt,name=type,proto3,enum=links.v1.LinkType" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Properties    []*PropertyShape       `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkSummary) Reset() {
	*x = LinkSummary{}
	mi := &file_env_v1_vars_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkSummary) ProtoMessage() {}

func (x *LinkSummary) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkSummary.ProtoReflect.Descriptor instead.
func (*LinkSummary) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{27}
}

func (x *LinkSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkSummary) GetType() v11.LinkType {
	if x != nil {
		return x.Type
	}
	return v11.LinkType(0)
}

func (x *LinkSummary) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LinkSummary) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *LinkSummary) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LinkSummary) GetProperties() []*PropertyShape {
	if x != nil {
		return x.Properties
	}
	return nil
}

type PropertyShape struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JsonType      string                 `protobuf:"bytes,2,opt,name=json_type,json=jsonType,proto3" json:"json_type,omitempty"`
	List          bool                   `protobuf:"varint,3,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyShape) Reset() {
	*x = PropertyShape{}
	mi := &file_env_v1_vars_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyShape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyShape) ProtoMessage() {}

func (x *PropertyShape) ProtoReflect() protoreflect.Message {
	mi := &file_env_v1_vars_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyShape.ProtoReflect.Descriptor instead.
func (*PropertyShape) Descriptor() ([]byte, []int) {
	return file_env_v1_vars_proto_rawDescGZIP(), []int{28}
}

func (x *PropertyShape) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropertyShape) GetJsonType() string {
	if x != nil {
		return x.JsonType
	}
	return ""
}

func (x *PropertyShape) GetList() bool {
	if x != nil {
		return x.List
	}
	return false
}

var File_env_v1_vars_proto protoreflect.FileDescriptor

const file_env_v1_vars_proto_rawDesc = "" +
	"\n" +
	"\x11env/v1/vars.proto\x12\x06env.v1\x1a\x1bbuf/validate/validate.proto\x1a deployments/v1/deployments.proto\x1a\x14links/v1/links.proto\"\xe2\x01\n" +
	"\n" +
	"Coordinate\x125\n" +
	"\x04slug\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x124\n" +
	"\x06folder\x18\x02 \x01(\tB\x1c\xbaH\x19r\x172\x15^(/[^/#[:cntrl:]]+)*$R\x06folder\x12+\n" +
	"\x03key\x18\x03 \x01(\tB\x19\xbaH\x16r\x14\x10\x012\x10^[^#[:cntrl:]]*$R\x03key\x12:\n" +
	"\venvironment\x18\x04 \x01(\tB\x18\xbaH\x15r\x132\x11^[^#*[:cntrl:]]*$R\venvironment\"\xcc\x01\n" +
	"\rValueMetadata\x122\n" +
	"\n" +
	"coordinate\x18\x01 \x01(\v2\x12.env.v1.CoordinateR\n" +
	"coordinate\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12/\n" +
	"\x06target\x18\x05 \x01(\v2\x12.env.v1.CoordinateH\x00R\x06target\x88\x01\x01B\t\n" +
	"\a_target\"[\n" +
	"\fVersionEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xeb\x01\n" +
	"\x0fSetValueRequest\x12A\n" +
	"\x05class\x18\x01 \x01(\x0e2!.deployments.v1.Environment.ClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x12:\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x12.env.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12.\n" +
	"\x10expected_version\x18\x04 \x01(\x03H\x00R\x0fexpectedVersion\x88\x01\x01B\x13\n" +
	"\x11_expected_version\"E\n" +
	"\x10SetValueResponse\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.env.v1.ValueMetadataR\bmetadata\"\x8d\x01\n" +
	"\x11ListValuesRequest\x12A\n" +
	"\x05class\x18\x01 \x01(\x0e2!.deployments.v1.Environment.ClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x125\n" +
	"\x04slug\x18\x02 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\"C\n" +
	"\x12ListValuesResponse\x12-\n" +
	"\x06values\x18\x01 \x03(\v2\x15.env.v1.ValueMetadataR\x06values\"\xa8\x01\n" +
	"\x0fGetValueRequest\x12A\n" +
	"\x05class\x18\x01 \x01(\x0e2!.deployments.v1.Environment.ClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x12:\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x12.env.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\x12\x16\n" +
	"\x06reveal\x18\x03 \x01(\bR\x06reveal\"q\n" +
	"\x10GetValueResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x121\n" +
	"\bmetadata\x18\x02 \x01(\v2\x15.env.v1.ValueMetadataR\bmetadata\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xb3\x01\n" +
	"\x13RevealValuesRequest\x12A\n" +
	"\x05class\x18\x01 \x01(\x0e2!.deployments.v1.Environment.ClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x125\n" +
	"\x04slug\x18\x02 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12\"\n" +
	"\x05cells\x18\x03 \x03(\v2\f.env.v1.CellR\x05cells\"\xa5\x01\n" +
	"\x04Cell\x124\n" +
	"\x06folder\x18\x01 \x01(\tB\x1c\xbaH\x19r\x172\x15^(/[^/#[:cntrl:]]+)*$R\x06folder\x12+\n" +
	"\x03key\x18\x02 \x01(\tB\x19\xbaH\x16r\x14\x10\x012\x10^[^#[:cntrl:]]*$R\x03key\x12:\n" +
	"\venvironment\x18\x03 \x01(\tB\x18\xbaH\x15r\x132\x11^[^#*[:cntrl:]]*$R\venvironment\"E\n" +
	"\x14RevealValuesResponse\x12-\n" +
	"\x06values\x18\x01 \x03(\v2\x15.env.v1.RevealedValueR\x06values\"X\n" +
	"\rRevealedValue\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.env.v1.ValueMetadataR\bmetadata\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xd8\x01\n" +
	"\x12DeleteValueRequest\x12A\n" +
	"\x05class\x18\x01 \x01(\x0e2!.deployments.v1.Environment.ClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x12:\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x12.env.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\x12.\n" +
	"\x10expected_version\x18\x03 \x01(\x03H\x00R\x0fexpectedVersion\x88\x01\x01B\x13\n" +
	"\x11_expected_version\"/\n" +
	"\x13DeleteValueResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xc8\x01\n" +
	"\x13SetReferenceRequest\x12A\n" +
	"\x05class\x18\x01 \x01(\x0e2!.deployments.v1.Environment.ClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x12:\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x12.env.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\x122\n" +
	"\x06target\x18\x03 \x01(\v2\x12.env.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\x06target\"I\n" +
	"\x14SetReferenceResponse\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.env.v1.ValueMetadataR\bmetadata\"\x96\x01\n" +
	"\x15ListReferencesRequest\x12A\n" +
	"\x05class\x18\x01 \x01(\x0e2!.deployments.v1.Environment.ClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x12:\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x12.env.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\"L\n" +
	"\x16ListReferencesResponse\x122\n" +
	"\n" +
	"references\x18\x01 \x03(\v2\x12.env.v1.CoordinateR\n" +
	"references\"\x94\x01\n" +
	"\x13ListVersionsRequest\x12A\n" +
	"\x05class\x18\x01 \x01(\x0e2!.deployments.v1.Environment.ClassB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05class\x12:\n" +
	"\n" +
	"coordinate\x18\x02 \x01(\v2\x12.env.v1.CoordinateB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"coordinate\"H\n" +
	"\x14ListVersionsResponse\x120\n" +
	"\bversions\x18\x01 \x03(\v2\x14.env.v1.VersionEntryR\bversions\"\x8a\x02\n" +
	"\x0eSetLinkRequest\x125\n" +
	"\x04slug\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12C\n" +
	"\x05class\x18\x02 \x01(\x0e2!.deployments.v1.Environment.ClassB\n" +
	"\xbaH\a\x82\x01\x04\x18\x01\x18\x02R\x05class\x12:\n" +
	"\venvironment\x18\x03 \x01(\tB\x18\xbaH\x15r\x132\x11^[^#*[:cntrl:]]*$R\venvironment\x12*\n" +
	"\x04link\x18\x04 \x01(\v2\x0e.links.v1.LinkB\x06\xbaH\x03\xc8\x01\x01R\x04link\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\"+\n" +
	"\x0fSetLinkResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"\xfa\x01\n" +
	"\x11RemoveLinkRequest\x125\n" +
	"\x04slug\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12C\n" +
	"\x05class\x18\x02 \x01(\x0e2!.deployments.v1.Environment.ClassB\n" +
	"\xbaH\a\x82\x01\x04\x18\x01\x18\x02R\x05class\x12:\n" +
	"\venvironment\x18\x03 \x01(\tB\x18\xbaH\x15r\x132\x11^[^#*[:cntrl:]]*$R\venvironment\x12-\n" +
	"\x04name\x18\x04 \x01(\tB\x19\xbaH\x16r\x14\x10\x012\x10^[^#[:cntrl:]]*$R\x04name\".\n" +
	"\x12RemoveLinkResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"\xca\x01\n" +
	"\x10ListLinksRequest\x125\n" +
	"\x04slug\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04slug\x12C\n" +
	"\x05class\x18\x02 \x01(\x0e2!.deployments.v1.Environment.ClassB\n" +
	"\xbaH\a\x82\x01\x04\x18\x01\x18\x02R\x05class\x12:\n" +
	"\venvironment\x18\x03 \x01(\tB\x18\xbaH\x15r\x132\x11^[^#*[:cntrl:]]*$R\venvironment\">\n" +
	"\x11ListLinksResponse\x12)\n" +
	"\x05links\x18\x01 \x03(\v2\x13.env.v1.LinkSummaryR\x05links\"\xc8\x01\n" +
	"\vLinkSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.links.v1.LinkTypeR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x125\n" +
	"\n" +
	"properties\x18\x06 \x03(\v2\x15.env.v1.PropertyShapeR\n" +
	"properties\"T\n" +
	"\rPropertyShape\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tjson_type\x18\x02 \x01(\tR\bjsonType\x12\x12\n" +
	"\x04list\x18\x03 \x01(\bR\x04list2\x90\x06\n" +
	"\x0eEnvVarsService\x12=\n" +
	"\bSetValue\x12\x17.env.v1.SetValueRequest\x1a\x18.env.v1.SetValueResponse\x12C\n" +
	"\n" +
	"ListValues\x12\x19.env.v1.ListValuesRequest\x1a\x1a.env.v1.ListValuesResponse\x12=\n" +
	"\bGetValue\x12\x17.env.v1.GetValueRequest\x1a\x18.env.v1.GetValueResponse\x12I\n" +
	"\fRevealValues\x12\x1b.env.v1.RevealValuesRequest\x1a\x1c.env.v1.RevealValuesResponse\x12F\n" +
	"\vDeleteValue\x12\x1a.env.v1.DeleteValueRequest\x1a\x1b.env.v1.DeleteValueResponse\x12I\n" +
	"\fSetReference\x12\x1b.env.v1.SetReferenceRequest\x1a\x1c.env.v1.SetReferenceResponse\x12O\n" +
	"\x0eListReferences\x12\x1d.env.v1.ListReferencesRequest\x1a\x1e.env.v1.ListReferencesResponse\x12I\n" +
	"\fListVersions\x12\x1b.env.v1.ListVersionsRequest\x1a\x1c.env.v1.ListVersionsResponse\x12:\n" +
	"\aSetLink\x12\x16.env.v1.SetLinkRequest\x1a\x17.env.v1.SetLinkResponse\x12C\n" +
	"\n" +
	"RemoveLink\x12\x19.env.v1.RemoveLinkRequest\x1a\x1a.env.v1.RemoveLinkResponse\x12@\n" +
	"\tListLinks\x12\x18.env.v1.ListLinksRequest\x1a\x19.env.v1.ListLinksResponseB/Z-github.com/ocelhq/ocel/pkg/proto/env/v1;envv1b\x06proto3"

var (
	file_env_v1_vars_proto_rawDescOnce sync.Once
	file_env_v1_vars_proto_rawDescData []byte
)

func file_env_v1_vars_proto_rawDescGZIP() []byte {
	file_env_v1_vars_proto_rawDescOnce.Do(func() {
		file_env_v1_vars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_env_v1_vars_proto_rawDesc), len(file_env_v1_vars_proto_rawDesc)))
	})
	return file_env_v1_vars_proto_rawDescData
}

var file_env_v1_vars_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_env_v1_vars_proto_goTypes = []any{
	(*Coordinate)(nil),             // 0: env.v1.Coordinate
	(*ValueMetadata)(nil),          // 1: env.v1.ValueMetadata
	(*VersionEntry)(nil),           // 2: env.v1.VersionEntry
	(*SetValueRequest)(nil),        // 3: env.v1.SetValueRequest
	(*SetValueResponse)(nil),       // 4: env.v1.SetValueResponse
	(*ListValuesRequest)(nil),      // 5: env.v1.ListValuesRequest
	(*ListValuesResponse)(nil),     // 6: env.v1.ListValuesResponse
	(*GetValueRequest)(nil),        // 7: env.v1.GetValueRequest
	(*GetValueResponse)(nil),       // 8: env.v1.GetValueResponse
	(*RevealValuesRequest)(nil),    // 9: env.v1.RevealValuesRequest
	(*Cell)(nil),                   // 10: env.v1.Cell
	(*RevealValuesResponse)(nil),   // 11: env.v1.RevealValuesResponse
	(*RevealedValue)(nil),          // 12: env.v1.RevealedValue
	(*DeleteValueRequest)(nil),     // 13: env.v1.DeleteValueRequest
	(*DeleteValueResponse)(nil),    // 14: env.v1.DeleteValueResponse
	(*SetReferenceRequest)(nil),    // 15: env.v1.SetReferenceRequest
	(*SetReferenceResponse)(nil),   // 16: env.v1.SetReferenceResponse
	(*ListReferencesRequest)(nil),  // 17: env.v1.ListReferencesRequest
	(*ListReferencesResponse)(nil), // 18: env.v1.ListReferencesResponse
	(*ListVersionsRequest)(nil),    // 19: env.v1.ListVersionsRequest
	(*ListVersionsResponse)(nil),   // 20: env.v1.ListVersionsResponse
	(*SetLinkRequest)(nil),         // 21: env.v1.SetLinkRequest
	(*SetLinkResponse)(nil),        // 22: env.v1.SetLinkResponse
	(*RemoveLinkRequest)(nil),      // 23: env.v1.RemoveLinkRequest
	(*RemoveLinkResponse)(nil),     // 24: env.v1.RemoveLinkResponse
	(*ListLinksRequest)(nil),       // 25: env.v1.ListLinksRequest
	(*ListLinksResponse)(nil),      // 26: env.v1.ListLinksResponse
	(*LinkSummary)(nil),            // 27: env.v1.LinkSummary
	(*PropertyShape)(nil),          // 28: env.v1.PropertyShape
	(v1.Environment_Class)(0),      // 29: deployments.v1.Environment.Class
	(*v11.Link)(nil),               // 30: links.v1.Link
	(v11.LinkType)(0),              // 31: links.v1.LinkType
}
var file_env_v1_vars_proto_depIdxs = []int32{
	0,  // 0: env.v1.ValueMetadata.coordinate:type_name -> env.v1.Coordinate
	0,  // 1: env.v1.ValueMetadata.target:type_name -> env.v1.Coordinate
	29, // 2: env.v1.SetValueRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 3: env.v1.SetValueRequest.coordinate:type_name -> env.v1.Coordinate
	1,  // 4: env.v1.SetValueResponse.metadata:type_name -> env.v1.ValueMetadata
	29, // 5: env.v1.ListValuesRequest.class:type_name -> deployments.v1.Environment.Class
	1,  // 6: env.v1.ListValuesResponse.values:type_name -> env.v1.ValueMetadata
	29, // 7: env.v1.GetValueRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 8: env.v1.GetValueRequest.coordinate:type_name -> env.v1.Coordinate
	1,  // 9: env.v1.GetValueResponse.metadata:type_name -> env.v1.ValueMetadata
	29, // 10: env.v1.RevealValuesRequest.class:type_name -> deployments.v1.Environment.Class
	10, // 11: env.v1.RevealValuesRequest.cells:type_name -> env.v1.Cell
	12, // 12: env.v1.RevealValuesResponse.values:type_name -> env.v1.RevealedValue
	1,  // 13: env.v1.RevealedValue.metadata:type_name -> env.v1.ValueMetadata
	29, // 14: env.v1.DeleteValueRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 15: env.v1.DeleteValueRequest.coordinate:type_name -> env.v1.Coordinate
	29, // 16: env.v1.SetReferenceRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 17: env.v1.SetReferenceRequest.coordinate:type_name -> env.v1.Coordinate
	0,  // 18: env.v1.SetReferenceRequest.target:type_name -> env.v1.Coordinate
	1,  // 19: env.v1.SetReferenceResponse.metadata:type_name -> env.v1.ValueMetadata
	29, // 20: env.v1.ListReferencesRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 21: env.v1.ListReferencesRequest.coordinate:type_name -> env.v1.Coordinate
	0,  // 22: env.v1.ListReferencesResponse.references:type_name -> env.v1.Coordinate
	29, // 23: env.v1.ListVersionsRequest.class:type_name -> deployments.v1.Environment.Class
	0,  // 24: env.v1.ListVersionsRequest.coordinate:type_name -> env.v1.Coordinate
	2,  // 25: env.v1.ListVersionsResponse.versions:type_name -> env.v1.VersionEntry
	29, // 26: env.v1.SetLinkRequest.class:type_name -> deployments.v1.Environment.Class
	30, // 27: env.v1.SetLinkRequest.link:type_name -> links.v1.Link
	29, // 28: env.v1.RemoveLinkRequest.class:type_name -> deployments.v1.Environment.Class
	29, // 29: env.v1.ListLinksRequest.class:type_name -> deployments.v1.Environment.Class
	27, // 30: env.v1.ListLinksResponse.links:type_name -> env.v1.LinkSummary
	31, // 31: env.v1.LinkSummary.type:type_name -> links.v1.LinkType
	28, // 32: env.v1.LinkSummary.properties:type_name -> env.v1.PropertyShape
	3,  // 33: env.v1.EnvVarsService.SetValue:input_type -> env.v1.SetValueRequest
	5,  // 34: env.v1.EnvVarsService.ListValues:input_type -> env.v1.ListValuesRequest
	7,  // 35: env.v1.EnvVarsService.GetValue:input_type -> env.v1.GetValueRequest
	9,  // 36: env.v1.EnvVarsService.RevealValues:input_type -> env.v1.RevealValuesRequest
	13, // 37: env.v1.EnvVarsService.DeleteValue:input_type -> env.v1.DeleteValueRequest
	15, // 38: env.v1.EnvVarsService.SetReference:input_type -> env.v1.SetReferenceRequest
	17, // 39: env.v1.EnvVarsService.ListReferences:input_type -> env.v1.ListReferencesRequest
	19, // 40: env.v1.EnvVarsService.ListVersions:input_type -> env.v1.ListVersionsRequest
	21, // 41: env.v1.EnvVarsService.SetLink:input_type -> env.v1.SetLinkRequest
	23, // 42: env.v1.EnvVarsService.RemoveLink:input_type -> env.v1.RemoveLinkRequest
	25, // 43: env.v1.EnvVarsService.ListLinks:input_type -> env.v1.ListLinksRequest
	4,  // 44: env.v1.EnvVarsService.SetValue:output_type -> env.v1.SetValueResponse
	6,  // 45: env.v1.EnvVarsService.ListValues:output_type -> env.v1.ListValuesResponse
	8,  // 46: env.v1.EnvVarsService.GetValue:output_type -> env.v1.GetValueResponse
	11, // 47: env.v1.EnvVarsService.RevealValues:output_type -> env.v1.RevealValuesResponse
	14, // 48: env.v1.EnvVarsService.DeleteValue:output_type -> env.v1.DeleteValueResponse
	16, // 49: env.v1.EnvVarsService.SetReference:output_type -> env.v1.SetReferenceResponse
	18, // 50: env.v1.EnvVarsService.ListReferences:output_type -> env.v1.ListReferencesResponse
	20, // 51: env.v1.EnvVarsService.ListVersions:output_type -> env.v1.ListVersionsResponse
	22, // 52: env.v1.EnvVarsService.SetLink:output_type -> env.v1.SetLinkResponse
	24, // 53: env.v1.EnvVarsService.RemoveLink:output_type -> env.v1.RemoveLinkResponse
	26, // 54: env.v1.EnvVarsService.ListLinks:output_type -> env.v1.ListLinksResponse
	44, // [44:55] is the sub-list for method output_type
	33, // [33:44] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_env_v1_vars_proto_init() }
func file_env_v1_vars_proto_init() {
	if File_env_v1_vars_proto != nil {
		return
	}
	file_env_v1_vars_proto_msgTypes[1].OneofWrappers = []any{}
	file_env_v1_vars_proto_msgTypes[3].OneofWrappers = []any{}
	file_env_v1_vars_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_env_v1_vars_proto_rawDesc), len(file_env_v1_vars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_env_v1_vars_proto_goTypes,
		DependencyIndexes: file_env_v1_vars_proto_depIdxs,
		MessageInfos:      file_env_v1_vars_proto_msgTypes,
	}.Build()
	File_env_v1_vars_proto = out.File
	file_env_v1_vars_proto_goTypes = nil
	file_env_v1_vars_proto_depIdxs = nil
}
