package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	envvarsv1 "github.com/ocelhq/ocel/pkg/proto/envvars/v1"
	linksv1 "github.com/ocelhq/ocel/pkg/proto/links/v1"
)

func shape(name, jsonType string, list bool) *envvarsv1.PropertyShape {
	return &envvarsv1.PropertyShape{Name: name, JsonType: jsonType, List: list}
}

func TestRenderLinkTypes(t *testing.T) {
	t.Run("writes what the checked-in fixture the transform package typechecks holds", func(t *testing.T) {
		got := renderLinkTypes("@ocel/provider-aws", "production", []*envvarsv1.LinkSummary{
			{
				Name: "network",
				Type: linksv1.LinkType_LINK_TYPE_CUSTOM,
				Properties: []*envvarsv1.PropertyShape{
					shape("securityGroupIds", "string", true),
					shape("subnetIds", "string", true),
				},
			},
			{
				Name: "orders",
				Type: linksv1.LinkType_LINK_TYPE_POSTGRES,
				Properties: []*envvarsv1.PropertyShape{
					shape("host", "string", false),
					shape("port", "number", false),
					shape("database", "string", false),
					shape("username", "string", false),
					shape("password", "string", false),
				},
			},
		})

		fixture := filepath.Join("..", "..", "..", "packages", "provider-aws", "typetests", "typed", linkTypesFileName)
		want, err := os.ReadFile(fixture)
		if err != nil {
			t.Fatalf("read %s: %v", fixture, err)
		}
		if got != string(want) {
			t.Errorf("renderLinkTypes() =\n%s\nwant\n%s", got, want)
		}
	})

	t.Run("names the coordinate it read and holds no value", func(t *testing.T) {
		got := renderLinkTypes("@ocel/provider-aws", "the preview environment pr-12", []*envvarsv1.LinkSummary{
			{Name: "network", Properties: []*envvarsv1.PropertyShape{shape("subnetIds", "string", true)}},
		})
		if want := "// generated by `ocel link generate` from the preview environment pr-12; do not edit\n"; got[:len(want)] != want {
			t.Errorf("header = %q, want %q", got[:len(want)], want)
		}
	})

	t.Run("marks the file as generated even when the coordinate published nothing", func(t *testing.T) {
		got := renderLinkTypes("@ocel/provider-aws", "production", nil)

		fixture := filepath.Join("..", "..", "..", "packages", "provider-aws", "typetests", "empty", linkTypesFileName)
		want, err := os.ReadFile(fixture)
		if err != nil {
			t.Fatalf("read %s: %v", fixture, err)
		}
		if got != string(want) {
			t.Errorf("renderLinkTypes() =\n%s\nwant\n%s", got, want)
		}
	})

	t.Run("quotes a key the way JavaScript reads it back", func(t *testing.T) {
		got := renderLinkTypes("@ocel/provider-aws", "production", []*envvarsv1.LinkSummary{
			{Name: "a\ab", Properties: []*envvarsv1.PropertyShape{
				shape("bell\a", "string", false),
				shape("astral\U000e0001", "string", false),
				shape("line\nbreak", "string", false),
			}},
		})

		for _, want := range []string{
			"\"a\\u0007b\"",
			"\"bell\\u0007\"",
			"\"astral\U000e0001\"",
			`"line\nbreak"`,
		} {
			if !strings.Contains(got, want) {
				t.Errorf("renderLinkTypes() =\n%s\nwant it to hold %q", got, want)
			}
		}
		for _, never := range []string{`\a`, `\U000e0001`} {
			if strings.Contains(got, never) {
				t.Errorf("renderLinkTypes() =\n%s\nwrote %q, which JavaScript reads as something else", got, never)
			}
		}
	})

	t.Run("renders every shape a record can carry", func(t *testing.T) {
		got := renderLinkTypes("@ocel/provider-aws", "production", []*envvarsv1.LinkSummary{
			{Name: "carries-nothing"},
			{Name: "shapes", Properties: []*envvarsv1.PropertyShape{
				shape("count", "number", false),
				shape("public", "boolean", false),
				shape("tags", "object", false),
				shape("empty", "unknown", true),
				shape("kebab-case", "string", false),
			}},
		})

		for _, want := range []string{
			"    \"carries-nothing\": {};\n",
			"count: number",
			"public: boolean",
			"tags: Record<string, unknown>",
			"empty: unknown[]",
			`"kebab-case": string`,
		} {
			if !strings.Contains(got, want) {
				t.Errorf("renderLinkTypes() =\n%s\nwant it to hold %q", got, want)
			}
		}
	})
}
