syntax = "proto3";
package links.v1;

option go_package = "github.com/ocelhq/ocel/pkg/proto/links/v1;linksv1";

enum LinkType {
  LINK_TYPE_UNSPECIFIED = 0;
  LINK_TYPE_POSTGRES = 1;
  LINK_TYPE_BUCKET = 2;
}

message Link {
  string name = 1;

  oneof properties {
    PostgresProperties postgres = 2;
    BucketProperties bucket = 3;
  }

  repeated Grant grants = 4;

  string source = 5;
}

message PostgresProperties {
  string host = 1;
  int32 port = 2;
  string database = 3;
  string username = 4;
  string password = 5 [debug_redact = true];
}

message BucketProperties {
  string bucket = 1;
}

message Grant {
  repeated string actions = 1;

  repeated string resources = 2;

  string label = 3;

  repeated GrantCondition conditions = 4;
}

message GrantCondition {
  string operator = 1;

  string key = 2;

  repeated string values = 3;
}
