// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: provider/v1/provider.proto

package providerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ocelhq/ocel/pkg/proto/provider/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProviderServiceName is the fully-qualified name of the ProviderService service.
	ProviderServiceName = "provider.v1.ProviderService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProviderServiceDeployProcedure is the fully-qualified name of the ProviderService's Deploy RPC.
	ProviderServiceDeployProcedure = "/provider.v1.ProviderService/Deploy"
	// ProviderServiceBootstrapProcedure is the fully-qualified name of the ProviderService's Bootstrap
	// RPC.
	ProviderServiceBootstrapProcedure = "/provider.v1.ProviderService/Bootstrap"
)

// ProviderServiceClient is a client for the provider.v1.ProviderService service.
type ProviderServiceClient interface {
	Deploy(context.Context, *v1.DeployRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error)
	// Bootstrap provisions the account-global, non-project-specific
	// resources a provider needs before any deploy can run (for the AWS
	// provider: the S3 bucket that holds Pulumi state, and a Pulumi
	// passphrase). It is a one-time-per-account action, re-run only when the
	// bootstrapped resources change. It reuses the DeployEvent stream:
	// progress/log events, then a terminal ResultEvent. Bootstrap carries no
	// outputs on its result.
	Bootstrap(context.Context, *v1.BootstrapRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error)
}

// NewProviderServiceClient constructs a client for the provider.v1.ProviderService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProviderServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProviderServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	providerServiceMethods := v1.File_provider_v1_provider_proto.Services().ByName("ProviderService").Methods()
	return &providerServiceClient{
		deploy: connect.NewClient[v1.DeployRequest, v1.DeployEvent](
			httpClient,
			baseURL+ProviderServiceDeployProcedure,
			connect.WithSchema(providerServiceMethods.ByName("Deploy")),
			connect.WithClientOptions(opts...),
		),
		bootstrap: connect.NewClient[v1.BootstrapRequest, v1.DeployEvent](
			httpClient,
			baseURL+ProviderServiceBootstrapProcedure,
			connect.WithSchema(providerServiceMethods.ByName("Bootstrap")),
			connect.WithClientOptions(opts...),
		),
	}
}

// providerServiceClient implements ProviderServiceClient.
type providerServiceClient struct {
	deploy    *connect.Client[v1.DeployRequest, v1.DeployEvent]
	bootstrap *connect.Client[v1.BootstrapRequest, v1.DeployEvent]
}

// Deploy calls provider.v1.ProviderService.Deploy.
func (c *providerServiceClient) Deploy(ctx context.Context, req *v1.DeployRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error) {
	return c.deploy.CallServerStream(ctx, connect.NewRequest(req))
}

// Bootstrap calls provider.v1.ProviderService.Bootstrap.
func (c *providerServiceClient) Bootstrap(ctx context.Context, req *v1.BootstrapRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error) {
	return c.bootstrap.CallServerStream(ctx, connect.NewRequest(req))
}

// ProviderServiceHandler is an implementation of the provider.v1.ProviderService service.
type ProviderServiceHandler interface {
	Deploy(context.Context, *v1.DeployRequest, *connect.ServerStream[v1.DeployEvent]) error
	// Bootstrap provisions the account-global, non-project-specific
	// resources a provider needs before any deploy can run (for the AWS
	// provider: the S3 bucket that holds Pulumi state, and a Pulumi
	// passphrase). It is a one-time-per-account action, re-run only when the
	// bootstrapped resources change. It reuses the DeployEvent stream:
	// progress/log events, then a terminal ResultEvent. Bootstrap carries no
	// outputs on its result.
	Bootstrap(context.Context, *v1.BootstrapRequest, *connect.ServerStream[v1.DeployEvent]) error
}

// NewProviderServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProviderServiceHandler(svc ProviderServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	providerServiceMethods := v1.File_provider_v1_provider_proto.Services().ByName("ProviderService").Methods()
	providerServiceDeployHandler := connect.NewServerStreamHandlerSimple(
		ProviderServiceDeployProcedure,
		svc.Deploy,
		connect.WithSchema(providerServiceMethods.ByName("Deploy")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceBootstrapHandler := connect.NewServerStreamHandlerSimple(
		ProviderServiceBootstrapProcedure,
		svc.Bootstrap,
		connect.WithSchema(providerServiceMethods.ByName("Bootstrap")),
		connect.WithHandlerOptions(opts...),
	)
	return "/provider.v1.ProviderService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProviderServiceDeployProcedure:
			providerServiceDeployHandler.ServeHTTP(w, r)
		case ProviderServiceBootstrapProcedure:
			providerServiceBootstrapHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProviderServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProviderServiceHandler struct{}

func (UnimplementedProviderServiceHandler) Deploy(context.Context, *v1.DeployRequest, *connect.ServerStream[v1.DeployEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("provider.v1.ProviderService.Deploy is not implemented"))
}

func (UnimplementedProviderServiceHandler) Bootstrap(context.Context, *v1.BootstrapRequest, *connect.ServerStream[v1.DeployEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("provider.v1.ProviderService.Bootstrap is not implemented"))
}
