// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: common/plan/v1/plan.proto

package planv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Change_Action int32

const (
	Change_ACTION_UNSPECIFIED         Change_Action = 0
	Change_ACTION_CREATE              Change_Action = 1
	Change_ACTION_UPDATE              Change_Action = 2
	Change_ACTION_REPLACE             Change_Action = 3
	Change_ACTION_DELETE              Change_Action = 4
	Change_ACTION_DISABLE_THEN_DELETE Change_Action = 5
	Change_ACTION_KEEP                Change_Action = 6
)

// Enum value maps for Change_Action.
var (
	Change_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_CREATE",
		2: "ACTION_UPDATE",
		3: "ACTION_REPLACE",
		4: "ACTION_DELETE",
		5: "ACTION_DISABLE_THEN_DELETE",
		6: "ACTION_KEEP",
	}
	Change_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":         0,
		"ACTION_CREATE":              1,
		"ACTION_UPDATE":              2,
		"ACTION_REPLACE":             3,
		"ACTION_DELETE":              4,
		"ACTION_DISABLE_THEN_DELETE": 5,
		"ACTION_KEEP":                6,
	}
)

func (x Change_Action) Enum() *Change_Action {
	p := new(Change_Action)
	*p = x
	return p
}

func (x Change_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Change_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_common_plan_v1_plan_proto_enumTypes[0].Descriptor()
}

func (Change_Action) Type() protoreflect.EnumType {
	return &file_common_plan_v1_plan_proto_enumTypes[0]
}

func (x Change_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Change_Action.Descriptor instead.
func (Change_Action) EnumDescriptor() ([]byte, []int) {
	return file_common_plan_v1_plan_proto_rawDescGZIP(), []int{2, 0}
}

type ChangePlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	EdgeKind      string                 `protobuf:"bytes,2,opt,name=edge_kind,json=edgeKind,proto3" json:"edge_kind,omitempty"`
	Groups        []*ChangeGroup         `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePlan) Reset() {
	*x = ChangePlan{}
	mi := &file_common_plan_v1_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePlan) ProtoMessage() {}

func (x *ChangePlan) ProtoReflect() protoreflect.Message {
	mi := &file_common_plan_v1_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePlan.ProtoReflect.Descriptor instead.
func (*ChangePlan) Descriptor() ([]byte, []int) {
	return file_common_plan_v1_plan_proto_rawDescGZIP(), []int{0}
}

func (x *ChangePlan) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ChangePlan) GetEdgeKind() string {
	if x != nil {
		return x.EdgeKind
	}
	return ""
}

func (x *ChangePlan) GetGroups() []*ChangeGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ChangeGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Feature       string                 `protobuf:"bytes,3,opt,name=feature,proto3" json:"feature,omitempty"`
	Action        Change_Action          `protobuf:"varint,4,opt,name=action,proto3,enum=common.plan.v1.Change_Action" json:"action,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Slow          bool                   `protobuf:"varint,6,opt,name=slow,proto3" json:"slow,omitempty"`
	Changes       []*Change              `protobuf:"bytes,7,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeGroup) Reset() {
	*x = ChangeGroup{}
	mi := &file_common_plan_v1_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeGroup) ProtoMessage() {}

func (x *ChangeGroup) ProtoReflect() protoreflect.Message {
	mi := &file_common_plan_v1_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeGroup.ProtoReflect.Descriptor instead.
func (*ChangeGroup) Descriptor() ([]byte, []int) {
	return file_common_plan_v1_plan_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeGroup) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ChangeGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChangeGroup) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *ChangeGroup) GetAction() Change_Action {
	if x != nil {
		return x.Action
	}
	return Change_ACTION_UNSPECIFIED
}

func (x *ChangeGroup) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ChangeGroup) GetSlow() bool {
	if x != nil {
		return x.Slow
	}
	return false
}

func (x *ChangeGroup) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Action        Change_Action          `protobuf:"varint,3,opt,name=action,proto3,enum=common.plan.v1.Change_Action" json:"action,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Slow          bool                   `protobuf:"varint,5,opt,name=slow,proto3" json:"slow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_common_plan_v1_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_common_plan_v1_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_common_plan_v1_plan_proto_rawDescGZIP(), []int{2}
}

func (x *Change) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Change) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Change) GetAction() Change_Action {
	if x != nil {
		return x.Action
	}
	return Change_ACTION_UNSPECIFIED
}

func (x *Change) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Change) GetSlow() bool {
	if x != nil {
		return x.Slow
	}
	return false
}

var File_common_plan_v1_plan_proto protoreflect.FileDescriptor

const file_common_plan_v1_plan_proto_rawDesc = "" +
	"\n" +
	"\x19common/plan/v1/plan.proto\x12\x0ecommon.plan.v1\"x\n" +
	"\n" +
	"ChangePlan\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\tedge_kind\x18\x02 \x01(\tR\bedgeKind\x123\n" +
	"\x06groups\x18\x03 \x03(\v2\x1b.common.plan.v1.ChangeGroupR\x06groups\"\xe4\x01\n" +
	"\vChangeGroup\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\afeature\x18\x03 \x01(\tR\afeature\x125\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1d.common.plan.v1.Change.ActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x12\n" +
	"\x04slow\x18\x06 \x01(\bR\x04slow\x120\n" +
	"\achanges\x18\a \x03(\v2\x16.common.plan.v1.ChangeR\achanges\"\xb4\x02\n" +
	"\x06Change\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1d.common.plan.v1.Change.ActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x12\n" +
	"\x04slow\x18\x05 \x01(\bR\x04slow\"\x9e\x01\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACTION_CREATE\x10\x01\x12\x11\n" +
	"\rACTION_UPDATE\x10\x02\x12\x12\n" +
	"\x0eACTION_REPLACE\x10\x03\x12\x11\n" +
	"\rACTION_DELETE\x10\x04\x12\x1e\n" +
	"\x1aACTION_DISABLE_THEN_DELETE\x10\x05\x12\x0f\n" +
	"\vACTION_KEEP\x10\x06B8Z6github.com/ocelhq/ocel/pkg/proto/common/plan/v1;planv1b\x06proto3"

var (
	file_common_plan_v1_plan_proto_rawDescOnce sync.Once
	file_common_plan_v1_plan_proto_rawDescData []byte
)

func file_common_plan_v1_plan_proto_rawDescGZIP() []byte {
	file_common_plan_v1_plan_proto_rawDescOnce.Do(func() {
		file_common_plan_v1_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_plan_v1_plan_proto_rawDesc), len(file_common_plan_v1_plan_proto_rawDesc)))
	})
	return file_common_plan_v1_plan_proto_rawDescData
}

var file_common_plan_v1_plan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_plan_v1_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_plan_v1_plan_proto_goTypes = []any{
	(Change_Action)(0),  // 0: common.plan.v1.Change.Action
	(*ChangePlan)(nil),  // 1: common.plan.v1.ChangePlan
	(*ChangeGroup)(nil), // 2: common.plan.v1.ChangeGroup
	(*Change)(nil),      // 3: common.plan.v1.Change
}
var file_common_plan_v1_plan_proto_depIdxs = []int32{
	2, // 0: common.plan.v1.ChangePlan.groups:type_name -> common.plan.v1.ChangeGroup
	0, // 1: common.plan.v1.ChangeGroup.action:type_name -> common.plan.v1.Change.Action
	3, // 2: common.plan.v1.ChangeGroup.changes:type_name -> common.plan.v1.Change
	0, // 3: common.plan.v1.Change.action:type_name -> common.plan.v1.Change.Action
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_plan_v1_plan_proto_init() }
func file_common_plan_v1_plan_proto_init() {
	if File_common_plan_v1_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_plan_v1_plan_proto_rawDesc), len(file_common_plan_v1_plan_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_plan_v1_plan_proto_goTypes,
		DependencyIndexes: file_common_plan_v1_plan_proto_depIdxs,
		EnumInfos:         file_common_plan_v1_plan_proto_enumTypes,
		MessageInfos:      file_common_plan_v1_plan_proto_msgTypes,
	}.Build()
	File_common_plan_v1_plan_proto = out.File
	file_common_plan_v1_plan_proto_goTypes = nil
	file_common_plan_v1_plan_proto_depIdxs = nil
}
