// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: dev/v1/dev.proto

package devv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ocelhq/ocel/pkg/proto/dev/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DevServiceName is the fully-qualified name of the DevService service.
	DevServiceName = "dev.v1.DevService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DevServiceSubscribeProcedure is the fully-qualified name of the DevService's Subscribe RPC.
	DevServiceSubscribeProcedure = "/dev.v1.DevService/Subscribe"
)

// DevServiceClient is a client for the dev.v1.DevService service.
type DevServiceClient interface {
	Subscribe(context.Context, *v1.SubscribeRequest) (*connect.ServerStreamForClient[v1.EnvUpdate], error)
}

// NewDevServiceClient constructs a client for the dev.v1.DevService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDevServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DevServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	devServiceMethods := v1.File_dev_v1_dev_proto.Services().ByName("DevService").Methods()
	return &devServiceClient{
		subscribe: connect.NewClient[v1.SubscribeRequest, v1.EnvUpdate](
			httpClient,
			baseURL+DevServiceSubscribeProcedure,
			connect.WithSchema(devServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// devServiceClient implements DevServiceClient.
type devServiceClient struct {
	subscribe *connect.Client[v1.SubscribeRequest, v1.EnvUpdate]
}

// Subscribe calls dev.v1.DevService.Subscribe.
func (c *devServiceClient) Subscribe(ctx context.Context, req *v1.SubscribeRequest) (*connect.ServerStreamForClient[v1.EnvUpdate], error) {
	return c.subscribe.CallServerStream(ctx, connect.NewRequest(req))
}

// DevServiceHandler is an implementation of the dev.v1.DevService service.
type DevServiceHandler interface {
	Subscribe(context.Context, *v1.SubscribeRequest, *connect.ServerStream[v1.EnvUpdate]) error
}

// NewDevServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDevServiceHandler(svc DevServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	devServiceMethods := v1.File_dev_v1_dev_proto.Services().ByName("DevService").Methods()
	devServiceSubscribeHandler := connect.NewServerStreamHandlerSimple(
		DevServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(devServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/dev.v1.DevService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DevServiceSubscribeProcedure:
			devServiceSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDevServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDevServiceHandler struct{}

func (UnimplementedDevServiceHandler) Subscribe(context.Context, *v1.SubscribeRequest, *connect.ServerStream[v1.EnvUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("dev.v1.DevService.Subscribe is not implemented"))
}
