// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: console/v1/connector.proto

package consolev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ocelhq/ocel/pkg/proto/console/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConnectorServiceName is the fully-qualified name of the ConnectorService service.
	ConnectorServiceName = "console.v1.ConnectorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConnectorServiceUpsertProcedure is the fully-qualified name of the ConnectorService's Upsert RPC.
	ConnectorServiceUpsertProcedure = "/console.v1.ConnectorService/Upsert"
	// ConnectorServiceListProcedure is the fully-qualified name of the ConnectorService's List RPC.
	ConnectorServiceListProcedure = "/console.v1.ConnectorService/List"
	// ConnectorServiceRemoveProcedure is the fully-qualified name of the ConnectorService's Remove RPC.
	ConnectorServiceRemoveProcedure = "/console.v1.ConnectorService/Remove"
	// ConnectorServiceSetAddressProcedure is the fully-qualified name of the ConnectorService's
	// SetAddress RPC.
	ConnectorServiceSetAddressProcedure = "/console.v1.ConnectorService/SetAddress"
	// ConnectorServiceHeartbeatProcedure is the fully-qualified name of the ConnectorService's
	// Heartbeat RPC.
	ConnectorServiceHeartbeatProcedure = "/console.v1.ConnectorService/Heartbeat"
)

// ConnectorServiceClient is a client for the console.v1.ConnectorService service.
type ConnectorServiceClient interface {
	Upsert(context.Context, *v1.UpsertConnectorRequest) (*v1.UpsertConnectorResponse, error)
	List(context.Context, *v1.ListConnectorsRequest) (*v1.ListConnectorsResponse, error)
	Remove(context.Context, *v1.RemoveConnectorRequest) (*v1.RemoveConnectorResponse, error)
	SetAddress(context.Context, *v1.SetConnectorAddressRequest) (*v1.SetConnectorAddressResponse, error)
	Heartbeat(context.Context, *v1.HeartbeatConnectorRequest) (*v1.HeartbeatConnectorResponse, error)
}

// NewConnectorServiceClient constructs a client for the console.v1.ConnectorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectorServiceMethods := v1.File_console_v1_connector_proto.Services().ByName("ConnectorService").Methods()
	return &connectorServiceClient{
		upsert: connect.NewClient[v1.UpsertConnectorRequest, v1.UpsertConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceUpsertProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListConnectorsRequest, v1.ListConnectorsResponse](
			httpClient,
			baseURL+ConnectorServiceListProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		remove: connect.NewClient[v1.RemoveConnectorRequest, v1.RemoveConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceRemoveProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("Remove")),
			connect.WithClientOptions(opts...),
		),
		setAddress: connect.NewClient[v1.SetConnectorAddressRequest, v1.SetConnectorAddressResponse](
			httpClient,
			baseURL+ConnectorServiceSetAddressProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("SetAddress")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v1.HeartbeatConnectorRequest, v1.HeartbeatConnectorResponse](
			httpClient,
			baseURL+ConnectorServiceHeartbeatProcedure,
			connect.WithSchema(connectorServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectorServiceClient implements ConnectorServiceClient.
type connectorServiceClient struct {
	upsert     *connect.Client[v1.UpsertConnectorRequest, v1.UpsertConnectorResponse]
	list       *connect.Client[v1.ListConnectorsRequest, v1.ListConnectorsResponse]
	remove     *connect.Client[v1.RemoveConnectorRequest, v1.RemoveConnectorResponse]
	setAddress *connect.Client[v1.SetConnectorAddressRequest, v1.SetConnectorAddressResponse]
	heartbeat  *connect.Client[v1.HeartbeatConnectorRequest, v1.HeartbeatConnectorResponse]
}

// Upsert calls console.v1.ConnectorService.Upsert.
func (c *connectorServiceClient) Upsert(ctx context.Context, req *v1.UpsertConnectorRequest) (*v1.UpsertConnectorResponse, error) {
	response, err := c.upsert.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// List calls console.v1.ConnectorService.List.
func (c *connectorServiceClient) List(ctx context.Context, req *v1.ListConnectorsRequest) (*v1.ListConnectorsResponse, error) {
	response, err := c.list.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Remove calls console.v1.ConnectorService.Remove.
func (c *connectorServiceClient) Remove(ctx context.Context, req *v1.RemoveConnectorRequest) (*v1.RemoveConnectorResponse, error) {
	response, err := c.remove.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetAddress calls console.v1.ConnectorService.SetAddress.
func (c *connectorServiceClient) SetAddress(ctx context.Context, req *v1.SetConnectorAddressRequest) (*v1.SetConnectorAddressResponse, error) {
	response, err := c.setAddress.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Heartbeat calls console.v1.ConnectorService.Heartbeat.
func (c *connectorServiceClient) Heartbeat(ctx context.Context, req *v1.HeartbeatConnectorRequest) (*v1.HeartbeatConnectorResponse, error) {
	response, err := c.heartbeat.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ConnectorServiceHandler is an implementation of the console.v1.ConnectorService service.
type ConnectorServiceHandler interface {
	Upsert(context.Context, *v1.UpsertConnectorRequest) (*v1.UpsertConnectorResponse, error)
	List(context.Context, *v1.ListConnectorsRequest) (*v1.ListConnectorsResponse, error)
	Remove(context.Context, *v1.RemoveConnectorRequest) (*v1.RemoveConnectorResponse, error)
	SetAddress(context.Context, *v1.SetConnectorAddressRequest) (*v1.SetConnectorAddressResponse, error)
	Heartbeat(context.Context, *v1.HeartbeatConnectorRequest) (*v1.HeartbeatConnectorResponse, error)
}

// NewConnectorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectorServiceHandler(svc ConnectorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectorServiceMethods := v1.File_console_v1_connector_proto.Services().ByName("ConnectorService").Methods()
	connectorServiceUpsertHandler := connect.NewUnaryHandlerSimple(
		ConnectorServiceUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(connectorServiceMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceListHandler := connect.NewUnaryHandlerSimple(
		ConnectorServiceListProcedure,
		svc.List,
		connect.WithSchema(connectorServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceRemoveHandler := connect.NewUnaryHandlerSimple(
		ConnectorServiceRemoveProcedure,
		svc.Remove,
		connect.WithSchema(connectorServiceMethods.ByName("Remove")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceSetAddressHandler := connect.NewUnaryHandlerSimple(
		ConnectorServiceSetAddressProcedure,
		svc.SetAddress,
		connect.WithSchema(connectorServiceMethods.ByName("SetAddress")),
		connect.WithHandlerOptions(opts...),
	)
	connectorServiceHeartbeatHandler := connect.NewUnaryHandlerSimple(
		ConnectorServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(connectorServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/console.v1.ConnectorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectorServiceUpsertProcedure:
			connectorServiceUpsertHandler.ServeHTTP(w, r)
		case ConnectorServiceListProcedure:
			connectorServiceListHandler.ServeHTTP(w, r)
		case ConnectorServiceRemoveProcedure:
			connectorServiceRemoveHandler.ServeHTTP(w, r)
		case ConnectorServiceSetAddressProcedure:
			connectorServiceSetAddressHandler.ServeHTTP(w, r)
		case ConnectorServiceHeartbeatProcedure:
			connectorServiceHeartbeatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectorServiceHandler struct{}

func (UnimplementedConnectorServiceHandler) Upsert(context.Context, *v1.UpsertConnectorRequest) (*v1.UpsertConnectorResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("console.v1.ConnectorService.Upsert is not implemented"))
}

func (UnimplementedConnectorServiceHandler) List(context.Context, *v1.ListConnectorsRequest) (*v1.ListConnectorsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("console.v1.ConnectorService.List is not implemented"))
}

func (UnimplementedConnectorServiceHandler) Remove(context.Context, *v1.RemoveConnectorRequest) (*v1.RemoveConnectorResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("console.v1.ConnectorService.Remove is not implemented"))
}

func (UnimplementedConnectorServiceHandler) SetAddress(context.Context, *v1.SetConnectorAddressRequest) (*v1.SetConnectorAddressResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("console.v1.ConnectorService.SetAddress is not implemented"))
}

func (UnimplementedConnectorServiceHandler) Heartbeat(context.Context, *v1.HeartbeatConnectorRequest) (*v1.HeartbeatConnectorResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("console.v1.ConnectorService.Heartbeat is not implemented"))
}
