syntax = "proto3";
package resources.v1;

option go_package = "github.com/ocelhq/ocel/pkg/proto/resources/v1;resourcesv1";

import "resources/v1/env.proto";

service ResourceService {
    rpc Declare(DeclareRequest) returns (DeclareResponse);

    rpc DeclareEnv(DeclareEnvRequest) returns (DeclareEnvResponse);

    rpc ReportEnvProblems(ReportEnvProblemsRequest) returns (ReportEnvProblemsResponse);
}

enum ResourceType {
    RESOURCE_TYPE_UNSPECIFIED = 0;
    RESOURCE_TYPE_POSTGRES = 1;
    RESOURCE_TYPE_BUCKET = 2;
}

message ResourceIdentifier {
  ResourceType type = 1;
  string name = 2;
}

message DeclareResponse {
}

message DeclareRequest {
  ResourceIdentifier resource = 1;

  oneof config {
    PostgresConfig postgres = 2;
    BucketConfig bucket = 3;
  }
}

message PostgresConfig {
  string version = 1;
}

message BucketConfig {
  repeated string allowed_origins = 1;
}
