// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: console/v1/connector.proto

package consolev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectorReach int32

const (
	ConnectorReach_CONNECTOR_REACH_UNSPECIFIED ConnectorReach = 0
	ConnectorReach_CONNECTOR_REACH_DIAL        ConnectorReach = 1
)

// Enum value maps for ConnectorReach.
var (
	ConnectorReach_name = map[int32]string{
		0: "CONNECTOR_REACH_UNSPECIFIED",
		1: "CONNECTOR_REACH_DIAL",
	}
	ConnectorReach_value = map[string]int32{
		"CONNECTOR_REACH_UNSPECIFIED": 0,
		"CONNECTOR_REACH_DIAL":        1,
	}
)

func (x ConnectorReach) Enum() *ConnectorReach {
	p := new(ConnectorReach)
	*p = x
	return p
}

func (x ConnectorReach) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectorReach) Descriptor() protoreflect.EnumDescriptor {
	return file_console_v1_connector_proto_enumTypes[0].Descriptor()
}

func (ConnectorReach) Type() protoreflect.EnumType {
	return &file_console_v1_connector_proto_enumTypes[0]
}

func (x ConnectorReach) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectorReach.Descriptor instead.
func (ConnectorReach) EnumDescriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{0}
}

type ConnectorDenial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verb          string                 `protobuf:"bytes,1,opt,name=verb,proto3" json:"verb,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorDenial) Reset() {
	*x = ConnectorDenial{}
	mi := &file_console_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorDenial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorDenial) ProtoMessage() {}

func (x *ConnectorDenial) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorDenial.ProtoReflect.Descriptor instead.
func (*ConnectorDenial) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectorDenial) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *ConnectorDenial) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *ConnectorDenial) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Connector struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Target         string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Vendor         string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Compute        ComputeKind            `protobuf:"varint,5,opt,name=compute,proto3,enum=console.v1.ComputeKind" json:"compute,omitempty"`
	Reach          ConnectorReach         `protobuf:"varint,6,opt,name=reach,proto3,enum=console.v1.ConnectorReach" json:"reach,omitempty"`
	Url            *string                `protobuf:"bytes,7,opt,name=url,proto3,oneof" json:"url,omitempty"`
	PublicKey      *string                `protobuf:"bytes,8,opt,name=public_key,json=publicKey,proto3,oneof" json:"public_key,omitempty"`
	TlsPin         *string                `protobuf:"bytes,9,opt,name=tls_pin,json=tlsPin,proto3,oneof" json:"tls_pin,omitempty"`
	Version        *string                `protobuf:"bytes,10,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Capabilities   []string               `protobuf:"bytes,11,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ConnectedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	LastSeenAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	LastDenied     *ConnectorDenial       `protobuf:"bytes,14,opt,name=last_denied,json=lastDenied,proto3" json:"last_denied,omitempty"`
	Online         bool                   `protobuf:"varint,15,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Connector) Reset() {
	*x = Connector{}
	mi := &file_console_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connector) ProtoMessage() {}

func (x *Connector) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connector.ProtoReflect.Descriptor instead.
func (*Connector) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *Connector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Connector) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Connector) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Connector) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Connector) GetCompute() ComputeKind {
	if x != nil {
		return x.Compute
	}
	return ComputeKind_COMPUTE_KIND_UNSPECIFIED
}

func (x *Connector) GetReach() ConnectorReach {
	if x != nil {
		return x.Reach
	}
	return ConnectorReach_CONNECTOR_REACH_UNSPECIFIED
}

func (x *Connector) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *Connector) GetPublicKey() string {
	if x != nil && x.PublicKey != nil {
		return *x.PublicKey
	}
	return ""
}

func (x *Connector) GetTlsPin() string {
	if x != nil && x.TlsPin != nil {
		return *x.TlsPin
	}
	return ""
}

func (x *Connector) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Connector) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Connector) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConnectedAt
	}
	return nil
}

func (x *Connector) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *Connector) GetLastDenied() *ConnectorDenial {
	if x != nil {
		return x.LastDenied
	}
	return nil
}

func (x *Connector) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type UpsertConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Reach         ConnectorReach         `protobuf:"varint,3,opt,name=reach,proto3,enum=console.v1.ConnectorReach" json:"reach,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertConnectorRequest) Reset() {
	*x = UpsertConnectorRequest{}
	mi := &file_console_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertConnectorRequest) ProtoMessage() {}

func (x *UpsertConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertConnectorRequest.ProtoReflect.Descriptor instead.
func (*UpsertConnectorRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertConnectorRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UpsertConnectorRequest) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *UpsertConnectorRequest) GetReach() ConnectorReach {
	if x != nil {
		return x.Reach
	}
	return ConnectorReach_CONNECTOR_REACH_UNSPECIFIED
}

type UpsertConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *Connector             `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertConnectorResponse) Reset() {
	*x = UpsertConnectorResponse{}
	mi := &file_console_v1_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertConnectorResponse) ProtoMessage() {}

func (x *UpsertConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertConnectorResponse.ProtoReflect.Descriptor instead.
func (*UpsertConnectorResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertConnectorResponse) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

type ListConnectorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsRequest) Reset() {
	*x = ListConnectorsRequest{}
	mi := &file_console_v1_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsRequest) ProtoMessage() {}

func (x *ListConnectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectorsRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{4}
}

type ListConnectorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connectors    []*Connector           `protobuf:"bytes,1,rep,name=connectors,proto3" json:"connectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorsResponse) Reset() {
	*x = ListConnectorsResponse{}
	mi := &file_console_v1_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorsResponse) ProtoMessage() {}

func (x *ListConnectorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectorsResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{5}
}

func (x *ListConnectorsResponse) GetConnectors() []*Connector {
	if x != nil {
		return x.Connectors
	}
	return nil
}

type RemoveConnectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectorRequest) Reset() {
	*x = RemoveConnectorRequest{}
	mi := &file_console_v1_connector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectorRequest) ProtoMessage() {}

func (x *RemoveConnectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectorRequest.ProtoReflect.Descriptor instead.
func (*RemoveConnectorRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveConnectorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveConnectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConnectorResponse) Reset() {
	*x = RemoveConnectorResponse{}
	mi := &file_console_v1_connector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConnectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConnectorResponse) ProtoMessage() {}

func (x *RemoveConnectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConnectorResponse.ProtoReflect.Descriptor instead.
func (*RemoveConnectorResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{7}
}

type SetConnectorAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	PublicKey     *string                `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3,oneof" json:"public_key,omitempty"`
	TlsPin        *string                `protobuf:"bytes,4,opt,name=tls_pin,json=tlsPin,proto3,oneof" json:"tls_pin,omitempty"`
	Compute       ComputeKind            `protobuf:"varint,5,opt,name=compute,proto3,enum=console.v1.ComputeKind" json:"compute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConnectorAddressRequest) Reset() {
	*x = SetConnectorAddressRequest{}
	mi := &file_console_v1_connector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectorAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectorAddressRequest) ProtoMessage() {}

func (x *SetConnectorAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectorAddressRequest.ProtoReflect.Descriptor instead.
func (*SetConnectorAddressRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{8}
}

func (x *SetConnectorAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetConnectorAddressRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SetConnectorAddressRequest) GetPublicKey() string {
	if x != nil && x.PublicKey != nil {
		return *x.PublicKey
	}
	return ""
}

func (x *SetConnectorAddressRequest) GetTlsPin() string {
	if x != nil && x.TlsPin != nil {
		return *x.TlsPin
	}
	return ""
}

func (x *SetConnectorAddressRequest) GetCompute() ComputeKind {
	if x != nil {
		return x.Compute
	}
	return ComputeKind_COMPUTE_KIND_UNSPECIFIED
}

type SetConnectorAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connector     *Connector             `protobuf:"bytes,1,opt,name=connector,proto3" json:"connector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConnectorAddressResponse) Reset() {
	*x = SetConnectorAddressResponse{}
	mi := &file_console_v1_connector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConnectorAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConnectorAddressResponse) ProtoMessage() {}

func (x *SetConnectorAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_connector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConnectorAddressResponse.ProtoReflect.Descriptor instead.
func (*SetConnectorAddressResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_connector_proto_rawDescGZIP(), []int{9}
}

func (x *SetConnectorAddressResponse) GetConnector() *Connector {
	if x != nil {
		return x.Connector
	}
	return nil
}

var File_console_v1_connector_proto protoreflect.FileDescriptor

const file_console_v1_connector_proto_rawDesc = "" +
	"\n" +
	"\x1aconsole/v1/connector.proto\x12\n" +
	"console.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bconsole/v1/deployment.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\x0fConnectorDenial\x12\x12\n" +
	"\x04verb\x18\x01 \x01(\tR\x04verb\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xf7\x04\n" +
	"\tConnector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x121\n" +
	"\acompute\x18\x05 \x01(\x0e2\x17.console.v1.ComputeKindR\acompute\x120\n" +
	"\x05reach\x18\x06 \x01(\x0e2\x1a.console.v1.ConnectorReachR\x05reach\x12\x15\n" +
	"\x03url\x18\a \x01(\tH\x00R\x03url\x88\x01\x01\x12\"\n" +
	"\n" +
	"public_key\x18\b \x01(\tH\x01R\tpublicKey\x88\x01\x01\x12\x1c\n" +
	"\atls_pin\x18\t \x01(\tH\x02R\x06tlsPin\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\n" +
	" \x01(\tH\x03R\aversion\x88\x01\x01\x12\"\n" +
	"\fcapabilities\x18\v \x03(\tR\fcapabilities\x12=\n" +
	"\fconnected_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12<\n" +
	"\flast_seen_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12<\n" +
	"\vlast_denied\x18\x0e \x01(\v2\x1b.console.v1.ConnectorDenialR\n" +
	"lastDenied\x12\x16\n" +
	"\x06online\x18\x0f \x01(\bR\x06onlineB\x06\n" +
	"\x04_urlB\r\n" +
	"\v_public_keyB\n" +
	"\n" +
	"\b_tls_pinB\n" +
	"\n" +
	"\b_version\"\xd0\x01\n" +
	"\x16UpsertConnectorRequest\x12D\n" +
	"\x06target\x18\x01 \x01(\tB,\xbaH)r'\x18\x80\x022\"^[a-z0-9._:-]+(?:/[a-z0-9._:-]+)+$R\x06target\x122\n" +
	"\x06vendor\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\x10\x01\x18@2\x0f^[a-z0-9._:-]+$R\x06vendor\x12<\n" +
	"\x05reach\x18\x03 \x01(\x0e2\x1a.console.v1.ConnectorReachB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05reach\"N\n" +
	"\x17UpsertConnectorResponse\x123\n" +
	"\tconnector\x18\x01 \x01(\v2\x15.console.v1.ConnectorR\tconnector\"\x17\n" +
	"\x15ListConnectorsRequest\"O\n" +
	"\x16ListConnectorsResponse\x125\n" +
	"\n" +
	"connectors\x18\x01 \x03(\v2\x15.console.v1.ConnectorR\n" +
	"connectors\"2\n" +
	"\x16RemoveConnectorRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\x19\n" +
	"\x17RemoveConnectorResponse\"\x87\x02\n" +
	"\x1aSetConnectorAddressRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1d\n" +
	"\x03url\x18\x02 \x01(\tB\v\xbaH\br\x06\x18\x80\x10\x88\x01\x01R\x03url\x12.\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02H\x00R\tpublicKey\x88\x01\x01\x12(\n" +
	"\atls_pin\x18\x04 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02H\x01R\x06tlsPin\x88\x01\x01\x12;\n" +
	"\acompute\x18\x05 \x01(\x0e2\x17.console.v1.ComputeKindB\b\xbaH\x05\x82\x01\x02\x10\x01R\acomputeB\r\n" +
	"\v_public_keyB\n" +
	"\n" +
	"\b_tls_pin\"R\n" +
	"\x1bSetConnectorAddressResponse\x123\n" +
	"\tconnector\x18\x01 \x01(\v2\x15.console.v1.ConnectorR\tconnector*K\n" +
	"\x0eConnectorReach\x12\x1f\n" +
	"\x1bCONNECTOR_REACH_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CONNECTOR_REACH_DIAL\x10\x012\xe6\x02\n" +
	"\x10ConnectorService\x12Q\n" +
	"\x06Upsert\x12\".console.v1.UpsertConnectorRequest\x1a#.console.v1.UpsertConnectorResponse\x12M\n" +
	"\x04List\x12!.console.v1.ListConnectorsRequest\x1a\".console.v1.ListConnectorsResponse\x12Q\n" +
	"\x06Remove\x12\".console.v1.RemoveConnectorRequest\x1a#.console.v1.RemoveConnectorResponse\x12]\n" +
	"\n" +
	"SetAddress\x12&.console.v1.SetConnectorAddressRequest\x1a'.console.v1.SetConnectorAddressResponseB7Z5github.com/ocelhq/ocel/pkg/proto/console/v1;consolev1b\x06proto3"

var (
	file_console_v1_connector_proto_rawDescOnce sync.Once
	file_console_v1_connector_proto_rawDescData []byte
)

func file_console_v1_connector_proto_rawDescGZIP() []byte {
	file_console_v1_connector_proto_rawDescOnce.Do(func() {
		file_console_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_v1_connector_proto_rawDesc), len(file_console_v1_connector_proto_rawDesc)))
	})
	return file_console_v1_connector_proto_rawDescData
}

var file_console_v1_connector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_console_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_console_v1_connector_proto_goTypes = []any{
	(ConnectorReach)(0),                 // 0: console.v1.ConnectorReach
	(*ConnectorDenial)(nil),             // 1: console.v1.ConnectorDenial
	(*Connector)(nil),                   // 2: console.v1.Connector
	(*UpsertConnectorRequest)(nil),      // 3: console.v1.UpsertConnectorRequest
	(*UpsertConnectorResponse)(nil),     // 4: console.v1.UpsertConnectorResponse
	(*ListConnectorsRequest)(nil),       // 5: console.v1.ListConnectorsRequest
	(*ListConnectorsResponse)(nil),      // 6: console.v1.ListConnectorsResponse
	(*RemoveConnectorRequest)(nil),      // 7: console.v1.RemoveConnectorRequest
	(*RemoveConnectorResponse)(nil),     // 8: console.v1.RemoveConnectorResponse
	(*SetConnectorAddressRequest)(nil),  // 9: console.v1.SetConnectorAddressRequest
	(*SetConnectorAddressResponse)(nil), // 10: console.v1.SetConnectorAddressResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
	(ComputeKind)(0),                    // 12: console.v1.ComputeKind
}
var file_console_v1_connector_proto_depIdxs = []int32{
	11, // 0: console.v1.ConnectorDenial.at:type_name -> google.protobuf.Timestamp
	12, // 1: console.v1.Connector.compute:type_name -> console.v1.ComputeKind
	0,  // 2: console.v1.Connector.reach:type_name -> console.v1.ConnectorReach
	11, // 3: console.v1.Connector.connected_at:type_name -> google.protobuf.Timestamp
	11, // 4: console.v1.Connector.last_seen_at:type_name -> google.protobuf.Timestamp
	1,  // 5: console.v1.Connector.last_denied:type_name -> console.v1.ConnectorDenial
	0,  // 6: console.v1.UpsertConnectorRequest.reach:type_name -> console.v1.ConnectorReach
	2,  // 7: console.v1.UpsertConnectorResponse.connector:type_name -> console.v1.Connector
	2,  // 8: console.v1.ListConnectorsResponse.connectors:type_name -> console.v1.Connector
	12, // 9: console.v1.SetConnectorAddressRequest.compute:type_name -> console.v1.ComputeKind
	2,  // 10: console.v1.SetConnectorAddressResponse.connector:type_name -> console.v1.Connector
	3,  // 11: console.v1.ConnectorService.Upsert:input_type -> console.v1.UpsertConnectorRequest
	5,  // 12: console.v1.ConnectorService.List:input_type -> console.v1.ListConnectorsRequest
	7,  // 13: console.v1.ConnectorService.Remove:input_type -> console.v1.RemoveConnectorRequest
	9,  // 14: console.v1.ConnectorService.SetAddress:input_type -> console.v1.SetConnectorAddressRequest
	4,  // 15: console.v1.ConnectorService.Upsert:output_type -> console.v1.UpsertConnectorResponse
	6,  // 16: console.v1.ConnectorService.List:output_type -> console.v1.ListConnectorsResponse
	8,  // 17: console.v1.ConnectorService.Remove:output_type -> console.v1.RemoveConnectorResponse
	10, // 18: console.v1.ConnectorService.SetAddress:output_type -> console.v1.SetConnectorAddressResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_console_v1_connector_proto_init() }
func file_console_v1_connector_proto_init() {
	if File_console_v1_connector_proto != nil {
		return
	}
	file_console_v1_deployment_proto_init()
	file_console_v1_connector_proto_msgTypes[1].OneofWrappers = []any{}
	file_console_v1_connector_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_v1_connector_proto_rawDesc), len(file_console_v1_connector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_v1_connector_proto_goTypes,
		DependencyIndexes: file_console_v1_connector_proto_depIdxs,
		EnumInfos:         file_console_v1_connector_proto_enumTypes,
		MessageInfos:      file_console_v1_connector_proto_msgTypes,
	}.Build()
	File_console_v1_connector_proto = out.File
	file_console_v1_connector_proto_goTypes = nil
	file_console_v1_connector_proto_depIdxs = nil
}
