// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/task/v1/task.proto

package taskv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/ocelhq/ocel/pkg/proto/app/topic/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNSPECIFIED RunStatus = 0
	RunStatus_RUN_STATUS_DELAYED     RunStatus = 1
	RunStatus_RUN_STATUS_QUEUED      RunStatus = 2
	RunStatus_RUN_STATUS_EXECUTING   RunStatus = 3
	RunStatus_RUN_STATUS_COMPLETED   RunStatus = 4
	RunStatus_RUN_STATUS_FAILED      RunStatus = 5
	RunStatus_RUN_STATUS_CANCELED    RunStatus = 6
	RunStatus_RUN_STATUS_EXPIRED     RunStatus = 7
	RunStatus_RUN_STATUS_TIMED_OUT   RunStatus = 8
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNSPECIFIED",
		1: "RUN_STATUS_DELAYED",
		2: "RUN_STATUS_QUEUED",
		3: "RUN_STATUS_EXECUTING",
		4: "RUN_STATUS_COMPLETED",
		5: "RUN_STATUS_FAILED",
		6: "RUN_STATUS_CANCELED",
		7: "RUN_STATUS_EXPIRED",
		8: "RUN_STATUS_TIMED_OUT",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNSPECIFIED": 0,
		"RUN_STATUS_DELAYED":     1,
		"RUN_STATUS_QUEUED":      2,
		"RUN_STATUS_EXECUTING":   3,
		"RUN_STATUS_COMPLETED":   4,
		"RUN_STATUS_FAILED":      5,
		"RUN_STATUS_CANCELED":    6,
		"RUN_STATUS_EXPIRED":     7,
		"RUN_STATUS_TIMED_OUT":   8,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_app_task_v1_task_proto_enumTypes[0].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_app_task_v1_task_proto_enumTypes[0]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{0}
}

type Debounce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Delay         *durationpb.Duration   `protobuf:"bytes,2,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Debounce) Reset() {
	*x = Debounce{}
	mi := &file_app_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Debounce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debounce) ProtoMessage() {}

func (x *Debounce) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debounce.ProtoReflect.Descriptor instead.
func (*Debounce) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Debounce) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Debounce) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

type TriggerOptions struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DueAt             *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	Ttl               *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	IdempotencyKeyTtl *durationpb.Duration   `protobuf:"bytes,4,opt,name=idempotency_key_ttl,json=idempotencyKeyTtl,proto3" json:"idempotency_key_ttl,omitempty"`
	Debounce          *Debounce              `protobuf:"bytes,5,opt,name=debounce,proto3" json:"debounce,omitempty"`
	Key               string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Lane              v1.Lane                `protobuf:"varint,7,opt,name=lane,proto3,enum=app.topic.v1.Lane" json:"lane,omitempty"`
	MaxAttempts       int32                  `protobuf:"varint,8,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	Tags              []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata          *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TriggerOptions) Reset() {
	*x = TriggerOptions{}
	mi := &file_app_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerOptions) ProtoMessage() {}

func (x *TriggerOptions) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerOptions.ProtoReflect.Descriptor instead.
func (*TriggerOptions) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerOptions) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

func (x *TriggerOptions) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *TriggerOptions) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TriggerOptions) GetIdempotencyKeyTtl() *durationpb.Duration {
	if x != nil {
		return x.IdempotencyKeyTtl
	}
	return nil
}

func (x *TriggerOptions) GetDebounce() *Debounce {
	if x != nil {
		return x.Debounce
	}
	return nil
}

func (x *TriggerOptions) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TriggerOptions) GetLane() v1.Lane {
	if x != nil {
		return x.Lane
	}
	return v1.Lane(0)
}

func (x *TriggerOptions) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *TriggerOptions) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TriggerOptions) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       *TriggerOptions        `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_app_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *TriggerRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TriggerRequest) GetOptions() *TriggerOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_app_task_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BatchTriggerItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       *TriggerOptions        `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTriggerItem) Reset() {
	*x = BatchTriggerItem{}
	mi := &file_app_task_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTriggerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTriggerItem) ProtoMessage() {}

func (x *BatchTriggerItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTriggerItem.ProtoReflect.Descriptor instead.
func (*BatchTriggerItem) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *BatchTriggerItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BatchTriggerItem) GetOptions() *TriggerOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type BatchTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Items         []*BatchTriggerItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTriggerRequest) Reset() {
	*x = BatchTriggerRequest{}
	mi := &file_app_task_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTriggerRequest) ProtoMessage() {}

func (x *BatchTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTriggerRequest.ProtoReflect.Descriptor instead.
func (*BatchTriggerRequest) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *BatchTriggerRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *BatchTriggerRequest) GetItems() []*BatchTriggerItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchTriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTriggerResponse) Reset() {
	*x = BatchTriggerResponse{}
	mi := &file_app_task_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTriggerResponse) ProtoMessage() {}

func (x *BatchTriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTriggerResponse.ProtoReflect.Descriptor instead.
func (*BatchTriggerResponse) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *BatchTriggerResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Run struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Status        RunStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=app.task.v1.RunStatus" json:"status,omitempty"`
	Payload       *structpb.Value        `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Output        *structpb.Value        `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Attempts      int32                  `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_app_task_v1_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{7}
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Run) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *Run) GetPayload() *structpb.Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Run) GetOutput() *structpb.Value {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Run) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Run) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Run) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Run) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Run) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Run) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

func (x *Run) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Run) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Run) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RetrieveRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRunRequest) Reset() {
	*x = RetrieveRunRequest{}
	mi := &file_app_task_v1_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRunRequest) ProtoMessage() {}

func (x *RetrieveRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRunRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRunRequest) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{8}
}

func (x *RetrieveRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetrieveRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRunResponse) Reset() {
	*x = RetrieveRunResponse{}
	mi := &file_app_task_v1_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRunResponse) ProtoMessage() {}

func (x *RetrieveRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRunResponse.ProtoReflect.Descriptor instead.
func (*RetrieveRunResponse) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{9}
}

func (x *RetrieveRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Statuses      []RunStatus            `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=app.task.v1.RunStatus" json:"statuses,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_app_task_v1_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{10}
}

func (x *ListRunsRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *ListRunsRequest) GetStatuses() []RunStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListRunsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListRunsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_app_task_v1_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{11}
}

func (x *ListRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListRunsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_app_task_v1_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{12}
}

func (x *CancelRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_app_task_v1_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{13}
}

func (x *CancelRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

type ReplayRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRunRequest) Reset() {
	*x = ReplayRunRequest{}
	mi := &file_app_task_v1_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRunRequest) ProtoMessage() {}

func (x *ReplayRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRunRequest.ProtoReflect.Descriptor instead.
func (*ReplayRunRequest) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{14}
}

func (x *ReplayRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReplayRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRunResponse) Reset() {
	*x = ReplayRunResponse{}
	mi := &file_app_task_v1_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRunResponse) ProtoMessage() {}

func (x *ReplayRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRunResponse.ProtoReflect.Descriptor instead.
func (*ReplayRunResponse) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{15}
}

func (x *ReplayRunResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RescheduleRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescheduleRunRequest) Reset() {
	*x = RescheduleRunRequest{}
	mi := &file_app_task_v1_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleRunRequest) ProtoMessage() {}

func (x *RescheduleRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleRunRequest.ProtoReflect.Descriptor instead.
func (*RescheduleRunRequest) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{16}
}

func (x *RescheduleRunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RescheduleRunRequest) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

type RescheduleRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *Run                   `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescheduleRunResponse) Reset() {
	*x = RescheduleRunResponse{}
	mi := &file_app_task_v1_task_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescheduleRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescheduleRunResponse) ProtoMessage() {}

func (x *RescheduleRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_v1_task_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescheduleRunResponse.ProtoReflect.Descriptor instead.
func (*RescheduleRunResponse) Descriptor() ([]byte, []int) {
	return file_app_task_v1_task_proto_rawDescGZIP(), []int{17}
}

func (x *RescheduleRunResponse) GetRun() *Run {
	if x != nil {
		return x.Run
	}
	return nil
}

var File_app_task_v1_task_proto protoreflect.FileDescriptor

const file_app_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x16app/task/v1/task.proto\x12\vapp.task.v1\x1a\x18app/topic/v1/topic.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\bDebounce\x12\x19\n" +
	"\x03key\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12@\n" +
	"\x05delay\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\x0f\xbaH\f\xaa\x01\t\"\x05\b\x80\x9a\x9e\x01*\x00R\x05delay\"\xed\x04\n" +
	"\x0eTriggerOptions\x12\xa3\x01\n" +
	"\x06due_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampBp\xbaHm\xba\x01j\n" +
	"\x14tasks.trigger.due_at\x122a run is due at most 30 days after it is triggered\x1a\x1ethis <= now + duration('720h')R\x05dueAt\x12;\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\x0e\xbaH\v\xaa\x01\b\"\x04\b\x80\xeaI*\x00R\x03ttl\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12S\n" +
	"\x13idempotency_key_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\b\xbaH\x05\xaa\x01\x02*\x00R\x11idempotencyKeyTtl\x121\n" +
	"\bdebounce\x18\x05 \x01(\v2\x15.app.task.v1.DebounceR\bdebounce\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x120\n" +
	"\x04lane\x18\a \x01(\x0e2\x12.app.topic.v1.LaneB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04lane\x12,\n" +
	"\fmax_attempts\x18\b \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\vmaxAttempts\x12 \n" +
	"\x04tags\x18\t \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\x04tags\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xa3\x01\n" +
	"\x0eTriggerRequest\x125\n" +
	"\x04task\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04task\x12#\n" +
	"\apayload\x18\x02 \x01(\fB\t\xbaH\x06z\x04\x18\x80\x80\x10R\apayload\x125\n" +
	"\aoptions\x18\x03 \x01(\v2\x1b.app.task.v1.TriggerOptionsR\aoptions\"!\n" +
	"\x0fTriggerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x10BatchTriggerItem\x12#\n" +
	"\apayload\x18\x01 \x01(\fB\t\xbaH\x06z\x04\x18\x80\x80\x10R\apayload\x125\n" +
	"\aoptions\x18\x02 \x01(\v2\x1b.app.task.v1.TriggerOptionsR\aoptions\"\x8e\x01\n" +
	"\x13BatchTriggerRequest\x125\n" +
	"\x04task\x18\x01 \x01(\tB!\xbaH\x1er\x1c\x18?2\x18^[a-z0-9]+(-[a-z0-9]+)*$R\x04task\x12@\n" +
	"\x05items\x18\x02 \x03(\v2\x1d.app.task.v1.BatchTriggerItemB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\x05items\"(\n" +
	"\x14BatchTriggerResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\xd7\x04\n" +
	"\x03Run\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.app.task.v1.RunStatusR\x06status\x120\n" +
	"\apayload\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\apayload\x12.\n" +
	"\x06output\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\x06output\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1a\n" +
	"\battempts\x18\a \x01(\x05R\battempts\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x121\n" +
	"\x06due_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\x129\n" +
	"\n" +
	"started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x129\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"-\n" +
	"\x12RetrieveRunRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"9\n" +
	"\x13RetrieveRunResponse\x12\"\n" +
	"\x03run\x18\x01 \x01(\v2\x10.app.task.v1.RunR\x03run\"\xb8\x01\n" +
	"\x0fListRunsRequest\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12C\n" +
	"\bstatuses\x18\x02 \x03(\x0e2\x16.app.task.v1.RunStatusB\x0f\xbaH\f\x92\x01\t\"\a\x82\x01\x04\x10\x01 \x00R\bstatuses\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12 \n" +
	"\x05limit\x18\x05 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\x05limit\"Y\n" +
	"\x10ListRunsResponse\x12$\n" +
	"\x04runs\x18\x01 \x03(\v2\x10.app.task.v1.RunR\x04runs\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"+\n" +
	"\x10CancelRunRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"7\n" +
	"\x11CancelRunResponse\x12\"\n" +
	"\x03run\x18\x01 \x01(\v2\x10.app.task.v1.RunR\x03run\"+\n" +
	"\x10ReplayRunRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"#\n" +
	"\x11ReplayRunResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xce\x01\n" +
	"\x14RescheduleRunRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12\x9c\x01\n" +
	"\x06due_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampBi\xbaHf\xba\x01`\n" +
	"\x17tasks.reschedule.due_at\x12%a run is due at most 30 days from now\x1a\x1ethis <= now + duration('720h')\xc8\x01\x01R\x05dueAt\";\n" +
	"\x15RescheduleRunResponse\x12\"\n" +
	"\x03run\x18\x01 \x01(\v2\x10.app.task.v1.RunR\x03run*\xec\x01\n" +
	"\tRunStatus\x12\x1a\n" +
	"\x16RUN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RUN_STATUS_DELAYED\x10\x01\x12\x15\n" +
	"\x11RUN_STATUS_QUEUED\x10\x02\x12\x18\n" +
	"\x14RUN_STATUS_EXECUTING\x10\x03\x12\x18\n" +
	"\x14RUN_STATUS_COMPLETED\x10\x04\x12\x15\n" +
	"\x11RUN_STATUS_FAILED\x10\x05\x12\x17\n" +
	"\x13RUN_STATUS_CANCELED\x10\x06\x12\x16\n" +
	"\x12RUN_STATUS_EXPIRED\x10\a\x12\x18\n" +
	"\x14RUN_STATUS_TIMED_OUT\x10\b2\xb3\x04\n" +
	"\vTaskService\x12D\n" +
	"\aTrigger\x12\x1b.app.task.v1.TriggerRequest\x1a\x1c.app.task.v1.TriggerResponse\x12S\n" +
	"\fBatchTrigger\x12 .app.task.v1.BatchTriggerRequest\x1a!.app.task.v1.BatchTriggerResponse\x12P\n" +
	"\vRetrieveRun\x12\x1f.app.task.v1.RetrieveRunRequest\x1a .app.task.v1.RetrieveRunResponse\x12G\n" +
	"\bListRuns\x12\x1c.app.task.v1.ListRunsRequest\x1a\x1d.app.task.v1.ListRunsResponse\x12J\n" +
	"\tCancelRun\x12\x1d.app.task.v1.CancelRunRequest\x1a\x1e.app.task.v1.CancelRunResponse\x12J\n" +
	"\tReplayRun\x12\x1d.app.task.v1.ReplayRunRequest\x1a\x1e.app.task.v1.ReplayRunResponse\x12V\n" +
	"\rRescheduleRun\x12!.app.task.v1.RescheduleRunRequest\x1a\".app.task.v1.RescheduleRunResponseB5Z3github.com/ocelhq/ocel/pkg/proto/app/task/v1;taskv1b\x06proto3"

var (
	file_app_task_v1_task_proto_rawDescOnce sync.Once
	file_app_task_v1_task_proto_rawDescData []byte
)

func file_app_task_v1_task_proto_rawDescGZIP() []byte {
	file_app_task_v1_task_proto_rawDescOnce.Do(func() {
		file_app_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_task_v1_task_proto_rawDesc), len(file_app_task_v1_task_proto_rawDesc)))
	})
	return file_app_task_v1_task_proto_rawDescData
}

var file_app_task_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_app_task_v1_task_proto_goTypes = []any{
	(RunStatus)(0),                // 0: app.task.v1.RunStatus
	(*Debounce)(nil),              // 1: app.task.v1.Debounce
	(*TriggerOptions)(nil),        // 2: app.task.v1.TriggerOptions
	(*TriggerRequest)(nil),        // 3: app.task.v1.TriggerRequest
	(*TriggerResponse)(nil),       // 4: app.task.v1.TriggerResponse
	(*BatchTriggerItem)(nil),      // 5: app.task.v1.BatchTriggerItem
	(*BatchTriggerRequest)(nil),   // 6: app.task.v1.BatchTriggerRequest
	(*BatchTriggerResponse)(nil),  // 7: app.task.v1.BatchTriggerResponse
	(*Run)(nil),                   // 8: app.task.v1.Run
	(*RetrieveRunRequest)(nil),    // 9: app.task.v1.RetrieveRunRequest
	(*RetrieveRunResponse)(nil),   // 10: app.task.v1.RetrieveRunResponse
	(*ListRunsRequest)(nil),       // 11: app.task.v1.ListRunsRequest
	(*ListRunsResponse)(nil),      // 12: app.task.v1.ListRunsResponse
	(*CancelRunRequest)(nil),      // 13: app.task.v1.CancelRunRequest
	(*CancelRunResponse)(nil),     // 14: app.task.v1.CancelRunResponse
	(*ReplayRunRequest)(nil),      // 15: app.task.v1.ReplayRunRequest
	(*ReplayRunResponse)(nil),     // 16: app.task.v1.ReplayRunResponse
	(*RescheduleRunRequest)(nil),  // 17: app.task.v1.RescheduleRunRequest
	(*RescheduleRunResponse)(nil), // 18: app.task.v1.RescheduleRunResponse
	(*durationpb.Duration)(nil),   // 19: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
	(v1.Lane)(0),                  // 21: app.topic.v1.Lane
	(*structpb.Struct)(nil),       // 22: google.protobuf.Struct
	(*structpb.Value)(nil),        // 23: google.protobuf.Value
}
var file_app_task_v1_task_proto_depIdxs = []int32{
	19, // 0: app.task.v1.Debounce.delay:type_name -> google.protobuf.Duration
	20, // 1: app.task.v1.TriggerOptions.due_at:type_name -> google.protobuf.Timestamp
	19, // 2: app.task.v1.TriggerOptions.ttl:type_name -> google.protobuf.Duration
	19, // 3: app.task.v1.TriggerOptions.idempotency_key_ttl:type_name -> google.protobuf.Duration
	1,  // 4: app.task.v1.TriggerOptions.debounce:type_name -> app.task.v1.Debounce
	21, // 5: app.task.v1.TriggerOptions.lane:type_name -> app.topic.v1.Lane
	22, // 6: app.task.v1.TriggerOptions.metadata:type_name -> google.protobuf.Struct
	2,  // 7: app.task.v1.TriggerRequest.options:type_name -> app.task.v1.TriggerOptions
	2,  // 8: app.task.v1.BatchTriggerItem.options:type_name -> app.task.v1.TriggerOptions
	5,  // 9: app.task.v1.BatchTriggerRequest.items:type_name -> app.task.v1.BatchTriggerItem
	0,  // 10: app.task.v1.Run.status:type_name -> app.task.v1.RunStatus
	23, // 11: app.task.v1.Run.payload:type_name -> google.protobuf.Value
	23, // 12: app.task.v1.Run.output:type_name -> google.protobuf.Value
	22, // 13: app.task.v1.Run.metadata:type_name -> google.protobuf.Struct
	20, // 14: app.task.v1.Run.created_at:type_name -> google.protobuf.Timestamp
	20, // 15: app.task.v1.Run.due_at:type_name -> google.protobuf.Timestamp
	20, // 16: app.task.v1.Run.started_at:type_name -> google.protobuf.Timestamp
	20, // 17: app.task.v1.Run.finished_at:type_name -> google.protobuf.Timestamp
	20, // 18: app.task.v1.Run.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 19: app.task.v1.RetrieveRunResponse.run:type_name -> app.task.v1.Run
	0,  // 20: app.task.v1.ListRunsRequest.statuses:type_name -> app.task.v1.RunStatus
	8,  // 21: app.task.v1.ListRunsResponse.runs:type_name -> app.task.v1.Run
	8,  // 22: app.task.v1.CancelRunResponse.run:type_name -> app.task.v1.Run
	20, // 23: app.task.v1.RescheduleRunRequest.due_at:type_name -> google.protobuf.Timestamp
	8,  // 24: app.task.v1.RescheduleRunResponse.run:type_name -> app.task.v1.Run
	3,  // 25: app.task.v1.TaskService.Trigger:input_type -> app.task.v1.TriggerRequest
	6,  // 26: app.task.v1.TaskService.BatchTrigger:input_type -> app.task.v1.BatchTriggerRequest
	9,  // 27: app.task.v1.TaskService.RetrieveRun:input_type -> app.task.v1.RetrieveRunRequest
	11, // 28: app.task.v1.TaskService.ListRuns:input_type -> app.task.v1.ListRunsRequest
	13, // 29: app.task.v1.TaskService.CancelRun:input_type -> app.task.v1.CancelRunRequest
	15, // 30: app.task.v1.TaskService.ReplayRun:input_type -> app.task.v1.ReplayRunRequest
	17, // 31: app.task.v1.TaskService.RescheduleRun:input_type -> app.task.v1.RescheduleRunRequest
	4,  // 32: app.task.v1.TaskService.Trigger:output_type -> app.task.v1.TriggerResponse
	7,  // 33: app.task.v1.TaskService.BatchTrigger:output_type -> app.task.v1.BatchTriggerResponse
	10, // 34: app.task.v1.TaskService.RetrieveRun:output_type -> app.task.v1.RetrieveRunResponse
	12, // 35: app.task.v1.TaskService.ListRuns:output_type -> app.task.v1.ListRunsResponse
	14, // 36: app.task.v1.TaskService.CancelRun:output_type -> app.task.v1.CancelRunResponse
	16, // 37: app.task.v1.TaskService.ReplayRun:output_type -> app.task.v1.ReplayRunResponse
	18, // 38: app.task.v1.TaskService.RescheduleRun:output_type -> app.task.v1.RescheduleRunResponse
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_app_task_v1_task_proto_init() }
func file_app_task_v1_task_proto_init() {
	if File_app_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_task_v1_task_proto_rawDesc), len(file_app_task_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_task_v1_task_proto_goTypes,
		DependencyIndexes: file_app_task_v1_task_proto_depIdxs,
		EnumInfos:         file_app_task_v1_task_proto_enumTypes,
		MessageInfos:      file_app_task_v1_task_proto_msgTypes,
	}.Build()
	File_app_task_v1_task_proto = out.File
	file_app_task_v1_task_proto_goTypes = nil
	file_app_task_v1_task_proto_depIdxs = nil
}
