package telemetry

var allowedEvents = []string{"command_completed", "dev_session_ended", "init_completed", "deploy_completed"}

var allowedProperties = []string{
	"command",
	"flags",
	"exit_code",
	"error_code",
	"duration_ms",
	"json",
	"tty",
	"skill_installed",
	"reloads",
	"resource_kinds",
	"error_codes",
	"language",
	"package_manager",
	"provider",
	"config_format",
	"success",
	"target",
	"frameworks",
	"languages",
	"app_count",
	"resource_counts",
	"plan_actions",
	"phase_ms",
	"first_deploy",
	"assumed",
	"cli_version",
	"os",
	"arch",
	"agent",
	"ci",
	"$process_person_profile",
}
