import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const SCHEMA_URL = "https://ocel.dev/schema/ocel.schema.json";
const SCHEMA_OUT = join(root, "www", "public", "schema", "ocel.schema.json");
const TYPES_OUT = join(root, "packages", "ocel", "src", "generated", "config.ts");

const read = (path) => JSON.parse(readFileSync(path, "utf8"));

function providerVariants() {
  const platform = join(root, "platform");
  const vendors = readdirSync(platform, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => join(platform, entry.name, "provider", "schema.options.json"))
    .filter((path) => {
      try {
        readFileSync(path);
        return true;
      } catch {
        return false;
      }
    });
  return vendors
    .map(read)
    .map(qualified)
    .sort((a, b) => a.properties.name.const.localeCompare(b.properties.name.const));
}

function qualified(variant) {
  const name = variant.properties.name.const;
  const prefix = name[0].toUpperCase() + name.slice(1);
  const rename = (node) => {
    if (!node || typeof node !== "object") return;
    if (Array.isArray(node)) {
      for (const item of node) rename(item);
      return;
    }
    if (typeof node.title === "string" && !node.title.startsWith(prefix)) {
      node.title = prefix + node.title;
    }
    for (const value of Object.values(node)) rename(value);
  };
  rename(variant.properties.options);
  return variant;
}

function schema() {
  const core = read(join(root, "pkg", "configdoc", "schema.core.json"));
  const variants = providerVariants();
  const merged = { $id: SCHEMA_URL, ...core };
  merged.properties = {
    ...core.properties,
    provider: { description: core.properties.provider.description, oneOf: variants },
  };
  return merged;
}

const RESERVED = new Set(["OcelConfig"]);

class Emitter {
  constructor() {
    this.interfaces = new Map();
  }

  type(node, indent = "") {
    if (node.$ref) return node.$ref;
    if (node.const !== undefined) return JSON.stringify(node.const);
    if (node.enum) return node.enum.map((value) => JSON.stringify(value)).join(" | ");
    if (node.oneOf) return node.oneOf.map((one) => this.type(one, indent)).join(" | ");
    switch (node.type) {
      case "string":
        return "string";
      case "boolean":
        return "boolean";
      case "integer":
      case "number":
        return "number";
      case "array":
        return `${this.wrapped(node.items, indent)}[]`;
      case "object":
        return this.object(node, indent);
      default:
        return "unknown";
    }
  }

  wrapped(node, indent) {
    const rendered = this.type(node, indent);
    return rendered.includes(" | ") ? `(${rendered})` : rendered;
  }

  object(node, indent) {
    if (!node.properties) {
      const values = node.additionalProperties;
      return values && values !== true
        ? `Record<string, ${this.type(values, indent)}>`
        : "Record<string, unknown>";
    }
    if (node.title && !RESERVED.has(node.title)) {
      this.declare(node.title, node);
      return node.title;
    }
    return this.body(node, indent);
  }

  body(node, indent) {
    const inner = `${indent}  `;
    const lines = [];
    for (const [key, property] of Object.entries(node.properties)) {
      if (property.description) {
        lines.push(`${inner}/** ${property.description} */`);
      }
      const optional = (node.required ?? []).includes(key) ? "" : "?";
      lines.push(`${inner}${quoted(key)}${optional}: ${this.type(property, inner)};`);
    }
    return `{\n${lines.join("\n")}\n${indent}}`;
  }

  declare(name, node) {
    if (this.interfaces.has(name)) return;
    this.interfaces.set(name, "");
    const doc = node.description ? `/** ${node.description} */\n` : "";
    this.interfaces.set(name, `${doc}export interface ${name} ${this.body(node, "")}\n`);
  }

  render() {
    return [...this.interfaces.values()].join("\n");
  }
}

function quoted(key) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function types(merged) {
  const emitter = new Emitter();
  const provider = merged.properties.provider;
  const descriptor = provider.oneOf.map((variant) => emitter.type(variant, "")).join("\n  | ");
  const config = emitter.body(
    {
      ...merged,
      properties: {
        ...merged.properties,
        provider: { description: provider.description, $ref: "ProviderDescriptor" },
      },
    },
    "",
  );

  const header = [
    "// generated by scripts/schema/build.mjs from the committed JSON Schema; do not edit",
    "",
    `/** ${provider.description} */`,
    `export type ProviderDescriptor =\n  | ${descriptor};`,
    "",
    `/** The project configuration \`ocel deploy\` reads, whether written as ${"`ocel.json`"} or as ${"`ocel.config.ts`"}. */`,
    `export interface OcelConfig ${config}`,
    "",
  ].join("\n");

  return `${header}\n${emitter.render()}`;
}

const merged = schema();
mkdirSync(dirname(SCHEMA_OUT), { recursive: true });
writeFileSync(SCHEMA_OUT, `${JSON.stringify(merged, null, 2)}\n`);
mkdirSync(dirname(TYPES_OUT), { recursive: true });
writeFileSync(TYPES_OUT, types(merged));
execFileSync("pnpm", ["exec", "biome", "format", "--write", SCHEMA_OUT, TYPES_OUT], {
  cwd: root,
  stdio: "inherit",
});
