import { createHash } from "node:crypto";
import { basename, join } from "node:path";

export const DNS_LABEL = /^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/;

export const STATE_FILE = ".ocel-e2e-node.json";

export const BUILD_LOG_FILE = ".deploy-build.log";

export const DEPLOY_RESULT_FILE = join(".ocel", "deploy-result.json");

const LOCAL_RUN_ID = "local";

export const PREVIEW_ROOT_STACK_PARAM_PREFIX = "/ocel/rootstack-preview/";

export const SLUG_PREFIX = "e2en-";

export const PREVIEW_LABEL_MAX_LEN = 63;

export const PREVIEW_APP_SEPARATOR = "--";

export const REF_HINT_LEN = 10;

export const REF_HASH_LEN = 8;

export const SMOKE_APPS = Object.freeze([
  Object.freeze({ name: "exp", framework: "express", path: "express" }),
  Object.freeze({ name: "hono", framework: "hono", path: "hono" }),
]);

const POINTER_LEN = REF_HINT_LEN + 1 + REF_HASH_LEN;

const LONGEST_APP_NAME = Math.max(...SMOKE_APPS.map((app) => app.name.length));

export const MAX_SLUG_LEN = Math.min(
  63 - "ocel-".length - "-preview".length,
  PREVIEW_LABEL_MAX_LEN -
    PREVIEW_APP_SEPARATOR.length -
    POINTER_LEN -
    PREVIEW_APP_SEPARATOR.length -
    LONGEST_APP_NAME,
);

export const SKIP_DRIFT_CHECK_ENV = Object.freeze({
  OCEL_SKIP_EDGE_RECONCILE: "1",
  OCEL_SKIP_TEARDOWN_REFRESH: "1",
});

export function withoutSkipDriftChecks(env) {
  const out = { ...env };
  for (const name of Object.keys(SKIP_DRIFT_CHECK_ENV)) {
    delete out[name];
  }
  return out;
}

function sanitizeToken(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function projectSlug({ runId }) {
  const run = sanitizeToken(String(runId ?? "")) || LOCAL_RUN_ID;
  const maxRun = MAX_SLUG_LEN - SLUG_PREFIX.length;
  return SLUG_PREFIX + run.slice(0, maxRun).replace(/-+$/, "");
}

export function projectSlugForRun() {
  return projectSlug({ runId: process.env.GITHUB_RUN_ID });
}

export function previewRef({ dir }) {
  const normalized = String(dir ?? "").trim().replace(/\/+$/, "");
  if (!normalized) {
    throw new Error("previewRef needs a directory: neither OCEL_E2E_NODE_DIR nor a working directory was set");
  }
  const hint = sanitizeToken(basename(normalized)).slice(0, REF_HINT_LEN).replace(/-+$/, "");
  const hash = createHash("sha256").update(normalized).digest("hex").slice(0, REF_HASH_LEN);
  return hint ? `${hint}-${hash}` : hash;
}

export function previewRefForApp(appDir) {
  return previewRef({ dir: process.env.OCEL_E2E_NODE_DIR || appDir });
}

export function previewLabel(slug, pointer, app) {
  if (!pointer) return "";
  return [slug, pointer, app].filter(Boolean).join(PREVIEW_APP_SEPARATOR);
}

export function previewLabelProblem(slug, pointer) {
  return SMOKE_APPS.flatMap((app) => {
    const label = previewLabel(slug, pointer, app.name);
    if (label.length <= PREVIEW_LABEL_MAX_LEN) return [];
    return [
      `${label} is ${label.length} characters; DNS labels cap at ${PREVIEW_LABEL_MAX_LEN} ` +
        `(project ${slug} + preview ${pointer} + app ${app.name})`,
    ];
  });
}

export function strandedProjectSlugs(parameterNames, keepSlug) {
  const slugs = (parameterNames ?? [])
    .map((name) => String(name ?? ""))
    .filter((name) => name.startsWith(PREVIEW_ROOT_STACK_PARAM_PREFIX))
    .map((name) => name.slice(PREVIEW_ROOT_STACK_PARAM_PREFIX.length))
    .filter((slug) => slug.startsWith(SLUG_PREFIX) && slug !== keepSlug);
  return [...new Set(slugs)].sort();
}

export function renderOcelConfig({ slug }) {
  const apps = SMOKE_APPS.map(
    (app) =>
      `    { name: ${JSON.stringify(app.name)}, path: ${JSON.stringify(app.path)}, ` +
      `framework: ${JSON.stringify(app.framework)} },`,
  );
  return [
    `import { defineConfig } from "ocel/config";`,
    `import awsProvider from "@ocel/provider-aws";`,
    ``,
    `// Generated by scripts/e2e-node/deploy.mjs. Do not edit.`,
    `export default defineConfig({`,
    `  slug: ${JSON.stringify(slug)},`,
    `  provider: awsProvider(),`,
    `  apps: [`,
    ...apps,
    `  ],`,
    `});`,
    ``,
  ].join("\n");
}

export const FUNCTION_URL_HOST = /\.lambda-url\.[a-z0-9-]+\.on\.aws$/;

export function isFunctionURLHost(host) {
  return FUNCTION_URL_HOST.test(String(host ?? "").toLowerCase());
}

export function urlHost(url) {
  try {
    return new URL(String(url)).host.toLowerCase();
  } catch {
    return "";
  }
}

export function leadingLabel(url) {
  return urlHost(url).split(".")[0] ?? "";
}

export function resolveAppURLs(result, { slug, pointer, apps = SMOKE_APPS }) {
  const urls = Array.isArray(result?.appUrls) ? result.appUrls.map(String) : [];
  const taken = new Set();
  const resolved = apps.map((app) => {
    const label = previewLabel(slug, pointer, app.name);
    const at = urls.findIndex((candidate, index) => !taken.has(index) && leadingLabel(candidate) === label);
    if (at === -1) {
      return { app: app.name, framework: app.framework, url: null, kind: "missing" };
    }
    taken.add(at);
    return { app: app.name, framework: app.framework, url: urls[at], kind: "edge" };
  });
  const unattributed = urls.filter((_, index) => !taken.has(index));
  return { resolved, unattributed };
}

export function serveMarker(framework) {
  return `ocel-node-smoke:${framework}:v1`;
}

export const ECHO_ROUTE = "/echo";

export const MARKER_ROUTE = "/";

export const HEALTH_ROUTE = "/health";

export function statusRoute(code) {
  return `/status/${code}`;
}

export const ECHO_PROBE_HEADER = "x-ocel-probe";

export function echoRequest(stamp) {
  return {
    path: `${ECHO_ROUTE}/deep/segment`,
    query: { a: "1", b: "two words", stamp },
    header: { name: ECHO_PROBE_HEADER, value: `probe-${stamp}` },
    body: { stamp, nested: { list: [1, 2, 3] } },
  };
}

export function echoMismatches(sent, echo) {
  const problems = [];
  if (echo?.framework !== sent.framework) {
    problems.push(`framework: sent ${sent.framework}, echoed ${JSON.stringify(echo?.framework)}`);
  }
  if (echo?.method !== "POST") {
    problems.push(`method: expected POST, echoed ${JSON.stringify(echo?.method)}`);
  }
  if (echo?.path !== sent.path) {
    problems.push(`path: sent ${sent.path}, echoed ${JSON.stringify(echo?.path)}`);
  }
  for (const [name, value] of Object.entries(sent.query)) {
    if (echo?.query?.[name] !== value) {
      problems.push(`query ${name}: sent ${JSON.stringify(value)}, echoed ${JSON.stringify(echo?.query?.[name])}`);
    }
  }
  if (echo?.probeHeader !== sent.header.value) {
    problems.push(
      `header ${sent.header.name}: sent ${JSON.stringify(sent.header.value)}, echoed ${JSON.stringify(echo?.probeHeader)}`,
    );
  }
  if (JSON.stringify(echo?.body) !== JSON.stringify(sent.body)) {
    problems.push(`body: sent ${JSON.stringify(sent.body)}, echoed ${JSON.stringify(echo?.body)}`);
  }
  return problems;
}

export const CF_RAY_HEADER = "cf-ray";

export function headerValue(headers, name) {
  if (typeof headers?.get === "function") return headers.get(name);
  const entries = Object.entries(headers ?? {});
  const found = entries.find(([key]) => key.toLowerCase() === name);
  return found ? String(found[1]) : null;
}

export function edgeVerdict({ url, status, headers }) {
  const host = urlHost(url);
  if (!host) {
    return { kind: "no-url", detail: `${JSON.stringify(url)} is not a URL` };
  }
  if (isFunctionURLHost(host)) {
    return {
      kind: "function-url",
      detail:
        `${host} is a Lambda Function URL, not an edge hostname — the app was never given a worker, ` +
        `and a Function URL is created with AuthorizationType: IAM, so it 403s for every unsigned request`,
    };
  }
  if (!headerValue(headers, CF_RAY_HEADER)) {
    return {
      kind: "not-cloudflare",
      detail: `${host} answered ${status} without a ${CF_RAY_HEADER} header, so Cloudflare never handled it`,
    };
  }
  return { kind: "edge", detail: `${host} answered ${status} with a ${CF_RAY_HEADER}` };
}

export function envSegment(environment) {
  if (environment?.class === "preview") {
    return `preview-${environment?.identity ?? ""}`;
  }
  return "prod";
}

export function lambdaFunctionNames(response) {
  return (response?.ResourceTagMappingList ?? [])
    .map((entry) => /^arn:aws:lambda:[^:]*:[^:]*:function:([^:]+)/.exec(entry?.ResourceARN ?? ""))
    .filter(Boolean)
    .map((match) => match[1]);
}

export function tail(text, maxLines) {
  const lines = String(text ?? "").split("\n");
  return lines.slice(Math.max(0, lines.length - maxLines)).join("\n");
}

