package realtimetypes

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ocelhq/ocel/cli/internal/declaration"
	resourcesv1 "github.com/ocelhq/ocel/pkg/proto/app/resources/v1"
)

func realtimeResource(name string, channels ...*resourcesv1.RealtimeChannel) declaration.Resource {
	return declaration.Resource{
		Name:     name,
		Type:     resourcesv1.ResourceType_RESOURCE_TYPE_REALTIME,
		Realtime: &resourcesv1.RealtimeConfig{Channels: channels},
	}
}

func channel(pattern, schema string, configure ...func(*resourcesv1.RealtimeChannel)) *resourcesv1.RealtimeChannel {
	c := &resourcesv1.RealtimeChannel{
		Pattern:   pattern,
		Schema:    schema,
		Subscribe: resourcesv1.RealtimeSubscribe_REALTIME_SUBSCRIBE_RULE,
		Publish:   resourcesv1.RealtimePublish_REALTIME_PUBLISH_SERVER,
	}
	for _, change := range configure {
		change(c)
	}
	return c
}

func wildcard(c *resourcesv1.RealtimeChannel) { c.Wildcard = true }

func browserPublish(c *resourcesv1.RealtimeChannel) {
	c.Publish = resourcesv1.RealtimePublish_REALTIME_PUBLISH_RULE
}

func TestRenderKeysEachResourceByNameAndEachChannelByPattern(t *testing.T) {
	got, err := Render([]declaration.Resource{
		realtimeResource("my-app",
			channel("orders/:orderId", `{"type":"object","properties":{"status":{"type":"string"}},"required":["status"]}`),
			channel("projects/:projectId/deploys/:deployId", `{"type":"string"}`, wildcard),
			channel("rooms/:roomId", `{"type":"object","properties":{"text":{"type":"string"}},"required":["text"]}`, browserPublish),
		),
		{Name: "jobs", Type: resourcesv1.ResourceType_RESOURCE_TYPE_TOPIC},
	})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	want := `// Generated by ocel from the realtime resources this project declares. Do not edit.
// Type a browser client with one: createRealtimeClient<RealtimeResources["name"]>({ url }).

export type RealtimeResources = {
  "my-app": {
    "orders/:orderId": { event: { status: string } };
    "projects/:projectId/deploys/:deployId": { event: string; wildcard: true };
    "rooms/:roomId": { event: { text: string }; publish: { text: string } };
  };
};
`
	if got != want {
		t.Fatalf("Render =\n%s\nwant\n%s", got, want)
	}
}

func TestRenderTypesEachJSONSchemaConstruct(t *testing.T) {
	for _, tc := range []struct {
		name   string
		schema string
		want   string
	}{
		{"no schema", ``, `unknown`},
		{"the true schema", `true`, `unknown`},
		{"scalars", `{"type":"object","properties":{"a":{"type":"integer"},"b":{"type":"number"},"c":{"type":"boolean"},"d":{"type":"null"}},"required":["a","b","c","d"]}`, `{ a: number; b: number; c: boolean; d: null }`},
		{"optional properties and quoted keys", `{"type":"object","properties":{"first-name":{"type":"string"},"age":{"type":"integer"}},"required":["first-name"]}`, `{ age?: number; "first-name": string }`},
		{"a type list", `{"type":["string","null"]}`, `string | null`},
		{"an enum", `{"enum":["paid","shipped",3,null]}`, `"paid" | "shipped" | 3 | null`},
		{"a const", `{"const":"live"}`, `"live"`},
		{"anyOf and oneOf", `{"anyOf":[{"type":"string"},{"oneOf":[{"type":"integer"},{"type":"boolean"}]}]}`, `string | (number | boolean)`},
		{"allOf", `{"allOf":[{"type":"object","properties":{"a":{"type":"string"}},"required":["a"]},{"type":"object","properties":{"b":{"type":"string"}},"required":["b"]}]}`, `{ a: string } & { b: string }`},
		{"an array", `{"type":"array","items":{"type":"string"}}`, `string[]`},
		{"an array of a union", `{"type":"array","items":{"type":["string","null"]}}`, `(string | null)[]`},
		{"a tuple", `{"type":"array","prefixItems":[{"type":"string"},{"type":"integer"}],"items":false}`, `[string, number]`},
		{"a map", `{"type":"object","additionalProperties":{"type":"integer"}}`, `Record<string, number>`},
		{"an open object", `{"type":"object","properties":{"a":{"type":"string"}},"required":["a"],"additionalProperties":true}`, `{ a: string; [key: string]: unknown }`},
		{"an object with no properties", `{"type":"object"}`, `Record<string, unknown>`},
		{"a $defs reference", `{"$defs":{"Item":{"type":"object","properties":{"sku":{"type":"string"}},"required":["sku"]}},"type":"array","items":{"$ref":"#/$defs/Item"}}`, `{ sku: string }[]`},
		{"a definitions reference", `{"definitions":{"Id":{"type":"string"}},"$ref":"#/definitions/Id"}`, `string`},
		{"a recursive reference", `{"$defs":{"Node":{"type":"object","properties":{"next":{"$ref":"#/$defs/Node"}}}},"$ref":"#/$defs/Node"}`, `{ next?: unknown }`},
		{"properties without a type", `{"properties":{"a":{"type":"string"}}}`, `{ a?: string }`},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := Render([]declaration.Resource{realtimeResource("app", channel("status", tc.schema))})
			if err != nil {
				t.Fatalf("Render: %v", err)
			}
			want := `"status": { event: ` + tc.want + ` };`
			if !strings.Contains(got, want) {
				t.Fatalf("Render =\n%s\nwant a line %s", got, want)
			}
		})
	}
}

func TestRenderRefusesASchemaThatIsNotJSON(t *testing.T) {
	_, err := Render([]declaration.Resource{realtimeResource("app", channel("status", `{"type":`))})
	if err == nil || !strings.Contains(err.Error(), `channel "status" of realtime "app"`) {
		t.Fatalf("Render error = %v, want one naming the channel and resource", err)
	}
}

func TestGenerateWritesTheFileOnlyWhileRealtimeIsDeclared(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, FileName)

	written, err := Generate(dir, []declaration.Resource{realtimeResource("app", channel("status", `{"type":"string"}`))})
	if err != nil || !written {
		t.Fatalf("Generate = %v, %v; want it written", written, err)
	}
	if content, err := os.ReadFile(path); err != nil || !strings.Contains(string(content), `"status": { event: string };`) {
		t.Fatalf("read %s = %q, %v", path, content, err)
	}

	written, err = Generate(dir, nil)
	if err != nil || written {
		t.Fatalf("Generate with nothing declared = %v, %v; want nothing written", written, err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("Generate left %s behind once nothing is declared: %v", path, err)
	}
}
