package realtimetypes

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/ocelhq/ocel/cli/internal/declaration"
	resourcesv1 "github.com/ocelhq/ocel/pkg/proto/app/resources/v1"
)

const FileName = "ocel-realtime.d.ts"

const header = "// Generated by ocel from the realtime resources this project declares. Do not edit.\n"

var bareIdentifier = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)

func Generate(dir string, resources []declaration.Resource) (bool, error) {
	path := filepath.Join(dir, FileName)
	if !slices.ContainsFunc(resources, isRealtime) {
		return false, removeGenerated(path)
	}
	content, err := Render(resources)
	if err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

func removeGenerated(path string) error {
	current, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if !bytes.HasPrefix(current, []byte(header)) {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("remove %s, which no realtime resource needs: %w", path, err)
	}
	return nil
}

func isRealtime(resource declaration.Resource) bool {
	return resource.Type == resourcesv1.ResourceType_RESOURCE_TYPE_REALTIME && resource.Realtime != nil
}

func Render(resources []declaration.Resource) (string, error) {
	realtime := slices.Clone(resources)
	realtime = slices.DeleteFunc(realtime, func(resource declaration.Resource) bool { return !isRealtime(resource) })
	slices.SortStableFunc(realtime, func(a, b declaration.Resource) int { return strings.Compare(a.Name, b.Name) })

	var out strings.Builder
	out.WriteString(header)
	out.WriteString("// Type a browser client with one: createRealtimeClient<RealtimeResources[\"name\"]>({ url }).\n\n")
	out.WriteString("export type RealtimeResources = {\n")
	for _, resource := range realtime {
		fmt.Fprintf(&out, "  %s: {\n", jsonLiteral(resource.Name))
		for _, channel := range resource.Realtime.GetChannels() {
			event, err := renderSchema(channel.GetSchema())
			if err != nil {
				return "", fmt.Errorf("channel %q of realtime %q has a schema that is not JSON: %w", channel.GetPattern(), resource.Name, err)
			}
			members := []string{"event: " + event}
			if channel.GetPublish() == resourcesv1.RealtimePublish_REALTIME_PUBLISH_RULE {
				members = append(members, "publish: "+event)
			}
			if channel.GetWildcard() {
				members = append(members, "wildcard: true")
			}
			fmt.Fprintf(&out, "    %s: { %s };\n", jsonLiteral(channel.GetPattern()), strings.Join(members, "; "))
		}
		out.WriteString("  };\n")
	}
	out.WriteString("};\n")
	return out.String(), nil
}

func renderSchema(written string) (string, error) {
	if strings.TrimSpace(written) == "" {
		return "unknown", nil
	}
	var root any
	if err := json.Unmarshal([]byte(written), &root); err != nil {
		return "", err
	}
	document := schemaDocument{root: root, resolving: map[string]bool{}}
	return document.render(root), nil
}

type schemaDocument struct {
	root      any
	resolving map[string]bool
}

func (d schemaDocument) render(schema any) string {
	switch schema := schema.(type) {
	case bool:
		if schema {
			return "unknown"
		}
		return "never"
	case map[string]any:
		return d.renderObjectSchema(schema)
	}
	return "unknown"
}

func (d schemaDocument) renderObjectSchema(schema map[string]any) string {
	if ref, ok := schema["$ref"].(string); ok {
		return d.renderReference(ref)
	}
	if value, ok := schema["const"]; ok {
		return jsonLiteral(value)
	}
	if values, ok := schema["enum"].([]any); ok {
		literals := make([]string, 0, len(values))
		for _, value := range values {
			literals = append(literals, jsonLiteral(value))
		}
		return joinTypes(literals, " | ")
	}
	for _, key := range []string{"anyOf", "oneOf"} {
		if members, ok := schema[key].([]any); ok {
			return d.renderEach(members, " | ")
		}
	}
	if members, ok := schema["allOf"].([]any); ok {
		return d.renderEach(members, " & ")
	}
	switch named := schema["type"].(type) {
	case string:
		return d.renderTyped(named, schema)
	case []any:
		types := make([]string, 0, len(named))
		for _, one := range named {
			if name, ok := one.(string); ok {
				types = append(types, d.renderTyped(name, schema))
			}
		}
		return joinTypes(types, " | ")
	}
	if _, ok := schema["properties"]; ok {
		return d.renderTyped("object", schema)
	}
	return "unknown"
}

func (d schemaDocument) renderEach(members []any, separator string) string {
	types := make([]string, 0, len(members))
	for _, member := range members {
		types = append(types, d.render(member))
	}
	return joinTypes(types, separator)
}

func (d schemaDocument) renderReference(ref string) string {
	if d.resolving[ref] {
		return "unknown"
	}
	target, ok := d.resolvePointer(ref)
	if !ok {
		return "unknown"
	}
	d.resolving[ref] = true
	defer delete(d.resolving, ref)
	return d.render(target)
}

func (d schemaDocument) resolvePointer(ref string) (any, bool) {
	pointer, isLocal := strings.CutPrefix(ref, "#")
	if !isLocal {
		return nil, false
	}
	node := d.root
	for _, token := range strings.Split(strings.TrimPrefix(pointer, "/"), "/") {
		if token == "" {
			continue
		}
		token = strings.ReplaceAll(strings.ReplaceAll(token, "~1", "/"), "~0", "~")
		object, ok := node.(map[string]any)
		if !ok {
			return nil, false
		}
		if node, ok = object[token]; !ok {
			return nil, false
		}
	}
	return node, true
}

func (d schemaDocument) renderTyped(name string, schema map[string]any) string {
	switch name {
	case "string", "boolean", "null":
		return name
	case "integer", "number":
		return "number"
	case "array":
		return d.renderArray(schema)
	case "object":
		return d.renderObject(schema)
	}
	return "unknown"
}

func (d schemaDocument) renderArray(schema map[string]any) string {
	items, hasItems := schema["items"]
	if prefix, ok := schema["prefixItems"].([]any); ok {
		elements := make([]string, 0, len(prefix)+1)
		for _, item := range prefix {
			elements = append(elements, d.render(item))
		}
		if !hasItems || items != false {
			elements = append(elements, "..."+parenthesize(d.render(items))+"[]")
		}
		return "[" + strings.Join(elements, ", ") + "]"
	}
	if !hasItems {
		return "unknown[]"
	}
	return parenthesize(d.render(items)) + "[]"
}

func (d schemaDocument) renderObject(schema map[string]any) string {
	properties, _ := schema["properties"].(map[string]any)
	additional, hasAdditional := schema["additionalProperties"]
	if len(properties) == 0 {
		if !hasAdditional {
			return "Record<string, unknown>"
		}
		return "Record<string, " + d.render(additional) + ">"
	}
	required := map[string]bool{}
	if names, ok := schema["required"].([]any); ok {
		for _, name := range names {
			if text, ok := name.(string); ok {
				required[text] = true
			}
		}
	}
	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	slices.Sort(names)
	members := make([]string, 0, len(names)+1)
	for _, name := range names {
		optional := "?"
		if required[name] {
			optional = ""
		}
		members = append(members, quoteKey(name)+optional+": "+d.render(properties[name]))
	}
	if hasAdditional && additional != false {
		members = append(members, "[key: string]: unknown")
	}
	return "{ " + strings.Join(members, "; ") + " }"
}

func jsonLiteral(value any) string {
	var buf bytes.Buffer
	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(value); err != nil {
		return "unknown"
	}
	return strings.TrimSuffix(buf.String(), "\n")
}

func joinTypes(types []string, separator string) string {
	if len(types) == 0 {
		return "never"
	}
	if len(types) == 1 {
		return types[0]
	}
	operands := make([]string, 0, len(types))
	for _, operand := range types {
		operands = append(operands, parenthesize(operand))
	}
	return strings.Join(operands, separator)
}

func parenthesize(typeText string) string {
	depth := 0
	isInString, isEscaped := false, false
	for _, char := range typeText {
		switch {
		case isEscaped:
			isEscaped = false
		case isInString && char == '\\':
			isEscaped = true
		case char == '"':
			isInString = !isInString
		case isInString:
		case char == '{' || char == '[' || char == '(' || char == '<':
			depth++
		case char == '}' || char == ']' || char == ')' || char == '>':
			depth--
		case (char == '|' || char == '&') && depth == 0:
			return "(" + typeText + ")"
		}
	}
	return typeText
}

func quoteKey(name string) string {
	if bareIdentifier.MatchString(name) {
		return name
	}
	return jsonLiteral(name)
}
