// generated by `ocel bindings generate` from production; do not edit
import "@ocel/transforms";

declare module "@ocel/transforms" {
  interface BindingsGenerated {
    generated: true;
  }

  interface Bindings {
    custom: {
      network: { securityGroupIds: string[]; subnetIds: string[] };
    };
    postgres: {
      orders: { host: string; port: number; database: string; username: string; password: string };
    };
  }
}
