#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE=".env.gobuildcache"

cd "$(dirname "$0")/.."

banner "gobuildcache — remote Go build cache"

# ── Stage 1: the S3 Express One Zone bucket ───────────────────────────────
stage "S3 Express One Zone bucket"
say "Directory-bucket names must end in --<az-id>--x-s3."
step "Pick the region CI is closest to (GitHub hosted runners live in us-east-1)."
ask GOBUILDCACHE_AWS_REGION "Region (e.g. us-east-1):"
step "List the zone ids available there:"
say ""
say "    aws ec2 describe-availability-zones --region $GOBUILDCACHE_AWS_REGION \\"
say "      --query 'AvailabilityZones[].ZoneId' --output text"
say ""
ask AZ_ID "Zone id to use (e.g. use1-az4):"
GOBUILDCACHE_S3_BUCKET="ocelhq-gobuildcache--${AZ_ID}--x-s3"
say "Create the bucket:"
say ""
say "    aws s3api create-bucket --bucket $GOBUILDCACHE_S3_BUCKET \\"
say "      --region $GOBUILDCACHE_AWS_REGION \\"
say "      --create-bucket-configuration 'Location={Type=AvailabilityZone,Name=${AZ_ID}},Bucket={DataRedundancy=SingleAvailabilityZone,Type=Directory}'"
say ""
note "Optional: add a lifecycle rule expiring objects after ~30 days so stale cache entries age out."
pause "Bucket created? Press Enter to continue"
write_env GOBUILDCACHE_AWS_REGION "$GOBUILDCACHE_AWS_REGION"
write_env GOBUILDCACHE_S3_BUCKET "$GOBUILDCACHE_S3_BUCKET"

# ── Stage 2: OIDC role scoped to the bucket ───────────────────────────────
stage "Build-cache IAM role (OIDC)"
say "CI assumes a role through GitHub's OIDC provider — no static keys."
say "Directory buckets are authorized via s3express:CreateSession — that one"
say "action on the bucket ARN is the whole permission policy."
ask AWS_ACCOUNT_ID "AWS account id (aws sts get-caller-identity --query Account --output text):"
ask GITHUB_REPO "GitHub repo (owner/name):"
say "Create the role (assumes the GitHub OIDC provider already exists in the account):"
say ""
say "    aws iam create-role --role-name gobuildcache \\"
say "      --max-session-duration 7200 \\"
say "      --assume-role-policy-document '{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Federated\":\"arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/token.actions.githubusercontent.com\"},\"Action\":\"sts:AssumeRoleWithWebIdentity\",\"Condition\":{\"StringEquals\":{\"token.actions.githubusercontent.com:aud\":\"sts.amazonaws.com\"},\"StringLike\":{\"token.actions.githubusercontent.com:sub\":\"repo:${GITHUB_REPO}:*\"}}}]}'"
say "    aws iam put-role-policy --role-name gobuildcache --policy-name gobuildcache \\"
say "      --policy-document '{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"s3express:CreateSession\",\"Resource\":\"arn:aws:s3express:${GOBUILDCACHE_AWS_REGION}:${AWS_ACCOUNT_ID}:bucket/${GOBUILDCACHE_S3_BUCKET}\"}]}'"
say ""
GOBUILDCACHE_AWS_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/gobuildcache"
ask GOBUILDCACHE_AWS_ROLE_ARN "Role ARN [$GOBUILDCACHE_AWS_ROLE_ARN]:" || true
[[ -z "$GOBUILDCACHE_AWS_ROLE_ARN" ]] && GOBUILDCACHE_AWS_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/gobuildcache"
write_env AWS_ACCOUNT_ID "$AWS_ACCOUNT_ID"
write_env GITHUB_REPO "$GITHUB_REPO"
write_env GOBUILDCACHE_AWS_ROLE_ARN "$GOBUILDCACHE_AWS_ROLE_ARN"

# ── Stage 3: GitHub Actions variables + secrets ───────────────────────────
stage "GitHub Actions"
say "CI reads two repo variables and one secret; the workflows skip the cache"
say "silently until all three exist."
set_var GOBUILDCACHE_S3_BUCKET "$GOBUILDCACHE_S3_BUCKET"
set_var GOBUILDCACHE_AWS_REGION "$GOBUILDCACHE_AWS_REGION"
set_secret GOBUILDCACHE_AWS_ROLE_ARN "$GOBUILDCACHE_AWS_ROLE_ARN"
pause

# ── Stage 4: local activation via mise.local.toml ─────────────────────────
stage "Local activation"
say "Local builds authorize with your ambient AWS credentials (profile, SSO,"
say "whatever the default chain finds) — they need s3express:CreateSession on"
say "the bucket. No static keys are written anywhere."
MISE_LOCAL="mise.local.toml"
MISE_BLOCK=$(cat <<EOF
[env]
GOCACHEPROG = "gobuildcache"
GOBUILDCACHE_BACKEND_TYPE = "s3"
GOBUILDCACHE_S3_BUCKET = "$GOBUILDCACHE_S3_BUCKET"
GOBUILDCACHE_AWS_REGION = "$GOBUILDCACHE_AWS_REGION"
GOBUILDCACHE_PRINT_STATS = "false"
EOF
)
if [[ -f "$MISE_LOCAL" ]]; then
  warn "$MISE_LOCAL already exists — merge this into it yourself:"
  printf '\n%s\n\n' "$MISE_BLOCK"
  pause "Merged? Press Enter to continue"
else
  printf '%s\n' "$MISE_BLOCK" > "$MISE_LOCAL"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$MISE_LOCAL"
  note "$MISE_LOCAL is gitignored; the gobuildcache binary itself is pinned in mise.toml."
fi
say "Reload the environment: cd out of the repo and back in, or run: mise env"
pause

# ── Stage 5: verify ───────────────────────────────────────────────────────
stage "Verify"
say "In a fresh shell, run a build with debug logging and watch for remote"
say "gets/puts against the bucket:"
say ""
say "    cd pkg/naming && GOBUILDCACHE_DEBUG=true go build -a ./..."
say ""
say "Then re-run it — the second build should be nearly instant."
if confirm "Did the debug log show S3 traffic?"; then
  say "Remote cache is live. CI picks it up on the next run — no further action."
else
  warn "Check: bucket/zone ids match, the IAM policy ARN region matches the bucket,"
  warn "and 'mise env' shows GOCACHEPROG=gobuildcache."
fi

finish
note "Values were also saved to $ENV_FILE (gitignored) so re-running this wizard is safe."
