import { describe, expect, it } from "vitest";

import {
  BYTECODE_EMBEDDED_MARKER,
  BYTECODE_S3_REHYDRATE_MARKER,
  DNS_LABEL,
  WARM_SUMMARY_MARKER,
  appAssetPrefix,
  bytecodeAppNamespace,
  bytecodeCacheEntry,
  bytecodeCacheKeyName,
  bytecodeEmbeddedOutcome,
  bytecodeRehydrateOutcome,
  deployURL,
  embeddedArtifactPairs,
  embeddedBytecodePath,
  envSegment,
  lambdaFunctionNames,
  lambdaLogGroups,
  logWindowVerdict,
  projectSlug,
  renderOcelConfig,
  sanitizeWorkerName,
  strongestCoverage,
  summarizeOutcomes,
  tail,
  warmCoverage,
  warmSummaryOutcome,
} from "./lib.mjs";

// This module is the single source of truth both scripts/e2e-next and
// scripts/e2e-node build their assertions on — the bytecode-cache key
// derivation is what has to mirror cloud/aws/deploy/bytecode.go and
// cloud/aws/cmd/lambdanode/bootstrap/bytecode.go exactly, on both sides, for
// any assertion built on it to mean anything. Before scripts/e2e-node existed
// this was covered only transitively through scripts/e2e-next/lib.test.mjs;
// this file tests it directly, at the layer both harnesses actually depend
// on.

describe("DNS_LABEL", () => {
  it("accepts a single valid label and rejects what is not one", () => {
    expect(DNS_LABEL.test("e2e-42-abcd1234")).toBe(true);
    expect(DNS_LABEL.test("a")).toBe(true);
    expect(DNS_LABEL.test("-leading")).toBe(false);
    expect(DNS_LABEL.test("trailing-")).toBe(false);
    expect(DNS_LABEL.test("Upper")).toBe(false);
    expect(DNS_LABEL.test("has.dot")).toBe(false);
    expect(DNS_LABEL.test("")).toBe(false);
  });
});

describe("projectSlug", () => {
  it("is a valid single DNS label carrying the run id", () => {
    const slug = projectSlug({ runId: "1234567890", dir: "/tmp/e2e-abc" });
    expect(DNS_LABEL.test(slug)).toBe(true);
    expect(slug).toMatch(/^e2e-1234567890-[0-9a-f]{8}$/);
  });

  it("is stable for the same inputs, and moves when the directory does", () => {
    const a = projectSlug({ runId: "1", dir: "/tmp/one" });
    const b = projectSlug({ runId: "1", dir: "/tmp/one" });
    const c = projectSlug({ runId: "1", dir: "/tmp/two" });
    expect(a).toBe(b);
    expect(a).not.toBe(c);
  });

  it("falls back to a fixed local token when no run id is given", () => {
    expect(projectSlug({ dir: "/tmp/x" })).toMatch(/^e2e-local-[0-9a-f]{8}$/);
  });

  it("never exceeds MAX_SLUG_LEN, however long the run id is", () => {
    const slug = projectSlug({ runId: "x".repeat(200), dir: "/tmp/x" });
    expect(slug.length).toBeLessThanOrEqual(52);
    expect(DNS_LABEL.test(slug)).toBe(true);
  });
});

describe("renderOcelConfig", () => {
  const config = renderOcelConfig({
    slug: "e2e-42-abcd1234",
    previewDomain: "*.e2e.example.com",
    apps: [{ name: "app", path: ".", framework: "next" }],
  });

  it("carries the project slug, provider and preview wildcard", () => {
    expect(config).toContain(`slug: "e2e-42-abcd1234"`);
    expect(config).toContain("awsProvider()");
    expect(config).toContain(`preview: "*.e2e.example.com"`);
  });

  it("renders each apps entry verbatim, in the given key order", () => {
    expect(config).toContain(`apps: [{ name: "app", path: ".", framework: "next" }]`);
  });

  it("omits the domains block when no preview domain is given", () => {
    expect(renderOcelConfig({ slug: "s", apps: [] })).not.toContain("domains:");
  });

  it("is pure: the same arguments render byte-for-byte the same file", () => {
    const args = { slug: "s", apps: [{ name: "app", path: ".", framework: "express" }] };
    expect(renderOcelConfig(args)).toBe(renderOcelConfig(args));
  });

  // Pinned so the generated-file marker cannot silently drift to something
  // inaccurate again — see this function's own doc comment: it used to claim
  // scripts/e2e-next/deploy.mjs wrote every rendered config, which stopped
  // being true the moment scripts/e2e-node started calling this too.
  it("names itself as an e2e harness output, not a single script's", () => {
    expect(config).toContain("// Generated by an ocel e2e harness (scripts/e2e-next or scripts/e2e-node). Do not edit.");
  });
});

describe("deployURL", () => {
  it("takes the first featured app URL", () => {
    expect(deployURL({ appUrls: ["https://a.example.com", "https://b.example.com"] })).toBe("https://a.example.com");
  });

  it("refuses a result with no URL, naming what it read", () => {
    expect(() => deployURL({ appUrls: [] })).toThrow(/no app URL/i);
    expect(() => deployURL({})).toThrow(/no app URL/i);
  });
});

describe("lambdaFunctionNames / lambdaLogGroups", () => {
  it("extracts bare function names from tagged ARNs", () => {
    expect(
      lambdaFunctionNames({
        ResourceTagMappingList: [{ ResourceARN: "arn:aws:lambda:us-east-1:1:function:proj--web-abc123" }],
      }),
    ).toEqual(["proj--web-abc123"]);
  });

  it("ignores non-function ARNs and an empty response", () => {
    expect(lambdaFunctionNames({})).toEqual([]);
    expect(lambdaFunctionNames({ ResourceTagMappingList: [{ ResourceARN: "arn:aws:s3:::bucket" }] })).toEqual([]);
  });

  it("maps the same names lambdaFunctionNames finds to their log groups", () => {
    const response = {
      ResourceTagMappingList: [
        { ResourceARN: "arn:aws:lambda:us-east-1:1:function:a" },
        { ResourceARN: "arn:aws:lambda:us-east-1:1:function:b" },
      ],
    };
    expect(lambdaLogGroups(response)).toEqual(lambdaFunctionNames(response).map((name) => `/aws/lambda/${name}`));
  });
});

describe("sanitizeWorkerName", () => {
  // Mirrors sanitizeWorkerName in cloud/aws/deploy/edgeworker.go byte for
  // byte: this is what appAssetPrefix and bytecodeAppNamespace apply to
  // `app` before composing a key, the same as their Go counterparts, so a
  // harness naming its app something Go would sanitize derives the same
  // namespace Go actually writes to rather than a different, empty one.
  it("lowercases and collapses everything outside [a-z0-9] into a single hyphen", () => {
    expect(sanitizeWorkerName("My App")).toBe("my-app");
    expect(sanitizeWorkerName("proj.slug_name")).toBe("proj-slug-name");
  });

  it("trims leading and trailing hyphens", () => {
    expect(sanitizeWorkerName("--edge--")).toBe("edge");
  });

  it("leaves an already-valid worker name untouched — every app name this repo's own harnesses pass today", () => {
    expect(sanitizeWorkerName("app")).toBe("app");
  });

  it("collapses distinct raw names to the same token, matching the Go side's own documented collision", () => {
    expect(sanitizeWorkerName("my.app")).toBe(sanitizeWorkerName("my-app"));
    expect(sanitizeWorkerName("web_1")).toBe(sanitizeWorkerName("web-1"));
  });

  it("clamps to the 63-character platform limit without leaving a trailing hyphen", () => {
    const clamped = sanitizeWorkerName("a".repeat(100));
    expect(clamped.length).toBe(63);
    expect(clamped.endsWith("-")).toBe(false);
  });

  it("falls back to a fixed name when nothing sanitizable remains", () => {
    expect(sanitizeWorkerName("...")).toBe("ocel-worker");
    expect(sanitizeWorkerName("")).toBe("ocel-worker");
  });
});

describe("envSegment", () => {
  it("names a preview by its identity", () => {
    expect(envSegment({ class: "preview", identity: "e2e-42-abcd1234" })).toBe("preview-e2e-42-abcd1234");
  });

  it("names production the fixed token, regardless of identity", () => {
    expect(envSegment({ class: "production", identity: "" })).toBe("prod");
    expect(envSegment({ class: "production" })).toBe("prod");
  });

  it("treats a missing or unrecognized class as production", () => {
    expect(envSegment(undefined)).toBe("prod");
    expect(envSegment({ class: "development" })).toBe("prod");
  });
});

describe("appAssetPrefix", () => {
  it("joins env/slug/app/buildId in that order", () => {
    expect(
      appAssetPrefix({
        environment: { class: "preview", identity: "e2e-42-abcd1234" },
        slug: "e2e-42-abcd1234",
        app: "app",
        buildId: "bld123",
      }),
    ).toBe("preview-e2e-42-abcd1234/e2e-42-abcd1234/app/bld123");
  });

  it("uses the fixed prod segment for a production deploy", () => {
    expect(appAssetPrefix({ environment: { class: "production" }, slug: "s", app: "app", buildId: "b" })).toBe(
      "prod/s/app/b",
    );
  });

  it("sanitizes app the same way the Go side does before composing the key", () => {
    expect(
      appAssetPrefix({ environment: { class: "production" }, slug: "s", app: "My App", buildId: "b" }),
    ).toBe("prod/s/my-app/b");
  });
});

describe("bytecodeAppNamespace", () => {
  it("joins bytecode/env/slug/app in that order — mirrors bytecodeAppNamespace in bytecode.go", () => {
    expect(
      bytecodeAppNamespace({
        environment: { class: "preview", identity: "e2e-42-abcd1234" },
        slug: "e2e-42-abcd1234",
        app: "app",
      }),
    ).toBe("bytecode/preview-e2e-42-abcd1234/e2e-42-abcd1234/app");
  });

  it("uses the fixed prod segment for a production deploy", () => {
    expect(bytecodeAppNamespace({ environment: { class: "production" }, slug: "s", app: "app" })).toBe(
      "bytecode/prod/s/app",
    );
  });

  it("is not appAssetPrefix's build-keyed prefix — the two must never collide", () => {
    const environment = { class: "preview", identity: "e2e-42-abcd1234" };
    const slug = "e2e-42-abcd1234";
    const app = "app";
    expect(bytecodeAppNamespace({ environment, slug, app })).not.toBe(
      appAssetPrefix({ environment, slug, app, buildId: "bld123" }),
    );
  });

  it("sanitizes app the same way appAssetPrefix does", () => {
    expect(bytecodeAppNamespace({ environment: { class: "production" }, slug: "s", app: "My App" })).toBe(
      "bytecode/prod/s/my-app",
    );
  });
});

describe("bytecodeCacheEntry / bytecodeCacheKeyName", () => {
  // Pins the full derivation this harness has to agree with the Go side on,
  // end to end: bytecodeAppNamespace + bytecodePrefixFor's hash segment +
  // bytecodeCacheKey's own "node<version>-<arch>.tar.gz" (cloud/aws/deploy/
  // bytecode.go, cloud/aws/cmd/lambdanode/bootstrap/bytecode.go). A real S3
  // listing under bytecodeAppNamespace returns names with the namespace
  // already stripped, which is what this parses.
  it("reads the hash, node version and arch out of a real key's tail", () => {
    const namespace = bytecodeAppNamespace({
      environment: { class: "preview", identity: "e2e-42-abcd1234" },
      slug: "e2e-42-abcd1234",
      app: "app",
    });
    const hash = "a1b2c3d4e5f6";
    const key = `${namespace}/${hash}/node24.3.1-x86_64.tar.gz`;

    expect(bytecodeCacheEntry(key.slice(namespace.length + 1))).toEqual({
      hash,
      filename: "node24.3.1-x86_64.tar.gz",
      nodeVersion: "24.3.1",
      arch: "x86_64",
    });
  });

  it("rejects a name with no hash/filename structure", () => {
    expect(bytecodeCacheEntry("node24.3.1-x86_64.tar.gz")).toBeNull();
  });

  it("rejects a name whose filename is not node<version>-<arch>.tar.gz", () => {
    expect(bytecodeCacheEntry("a1b2c3/not-a-cache-file")).toBeNull();
  });

  it("parses a real archive name into its node version and arch", () => {
    expect(bytecodeCacheKeyName("node24.3.1-x86_64.tar.gz")).toEqual({ nodeVersion: "24.3.1", arch: "x86_64" });
  });

  it("rejects a version that is not three dot-separated numbers", () => {
    expect(bytecodeCacheKeyName("node24-x86_64.tar.gz")).toBeNull();
    expect(bytecodeCacheKeyName("nodev24.3.1-x86_64.tar.gz")).toBeNull();
  });

  it("rejects anything that is not the node<version>-<arch>.tar.gz shape", () => {
    expect(bytecodeCacheKeyName("some-other-object.tar.gz")).toBeNull();
    expect(bytecodeCacheKeyName("")).toBeNull();
    expect(bytecodeCacheKeyName(undefined)).toBeNull();
  });
});

describe("bytecodeRehydrateOutcome", () => {
  const key = "preview-e2e-42/e2e-42/app/bld123/bytecode/proj--web-abc123/node24.3.1-x86_64.tar.gz";

  it("recognizes a rehydrate hit naming the key", () => {
    expect(bytecodeRehydrateOutcome(`ocel: rehydrated compile cache from ${key}: 4096 bytes in 312ms`, key)).toEqual({
      kind: "hit",
      message: `ocel: rehydrated compile cache from ${key}: 4096 bytes in 312ms`,
    });
  });

  it("recognizes the expected first-cold-start miss", () => {
    expect(bytecodeRehydrateOutcome(`ocel: no compile cache at ${key} yet; nothing to rehydrate`, key).kind).toBe("miss");
  });

  it("recognizes a fetch failure", () => {
    expect(bytecodeRehydrateOutcome(`ocel: could not fetch the compile cache at ${key}: connection reset`, key).kind).toBe(
      "fetch-error",
    );
  });

  it("ignores unrelated log lines, and a line naming a different key", () => {
    expect(bytecodeRehydrateOutcome("START RequestId: abc", key)).toBeNull();
    expect(
      bytecodeRehydrateOutcome(`ocel: rehydrated compile cache from some/other/key.tar.gz: 10 bytes in 1ms`, key),
    ).toBeNull();
  });

  it("recognizes a cache over the ceiling", () => {
    expect(
      bytecodeRehydrateOutcome(
        `ocel: compile cache at ${key} is 100000000 bytes, over the 67108864 byte ceiling; skipping rehydration`,
        key,
      ).kind,
    ).toBe("over-ceiling");
  });

  it("recognizes an extraction failure, and does not confuse it with a hit", () => {
    const message = `ocel: could not rehydrate the compile cache from ${key}: unexpected EOF`;
    expect(bytecodeRehydrateOutcome(message, key)).toEqual({ kind: "extract-error", message });
    expect(bytecodeRehydrateOutcome(message, key).kind).not.toBe("hit");
  });

  it("recognizes a rehydration timeout", () => {
    expect(
      bytecodeRehydrateOutcome(`ocel: rehydrating the compile cache from ${key} ran out of time: context deadline exceeded`, key)
        .kind,
    ).toBe("timeout");
  });

  it("recognizes a dir-clear failure that names no key at all", () => {
    expect(
      bytecodeRehydrateOutcome(
        "ocel: could not clear /tmp/.ocel/compile-cache before rehydrating the compile cache: permission denied",
        key,
      ).kind,
    ).toBe("clear-error");
  });

  it("recognizes the feature disabling itself before a key could ever be composed", () => {
    expect(bytecodeRehydrateOutcome("ocel: could not read node's version, compile cache disabled: exit status 1", key).kind).toBe(
      "disabled",
    );
    expect(bytecodeRehydrateOutcome('ocel: not a node version: "garbage", compile cache disabled', key).kind).toBe("disabled");
    expect(bytecodeRehydrateOutcome("ocel: no aws config for the compile cache: no EC2 IMDS role found", key).kind).toBe(
      "disabled",
    );
  });
});

describe("bytecodeEmbeddedOutcome", () => {
  const tarPath = "/var/task/.ocel/bytecode/node24.3.1-x86_64.tar";

  it("recognizes a hit naming the tar", () => {
    const message = `ocel: loaded embedded compile cache from ${tarPath}: 4096 bytes in 7ms`;
    expect(bytecodeEmbeddedOutcome(message, tarPath)).toEqual({ kind: "hit", message });
  });

  it("classifies each way the local leg can fail without calling any of them a hit", () => {
    expect(
      bytecodeEmbeddedOutcome(`ocel: could not open the embedded compile cache at ${tarPath}: permission denied`, tarPath).kind,
    ).toBe("open-error");
    expect(
      bytecodeEmbeddedOutcome(
        `ocel: could not clear /tmp/.ocel/compile-cache before loading the embedded compile cache at ${tarPath}: read-only`,
        tarPath,
      ).kind,
    ).toBe("clear-error");
    expect(
      bytecodeEmbeddedOutcome(`ocel: could not load the embedded compile cache at ${tarPath}: unexpected EOF`, tarPath).kind,
    ).toBe("load-error");
  });

  it("ignores unrelated lines, and a line naming a different tar", () => {
    expect(bytecodeEmbeddedOutcome("START RequestId: abc", tarPath)).toBeNull();
    expect(
      bytecodeEmbeddedOutcome(
        "ocel: loaded embedded compile cache from /var/task/.ocel/bytecode/node22.0.0-x86_64.tar: 1 bytes in 1ms",
        tarPath,
      ),
    ).toBeNull();
  });

  it("does not confuse the two read legs in either direction", () => {
    const key = "preview/app/bld/bytecode/fn/node24.3.1-x86_64.tar.gz";
    const s3Hit = `ocel: rehydrated compile cache from ${key}: 4096 bytes in 312ms`;
    const embeddedHit = `ocel: loaded embedded compile cache from ${tarPath}: 4096 bytes in 7ms`;
    expect(bytecodeEmbeddedOutcome(s3Hit, tarPath)).toBeNull();
    expect(bytecodeRehydrateOutcome(embeddedHit, key)).toBeNull();
    expect(BYTECODE_EMBEDDED_MARKER).not.toContain(BYTECODE_S3_REHYDRATE_MARKER);
    expect(BYTECODE_S3_REHYDRATE_MARKER).not.toContain(BYTECODE_EMBEDDED_MARKER);
  });
});

describe("embeddedBytecodePath", () => {
  it("mirrors the key's basename into the artifact, minus the gzip layer", () => {
    expect(embeddedBytecodePath("preview-e2e-42/e2e-42/app/bld123/bytecode/proj--web-abc123/node24.3.1-arm64.tar.gz")).toBe(
      ".ocel/bytecode/node24.3.1-arm64.tar",
    );
    expect(embeddedBytecodePath("node24.3.1-x86_64.tar.gz")).toBe(".ocel/bytecode/node24.3.1-x86_64.tar");
  });

  it("refuses a key that names no cache tarball", () => {
    expect(embeddedBytecodePath("a/b/some-other-object.tar.gz")).toBeNull();
    expect(embeddedBytecodePath("a/b/node24.3.1-x86_64.tar")).toBeNull();
    expect(embeddedBytecodePath("")).toBeNull();
  });
});

describe("embeddedArtifactPairs", () => {
  const original = "e2e-42/web-server/abc123.zip";
  const embedded = "e2e-42/web-server/abc123-bc-deadbeefdeadb.zip";

  it("pairs a repackaged artifact with the original it extends", () => {
    expect(embeddedArtifactPairs([original, embedded])).toEqual([{ embedded, original, digest: "deadbeefdeadb" }]);
  });

  it("reports a repackaged artifact whose original is gone rather than dropping it", () => {
    expect(embeddedArtifactPairs([embedded])).toEqual([{ embedded, original: null, digest: "deadbeefdeadb" }]);
  });

  it("finds none when the deploy embedded nothing", () => {
    expect(embeddedArtifactPairs([original, "e2e-42/other/def456.zip"])).toEqual([]);
    expect(embeddedArtifactPairs([])).toEqual([]);
    expect(embeddedArtifactPairs(undefined)).toEqual([]);
  });
});

describe("warmSummaryOutcome", () => {
  const summary = { state: "published", entries: 12, loaded: 12, stoppedBy: "complete", bytes: 4096, key: "k", uploaded: true };

  it("reads the summary out of the membrane's stderr line", () => {
    const message = `${WARM_SUMMARY_MARKER} ${JSON.stringify(summary)}`;
    expect(warmSummaryOutcome(message)).toEqual({ kind: "summary", summary, message });
  });

  it("ignores every other log line", () => {
    expect(warmSummaryOutcome("START RequestId: abc")).toBeNull();
    expect(warmSummaryOutcome(undefined)).toBeNull();
  });

  it("reports a marked line whose JSON was truncated rather than dropping it", () => {
    const outcome = warmSummaryOutcome(`${WARM_SUMMARY_MARKER} {"state":"publis`);
    expect(outcome.kind).toBe("unreadable");
    expect(outcome.reason).toBeTruthy();
  });
});

describe("warmCoverage", () => {
  const key = "preview-e2e-42/e2e-42/app/bld123/bytecode/proj--web-abc123/node24.3.1-x86_64.tar.gz";
  const published = { state: "published", entries: 12, loaded: 12, stoppedBy: "complete", bytes: 4096, key, uploaded: true };

  it("proves a whole bundle when this pass's own PUT created the object", () => {
    expect(warmCoverage(published, key).kind).toBe("complete");
  });

  it("reports a walk the ceiling or the deadline cut short as partial", () => {
    expect(warmCoverage({ ...published, loaded: 7, stoppedBy: "ceiling" }, key).kind).toBe("partial");
  });

  it("refuses to believe a published state that claims no upload", () => {
    expect(warmCoverage({ ...published, uploaded: false }, key).kind).toBe("failed");
  });

  it("proves nothing from an already-cached pass", () => {
    expect(warmCoverage({ state: "already-cached" }, key).kind).toBe("unproven");
  });

  it("sets a summary naming another build's key aside", () => {
    expect(warmCoverage({ ...published, key: "other/build/node24.3.1-x86_64.tar.gz" }, key).kind).toBe("other-build");
  });

  it("reports a node app's whole-graph publish as its own, distinct, complete verdict", () => {
    const verdict = warmCoverage({ state: "published", uploaded: true, bytes: 4096, key, wholeGraphLoadedAtInit: true }, key);
    expect(verdict.kind).toBe("whole-graph");
    expect(verdict.detail).toContain("no entry table to walk");
  });
});

describe("strongestCoverage", () => {
  it("takes the pass that actually wrote the object over one that found it there", () => {
    const complete = { kind: "complete", detail: "" };
    expect(strongestCoverage([{ kind: "unproven", detail: "" }, complete])).toBe(complete);
  });

  it("reports nothing seen as null", () => {
    expect(strongestCoverage([])).toBeNull();
  });

  it("ranks a node app's whole-graph verdict above partial and alongside complete", () => {
    const wholeGraph = { kind: "whole-graph", detail: "" };
    expect(strongestCoverage([{ kind: "partial", detail: "" }, wholeGraph])).toBe(wholeGraph);
  });
});

describe("summarizeOutcomes", () => {
  it("counts outcomes by kind", () => {
    expect(summarizeOutcomes([{ kind: "miss" }, { kind: "fetch-error" }, { kind: "miss" }])).toBe("2 miss, 1 fetch-error");
  });

  it("says so when nothing related was seen at all", () => {
    expect(summarizeOutcomes([])).toBe("0 related lines");
  });
});

describe("logWindowVerdict", () => {
  const pageLimit = 1000;

  it("reads a window that was polled cleanly to its end", () => {
    const verdict = logWindowVerdict({ attempts: 5, failures: 0, confirmed: true, events: 12, pageLimit });
    expect(verdict.kind).toBe("read");
  });

  it("reports a window never read to its end as unread, however many polls succeeded", () => {
    const verdict = logWindowVerdict({ attempts: 13, failures: 1, confirmed: false, events: 0, pageLimit });
    expect(verdict.kind).toBe("unread");
  });

  it("reports a full page as truncated, because a line could have been dropped off its end", () => {
    const verdict = logWindowVerdict({ attempts: 2, failures: 0, confirmed: true, events: pageLimit, pageLimit });
    expect(verdict.kind).toBe("truncated");
  });
});

describe("tail", () => {
  it("keeps the last N lines", () => {
    expect(tail("a\nb\nc\nd", 2)).toBe("c\nd");
  });

  it("returns everything when there are fewer lines than requested", () => {
    expect(tail("a\nb", 5)).toBe("a\nb");
  });
});
