// Pure helpers shared by every deployment-e2e harness (scripts/e2e-next,
// scripts/e2e-node, and any future one). Each harness runs its lifecycle
// scripts as separate processes, so everything they share travels through
// files in the temp/smoke app directory rather than memory.
//
// What lives here is framework-agnostic: project/slug derivation, the
// ocel.config.ts renderer, the bytecode-cache key shape
// (cloud/aws/deploy/bytecode.go) and the CloudWatch line matching for its two
// read legs and the warm pass (cloud/aws/cmd/lambdanode/bootstrap/{bytecode,
// warm}.go), plus the tar/zip readers the bytecode assertions use to look
// inside what a deploy actually produced. A harness's own framework-specific
// probes (Next's ISR/tag/golden routes, a plain node app's health route) stay
// in that harness's own lib.mjs, which re-exports this module's surface
// alongside them — see scripts/e2e-next/lib.mjs for the pattern.

import { createHash } from "node:crypto";

/** A valid single DNS label, per RFC 1035 (mirrors cli/internal/previewid). */
export const DNS_LABEL = /^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/;

/** The file a harness's deploy script persists this app's identity to. */
export const STATE_FILE = ".ocel-e2e.json";

/** The file every byte of a deploy's output is redirected to. */
export const BUILD_LOG_FILE = ".adapter-build.log";

/** The CLI's machine-readable deploy result, relative to the app directory. */
export const DEPLOY_RESULT_FILE = ".ocel/deploy-result.json";

/** How many hex characters of the app dir's hash disambiguate one deploy. */
const HASH_LEN = 8;

/** Run-id token used when a harness's scripts run outside GitHub Actions. */
export const LOCAL_RUN_ID = "local";

/**
 * The longest slug a preview pointer named after it can still be served on: the
 * route hostname's first label is the pointer plus an 11-character suffix
 * (cloud/aws/deploy/previewhost.go) and a DNS label holds 63, which is the same
 * cap `ocel preview up --name` enforces (cli/internal/previewid).
 */
export const MAX_SLUG_LEN = 52;

/**
 * projectSlug derives the identity that isolates one deployed app: the `slug`
 * of the Ocel project it deploys into, which is also the name of the
 * persistent preview pointer inside that project. A project is the unit
 * concurrent deploys must not share — it namespaces the Pulumi stacks, the
 * deployments store, the asset prefixes and the Cloudflare worker scripts and
 * routes — so every deployed app gets its own.
 *
 * It must be a valid single DNS label within MAX_SLUG_LEN (it becomes the
 * preview subdomain when a worker fronts the app), unique per app, and stable
 * for a given run and directory: a harness's cleanup re-derives it when its
 * state file is lost, and a slug it cannot re-derive is infrastructure nothing
 * will ever tear down.
 */
export function projectSlug({ runId, dir }) {
  const run = sanitizeToken(String(runId ?? "")) || LOCAL_RUN_ID;
  const hash = createHash("sha256").update(String(dir ?? "")).digest("hex").slice(0, HASH_LEN);
  // "e2e-" gives the label its required letter start; the run token is capped
  // so run + hash can never push the slug past MAX_SLUG_LEN.
  const maxRun = MAX_SLUG_LEN - "e2e-".length - 1 - HASH_LEN;
  return `e2e-${run.slice(0, maxRun)}-${hash}`;
}

function sanitizeToken(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * renderOcelConfig is the ocel.config.ts a harness writes into its deployed
 * app. `slug` is that app's own project (projectSlug) — that is what gives it
 * its own worker scripts and asset prefixes — and `apps` is rendered
 * verbatim, one literal object per entry, so a caller controls exactly which
 * keys appear and in what order (a framework harness's own wrapper is what
 * fixes those). Pure: a harness's cleanup script can re-render it from the
 * same arguments when a failed deploy left no config to tear down.
 * `ocel` and `@ocel/provider-aws` must resolve from the app directory — the
 * config is bundled and executed from there.
 */
export function renderOcelConfig({ slug, previewDomain, apps }) {
  const lines = [
    `import { defineConfig } from "ocel/config";`,
    `import awsProvider from "@ocel/provider-aws";`,
    ``,
    `// Generated by an e2e harness. Do not edit.`,
    `export default defineConfig({`,
    `  slug: ${JSON.stringify(slug)},`,
    `  provider: awsProvider(),`,
  ];
  if (previewDomain) {
    lines.push(`  domains: {`, `    preview: ${JSON.stringify(previewDomain)},`, `  },`);
  }
  lines.push(`  apps: [${(apps ?? []).map(renderAppLiteral).join(", ")}],`, `});`, ``);
  return lines.join("\n");
}

// renderAppLiteral renders one `apps` entry as `{ key: "value", ... }`, in the
// key order the caller passed — JSON.stringify would compact it and drop the
// spacing every harness's tests (and a human reading the rendered file) expect.
function renderAppLiteral(app) {
  return `{ ${Object.entries(app ?? {})
    .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
    .join(", ")} }`;
}

/**
 * deployURL is the URL a harness reads back from a deploy: the CLI's own
 * result document. A successful deploy that featured no app URL is a failure
 * for e2e purposes: the harness has nothing to test.
 */
export function deployURL(result) {
  const url = result?.appUrls?.[0];
  if (!url) {
    throw new Error(`deploy result carries no app URL: ${JSON.stringify(result ?? null)}`);
  }
  return url;
}

/**
 * lambdaFunctionNames maps a resourcegroupstaggingapi get-resources response
 * to the names of the Lambda functions it found. Function names are
 * Pulumi-autonamed, so the ocel tags (cloud/aws/deploy/function.go) are the
 * only way to find them.
 */
export function lambdaFunctionNames(response) {
  return (response?.ResourceTagMappingList ?? [])
    .map((entry) => /^arn:aws:lambda:[^:]*:[^:]*:function:([^:]+)/.exec(entry?.ResourceARN ?? ""))
    .filter(Boolean)
    .map((match) => match[1]);
}

/**
 * lambdaLogGroups maps a resourcegroupstaggingapi get-resources response into
 * the CloudWatch log groups of the Lambdas it found; the caller filters on
 * `ocel:project`, this app's own slug being what is unique per deploy.
 */
export function lambdaLogGroups(response) {
  return lambdaFunctionNames(response).map((name) => `/aws/lambda/${name}`);
}

/**
 * envSegment is the environment segment of an app's asset-key prefix. Mirrors
 * envSegment in cloud/aws/server/server.go: "prod" for a production deploy,
 * "preview-<identity>" for a preview one — the same token a deploy's Pulumi
 * stack name also carries.
 */
export function envSegment(environment) {
  if (environment?.class === "preview") {
    return `preview-${environment?.identity ?? ""}`;
  }
  return "prod";
}

/**
 * appAssetPrefix is the S3 key prefix one app's assets — and, when it caches,
 * its bytecode archive — live under. Mirrors appAssetPrefixFor in
 * cloud/aws/deploy/prerender.go: <env>/<slug>/<app>/<buildId>. `app` is
 * assumed to already be a valid worker name (sanitizeWorkerName's job on the
 * Go side); a harness declaring its smoke app under a fixed, already-valid
 * name needs no sanitizing here.
 */
export function appAssetPrefix({ environment, slug, app, buildId }) {
  return [envSegment(environment), slug, app, buildId].join("/");
}

/**
 * bytecodeAppNamespace is the S3 prefix every one of an app's bytecode
 * caches lives under, one level above the content-hash segment that picks
 * which one. Mirrors bytecodeAppNamespace in cloud/aws/deploy/bytecode.go:
 * bytecode/<env>/<slug>/<app>. `app` is assumed to already be a valid worker
 * name — the same assumption appAssetPrefix makes, for the same reason.
 *
 * Deliberately its own namespace, not appAssetPrefix's build-keyed one: that
 * prefix is what prune sweeps on every build (prune.go), and a bytecode
 * cache living under it would be reaped by the very redeploy it exists to
 * speed up — see the Go doc comment on bytecodeKeyNamespace. The fixed
 * "bytecode" segment leads rather than trailing env/slug so the asset
 * bucket's expiry lifecycle rule can select every bytecode object with one
 * literal S3 prefix filter.
 */
export function bytecodeAppNamespace({ environment, slug, app }) {
  return ["bytecode", envSegment(environment), slug, app].join("/");
}

const BYTECODE_ARCHIVE_NAME = /^node(\d+\.\d+\.\d+)-([a-z0-9_]+)\.tar\.gz$/;

/**
 * bytecodeCacheKeyName parses the filename segment of a bytecode cache key —
 * everything after bytecodeCacheEntry's own prefix — into its node version
 * and arch, or null if it does not have the "node<version>-<arch>.tar.gz"
 * shape bytecodeCacheKey in bytecode.go composes. A caller lists objects
 * under the prefix and uses this to tell a real cache archive from anything
 * else that might land there, and to assert the version is the
 * three-dot-separated-numbers shape bytecode.go's canonicalNodeVersion
 * requires.
 */
export function bytecodeCacheKeyName(name) {
  const match = BYTECODE_ARCHIVE_NAME.exec(name ?? "");
  if (!match) return null;
  return { nodeVersion: match[1], arch: match[2] };
}

const BYTECODE_CACHE_ENTRY = /^([^/]+)\/(.+)$/;

/**
 * bytecodeCacheEntry reads one name found by listing bytecodeAppNamespace
 * (an S3 key with that namespace already stripped) into the content hash it
 * names, plus whatever bytecodeCacheKeyName can read out of its filename —
 * or null for anything that does not have the shape bytecodePrefixFor and
 * bytecodeCacheKey together produce: <hash>/node<version>-<arch>.tar.gz.
 *
 * Carries no function name: the key is the content hash of the function's
 * whole `.func` tree plus its runtime shape, nothing else — two functions
 * whose trees hash identically share one cache object, by design (see
 * bytecodeCacheKey's own doc comment in
 * cloud/aws/cmd/lambdanode/bootstrap/bytecode.go).
 *
 * The hash itself (hashArtifact in cloud/aws/deploy/artifact.go, a content
 * hash of the function's whole `.func` tree) is deliberately not reproduced
 * here: nothing outside a running deploy can compute it ahead of time, so the
 * caller discovers it from what is actually in the bucket rather than from a
 * second, independent hash implementation — exactly the kind of drift this
 * suite exists to catch, not add.
 */
export function bytecodeCacheEntry(name) {
  const match = BYTECODE_CACHE_ENTRY.exec(name ?? "");
  if (!match) return null;
  const [, hash, filename] = match;
  const parsed = bytecodeCacheKeyName(filename);
  if (!parsed) return null;
  return { hash, filename, ...parsed };
}

/**
 * The stderr line the S3 read leg logs on a hit, up to the key it names
 * (rehydrateCompileCache, cloud/aws/cmd/lambdanode/bootstrap/bytecode.go).
 * Exported so a caller that must prove this leg *never* ran — assert-embed.mjs,
 * where an S3 fetch means the embedded copy was not used — can look for it
 * without knowing which key an instance would have composed.
 */
export const BYTECODE_S3_REHYDRATE_MARKER = "rehydrated compile cache from ";

/**
 * The stderr line the embedded read leg logs on a hit, up to the path it names
 * (embeddedBytecodeCache, cloud/aws/cmd/lambdanode/bootstrap/bytecode.go).
 * Deliberately not a superstring or substring of BYTECODE_S3_REHYDRATE_MARKER:
 * the two legs are only distinguishable in CloudWatch because these two
 * wordings share no matchable text, and a change on the Go side that made one
 * contain the other would silently turn "read from the artifact" into "read
 * from S3" for every assertion here.
 */
export const BYTECODE_EMBEDDED_MARKER = "loaded embedded compile cache from ";

/** The env var gating the deploy-time embed pass (cloud/aws/deploy/embed.go). */
export const BYTECODE_EMBED_ENV = "OCEL_BYTECODE_EMBED";

/**
 * bytecodeEmbedEnabled mirrors the deploy's own gate: opt-in, and only the
 * literal "1". Anything else — unset, "true", "0" — is off, so an assertion
 * written for the embedded artifact skips rather than failing a deployment
 * that was never asked to embed.
 */
export function bytecodeEmbedEnabled(env) {
  return (env ?? {})[BYTECODE_EMBED_ENV] === "1";
}

/**
 * embeddedBytecodePath is the path, inside the deployed `.func` zip, that the
 * embed pass bakes the cache at key to — `.ocel/bytecode/node<version>-<arch>.tar`
 * — or null for a key that names no cache tarball.
 *
 * Both sides derive it this way, from the key rather than from a version and an
 * arch read again: embeddedTarPath (cloud/aws/deploy/embed.go) on the way in and
 * embeddedBytecodePath (bytecode.go) on the way out. Asserting the same
 * derivation from the key an independent S3 listing found is what proves the
 * match rule holds, rather than just that *some* tar was embedded.
 *
 * The stored object is gzipped and the embedded one is not — the zip container
 * compresses it instead — so this is the key's basename minus the `.gz`.
 */
export function embeddedBytecodePath(key) {
  const name = String(key ?? "").split("/").pop();
  if (!bytecodeCacheKeyName(name)) return null;
  return `.ocel/bytecode/${name.slice(0, -".gz".length)}`;
}

/**
 * bytecodeEmbeddedOutcome classifies one CloudWatch message against every line
 * the embedded read leg can emit for the tar at tarPath — the absolute
 * /var/task path the membrane logs, not the zip-relative one. Same contract as
 * bytecodeRehydrateOutcome: null for an unrelated line, and every failure mode
 * classified rather than dropped, so "the embedded leg was tried and failed" is
 * never reported as "the embedded leg never ran".
 *
 * An absent tar produces no line at all by design (an artifact built without the
 * embed pass is the ordinary case), so there is no "miss" kind here: absence is
 * the caller's to conclude from the whole window, not from any one message.
 */
export function bytecodeEmbeddedOutcome(message, tarPath) {
  const text = String(message ?? "");
  if (text.includes(`could not open the embedded compile cache at ${tarPath}:`)) {
    return { kind: "open-error", message: text };
  }
  if (text.includes(`before loading the embedded compile cache at ${tarPath}:`)) {
    return { kind: "clear-error", message: text };
  }
  if (text.includes(`could not load the embedded compile cache at ${tarPath}:`)) {
    return { kind: "load-error", message: text };
  }
  if (text.includes(`${BYTECODE_EMBEDDED_MARKER}${tarPath}:`)) {
    return { kind: "hit", message: text };
  }
  return null;
}

const EMBEDDED_ARTIFACT_KEY = /^(.*)-bc-([0-9a-f]+)\.zip$/;

/**
 * embeddedArtifactPairs picks the repackaged artifacts out of a listing of
 * artifact keys and pairs each with the original it extends. The embed pass
 * writes `<original key minus .zip>-bc-<digest>.zip` beside the original rather
 * than replacing it (embeddedArtifactKey, cloud/aws/deploy/embed.go), so both
 * objects are present afterwards and the pair is discoverable from the bucket
 * alone — nothing outside the deploy is told either key.
 *
 * `original` is null when the counterpart is missing from the listing, which is
 * a fact worth surfacing rather than a pair to drop: it means the artifact the
 * function was warmed on is gone, and the "the code changed" assertion has
 * nothing left to compare against.
 */
export function embeddedArtifactPairs(keys) {
  const all = new Set(keys ?? []);
  return (keys ?? []).flatMap((key) => {
    const match = EMBEDDED_ARTIFACT_KEY.exec(key);
    if (!match) return [];
    const original = `${match[1]}.zip`;
    return [{ embedded: key, original: all.has(original) ? original : null, digest: match[2] }];
  });
}

/**
 * bytecodeRehydrateOutcome classifies one CloudWatch log message against
 * every read-leg line rehydrateCompileCache, rehydrateBytecodeCache and
 * resolveBytecodeResolution (cloud/aws/cmd/lambdanode/bootstrap/bytecode.go)
 * can emit, or null when the message is unrelated. That file is the source
 * of truth for the literal strings matched below — a wording change there
 * must be mirrored here, or a message that used to classify silently starts
 * returning null. assert-bytecode.mjs uses this to tell a proven hit from
 * every failure mode it can only report as a symptom: matched by exact
 * substring rather than parsed, since these are the literal lines the
 * membrane emits, not a format to decode.
 *
 * The `dir`-clear failure and the two resolveBytecodeResolution off-switch
 * lines name no key — the off-switch lines because a version probe or AWS
 * config load can fail before a key is ever composed, the clear failure
 * because its format string names `dir`, not `key`, even though the key is
 * already fully composed and in hand by then — so all three are matched on
 * a keyless substring instead, the same technique as "disabled" below: none
 * of the other lines this function matches could ever produce that
 * substring, so it stays unambiguous without `key` to narrow it. Classified
 * anyway, under "disabled" and "clear-error", because a caller polling by
 * key would otherwise never learn the feature turned itself off, or failed
 * before it could even try to read, on some instance.
 */
export function bytecodeRehydrateOutcome(message, key) {
  const text = String(message ?? "");
  if (text.includes(`${BYTECODE_S3_REHYDRATE_MARKER}${key}:`)) {
    return { kind: "hit", message: text };
  }
  if (text.includes(`no compile cache at ${key} yet`)) {
    return { kind: "miss", message: text };
  }
  if (text.includes(`could not fetch the compile cache at ${key}:`)) {
    return { kind: "fetch-error", message: text };
  }
  if (text.includes(`compile cache at ${key} is`) && text.includes("skipping rehydration")) {
    return { kind: "over-ceiling", message: text };
  }
  if (text.includes(`could not rehydrate the compile cache from ${key}:`)) {
    return { kind: "extract-error", message: text };
  }
  if (text.includes(`rehydrating the compile cache from ${key} ran out of time:`)) {
    return { kind: "timeout", message: text };
  }
  if (text.includes("before rehydrating the compile cache:")) {
    return { kind: "clear-error", message: text };
  }
  if (text.includes("compile cache disabled") || text.includes("no aws config for the compile cache:")) {
    return { kind: "disabled", message: text };
  }
  return null;
}

/**
 * summarizeOutcomes turns the non-hit outcomes collected while polling into
 * "N kind, M kind" — a caller counting instances covers every failure mode the
 * *Outcome classifiers above can produce without a case list growing at the call
 * site every time one of them learns a new one.
 */
export function summarizeOutcomes(outcomes) {
  const counts = new Map();
  for (const { kind } of outcomes) counts.set(kind, (counts.get(kind) ?? 0) + 1);
  return [...counts.entries()].map(([kind, n]) => `${n} ${kind}`).join(", ") || "0 related lines";
}

/**
 * logWindowVerdict decides whether a poll loop read enough of a CloudWatch
 * window for the *absence* of a line in it to mean anything.
 *
 * A presence claim needs no such thing — one successful read that finds the line
 * settles it, and every failed read only risks a false failure. An absence claim
 * is the opposite: it is a statement about the whole window, so it is only as
 * strong as the reading of it, and a poll loop that half failed can produce a
 * clean-looking result for entirely the wrong reason.
 *
 * `filter-log-events` re-reads the window from its start every time, so one
 * successful call sees everything ingested before it and nothing after. Failures
 * *inside* the loop are therefore recoverable — a later read covers what they
 * missed — but the loop has to end on a successful read, or the newest part of
 * the window was never looked at. Hence `confirmed`: the outcome of a final read
 * taken after the loop, not of the loop as a whole.
 *
 * `events` is how many that final read returned. At `pageLimit` the response is
 * a truncated view of the window rather than the whole of it, and a line the
 * caller is claiming never appeared may simply have been paged off the end.
 */
export function logWindowVerdict({ attempts, failures, confirmed, events, pageLimit }) {
  const tried = `${attempts - failures}/${attempts} reads succeeded`;
  if (!confirmed) {
    return {
      kind: "unread",
      detail: `${tried}, and the last one did not, so the window was never read to its end`,
    };
  }
  if (events >= pageLimit) {
    return {
      kind: "truncated",
      detail: `${tried}, but the final read came back with ${events} events — the ${pageLimit}-event page maximum`,
    };
  }
  return { kind: "read", detail: `${tried}, the last of them returning all ${events} events in the window` };
}

/**
 * The stderr line a warm invocation lands its whole summary on
 * (answerWarmInvocation, cloud/aws/cmd/lambdanode/bootstrap/warm.go). The
 * deploy reads that same summary out of the invoke's response payload, but the
 * response is gone by the time anything asserts against the deployment —
 * CloudWatch is the only place it survives, which is what makes the deploy's
 * warm pass observable from outside at all.
 */
export const WARM_SUMMARY_MARKER = "ocel: warm invocation:";

/**
 * warmSummaryOutcome classifies one CloudWatch message as the warm summary the
 * membrane logged, or null when it is some other line.
 *
 * A line carrying the marker but no readable JSON is returned as "unreadable"
 * rather than dropped: that is a summary CloudWatch split or truncated, and
 * treating it as "no warm ever happened" would turn a reporting problem into a
 * claim about the deployment.
 */
export function warmSummaryOutcome(message) {
  const text = String(message ?? "");
  const at = text.indexOf(WARM_SUMMARY_MARKER);
  if (at === -1) return null;
  try {
    return { kind: "summary", summary: JSON.parse(text.slice(at + WARM_SUMMARY_MARKER.length)), message: text };
  } catch (err) {
    return { kind: "unreadable", message: text, reason: err.message };
  }
}

/**
 * warmCoverage says what one warm summary proves about the cache the build
 * ended up with. The states are warm.go's four, read for two separate claims:
 * that *this pass* is what published the object (attribution), and that what it
 * published covers the whole bundle (coverage).
 *
 * Attribution rests on the PUT being create-if-absent: exactly one writer can
 * ever create a given key, and warm.go reports that writer as
 * published/uploaded:true and every loser as already-cached. So published with
 * uploaded:true is the only reply that proves warming — not a request, not an
 * earlier run — created the object at `key`. published without uploaded:true is
 * not a weaker version of that claim but a contradiction, and is reported as a
 * failure rather than believed.
 *
 * Coverage is loaded against entries, qualified by where the walk stopped. A
 * ceiling or deadline stop is a real, reportable outcome of a bundle that is
 * too big or too slow to warm whole — "partial", for a caller to surface — not
 * a broken cache and not a proof of a complete one. A publish the membrane
 * could not account for (`uncounted`: node never reported back, or the artifact
 * has no warm capability) is "partial" for the same reason: the object landed,
 * and nothing measured what went into it. A node app that HAS no entry table —
 * loadUserApp loads the whole module graph at INIT, before a warm invocation
 * can ever reach it — reports entries:1, loaded:1 for that one unit rather than
 * leaving this uncounted; see packages/lambda-entrypoints/src/node/entrypoint.mts's
 * warmNode.
 *
 * already-cached is "unproven", never a pass: the object exists, but this pass
 * neither wrote it nor measured what is in it.
 */
export function warmCoverage(summary, key) {
  const state = summary?.state ?? "";
  const entries = summary?.entries ?? 0;
  const loaded = summary?.loaded ?? 0;
  const failures = summary?.failures ?? [];
  const stoppedBy = summary?.stoppedBy ?? "";
  const uncounted = summary?.uncounted ?? "";
  const skipped = summary?.skipped ?? [];
  const walk = uncounted
    ? `entry counts unknown (${uncounted}), ${summary?.bytes ?? 0} bytes`
    : `${loaded}/${entries} entries loaded, ${failures.length} failed, ` +
      `${summary?.skippedCount ?? 0} skipped${skipped.length ? ` (${skipped.join(", ")})` : ""}, ` +
      `stopped by ${stoppedBy || "(unreported)"}, ${summary?.bytes ?? 0} bytes`;

  // A summary naming another key is another build's, and says nothing either
  // way about this one — the key carries the build id, so the two can never be
  // confused for each other.
  if (summary?.key && key && summary.key !== key) {
    return { kind: "other-build", detail: `names ${summary.key}, not ${key}` };
  }

  switch (state) {
    case "published":
      if (summary?.uploaded !== true) {
        return { kind: "failed", detail: `published without uploaded:true (${walk}) — the two cannot both be true` };
      }
      if (uncounted) {
        return { kind: "partial", detail: walk };
      }
      if (entries === 0) {
        return { kind: "failed", detail: `published a cache for a bundle reporting no entries at all (${walk})` };
      }
      if (loaded !== entries || (stoppedBy && stoppedBy !== "complete")) {
        return { kind: "partial", detail: walk };
      }
      return { kind: "complete", detail: walk };
    case "already-cached":
      return {
        kind: "unproven",
        detail: entries
          ? `the walk ran (${walk}) but another writer had already created the object`
          : "the instance started on a cache that already existed, so nothing was walked or written",
      };
    case "disabled":
      return { kind: "failed", detail: `nothing to warm: ${summary?.error ?? "(no reason given)"}` };
    case "failed":
      return { kind: "failed", detail: `${walk}: ${summary?.error ?? "(no reason given)"}` };
    default:
      return { kind: "failed", detail: `unrecognized warm state ${JSON.stringify(state)}` };
  }
}

/**
 * How much a coverage verdict proves, weakest first. A window can hold more
 * than one summary for the same key — a redeployed build warms again, and that
 * second pass legitimately answers already-cached — so a caller takes the
 * strongest rather than the first or the last: the object is one object, and
 * the pass that actually wrote it is the one that says what is in it.
 */
const WARM_COVERAGE_RANK = ["failed", "unproven", "partial", "complete"];

export function strongestCoverage(verdicts) {
  return (verdicts ?? []).reduce((best, verdict) => {
    if (!best) return verdict;
    return WARM_COVERAGE_RANK.indexOf(verdict.kind) > WARM_COVERAGE_RANK.indexOf(best.kind) ? verdict : best;
  }, null);
}

const TAR_BLOCK_SIZE = 512;

function tarString(block, start, length) {
  const slice = block.subarray(start, start + length);
  const end = slice.indexOf(0);
  return Buffer.from(end === -1 ? slice : slice.subarray(0, end)).toString("utf8");
}

function tarHeaderChecksum(block) {
  let sum = 0;
  for (let i = 0; i < block.length; i++) {
    sum += i >= 148 && i < 156 ? 0x20 : block[i];
  }
  return sum;
}

/**
 * tarEntryNames walks an uncompressed tar buffer and returns each entry's
 * name (its ustar `prefix` field joined on, when set). It exists so a
 * bytecode assertion can prove the membrane's upload is a real archive rather
 * than truncated or empty bytes, without a dependency: every header's checksum
 * is verified, and a buffer that runs out mid-header or never reaches the
 * two-zero-block end-of-archive marker throws rather than silently returning a
 * partial entry list.
 */
export function tarEntryNames(buffer) {
  const names = [];
  let offset = 0;
  let sawEnd = false;
  while (offset < buffer.length) {
    if (offset + TAR_BLOCK_SIZE > buffer.length) {
      throw new Error(`truncated tar header at byte ${offset} of ${buffer.length}`);
    }
    const header = buffer.subarray(offset, offset + TAR_BLOCK_SIZE);
    if (header.every((byte) => byte === 0)) {
      sawEnd = true;
      break;
    }
    const rawChecksum = tarString(header, 148, 8).trim();
    const wantChecksum = rawChecksum ? parseInt(rawChecksum, 8) : NaN;
    if (!Number.isInteger(wantChecksum) || tarHeaderChecksum(header) !== wantChecksum) {
      throw new Error(`tar header at byte ${offset} fails its checksum`);
    }
    const name = tarString(header, 0, 100);
    const prefix = tarString(header, 345, 155);
    const size = parseInt(tarString(header, 124, 12).trim() || "0", 8) || 0;
    names.push(prefix ? `${prefix}/${name}` : name);
    offset += TAR_BLOCK_SIZE + Math.ceil(size / TAR_BLOCK_SIZE) * TAR_BLOCK_SIZE;
  }
  if (!sawEnd) {
    throw new Error("tar has no end-of-archive marker; the archive is truncated");
  }
  return names;
}

const ZIP_EOCD_SIGNATURE = 0x06054b50;
const ZIP_EOCD_MIN_SIZE = 22;
const ZIP64_LOCATOR_SIGNATURE = 0x07064b50;
const ZIP64_LOCATOR_SIZE = 20;
const ZIP64_EOCD_SIGNATURE = 0x06064b50;
const ZIP_CENTRAL_SIGNATURE = 0x02014b50;
const ZIP_CENTRAL_MIN_SIZE = 46;

/**
 * zipEntryNames reads a zip's central directory and returns every entry's
 * name. It exists so an embed assertion can look inside the package Lambda
 * actually deployed — fetched from the presigned Code.Location — without a
 * dependency and without shelling out to unzip(1).
 *
 * It reads the central directory rather than scanning for local headers
 * because only the central directory is authoritative: a local header can be
 * a leftover from a truncated write, and the embed pass copies existing
 * entries through zip.Writer.Copy (cloud/aws/deploy/embed.go), which rewrites
 * the central directory and nothing else.
 *
 * Every malformed input throws rather than returning a short list. The one
 * claim built on this is that a named entry is *absent*, and a parser that
 * quietly stopped early would make that claim out of its own bug.
 */
export function zipEntryNames(buffer) {
  const eocd = findZipEOCD(buffer);
  let count = buffer.readUInt16LE(eocd + 10);
  let start = buffer.readUInt32LE(eocd + 16);

  // A zip past 65535 entries or 4 GiB parks the real values in a zip64 record
  // and leaves these fields saturated. A pnpm node_modules tree reaches the
  // entry count long before the size, so this is a real case here, not
  // defensive padding.
  if (count === 0xffff || start === 0xffffffff) {
    const locator = eocd - ZIP64_LOCATOR_SIZE;
    if (locator < 0 || buffer.readUInt32LE(locator) !== ZIP64_LOCATOR_SIGNATURE) {
      throw new Error("zip end-of-central-directory is saturated but carries no zip64 locator");
    }
    const zip64 = asIndex(buffer.readBigUInt64LE(locator + 8), buffer.length, "zip64 end-of-central-directory offset");
    if (buffer.readUInt32LE(zip64) !== ZIP64_EOCD_SIGNATURE) {
      throw new Error(`no zip64 end-of-central-directory record at byte ${zip64}`);
    }
    count = asIndex(buffer.readBigUInt64LE(zip64 + 32), Number.MAX_SAFE_INTEGER, "zip64 entry count");
    start = asIndex(buffer.readBigUInt64LE(zip64 + 48), buffer.length, "zip64 central directory offset");
  }

  const names = [];
  let offset = start;
  for (let i = 0; i < count; i++) {
    if (offset + ZIP_CENTRAL_MIN_SIZE > buffer.length) {
      throw new Error(`zip central directory entry ${i} runs past the end of the buffer at byte ${offset}`);
    }
    if (buffer.readUInt32LE(offset) !== ZIP_CENTRAL_SIGNATURE) {
      throw new Error(`zip central directory entry ${i} at byte ${offset} has no central-file-header signature`);
    }
    const nameLen = buffer.readUInt16LE(offset + 28);
    const extraLen = buffer.readUInt16LE(offset + 30);
    const commentLen = buffer.readUInt16LE(offset + 32);
    const nameAt = offset + ZIP_CENTRAL_MIN_SIZE;
    if (nameAt + nameLen > buffer.length) {
      throw new Error(`zip central directory entry ${i} names ${nameLen} bytes past the end of the buffer`);
    }
    names.push(buffer.toString("utf8", nameAt, nameAt + nameLen));
    offset = nameAt + nameLen + extraLen + commentLen;
  }
  return names;
}

// The end-of-central-directory record is last but variable-length: its trailing
// comment can be up to 65535 bytes, so it is found by scanning back rather than
// read at a fixed offset. Scanning from the end takes the *last* candidate,
// which is the real one even when an entry's contents happen to hold the same
// four bytes.
function findZipEOCD(buffer) {
  const floor = Math.max(0, buffer.length - ZIP_EOCD_MIN_SIZE - 0xffff);
  for (let at = buffer.length - ZIP_EOCD_MIN_SIZE; at >= floor; at--) {
    if (buffer.readUInt32LE(at) === ZIP_EOCD_SIGNATURE) return at;
  }
  throw new Error(`no zip end-of-central-directory record in ${buffer.length} bytes; this is not a zip`);
}

function asIndex(value, limit, what) {
  if (value > BigInt(limit)) throw new Error(`${what} (${value}) is past the end of the buffer`);
  return Number(value);
}

export function tail(text, maxLines) {
  const lines = text.split("\n");
  return lines.slice(Math.max(0, lines.length - maxLines)).join("\n");
}
