syntax = "proto3";
package common.environment.v1;

option go_package = "github.com/ocelhq/ocel/pkg/proto/common/environment/v1;environmentv1";

import "buf/validate/validate.proto";

enum Tier {
  TIER_UNSPECIFIED = 0;
  TIER_PREVIEW = 1;
  TIER_PRODUCTION = 2;
}

enum Lifecycle {
  LIFECYCLE_UNSPECIFIED = 0;
  LIFECYCLE_EPHEMERAL = 1;
  LIFECYCLE_PERSISTENT = 2;
}

message Environment {
  Tier tier = 1 [(buf.validate.field).enum.defined_only = true];

  Lifecycle lifecycle = 2 [(buf.validate.field).enum.defined_only = true];

  string identity = 3;
}
