import { createHash } from "node:crypto";
import { basename, join, relative } from "node:path";

export const DNS_LABEL = /^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/;

export const STATE_FILE = ".ocel-e2e.json";

export const BUILD_LOG_FILE = ".adapter-build.log";

export const DEPLOY_RESULT_FILE = join(".ocel", "deploy-result.json");

const LOCAL_RUN_ID = "local";

export const PREVIEW_ROOT_STACK_PARAM_PREFIX = "/ocel/rootstack-preview/";

export const SLUG_PREFIX = "e2e-";

export const APP_NAME = "app";

export const MAX_SLUG_LEN = 63 - "ocel-".length - "-preview".length;

export const SKIP_DRIFT_CHECK_ENV = Object.freeze({
  OCEL_SKIP_EDGE_RECONCILE: "1",
  OCEL_SKIP_TEARDOWN_REFRESH: "1",
});

export function withoutSkipDriftChecks(env) {
  const out = { ...env };
  for (const name of Object.keys(SKIP_DRIFT_CHECK_ENV)) {
    delete out[name];
  }
  return out;
}

export function projectSlug({ runId }) {
  const run = sanitizeToken(String(runId ?? "")) || LOCAL_RUN_ID;
  const maxRun = MAX_SLUG_LEN - SLUG_PREFIX.length;
  return SLUG_PREFIX + run.slice(0, maxRun).replace(/-+$/, "");
}

export const REF_HINT_LEN = 12;

export const REF_HASH_LEN = 8;

export function previewRef({ dir }) {
  const normalized = String(dir ?? "").trim().replace(/\/+$/, "");
  if (!normalized) {
    throw new Error("previewRef needs a directory: neither NEXT_TEST_DIR nor a working directory was set");
  }
  const hint = sanitizeToken(basename(normalized)).slice(0, REF_HINT_LEN).replace(/-+$/, "");
  const hash = createHash("sha256").update(normalized).digest("hex").slice(0, REF_HASH_LEN);
  return hint ? `${hint}-${hash}` : hash;
}

export function projectSlugForRun() {
  return projectSlug({ runId: process.env.GITHUB_RUN_ID });
}

export function previewRefForApp(appDir) {
  return previewRef({ dir: process.env.NEXT_TEST_DIR || appDir });
}

export function strandedProjectSlugs(parameterNames, keepSlug) {
  const slugs = (parameterNames ?? [])
    .map((name) => String(name ?? ""))
    .filter((name) => name.startsWith(PREVIEW_ROOT_STACK_PARAM_PREFIX))
    .map((name) => name.slice(PREVIEW_ROOT_STACK_PARAM_PREFIX.length))
    .filter((slug) => slug.startsWith(SLUG_PREFIX) && slug !== keepSlug);
  return [...new Set(slugs)].sort();
}

function sanitizeToken(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function renderOcelConfig({ slug }) {
  return [
    `import { defineConfig } from "ocel/config";`,
    `import awsProvider from "@ocel/provider-aws";`,
    ``,
    `// Generated by scripts/e2e-next/deploy.mjs. Do not edit.`,
    `export default defineConfig({`,
    `  slug: ${JSON.stringify(slug)},`,
    `  provider: awsProvider(),`,
    `  apps: [{ name: ${JSON.stringify(APP_NAME)}, path: ".", framework: "next" }],`,
    `});`,
    ``,
  ].join("\n");
}

export function withBuildScript(pkg) {
  if (pkg.scripts?.build) {
    return pkg;
  }
  return { ...pkg, scripts: { ...pkg.scripts, build: "next build" } };
}

export const TYPESCRIPT_PIN = "^5";

export function withPinnedTypeScript(pkg) {
  const patched = { ...pkg };
  let changed = false;

  for (const field of ["dependencies", "devDependencies"]) {
    const range = pkg[field]?.typescript;
    if (range && range !== TYPESCRIPT_PIN) {
      patched[field] = { ...pkg[field], typescript: TYPESCRIPT_PIN };
      changed = true;
    }
  }

  if (!pkg.dependencies?.typescript && !pkg.devDependencies?.typescript) {
    patched.devDependencies = { ...pkg.devDependencies, typescript: TYPESCRIPT_PIN };
    changed = true;
  }

  if (pkg.overrides?.typescript !== TYPESCRIPT_PIN) {
    patched.overrides = { ...pkg.overrides, typescript: TYPESCRIPT_PIN };
    changed = true;
  }

  if (pkg.pnpm?.overrides?.typescript !== TYPESCRIPT_PIN) {
    patched.pnpm = { ...pkg.pnpm, overrides: { ...pkg.pnpm?.overrides, typescript: TYPESCRIPT_PIN } };
    changed = true;
  }

  return changed ? patched : pkg;
}

export const ISR_ROUTE = "/isr";
export const ISR_REVALIDATE_SECONDS = 5;

export function isrToken(html) {
  return /isr-token:(?:<!--.*?-->)?(\d+)/.exec(String(html ?? ""))?.[1] ?? null;
}

export const TAG_PROBE_ROUTE = "/api/revalidate-tag";

export function tagProbeTag(stamp) {
  return `ocel-publisher-probe-${stamp}`;
}

export const GOLDEN_ROUTE = "/golden";
export const GOLDEN_MARKER = "golden-body:v1";

export const GOLDEN_REVALIDATE_SECONDS = 3;

export const PREFETCH_PURPOSE_HEADER = "purpose";
export const PREFETCH_PURPOSE_VALUE = "prefetch";

export const GOLDEN_VOLATILE_HEADERS = new Set([
  "date",
  "age",
  "x-nextjs-cache",
  "x-ocel-cache",
  "x-vercel-cache",
  "cf-ray",
  "cf-cache-status",
  "x-amzn-requestid",
  "x-amzn-trace-id",
  "x-amzn-remapped-date",
  "server-timing",
  "report-to",
  "nel",
  "alt-svc",
  "connection",
  "keep-alive",
  "transfer-encoding",
  "content-encoding",
  "content-length",
]);

function headerMap(headers) {
  const entries =
    typeof headers?.entries === "function" ? [...headers.entries()] : Object.entries(headers ?? {});
  const map = new Map();
  for (const [name, value] of entries) {
    const lower = String(name).toLowerCase();
    if (GOLDEN_VOLATILE_HEADERS.has(lower)) continue;
    map.set(lower, String(value));
  }
  return map;
}

export function goldenDifferences(withHeader, without) {
  const differences = [];
  if (withHeader?.status !== without?.status) {
    differences.push(`status: with=${withHeader?.status} without=${without?.status}`);
  }
  if (withHeader?.body !== without?.body) {
    differences.push(
      `body: ${byteDiff(String(withHeader?.body ?? ""), String(without?.body ?? ""))}`,
    );
  }
  const a = headerMap(withHeader?.headers);
  const b = headerMap(without?.headers);
  for (const name of [...new Set([...a.keys(), ...b.keys()])].sort()) {
    if (a.get(name) !== b.get(name)) {
      differences.push(`header ${name}: with=${a.get(name) ?? "(absent)"} without=${b.get(name) ?? "(absent)"}`);
    }
  }
  return differences;
}

function byteDiff(a, b) {
  if (a.length !== b.length) return `lengths ${a.length} vs ${b.length}`;
  const at = [...a].findIndex((char, index) => char !== b[index]);
  return `differs at offset ${at}: ${JSON.stringify(a.slice(at, at + 40))} vs ${JSON.stringify(b.slice(at, at + 40))}`;
}

export function deployURL(result) {
  const url = result?.appUrls?.[0];
  if (!url) {
    throw new Error(`deploy result carries no app URL: ${JSON.stringify(result ?? null)}`);
  }
  return url;
}

export function markerLines({ buildId, promotionId }) {
  return [
    `BUILD_ID: ${buildId || "undefined"}`,
    `DEPLOYMENT_ID: ${promotionId || "undefined"}`,
    `IMMUTABLE_ASSET_TOKEN: undefined`,
  ];
}

export function lambdaFunctionNames(response) {
  return (response?.ResourceTagMappingList ?? [])
    .map((entry) => /^arn:aws:lambda:[^:]*:[^:]*:function:([^:]+)/.exec(entry?.ResourceARN ?? ""))
    .filter(Boolean)
    .map((match) => match[1]);
}

export function lambdaLogGroups(response) {
  return lambdaFunctionNames(response).map((name) => `/aws/lambda/${name}`);
}

export function envSegment(environment) {
  if (environment?.class === "preview") {
    return `preview-${environment?.identity ?? ""}`;
  }
  return "prod";
}

export function appAssetPrefix({ environment, slug, app, buildId }) {
  return [envSegment(environment), slug, app, buildId].join("/");
}

export function bytecodeCacheKeyPrefix({ prefix, functionName }) {
  return `${prefix}/bytecode/${functionName}/`;
}

const BYTECODE_ARCHIVE_NAME = /^node(\d+\.\d+\.\d+)-([a-z0-9_]+)\.tar\.gz$/;

export function bytecodeCacheKeyName(name) {
  const match = BYTECODE_ARCHIVE_NAME.exec(name ?? "");
  if (!match) return null;
  return { nodeVersion: match[1], arch: match[2] };
}

export const BYTECODE_S3_REHYDRATE_MARKER = "rehydrated compile cache from ";

export const BYTECODE_EMBEDDED_MARKER = "loaded embedded compile cache from ";

export const BYTECODE_EMBED_ENV = "OCEL_BYTECODE_EMBED";

export function bytecodeEmbedEnabled(env) {
  return (env ?? {})[BYTECODE_EMBED_ENV] === "1";
}

export function embeddedBytecodePath(key) {
  const name = String(key ?? "").split("/").pop();
  if (!bytecodeCacheKeyName(name)) return null;
  return `.ocel/bytecode/${name.slice(0, -".gz".length)}`;
}

export function bytecodeEmbeddedOutcome(message, tarPath) {
  const text = String(message ?? "");
  if (text.includes(`could not open the embedded compile cache at ${tarPath}:`)) {
    return { kind: "open-error", message: text };
  }
  if (text.includes(`before loading the embedded compile cache at ${tarPath}:`)) {
    return { kind: "clear-error", message: text };
  }
  if (text.includes(`could not load the embedded compile cache at ${tarPath}:`)) {
    return { kind: "load-error", message: text };
  }
  if (text.includes(`${BYTECODE_EMBEDDED_MARKER}${tarPath}:`)) {
    return { kind: "hit", message: text };
  }
  return null;
}

const EMBEDDED_ARTIFACT_KEY = /^(.*)-bc-([0-9a-f]+)\.zip$/;

export function embeddedArtifactPairs(keys) {
  const all = new Set(keys ?? []);
  return (keys ?? []).flatMap((key) => {
    const match = EMBEDDED_ARTIFACT_KEY.exec(key);
    if (!match) return [];
    const original = `${match[1]}.zip`;
    return [{ embedded: key, original: all.has(original) ? original : null, digest: match[2] }];
  });
}

export function bytecodeRehydrateOutcome(message, key) {
  const text = String(message ?? "");
  if (text.includes(`${BYTECODE_S3_REHYDRATE_MARKER}${key}:`)) {
    return { kind: "hit", message: text };
  }
  if (text.includes(`no compile cache at ${key} yet`)) {
    return { kind: "miss", message: text };
  }
  if (text.includes(`could not fetch the compile cache at ${key}:`)) {
    return { kind: "fetch-error", message: text };
  }
  if (text.includes(`compile cache at ${key} is`) && text.includes("skipping rehydration")) {
    return { kind: "over-ceiling", message: text };
  }
  if (text.includes(`could not rehydrate the compile cache from ${key}:`)) {
    return { kind: "extract-error", message: text };
  }
  if (text.includes(`rehydrating the compile cache from ${key} ran out of time:`)) {
    return { kind: "timeout", message: text };
  }
  if (text.includes("before rehydrating the compile cache:")) {
    return { kind: "clear-error", message: text };
  }
  if (text.includes("compile cache disabled") || text.includes("no aws config for the compile cache:")) {
    return { kind: "disabled", message: text };
  }
  return null;
}

export function summarizeOutcomes(outcomes) {
  const counts = new Map();
  for (const { kind } of outcomes) counts.set(kind, (counts.get(kind) ?? 0) + 1);
  return [...counts.entries()].map(([kind, n]) => `${n} ${kind}`).join(", ") || "0 related lines";
}

export function logWindowVerdict({ attempts, failures, confirmed, events, pageLimit }) {
  const tried = `${attempts - failures}/${attempts} reads succeeded`;
  if (!confirmed) {
    return {
      kind: "unread",
      detail: `${tried}, and the last one did not, so the window was never read to its end`,
    };
  }
  if (events >= pageLimit) {
    return {
      kind: "truncated",
      detail: `${tried}, but the final read came back with ${events} events — the ${pageLimit}-event page maximum`,
    };
  }
  return { kind: "read", detail: `${tried}, the last of them returning all ${events} events in the window` };
}

export const WARM_SUMMARY_MARKER = "ocel: warm invocation:";

export function warmSummaryOutcome(message) {
  const text = String(message ?? "");
  const at = text.indexOf(WARM_SUMMARY_MARKER);
  if (at === -1) return null;
  try {
    return { kind: "summary", summary: JSON.parse(text.slice(at + WARM_SUMMARY_MARKER.length)), message: text };
  } catch (err) {
    return { kind: "unreadable", message: text, reason: err.message };
  }
}

export function warmCoverage(summary, key) {
  const state = summary?.state ?? "";
  const entries = summary?.entries ?? 0;
  const loaded = summary?.loaded ?? 0;
  const failures = summary?.failures ?? [];
  const stoppedBy = summary?.stoppedBy ?? "";
  const uncounted = summary?.uncounted ?? "";
  const skipped = summary?.skipped ?? [];
  const walk = uncounted
    ? `entry counts unknown (${uncounted}), ${summary?.bytes ?? 0} bytes`
    : `${loaded}/${entries} entries loaded, ${failures.length} failed, ` +
      `${summary?.skippedCount ?? 0} skipped${skipped.length ? ` (${skipped.join(", ")})` : ""}, ` +
      `stopped by ${stoppedBy || "(unreported)"}, ${summary?.bytes ?? 0} bytes`;

  if (summary?.key && key && summary.key !== key) {
    return { kind: "other-build", detail: `names ${summary.key}, not ${key}` };
  }

  switch (state) {
    case "published":
      if (summary?.uploaded !== true) {
        return { kind: "failed", detail: `published without uploaded:true (${walk}) — the two cannot both be true` };
      }
      if (uncounted) {
        return { kind: "partial", detail: walk };
      }
      if (entries === 0) {
        return { kind: "failed", detail: `published a cache for a bundle reporting no entries at all (${walk})` };
      }
      if (loaded !== entries || (stoppedBy && stoppedBy !== "complete")) {
        return { kind: "partial", detail: walk };
      }
      return { kind: "complete", detail: walk };
    case "already-cached":
      return {
        kind: "unproven",
        detail: entries
          ? `the walk ran (${walk}) but another writer had already created the object`
          : "the instance started on a cache that already existed, so nothing was walked or written",
      };
    case "disabled":
      return { kind: "failed", detail: `nothing to warm: ${summary?.error ?? "(no reason given)"}` };
    case "failed":
      return { kind: "failed", detail: `${walk}: ${summary?.error ?? "(no reason given)"}` };
    default:
      return { kind: "failed", detail: `unrecognized warm state ${JSON.stringify(state)}` };
  }
}

const WARM_COVERAGE_RANK = ["failed", "unproven", "partial", "complete"];

export function strongestCoverage(verdicts) {
  return (verdicts ?? []).reduce((best, verdict) => {
    if (!best) return verdict;
    return WARM_COVERAGE_RANK.indexOf(verdict.kind) > WARM_COVERAGE_RANK.indexOf(best.kind) ? verdict : best;
  }, null);
}

const TAR_BLOCK_SIZE = 512;

function tarString(block, start, length) {
  const slice = block.subarray(start, start + length);
  const end = slice.indexOf(0);
  return Buffer.from(end === -1 ? slice : slice.subarray(0, end)).toString("utf8");
}

function tarHeaderChecksum(block) {
  let sum = 0;
  for (let i = 0; i < block.length; i++) {
    sum += i >= 148 && i < 156 ? 0x20 : block[i];
  }
  return sum;
}

export function tarEntryNames(buffer) {
  const names = [];
  let offset = 0;
  let sawEnd = false;
  while (offset < buffer.length) {
    if (offset + TAR_BLOCK_SIZE > buffer.length) {
      throw new Error(`truncated tar header at byte ${offset} of ${buffer.length}`);
    }
    const header = buffer.subarray(offset, offset + TAR_BLOCK_SIZE);
    if (header.every((byte) => byte === 0)) {
      sawEnd = true;
      break;
    }
    const rawChecksum = tarString(header, 148, 8).trim();
    const wantChecksum = rawChecksum ? parseInt(rawChecksum, 8) : NaN;
    if (!Number.isInteger(wantChecksum) || tarHeaderChecksum(header) !== wantChecksum) {
      throw new Error(`tar header at byte ${offset} fails its checksum`);
    }
    const name = tarString(header, 0, 100);
    const prefix = tarString(header, 345, 155);
    const size = parseInt(tarString(header, 124, 12).trim() || "0", 8) || 0;
    names.push(prefix ? `${prefix}/${name}` : name);
    offset += TAR_BLOCK_SIZE + Math.ceil(size / TAR_BLOCK_SIZE) * TAR_BLOCK_SIZE;
  }
  if (!sawEnd) {
    throw new Error("tar has no end-of-archive marker; the archive is truncated");
  }
  return names;
}

const ZIP_EOCD_SIGNATURE = 0x06054b50;
const ZIP_EOCD_MIN_SIZE = 22;
const ZIP64_LOCATOR_SIGNATURE = 0x07064b50;
const ZIP64_LOCATOR_SIZE = 20;
const ZIP64_EOCD_SIGNATURE = 0x06064b50;
const ZIP_CENTRAL_SIGNATURE = 0x02014b50;
const ZIP_CENTRAL_MIN_SIZE = 46;

export function zipEntryNames(buffer) {
  const eocd = findZipEOCD(buffer);
  let count = buffer.readUInt16LE(eocd + 10);
  let start = buffer.readUInt32LE(eocd + 16);

  if (count === 0xffff || start === 0xffffffff) {
    const locator = eocd - ZIP64_LOCATOR_SIZE;
    if (locator < 0 || buffer.readUInt32LE(locator) !== ZIP64_LOCATOR_SIGNATURE) {
      throw new Error("zip end-of-central-directory is saturated but carries no zip64 locator");
    }
    const zip64 = asIndex(buffer.readBigUInt64LE(locator + 8), buffer.length, "zip64 end-of-central-directory offset");
    if (buffer.readUInt32LE(zip64) !== ZIP64_EOCD_SIGNATURE) {
      throw new Error(`no zip64 end-of-central-directory record at byte ${zip64}`);
    }
    count = asIndex(buffer.readBigUInt64LE(zip64 + 32), Number.MAX_SAFE_INTEGER, "zip64 entry count");
    start = asIndex(buffer.readBigUInt64LE(zip64 + 48), buffer.length, "zip64 central directory offset");
  }

  const names = [];
  let offset = start;
  for (let i = 0; i < count; i++) {
    if (offset + ZIP_CENTRAL_MIN_SIZE > buffer.length) {
      throw new Error(`zip central directory entry ${i} runs past the end of the buffer at byte ${offset}`);
    }
    if (buffer.readUInt32LE(offset) !== ZIP_CENTRAL_SIGNATURE) {
      throw new Error(`zip central directory entry ${i} at byte ${offset} has no central-file-header signature`);
    }
    const nameLen = buffer.readUInt16LE(offset + 28);
    const extraLen = buffer.readUInt16LE(offset + 30);
    const commentLen = buffer.readUInt16LE(offset + 32);
    const nameAt = offset + ZIP_CENTRAL_MIN_SIZE;
    if (nameAt + nameLen > buffer.length) {
      throw new Error(`zip central directory entry ${i} names ${nameLen} bytes past the end of the buffer`);
    }
    names.push(buffer.toString("utf8", nameAt, nameAt + nameLen));
    offset = nameAt + nameLen + extraLen + commentLen;
  }
  return names;
}

function findZipEOCD(buffer) {
  const floor = Math.max(0, buffer.length - ZIP_EOCD_MIN_SIZE - 0xffff);
  for (let at = buffer.length - ZIP_EOCD_MIN_SIZE; at >= floor; at--) {
    if (buffer.readUInt32LE(at) === ZIP_EOCD_SIGNATURE) return at;
  }
  throw new Error(`no zip end-of-central-directory record in ${buffer.length} bytes; this is not a zip`);
}

function asIndex(value, limit, what) {
  if (value > BigInt(limit)) throw new Error(`${what} (${value}) is past the end of the buffer`);
  return Number(value);
}

export function tail(text, maxLines) {
  const lines = text.split("\n");
  return lines.slice(Math.max(0, lines.length - maxLines)).join("\n");
}

const HARNESS_OUTPUT = /--test output start-- (.*) --test output end--/;
const HARNESS_STARTING = /\bStarting (\S+\.test\.\w+) retry \d+\/\d+/;

export function suitesFromHarnessOutput(stdout, nextjsDir) {
  const suites = [];
  for (const line of stdout.split("\n")) {
    const framed = HARNESS_OUTPUT.exec(line);
    if (!framed) continue;
    let results;
    try {
      results = JSON.parse(framed[1]);
    } catch {
      continue;
    }
    const name = results?.testResults?.[0]?.name;
    if (!name) continue;
    suites.push({ suite: relative(nextjsDir, name).replace(/\\/g, "/"), results });
  }
  return suites;
}

export function suitesStartedInHarnessOutput(stdout) {
  const started = new Set();
  for (const line of stdout.split("\n")) {
    const match = HARNESS_STARTING.exec(line.trim());
    if (match) started.add(match[1]);
  }
  return [...started];
}

export const BASELINE_INCLUDE_PATTERN = "test/e2e/**/*.test.{t,j}s{,x}";

export function suiteResultFromJest(results) {
  const testResults = results?.testResults ?? [];
  const execError = testResults.some((suite) => suite?.testExecError);
  let passed = 0;
  let pending = 0;
  const failed = [];
  for (const suite of testResults) {
    for (const assertion of suite?.assertionResults ?? []) {
      if (assertion.status === "passed") {
        passed += 1;
      } else if (assertion.status === "failed") {
        failed.push([...(assertion.ancestorTitles ?? []), assertion.title].filter(Boolean).join(" "));
      } else {
        pending += 1;
      }
    }
  }
  if (execError || passed + failed.length + pending === 0) {
    return { outcome: "runtimeError" };
  }
  if (passed === 0 && failed.length === 0) {
    return { outcome: "whollySkipped" };
  }
  return { outcome: "signal", failed, flakey: [] };
}

export function buildBaselineManifest(suites) {
  const manifestSuites = {};
  const exclude = new Set();
  for (const { suite, results } of suites) {
    const entry = suiteResultFromJest(results);
    if (entry.outcome === "whollySkipped") continue;
    if (entry.outcome === "runtimeError") {
      exclude.add(suite);
      continue;
    }
    if (entry.failed.length > 0 || entry.flakey.length > 0) {
      manifestSuites[suite] = { failed: entry.failed, flakey: entry.flakey };
    }
  }
  return {
    version: 2,
    suites: manifestSuites,
    rules: { include: [BASELINE_INCLUDE_PATTERN], exclude: [...exclude].sort() },
  };
}

export function mergeBaselineManifest(manifests) {
  const suites = {};
  const exclude = new Set();
  for (const manifest of manifests) {
    for (const [suite, entry] of Object.entries(manifest?.suites ?? {})) {
      const prior = suites[suite];
      suites[suite] = prior
        ? { failed: union(prior.failed, entry.failed), flakey: union(prior.flakey, entry.flakey) }
        : { failed: [...(entry.failed ?? [])], flakey: [...(entry.flakey ?? [])] };
    }
    for (const pattern of manifest?.rules?.exclude ?? []) {
      exclude.add(pattern);
    }
  }
  return {
    version: 2,
    suites: Object.fromEntries(Object.keys(suites).sort().map((suite) => [suite, suites[suite]])),
    rules: { include: [BASELINE_INCLUDE_PATTERN], exclude: [...exclude].sort() },
  };
}

function union(a, b) {
  return [...new Set([...(a ?? []), ...(b ?? [])])];
}
