// Pure helpers shared by the Next.js adapter-harness lifecycle scripts
// (deploy.mjs, logs.mjs, cleanup.mjs, merge-baseline.mjs). The harness runs
// them as separate processes, so everything they share travels through files in
// the temp app directory rather than memory.

import { createHash } from "node:crypto";
import { join } from "node:path";

/** A valid single DNS label, per RFC 1035 (mirrors cli/internal/previewid). */
export const DNS_LABEL = /^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/;

/** The file deploy.mjs persists this app's identity to, read by logs/cleanup. */
export const STATE_FILE = ".ocel-e2e.json";

/** The file every byte of the deploy's output is redirected to. */
export const BUILD_LOG_FILE = ".adapter-build.log";

/** The CLI's machine-readable deploy result, relative to the app directory. */
export const DEPLOY_RESULT_FILE = join(".ocel", "deploy-result.json");

/** How many hex characters of the temp dir's hash disambiguate one app. */
const HASH_LEN = 8;

/** Run-id token used when the scripts run outside GitHub Actions. */
const LOCAL_RUN_ID = "local";

/**
 * The name every temp app is declared under. Isolation lives in the project slug
 * (projectSlug), so a per-app name would buy nothing and cost length: the
 * Cloudflare worker script name derived from both ("ocel-<slug>-preview-<app>")
 * has 63 characters to fit in.
 */
export const APP_NAME = "app";

/**
 * The longest slug a preview pointer named after it can still be served on: the
 * route hostname's first label is the pointer plus an 11-character suffix
 * (cloud/aws/deploy/previewhost.go) and a DNS label holds 63, which is the same
 * cap `ocel preview up --name` enforces (cli/internal/previewid).
 */
export const MAX_SLUG_LEN = 52;

/**
 * projectSlug derives the identity that isolates one temp app: the `slug` of the
 * Ocel project it deploys into, which is also the name of the persistent preview
 * pointer inside that project. A project is the unit concurrent deploys must not
 * share — it namespaces the Pulumi stacks, the deployments store, the asset
 * prefixes and the Cloudflare worker scripts and routes — so every temp app gets
 * its own.
 *
 * It must be a valid single DNS label within MAX_SLUG_LEN (it becomes the
 * preview subdomain), unique per temp app, and stable for a given run and
 * directory: cleanup re-derives it when the state file is lost, and a slug it
 * cannot re-derive is infrastructure nothing will ever tear down.
 */
export function projectSlug({ runId, dir }) {
  const run = sanitizeToken(String(runId ?? "")) || LOCAL_RUN_ID;
  const hash = createHash("sha256").update(String(dir ?? "")).digest("hex").slice(0, HASH_LEN);
  // "e2e-" gives the label its required letter start; the run token is capped
  // so run + hash can never push the slug past MAX_SLUG_LEN.
  const maxRun = MAX_SLUG_LEN - "e2e-".length - 1 - HASH_LEN;
  return `e2e-${run.slice(0, maxRun)}-${hash}`;
}

/**
 * projectSlugForApp is how deploy.mjs and cleanup.mjs derive the slug. Both must
 * derive the same one from the same environment — a drift between them means
 * cleanup tears down the wrong project, or nothing — so the environment read
 * lives here, in one place, rather than at each call site.
 */
export function projectSlugForApp(appDir) {
  return projectSlug({ runId: process.env.GITHUB_RUN_ID, dir: process.env.NEXT_TEST_DIR || appDir });
}

function sanitizeToken(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * renderOcelConfig is the ocel.config.ts written into the temp app. `slug` is
 * this app's own project (projectSlug) — that is what gives it its own worker
 * scripts and asset prefixes — and the app under it is declared explicitly
 * rather than discovered, under APP_NAME. Pure: cleanup re-renders it from the
 * same environment when a failed deploy left no config to tear down.
 * `ocel` and `@ocel/provider-aws` must resolve from the app directory —
 * the config is bundled and executed from there.
 */
export function renderOcelConfig({ slug, previewDomain }) {
  const lines = [
    `import { defineConfig } from "ocel/config";`,
    `import awsProvider from "@ocel/provider-aws";`,
    ``,
    `// Generated by scripts/e2e-next/deploy.mjs. Do not edit.`,
    `export default defineConfig({`,
    `  slug: ${JSON.stringify(slug)},`,
    `  provider: awsProvider(),`,
  ];
  if (previewDomain) {
    lines.push(`  domains: {`, `    preview: ${JSON.stringify(previewDomain)},`, `  },`);
  }
  lines.push(
    `  apps: [{ name: ${JSON.stringify(APP_NAME)}, path: ".", framework: "next" }],`,
    `});`,
    ``,
  );
  return lines.join("\n");
}

/**
 * withBuildScript returns the app's package.json with a `build` script, which
 * buildNext requires (it throws without one). An app that already declares one
 * keeps it: the fixture may build with flags of its own.
 */
export function withBuildScript(pkg) {
  if (pkg.scripts?.build) {
    return pkg;
  }
  return { ...pkg, scripts: { ...pkg.scripts, build: "next build" } };
}

/**
 * The smoke app's revalidation probe, and the window it declares. Mirrors
 * `revalidate` and the marker in smoke-app/app/isr/page.tsx — assert-isr.mjs
 * reads them from here so the page and its assertion cannot drift apart.
 */
export const ISR_ROUTE = "/isr";
export const ISR_REVALIDATE_SECONDS = 5;

/**
 * isrToken pulls the probe page's per-render token out of its html. Null when
 * the marker is absent, which means the response was not that page at all —
 * a redirect, an error page, or a build that dropped the route — and must be
 * reported as such rather than compared as a value.
 */
export function isrToken(html) {
  return /isr-token:(\d+)/.exec(String(html ?? ""))?.[1] ?? null;
}

/**
 * The tag-publisher probe's route, and the tag it raises. Mirrors
 * smoke-app/app/api/revalidate-tag/route.ts — assert-tag-publisher.mjs reads
 * them from here so the route and its assertion cannot drift apart.
 */
export const TAG_PROBE_ROUTE = "/api/revalidate-tag";

/**
 * tagProbeTag names one run's invalidation. It must be unique per run: the
 * assertion proves the publisher carried *this* raise, and a tag some earlier
 * run already published would be found in the snapshot before the probe fired.
 */
export function tagProbeTag(stamp) {
  return `ocel-publisher-probe-${stamp}`;
}

/**
 * The golden comparison's probe route and the marker its body carries. Mirrors
 * smoke-app/app/golden/page.tsx — assert-suppression-golden.mjs reads them from
 * here so the page and its assertion cannot drift apart.
 */
export const GOLDEN_ROUTE = "/golden";
export const GOLDEN_MARKER = "golden-body:v1";

/**
 * The probe page's own `revalidate`, kept short on purpose. `purpose: prefetch`
 * is read at exactly one place in Next's response cache
 * (`if (!entry.isStale || context.isPrefetch) return entry;`), where the FIRST
 * operand short-circuits on a fresh entry — so a comparison made against a
 * freshly warmed page proves only that the header does not change a fresh
 * serve, and never evaluates the branch it is guarding. The assertion waits out
 * this window before each pair so both legs are answered from a STALE entry,
 * which is the only state where `purpose` can change anything — and the state
 * suppression puts every governed route into.
 */
export const GOLDEN_REVALIDATE_SECONDS = 3;

/**
 * The header the edge stamps on a user-path forward to suppress Next's own
 * self-revalidation (bd ocelhq-wvag.26, workers/nextjs/src/index.ts).
 */
export const PREFETCH_PURPOSE_HEADER = "purpose";
export const PREFETCH_PURPOSE_VALUE = "prefetch";

/**
 * Headers a golden comparison must ignore, because they differ between any two
 * responses whatever the request carried:
 *
 * - `date`/`age`: the responses are seconds apart.
 * - `x-nextjs-cache`: the freshness of the entry each render was answered from,
 *   which is what the suppression legitimately changes.
 * - `x-ocel-cache`: the tier that answered. Compared separately by the
 *   assertion, which requires both legs to report the same one — a difference
 *   there means the legs were never comparable, not that the render differed.
 * - the Cloudflare and connection-level set: stamped per response by the edge
 *   and the transport, never by the render.
 * - the `x-amzn-*` set: the Lambda Function URL stamps a fresh request id, trace
 *   id and receive date on every invocation and the edge forwards them, so they
 *   differ between any two responses by construction. They reached this
 *   comparison for the first time on the live run for ocelhq-wvag.27 — a local
 *   run has no Function URL in front of it — and failed both variants on nothing
 *   but per-invocation ids while the bodies were byte-identical.
 *
 * Everything else — status, body bytes, content-type, etag, x-matched-path,
 * x-nextjs-postponed, Next's own vary — is compared, which is the point: the
 * caveat this gate exists for is that a future Next could make `purpose`
 * change what is rendered.
 */
export const GOLDEN_VOLATILE_HEADERS = new Set([
  "date",
  "age",
  "x-nextjs-cache",
  "x-ocel-cache",
  "cf-ray",
  "cf-cache-status",
  "x-amzn-requestid",
  "x-amzn-trace-id",
  "x-amzn-remapped-date",
  "server-timing",
  "report-to",
  "nel",
  "alt-svc",
  "connection",
  "keep-alive",
  "transfer-encoding",
  "content-encoding",
  "content-length",
]);

function headerMap(headers) {
  const entries =
    typeof headers?.entries === "function" ? [...headers.entries()] : Object.entries(headers ?? {});
  const map = new Map();
  for (const [name, value] of entries) {
    const lower = String(name).toLowerCase();
    if (GOLDEN_VOLATILE_HEADERS.has(lower)) continue;
    map.set(lower, String(value));
  }
  return map;
}

/**
 * goldenDifferences compares two fetches of the same route that differ only in
 * whether the origin leg carried `purpose: prefetch`, and returns one line per
 * difference — empty when the header had no observable side effect.
 *
 * A leg is `{ status, headers, body }`. Bodies are compared as exact strings:
 * the probe page renders no clock and no request data, so any difference at all
 * is the header's.
 */
export function goldenDifferences(withHeader, without) {
  const differences = [];
  if (withHeader?.status !== without?.status) {
    differences.push(`status: with=${withHeader?.status} without=${without?.status}`);
  }
  if (withHeader?.body !== without?.body) {
    differences.push(
      `body: ${byteDiff(String(withHeader?.body ?? ""), String(without?.body ?? ""))}`,
    );
  }
  const a = headerMap(withHeader?.headers);
  const b = headerMap(without?.headers);
  for (const name of [...new Set([...a.keys(), ...b.keys()])].sort()) {
    if (a.get(name) !== b.get(name)) {
      differences.push(`header ${name}: with=${a.get(name) ?? "(absent)"} without=${b.get(name) ?? "(absent)"}`);
    }
  }
  return differences;
}

/** Where two bodies first diverge, and by how much — enough to act on. */
function byteDiff(a, b) {
  if (a.length !== b.length) return `lengths ${a.length} vs ${b.length}`;
  const at = [...a].findIndex((char, index) => char !== b[index]);
  return `differs at offset ${at}: ${JSON.stringify(a.slice(at, at + 40))} vs ${JSON.stringify(b.slice(at, at + 40))}`;
}

/**
 * deployURL is the URL the harness reads from the deploy script's stdout, taken
 * from the CLI's deploy result. A successful deploy that featured no app URL is
 * a failure for our purposes: the harness has nothing to test.
 */
export function deployURL(result) {
  const url = result?.appUrls?.[0];
  if (!url) {
    throw new Error(`deploy result carries no app URL: ${JSON.stringify(result ?? null)}`);
  }
  return url;
}

/**
 * markerLines formats the three lines the harness parses out of the logs
 * script's output. A missing value is reported as the literal "undefined",
 * which is what the contract asks for — never a blank value.
 *
 * `DEPLOYMENT_ID` is the harness's own marker name, not ours: it is an external
 * contract, so it keeps that spelling while carrying Ocel's promotion id.
 * IMMUTABLE_ASSET_TOKEN is always undefined — the Ocel adapter never sets
 * `config.deploymentId`, so its assets carry no `?dpl=` token.
 */
export function markerLines({ buildId, promotionId }) {
  return [
    `BUILD_ID: ${buildId || "undefined"}`,
    `DEPLOYMENT_ID: ${promotionId || "undefined"}`,
    `IMMUTABLE_ASSET_TOKEN: undefined`,
  ];
}

/**
 * lambdaFunctionNames maps a resourcegroupstaggingapi get-resources response
 * to the names of the Lambda functions it found. Function names are
 * Pulumi-autonamed, so the ocel tags (cloud/aws/deploy/function.go) are the
 * only way to find them.
 */
export function lambdaFunctionNames(response) {
  return (response?.ResourceTagMappingList ?? [])
    .map((entry) => /^arn:aws:lambda:[^:]*:[^:]*:function:([^:]+)/.exec(entry?.ResourceARN ?? ""))
    .filter(Boolean)
    .map((match) => match[1]);
}

/**
 * lambdaLogGroups maps a resourcegroupstaggingapi get-resources response into
 * the CloudWatch log groups of the Lambdas it found; the caller filters on
 * `ocel:project`, this app's own slug being what is unique per deploy.
 */
export function lambdaLogGroups(response) {
  return lambdaFunctionNames(response).map((name) => `/aws/lambda/${name}`);
}

/**
 * envSegment is the environment segment of an app's asset-key prefix. Mirrors
 * envSegment in cloud/aws/server/server.go: "prod" for a production deploy,
 * "preview-<identity>" for a preview one — the same token a deploy's Pulumi
 * stack name also carries.
 */
export function envSegment(environment) {
  if (environment?.class === "preview") {
    return `preview-${environment?.identity ?? ""}`;
  }
  return "prod";
}

/**
 * appAssetPrefix is the S3 key prefix one app's assets — and, when it caches,
 * its bytecode archive — live under. Mirrors appAssetPrefixFor in
 * cloud/aws/deploy/prerender.go: <env>/<slug>/<app>/<buildId>. `app` is
 * assumed to already be a valid worker name (sanitizeWorkerName's job on the
 * Go side) — every app this suite deploys is declared under the constant
 * APP_NAME, which needs no sanitizing.
 */
export function appAssetPrefix({ environment, slug, app, buildId }) {
  return [envSegment(environment), slug, app, buildId].join("/");
}

/**
 * bytecodeCacheKeyPrefix is the S3 prefix every bytecode cache object for one
 * function lives under. Mirrors the directory portion of bytecodeCacheKey in
 * cloud/aws/cmd/lambdanode/bootstrap/bytecode.go — the filename that follows
 * it carries the live node patch version, which nothing outside a running
 * instance can know ahead of time, so a caller lists this prefix rather than
 * composing the full key.
 */
export function bytecodeCacheKeyPrefix({ prefix, functionName }) {
  return `${prefix}/bytecode/${functionName}/`;
}

const BYTECODE_ARCHIVE_NAME = /^node(\d+\.\d+\.\d+)-([a-z0-9_]+)\.tar\.gz$/;

/**
 * bytecodeCacheKeyName parses the filename segment of a bytecode cache key —
 * everything after bytecodeCacheKeyPrefix — into its node version and arch,
 * or null if it does not have the "node<version>-<arch>.tar.gz" shape
 * bytecodeCacheKey in bytecode.go composes. A caller lists objects under the
 * prefix and uses this to tell a real cache archive from anything else that
 * might land there, and to assert the version is the three-dot-separated-
 * numbers shape bytecode.go's canonicalNodeVersion requires.
 */
export function bytecodeCacheKeyName(name) {
  const match = BYTECODE_ARCHIVE_NAME.exec(name ?? "");
  if (!match) return null;
  return { nodeVersion: match[1], arch: match[2] };
}

/**
 * bytecodeRehydrateOutcome classifies one CloudWatch log message against
 * every read-leg line rehydrateCompileCache, rehydrateBytecodeCache and
 * resolveBytecodeResolution (cloud/aws/cmd/lambdanode/bootstrap/bytecode.go)
 * can emit, or null when the message is unrelated. That file is the source
 * of truth for the literal strings matched below — a wording change there
 * must be mirrored here, or a message that used to classify silently starts
 * returning null. assert-bytecode.mjs uses this to tell a proven hit from
 * every failure mode it can only report as a symptom: matched by exact
 * substring rather than parsed, since these are the literal lines the
 * membrane emits, not a format to decode.
 *
 * `dir`-clear failures (the one read-leg line that names neither `key` nor
 * anything else this function is given) are not classified here — nothing
 * to match them against reaches this call. The two off-switch lines in
 * resolveBytecodeResolution (a version probe or AWS config load that failed
 * before a key was ever composed) also name no key; they are still
 * classified, under "disabled", because a caller polling by key would
 * otherwise never learn the feature turned itself off on some instances.
 */
export function bytecodeRehydrateOutcome(message, key) {
  const text = String(message ?? "");
  if (text.includes(`rehydrated compile cache from ${key}:`)) {
    return { kind: "hit", message: text };
  }
  if (text.includes(`no compile cache at ${key} yet`)) {
    return { kind: "miss", message: text };
  }
  if (text.includes(`could not fetch the compile cache at ${key}:`)) {
    return { kind: "fetch-error", message: text };
  }
  if (text.includes(`compile cache at ${key} is`) && text.includes("skipping rehydration")) {
    return { kind: "over-ceiling", message: text };
  }
  if (text.includes(`could not rehydrate the compile cache from ${key}:`)) {
    return { kind: "extract-error", message: text };
  }
  if (text.includes(`rehydrating the compile cache from ${key} ran out of time:`)) {
    return { kind: "timeout", message: text };
  }
  if (text.includes("compile cache disabled") || text.includes("no aws config for the compile cache:")) {
    return { kind: "disabled", message: text };
  }
  return null;
}

const TAR_BLOCK_SIZE = 512;

function tarString(block, start, length) {
  const slice = block.subarray(start, start + length);
  const end = slice.indexOf(0);
  return Buffer.from(end === -1 ? slice : slice.subarray(0, end)).toString("utf8");
}

function tarHeaderChecksum(block) {
  let sum = 0;
  for (let i = 0; i < block.length; i++) {
    sum += i >= 148 && i < 156 ? 0x20 : block[i];
  }
  return sum;
}

/**
 * tarEntryNames walks an uncompressed tar buffer and returns each entry's
 * name (its ustar `prefix` field joined on, when set). It exists so
 * assert-bytecode.mjs can prove the membrane's upload is a real archive
 * rather than truncated or empty bytes, without a dependency: every header's
 * checksum is verified, and a buffer that runs out mid-header or never
 * reaches the two-zero-block end-of-archive marker throws rather than
 * silently returning a partial entry list.
 */
export function tarEntryNames(buffer) {
  const names = [];
  let offset = 0;
  let sawEnd = false;
  while (offset < buffer.length) {
    if (offset + TAR_BLOCK_SIZE > buffer.length) {
      throw new Error(`truncated tar header at byte ${offset} of ${buffer.length}`);
    }
    const header = buffer.subarray(offset, offset + TAR_BLOCK_SIZE);
    if (header.every((byte) => byte === 0)) {
      sawEnd = true;
      break;
    }
    const rawChecksum = tarString(header, 148, 8).trim();
    const wantChecksum = rawChecksum ? parseInt(rawChecksum, 8) : NaN;
    if (!Number.isInteger(wantChecksum) || tarHeaderChecksum(header) !== wantChecksum) {
      throw new Error(`tar header at byte ${offset} fails its checksum`);
    }
    const name = tarString(header, 0, 100);
    const prefix = tarString(header, 345, 155);
    const size = parseInt(tarString(header, 124, 12).trim() || "0", 8) || 0;
    names.push(prefix ? `${prefix}/${name}` : name);
    offset += TAR_BLOCK_SIZE + Math.ceil(size / TAR_BLOCK_SIZE) * TAR_BLOCK_SIZE;
  }
  if (!sawEnd) {
    throw new Error("tar has no end-of-archive marker; the archive is truncated");
  }
  return names;
}

export function tail(text, maxLines) {
  const lines = text.split("\n");
  return lines.slice(Math.max(0, lines.length - maxLines)).join("\n");
}

/** Recovers the harness's test-file key from `${test.file}.results.json`. */
export function suiteFromResultsPath(resultsPath) {
  return resultsPath
    .replace(/\\/g, "/")
    .replace(/^\.\//, "")
    .replace(/\.results\.json$/, "");
}

/**
 * suiteResultFromJest reduces one suite's Jest JSON output to the baseline
 * manifest's per-suite entry. Case names are the full "ancestors > title" path,
 * which is what the harness's excludedCases matches on.
 *
 * A suite that produced no assertions at all did not merely fail — it never
 * ran (a crash while loading, a deploy the harness could not reach), which the
 * manifest records as runtimeError so the whole file is skipped rather than
 * every case in it being listed.
 */
export function suiteResultFromJest(results) {
  const passed = [];
  const failed = [];
  for (const suite of results?.testResults ?? []) {
    for (const assertion of suite?.assertionResults ?? []) {
      const name = [...(assertion.ancestorTitles ?? []), assertion.title].filter(Boolean).join(" > ");
      if (assertion.status === "passed") {
        passed.push(name);
      } else if (assertion.status === "failed") {
        failed.push(name);
      }
    }
  }
  return { passed, failed, flakey: [], runtimeError: passed.length === 0 && failed.length === 0 };
}

/**
 * buildBaselineManifest turns one group's collected Jest results files into a
 * baseline manifest fragment, keyed by test file — the legacy (unversioned)
 * NEXT_EXTERNAL_TESTS_FILTERS shape, where a listed suite's `failed` cases are
 * excluded and any newly added case is automatically included.
 */
export function buildBaselineManifest(files) {
  const manifest = {};
  for (const { path, results } of files) {
    manifest[suiteFromResultsPath(path)] = suiteResultFromJest(results);
  }
  return manifest;
}

/**
 * mergeBaselineManifest folds every group's fragment into the one manifest the
 * repo commits. Suites are disjoint across groups in a single run, but merging
 * is defined anyway — a re-run of one group must not drop the others' entries —
 * and a suite any group saw crash stays marked as a runtime error. Keys are
 * sorted so the committed baseline diffs cleanly.
 */
export function mergeBaselineManifest(manifests) {
  const merged = {};
  for (const manifest of manifests) {
    for (const [suite, entry] of Object.entries(manifest ?? {})) {
      const prior = merged[suite];
      if (!prior) {
        merged[suite] = {
          passed: [...(entry.passed ?? [])],
          failed: [...(entry.failed ?? [])],
          flakey: [...(entry.flakey ?? [])],
          runtimeError: Boolean(entry.runtimeError),
        };
        continue;
      }
      merged[suite] = {
        passed: union(prior.passed, entry.passed),
        failed: union(prior.failed, entry.failed),
        flakey: union(prior.flakey, entry.flakey),
        runtimeError: prior.runtimeError || Boolean(entry.runtimeError),
      };
    }
  }
  return Object.fromEntries(Object.keys(merged).sort().map((suite) => [suite, merged[suite]]));
}

function union(a, b) {
  return [...new Set([...(a ?? []), ...(b ?? [])])];
}
