// Pure helpers shared by the Next.js adapter-harness lifecycle scripts
// (deploy.mjs, logs.mjs, cleanup.mjs, merge-baseline.mjs).
//
// The harness runs deploy and logs as separate processes, so everything they
// share travels through files in the temp app directory rather than memory.
// Keeping the derivations here — slug, config, package.json patch, result
// reading, marker formatting, baseline merging — makes the parts that can be
// wrong on a real cloud run testable without one.

import { createHash } from "node:crypto";

/** A valid single DNS label, per RFC 1035 (mirrors cli/internal/previewid). */
export const DNS_LABEL = /^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/;

/** The file deploy.mjs persists this app's identity to, read by logs/cleanup. */
export const STATE_FILE = ".ocel-e2e.json";

/** The file every byte of the deploy's output is redirected to. */
export const BUILD_LOG_FILE = ".adapter-build.log";

/** How many hex characters of the temp dir's hash disambiguate one app. */
const HASH_LEN = 8;

/** Run-id token used when the scripts run outside GitHub Actions. */
const LOCAL_RUN_ID = "local";

/**
 * previewSlug derives this temp app's identity: the name of its preview
 * environment, its declared app name, and therefore its Cloudflare worker
 * script and S3 asset prefix. It must be a valid single DNS label (it becomes a
 * preview subdomain), unique per temp app (each suite gets its own app rather
 * than racing a shared one), and stable for a given run and directory so
 * logs/cleanup can re-derive it if the state file is ever lost.
 */
export function previewSlug({ runId, dir }) {
  const run = sanitizeToken(String(runId ?? "")) || LOCAL_RUN_ID;
  const hash = createHash("sha256").update(String(dir ?? "")).digest("hex").slice(0, HASH_LEN);
  // "e2e-" gives the label its required letter start; the run token is capped
  // so run + hash can never push the label past the DNS limit.
  const maxRun = 63 - "e2e-".length - 1 - HASH_LEN;
  return `e2e-${run.slice(0, maxRun)}-${hash}`;
}

/**
 * projectSlug lowers an arbitrary project identifier into the DNS-label shape
 * ocel.config.ts requires of `slug` (projectId is not constrained to it: a
 * "proj_ab12" id is a valid project id and an invalid slug).
 */
export function projectSlug(value) {
  const token = sanitizeToken(String(value ?? "")).slice(0, 63).replace(/-+$/, "");
  if (!token) {
    throw new Error(`cannot derive a project slug from ${JSON.stringify(value)}`);
  }
  return token;
}

/** sanitizeToken lowers a value to the DNS-label alphabet, collapsing runs of separators. */
function sanitizeToken(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * renderOcelConfig is the ocel.config.ts written into the temp app. The app is
 * declared explicitly rather than discovered, and its name is the unique slug:
 * that is what gives each test app its own worker script and asset prefix.
 * `@ocel/sdk` and `@ocel/provider-aws` must resolve from the app directory —
 * the config is bundled and executed from there.
 */
export function renderOcelConfig({ slug, projectId, previewDomain, appName }) {
  const lines = [
    `import { defineConfig } from "@ocel/sdk/config";`,
    `import awsProvider from "@ocel/provider-aws";`,
    ``,
    `// Generated by scripts/e2e-next/deploy.mjs. Do not edit.`,
    `export default defineConfig({`,
    `  slug: ${JSON.stringify(slug)},`,
    `  projectId: ${JSON.stringify(projectId)},`,
    `  provider: awsProvider(),`,
  ];
  if (previewDomain) {
    lines.push(`  domains: {`, `    preview: ${JSON.stringify(previewDomain)},`, `  },`);
  }
  lines.push(
    `  apps: [{ name: ${JSON.stringify(appName)}, path: ".", framework: "next" }],`,
    `});`,
    ``,
  );
  return lines.join("\n");
}

/**
 * withBuildScript returns the app's package.json with a `build` script, which
 * buildNext requires (it throws without one). An app that already declares one
 * keeps it: the fixture may build with flags of its own.
 */
export function withBuildScript(pkg) {
  if (pkg.scripts?.build) {
    return pkg;
  }
  return { ...pkg, scripts: { ...pkg.scripts, build: "next build" } };
}

/**
 * deployURL is the URL the harness reads from the deploy script's stdout, taken
 * from the CLI's .ocel/deploy-result.json. A successful deploy that featured no
 * app URL is a failure for our purposes: the harness has nothing to test.
 */
export function deployURL(result) {
  const url = result?.appUrls?.[0];
  if (!url) {
    throw new Error(`deploy result carries no app URL: ${JSON.stringify(result ?? null)}`);
  }
  return url;
}

/**
 * markerLines formats the three lines the harness parses out of the logs
 * script's output. A missing value is reported as the literal "undefined",
 * which is what the contract asks for — never a blank value.
 *
 * IMMUTABLE_ASSET_TOKEN is always undefined: the Ocel adapter never sets
 * `config.deploymentId`, so its assets carry no `?dpl=` token.
 */
export function markerLines({ buildId, deploymentId }) {
  return [
    `BUILD_ID: ${buildId || "undefined"}`,
    `DEPLOYMENT_ID: ${deploymentId || "undefined"}`,
    `IMMUTABLE_ASSET_TOKEN: undefined`,
  ];
}

/**
 * lambdaLogGroups maps a resourcegroupstaggingapi get-resources response into
 * the CloudWatch log groups of the Lambdas it found. Function names are
 * Pulumi-autonamed, so the `ocel:app` tag (cloud/aws/deploy/function.go) is the
 * only way to find this app's functions.
 */
export function lambdaLogGroups(response) {
  return (response?.ResourceTagMappingList ?? [])
    .map((entry) => /^arn:aws:lambda:[^:]*:[^:]*:function:([^:]+)/.exec(entry?.ResourceARN ?? ""))
    .filter(Boolean)
    .map((match) => `/aws/lambda/${match[1]}`);
}

/** tail keeps the last maxLines lines of text. */
export function tail(text, maxLines) {
  const lines = text.split("\n");
  return lines.slice(Math.max(0, lines.length - maxLines)).join("\n");
}

/**
 * suiteFromResultsPath recovers the harness's test-file key from the path of
 * the per-suite Jest results file run-tests.js writes next to it
 * (`${test.file}.results.json`).
 */
export function suiteFromResultsPath(resultsPath) {
  return resultsPath
    .replace(/\\/g, "/")
    .replace(/^\.\//, "")
    .replace(/\.results\.json$/, "");
}

/**
 * suiteResultFromJest reduces one suite's Jest JSON output to the baseline
 * manifest's per-suite entry. Case names are the full "ancestors > title" path,
 * which is what the harness's excludedCases matches on.
 *
 * A suite that produced no assertions at all did not merely fail — it never
 * ran (a crash while loading, a deploy the harness could not reach), which the
 * manifest records as runtimeError so the whole file is skipped rather than
 * every case in it being listed.
 */
export function suiteResultFromJest(results) {
  const passed = [];
  const failed = [];
  for (const suite of results?.testResults ?? []) {
    for (const assertion of suite?.assertionResults ?? []) {
      const name = [...(assertion.ancestorTitles ?? []), assertion.title].filter(Boolean).join(" > ");
      if (assertion.status === "passed") {
        passed.push(name);
      } else if (assertion.status === "failed") {
        failed.push(name);
      }
    }
  }
  return { passed, failed, flakey: [], runtimeError: passed.length === 0 && failed.length === 0 };
}

/**
 * buildBaselineManifest turns one group's collected Jest results files into a
 * baseline manifest fragment, keyed by test file — the legacy (unversioned)
 * NEXT_EXTERNAL_TESTS_FILTERS shape, where a listed suite's `failed` cases are
 * excluded and any newly added case is automatically included.
 */
export function buildBaselineManifest(files) {
  const manifest = {};
  for (const { path, results } of files) {
    manifest[suiteFromResultsPath(path)] = suiteResultFromJest(results);
  }
  return manifest;
}

/**
 * mergeBaselineManifest folds every group's fragment into the one manifest the
 * repo commits. Suites are disjoint across groups in a single run, but merging
 * is defined anyway — a re-run of one group must not drop the others' entries —
 * and a suite any group saw crash stays marked as a runtime error. Keys are
 * sorted so the committed baseline diffs cleanly.
 */
export function mergeBaselineManifest(manifests) {
  const merged = {};
  for (const manifest of manifests) {
    for (const [suite, entry] of Object.entries(manifest ?? {})) {
      const prior = merged[suite];
      if (!prior) {
        merged[suite] = {
          passed: [...(entry.passed ?? [])],
          failed: [...(entry.failed ?? [])],
          flakey: [...(entry.flakey ?? [])],
          runtimeError: Boolean(entry.runtimeError),
        };
        continue;
      }
      merged[suite] = {
        passed: union(prior.passed, entry.passed),
        failed: union(prior.failed, entry.failed),
        flakey: union(prior.flakey, entry.flakey),
        runtimeError: prior.runtimeError || Boolean(entry.runtimeError),
      };
    }
  }
  return Object.fromEntries(Object.keys(merged).sort().map((suite) => [suite, merged[suite]]));
}

function union(a, b) {
  return [...new Set([...(a ?? []), ...(b ?? [])])];
}
