// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: deployments/v1/deployments.proto

package deploymentsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ocelhq/ocel/pkg/proto/deployments/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeploymentServiceName is the fully-qualified name of the DeploymentService service.
	DeploymentServiceName = "deployments.v1.DeploymentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeploymentServiceDeployProcedure is the fully-qualified name of the DeploymentService's Deploy
	// RPC.
	DeploymentServiceDeployProcedure = "/deployments.v1.DeploymentService/Deploy"
	// DeploymentServiceBootstrapProcedure is the fully-qualified name of the DeploymentService's
	// Bootstrap RPC.
	DeploymentServiceBootstrapProcedure = "/deployments.v1.DeploymentService/Bootstrap"
	// DeploymentServiceDestroyPreviewProcedure is the fully-qualified name of the DeploymentService's
	// DestroyPreview RPC.
	DeploymentServiceDestroyPreviewProcedure = "/deployments.v1.DeploymentService/DestroyPreview"
	// DeploymentServiceDestroyProjectProcedure is the fully-qualified name of the DeploymentService's
	// DestroyProject RPC.
	DeploymentServiceDestroyProjectProcedure = "/deployments.v1.DeploymentService/DestroyProject"
	// DeploymentServicePlanDestroyProjectProcedure is the fully-qualified name of the
	// DeploymentService's PlanDestroyProject RPC.
	DeploymentServicePlanDestroyProjectProcedure = "/deployments.v1.DeploymentService/PlanDestroyProject"
	// DeploymentServiceListEnvironmentsProcedure is the fully-qualified name of the DeploymentService's
	// ListEnvironments RPC.
	DeploymentServiceListEnvironmentsProcedure = "/deployments.v1.DeploymentService/ListEnvironments"
	// DeploymentServicePreflightProcedure is the fully-qualified name of the DeploymentService's
	// Preflight RPC.
	DeploymentServicePreflightProcedure = "/deployments.v1.DeploymentService/Preflight"
	// DeploymentServiceListPromotionsProcedure is the fully-qualified name of the DeploymentService's
	// ListPromotions RPC.
	DeploymentServiceListPromotionsProcedure = "/deployments.v1.DeploymentService/ListPromotions"
	// DeploymentServiceRollbackProcedure is the fully-qualified name of the DeploymentService's
	// Rollback RPC.
	DeploymentServiceRollbackProcedure = "/deployments.v1.DeploymentService/Rollback"
	// DeploymentServicePruneProcedure is the fully-qualified name of the DeploymentService's Prune RPC.
	DeploymentServicePruneProcedure = "/deployments.v1.DeploymentService/Prune"
)

// DeploymentServiceClient is a client for the deployments.v1.DeploymentService service.
type DeploymentServiceClient interface {
	Deploy(context.Context, *v1.DeployRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error)
	// Bootstrap provisions the account-global, non-project-specific
	// resources a provider needs before any deploy can run (for the AWS
	// provider: the S3 bucket that holds Pulumi state, and a Pulumi
	// passphrase). It is a one-time-per-account action, re-run only when the
	// bootstrapped resources change. It reuses the DeployEvent stream:
	// progress/log events, then a terminal ResultEvent. Bootstrap carries no
	// outputs on its result.
	Bootstrap(context.Context, *v1.BootstrapRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error)
	// DestroyPreview tears down the single preview environment addressed by
	// DestroyPreviewRequest.environment. It is the inverse of a preview Deploy
	// and reuses the same DeployEvent stream: progress/log events, then a
	// terminal ResultEvent (which carries no outputs). The provider selects
	// exactly the environment named by the Environment block; the CLI never
	// asks it to reverse-engineer how the teardown was invoked. It backs
	// `ocel preview rm`.
	DestroyPreview(context.Context, *v1.DestroyPreviewRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error)
	// DestroyProject tears down an entire production project (ADR 0001): the
	// imperative root stack, every app-deploy stack, and the stateful infra
	// stack, plus the project's R2 assets and root-stack state. Unlike
	// DestroyPreview it names no environment — a project is the unit — and it
	// fans out across both systems (Pulumi/AWS + the imperative edge) rather
	// than selecting one stack. It is best-effort: it continues past a failed
	// step and reports what remains, so a re-run resumes idempotently. It
	// reuses the DeployEvent stream (progress/log, then a terminal
	// ResultEvent), and backs `ocel destroy`. Production-only.
	DestroyProject(context.Context, *v1.DestroyProjectRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error)
	// PlanDestroyProject enumerates, without removing anything, exactly what a
	// DestroyProject would tear down: the project's app-deploy stacks, its
	// infra stack, and whether it has a root stack. The CLI calls it to show
	// the blast radius before asking the operator to type the project name, and
	// to exit cleanly when there is nothing to destroy. Read-only and unary.
	PlanDestroyProject(context.Context, *v1.PlanDestroyProjectRequest) (*v1.PlanDestroyProjectResponse, error)
	// ListEnvironments enumerates the preview environments the provider knows
	// about from its own authoritative state, one entry per environment. It
	// backs `ocel preview ls`.
	ListEnvironments(context.Context, *v1.ListEnvironmentsRequest) (*v1.ListEnvironmentsResponse, error)
	// Preflight reports what the provider's ambient account/profile points at:
	// the class the pointed-at infrastructure is stamped with, and whether that
	// infrastructure exists yet. The CLI calls it before a preview or deploy to
	// refuse fast and locally when the infrastructure is missing or is the
	// wrong class, before anything is provisioned. It is authoritative: the
	// provider enforces the same class match itself.
	Preflight(context.Context, *v1.PreflightRequest) (*v1.PreflightResponse, error)
	// ListPromotions enumerates a production project's promotion history,
	// newest first, each entry marked with whether it is the currently active
	// one. It backs `ocel deployments ls`. Production-only: a project with no
	// root stack (never deployed to production) returns an empty list rather
	// than an error.
	ListPromotions(context.Context, *v1.ListPromotionsRequest) (*v1.ListPromotionsResponse, error)
	// Rollback atomically re-points a production project's active-deployment
	// pointer at a prior Promotion: the immediately previous one when
	// RollbackRequest.to is empty, or a specific one when set. It backs
	// `ocel rollback` / `ocel rollback --to <promotionId>`. Production-only;
	// an unknown promotion id is rejected with a clear error.
	Rollback(context.Context, *v1.RollbackRequest) (*v1.RollbackResponse, error)
	// Prune reclaims old Deployments: every Promotion outside a keep_n-deep
	// window of a production project's promotion history, always pinning the
	// currently active one. For each collected Promotion it destroys the
	// app-deploy stacks its records named, deletes their R2/S3 static-asset
	// and ISR/prerender prefixes, and deletes the store records themselves.
	// It backs `ocel deployments prune`, a standalone command never run
	// inline on deploy. Production-only.
	//
	// Prune streams progress/log events as it destroys each stack (a reclaim
	// can run for minutes), then a terminal ResultEvent - the same DeployEvent
	// contract Deploy/Bootstrap/Destroy speak. The kept-vs-reclaimed summary
	// is delivered as the final progress lines before the result, so it carries
	// no dedicated response message.
	Prune(context.Context, *v1.PruneRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error)
}

// NewDeploymentServiceClient constructs a client for the deployments.v1.DeploymentService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeploymentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeploymentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deploymentServiceMethods := v1.File_deployments_v1_deployments_proto.Services().ByName("DeploymentService").Methods()
	return &deploymentServiceClient{
		deploy: connect.NewClient[v1.DeployRequest, v1.DeployEvent](
			httpClient,
			baseURL+DeploymentServiceDeployProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("Deploy")),
			connect.WithClientOptions(opts...),
		),
		bootstrap: connect.NewClient[v1.BootstrapRequest, v1.DeployEvent](
			httpClient,
			baseURL+DeploymentServiceBootstrapProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("Bootstrap")),
			connect.WithClientOptions(opts...),
		),
		destroyPreview: connect.NewClient[v1.DestroyPreviewRequest, v1.DeployEvent](
			httpClient,
			baseURL+DeploymentServiceDestroyPreviewProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("DestroyPreview")),
			connect.WithClientOptions(opts...),
		),
		destroyProject: connect.NewClient[v1.DestroyProjectRequest, v1.DeployEvent](
			httpClient,
			baseURL+DeploymentServiceDestroyProjectProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("DestroyProject")),
			connect.WithClientOptions(opts...),
		),
		planDestroyProject: connect.NewClient[v1.PlanDestroyProjectRequest, v1.PlanDestroyProjectResponse](
			httpClient,
			baseURL+DeploymentServicePlanDestroyProjectProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("PlanDestroyProject")),
			connect.WithClientOptions(opts...),
		),
		listEnvironments: connect.NewClient[v1.ListEnvironmentsRequest, v1.ListEnvironmentsResponse](
			httpClient,
			baseURL+DeploymentServiceListEnvironmentsProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("ListEnvironments")),
			connect.WithClientOptions(opts...),
		),
		preflight: connect.NewClient[v1.PreflightRequest, v1.PreflightResponse](
			httpClient,
			baseURL+DeploymentServicePreflightProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("Preflight")),
			connect.WithClientOptions(opts...),
		),
		listPromotions: connect.NewClient[v1.ListPromotionsRequest, v1.ListPromotionsResponse](
			httpClient,
			baseURL+DeploymentServiceListPromotionsProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("ListPromotions")),
			connect.WithClientOptions(opts...),
		),
		rollback: connect.NewClient[v1.RollbackRequest, v1.RollbackResponse](
			httpClient,
			baseURL+DeploymentServiceRollbackProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("Rollback")),
			connect.WithClientOptions(opts...),
		),
		prune: connect.NewClient[v1.PruneRequest, v1.DeployEvent](
			httpClient,
			baseURL+DeploymentServicePruneProcedure,
			connect.WithSchema(deploymentServiceMethods.ByName("Prune")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deploymentServiceClient implements DeploymentServiceClient.
type deploymentServiceClient struct {
	deploy             *connect.Client[v1.DeployRequest, v1.DeployEvent]
	bootstrap          *connect.Client[v1.BootstrapRequest, v1.DeployEvent]
	destroyPreview     *connect.Client[v1.DestroyPreviewRequest, v1.DeployEvent]
	destroyProject     *connect.Client[v1.DestroyProjectRequest, v1.DeployEvent]
	planDestroyProject *connect.Client[v1.PlanDestroyProjectRequest, v1.PlanDestroyProjectResponse]
	listEnvironments   *connect.Client[v1.ListEnvironmentsRequest, v1.ListEnvironmentsResponse]
	preflight          *connect.Client[v1.PreflightRequest, v1.PreflightResponse]
	listPromotions     *connect.Client[v1.ListPromotionsRequest, v1.ListPromotionsResponse]
	rollback           *connect.Client[v1.RollbackRequest, v1.RollbackResponse]
	prune              *connect.Client[v1.PruneRequest, v1.DeployEvent]
}

// Deploy calls deployments.v1.DeploymentService.Deploy.
func (c *deploymentServiceClient) Deploy(ctx context.Context, req *v1.DeployRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error) {
	return c.deploy.CallServerStream(ctx, connect.NewRequest(req))
}

// Bootstrap calls deployments.v1.DeploymentService.Bootstrap.
func (c *deploymentServiceClient) Bootstrap(ctx context.Context, req *v1.BootstrapRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error) {
	return c.bootstrap.CallServerStream(ctx, connect.NewRequest(req))
}

// DestroyPreview calls deployments.v1.DeploymentService.DestroyPreview.
func (c *deploymentServiceClient) DestroyPreview(ctx context.Context, req *v1.DestroyPreviewRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error) {
	return c.destroyPreview.CallServerStream(ctx, connect.NewRequest(req))
}

// DestroyProject calls deployments.v1.DeploymentService.DestroyProject.
func (c *deploymentServiceClient) DestroyProject(ctx context.Context, req *v1.DestroyProjectRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error) {
	return c.destroyProject.CallServerStream(ctx, connect.NewRequest(req))
}

// PlanDestroyProject calls deployments.v1.DeploymentService.PlanDestroyProject.
func (c *deploymentServiceClient) PlanDestroyProject(ctx context.Context, req *v1.PlanDestroyProjectRequest) (*v1.PlanDestroyProjectResponse, error) {
	response, err := c.planDestroyProject.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListEnvironments calls deployments.v1.DeploymentService.ListEnvironments.
func (c *deploymentServiceClient) ListEnvironments(ctx context.Context, req *v1.ListEnvironmentsRequest) (*v1.ListEnvironmentsResponse, error) {
	response, err := c.listEnvironments.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Preflight calls deployments.v1.DeploymentService.Preflight.
func (c *deploymentServiceClient) Preflight(ctx context.Context, req *v1.PreflightRequest) (*v1.PreflightResponse, error) {
	response, err := c.preflight.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListPromotions calls deployments.v1.DeploymentService.ListPromotions.
func (c *deploymentServiceClient) ListPromotions(ctx context.Context, req *v1.ListPromotionsRequest) (*v1.ListPromotionsResponse, error) {
	response, err := c.listPromotions.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Rollback calls deployments.v1.DeploymentService.Rollback.
func (c *deploymentServiceClient) Rollback(ctx context.Context, req *v1.RollbackRequest) (*v1.RollbackResponse, error) {
	response, err := c.rollback.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Prune calls deployments.v1.DeploymentService.Prune.
func (c *deploymentServiceClient) Prune(ctx context.Context, req *v1.PruneRequest) (*connect.ServerStreamForClient[v1.DeployEvent], error) {
	return c.prune.CallServerStream(ctx, connect.NewRequest(req))
}

// DeploymentServiceHandler is an implementation of the deployments.v1.DeploymentService service.
type DeploymentServiceHandler interface {
	Deploy(context.Context, *v1.DeployRequest, *connect.ServerStream[v1.DeployEvent]) error
	// Bootstrap provisions the account-global, non-project-specific
	// resources a provider needs before any deploy can run (for the AWS
	// provider: the S3 bucket that holds Pulumi state, and a Pulumi
	// passphrase). It is a one-time-per-account action, re-run only when the
	// bootstrapped resources change. It reuses the DeployEvent stream:
	// progress/log events, then a terminal ResultEvent. Bootstrap carries no
	// outputs on its result.
	Bootstrap(context.Context, *v1.BootstrapRequest, *connect.ServerStream[v1.DeployEvent]) error
	// DestroyPreview tears down the single preview environment addressed by
	// DestroyPreviewRequest.environment. It is the inverse of a preview Deploy
	// and reuses the same DeployEvent stream: progress/log events, then a
	// terminal ResultEvent (which carries no outputs). The provider selects
	// exactly the environment named by the Environment block; the CLI never
	// asks it to reverse-engineer how the teardown was invoked. It backs
	// `ocel preview rm`.
	DestroyPreview(context.Context, *v1.DestroyPreviewRequest, *connect.ServerStream[v1.DeployEvent]) error
	// DestroyProject tears down an entire production project (ADR 0001): the
	// imperative root stack, every app-deploy stack, and the stateful infra
	// stack, plus the project's R2 assets and root-stack state. Unlike
	// DestroyPreview it names no environment — a project is the unit — and it
	// fans out across both systems (Pulumi/AWS + the imperative edge) rather
	// than selecting one stack. It is best-effort: it continues past a failed
	// step and reports what remains, so a re-run resumes idempotently. It
	// reuses the DeployEvent stream (progress/log, then a terminal
	// ResultEvent), and backs `ocel destroy`. Production-only.
	DestroyProject(context.Context, *v1.DestroyProjectRequest, *connect.ServerStream[v1.DeployEvent]) error
	// PlanDestroyProject enumerates, without removing anything, exactly what a
	// DestroyProject would tear down: the project's app-deploy stacks, its
	// infra stack, and whether it has a root stack. The CLI calls it to show
	// the blast radius before asking the operator to type the project name, and
	// to exit cleanly when there is nothing to destroy. Read-only and unary.
	PlanDestroyProject(context.Context, *v1.PlanDestroyProjectRequest) (*v1.PlanDestroyProjectResponse, error)
	// ListEnvironments enumerates the preview environments the provider knows
	// about from its own authoritative state, one entry per environment. It
	// backs `ocel preview ls`.
	ListEnvironments(context.Context, *v1.ListEnvironmentsRequest) (*v1.ListEnvironmentsResponse, error)
	// Preflight reports what the provider's ambient account/profile points at:
	// the class the pointed-at infrastructure is stamped with, and whether that
	// infrastructure exists yet. The CLI calls it before a preview or deploy to
	// refuse fast and locally when the infrastructure is missing or is the
	// wrong class, before anything is provisioned. It is authoritative: the
	// provider enforces the same class match itself.
	Preflight(context.Context, *v1.PreflightRequest) (*v1.PreflightResponse, error)
	// ListPromotions enumerates a production project's promotion history,
	// newest first, each entry marked with whether it is the currently active
	// one. It backs `ocel deployments ls`. Production-only: a project with no
	// root stack (never deployed to production) returns an empty list rather
	// than an error.
	ListPromotions(context.Context, *v1.ListPromotionsRequest) (*v1.ListPromotionsResponse, error)
	// Rollback atomically re-points a production project's active-deployment
	// pointer at a prior Promotion: the immediately previous one when
	// RollbackRequest.to is empty, or a specific one when set. It backs
	// `ocel rollback` / `ocel rollback --to <promotionId>`. Production-only;
	// an unknown promotion id is rejected with a clear error.
	Rollback(context.Context, *v1.RollbackRequest) (*v1.RollbackResponse, error)
	// Prune reclaims old Deployments: every Promotion outside a keep_n-deep
	// window of a production project's promotion history, always pinning the
	// currently active one. For each collected Promotion it destroys the
	// app-deploy stacks its records named, deletes their R2/S3 static-asset
	// and ISR/prerender prefixes, and deletes the store records themselves.
	// It backs `ocel deployments prune`, a standalone command never run
	// inline on deploy. Production-only.
	//
	// Prune streams progress/log events as it destroys each stack (a reclaim
	// can run for minutes), then a terminal ResultEvent - the same DeployEvent
	// contract Deploy/Bootstrap/Destroy speak. The kept-vs-reclaimed summary
	// is delivered as the final progress lines before the result, so it carries
	// no dedicated response message.
	Prune(context.Context, *v1.PruneRequest, *connect.ServerStream[v1.DeployEvent]) error
}

// NewDeploymentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeploymentServiceHandler(svc DeploymentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deploymentServiceMethods := v1.File_deployments_v1_deployments_proto.Services().ByName("DeploymentService").Methods()
	deploymentServiceDeployHandler := connect.NewServerStreamHandlerSimple(
		DeploymentServiceDeployProcedure,
		svc.Deploy,
		connect.WithSchema(deploymentServiceMethods.ByName("Deploy")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServiceBootstrapHandler := connect.NewServerStreamHandlerSimple(
		DeploymentServiceBootstrapProcedure,
		svc.Bootstrap,
		connect.WithSchema(deploymentServiceMethods.ByName("Bootstrap")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServiceDestroyPreviewHandler := connect.NewServerStreamHandlerSimple(
		DeploymentServiceDestroyPreviewProcedure,
		svc.DestroyPreview,
		connect.WithSchema(deploymentServiceMethods.ByName("DestroyPreview")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServiceDestroyProjectHandler := connect.NewServerStreamHandlerSimple(
		DeploymentServiceDestroyProjectProcedure,
		svc.DestroyProject,
		connect.WithSchema(deploymentServiceMethods.ByName("DestroyProject")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServicePlanDestroyProjectHandler := connect.NewUnaryHandlerSimple(
		DeploymentServicePlanDestroyProjectProcedure,
		svc.PlanDestroyProject,
		connect.WithSchema(deploymentServiceMethods.ByName("PlanDestroyProject")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServiceListEnvironmentsHandler := connect.NewUnaryHandlerSimple(
		DeploymentServiceListEnvironmentsProcedure,
		svc.ListEnvironments,
		connect.WithSchema(deploymentServiceMethods.ByName("ListEnvironments")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServicePreflightHandler := connect.NewUnaryHandlerSimple(
		DeploymentServicePreflightProcedure,
		svc.Preflight,
		connect.WithSchema(deploymentServiceMethods.ByName("Preflight")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServiceListPromotionsHandler := connect.NewUnaryHandlerSimple(
		DeploymentServiceListPromotionsProcedure,
		svc.ListPromotions,
		connect.WithSchema(deploymentServiceMethods.ByName("ListPromotions")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServiceRollbackHandler := connect.NewUnaryHandlerSimple(
		DeploymentServiceRollbackProcedure,
		svc.Rollback,
		connect.WithSchema(deploymentServiceMethods.ByName("Rollback")),
		connect.WithHandlerOptions(opts...),
	)
	deploymentServicePruneHandler := connect.NewServerStreamHandlerSimple(
		DeploymentServicePruneProcedure,
		svc.Prune,
		connect.WithSchema(deploymentServiceMethods.ByName("Prune")),
		connect.WithHandlerOptions(opts...),
	)
	return "/deployments.v1.DeploymentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeploymentServiceDeployProcedure:
			deploymentServiceDeployHandler.ServeHTTP(w, r)
		case DeploymentServiceBootstrapProcedure:
			deploymentServiceBootstrapHandler.ServeHTTP(w, r)
		case DeploymentServiceDestroyPreviewProcedure:
			deploymentServiceDestroyPreviewHandler.ServeHTTP(w, r)
		case DeploymentServiceDestroyProjectProcedure:
			deploymentServiceDestroyProjectHandler.ServeHTTP(w, r)
		case DeploymentServicePlanDestroyProjectProcedure:
			deploymentServicePlanDestroyProjectHandler.ServeHTTP(w, r)
		case DeploymentServiceListEnvironmentsProcedure:
			deploymentServiceListEnvironmentsHandler.ServeHTTP(w, r)
		case DeploymentServicePreflightProcedure:
			deploymentServicePreflightHandler.ServeHTTP(w, r)
		case DeploymentServiceListPromotionsProcedure:
			deploymentServiceListPromotionsHandler.ServeHTTP(w, r)
		case DeploymentServiceRollbackProcedure:
			deploymentServiceRollbackHandler.ServeHTTP(w, r)
		case DeploymentServicePruneProcedure:
			deploymentServicePruneHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeploymentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeploymentServiceHandler struct{}

func (UnimplementedDeploymentServiceHandler) Deploy(context.Context, *v1.DeployRequest, *connect.ServerStream[v1.DeployEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.Deploy is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) Bootstrap(context.Context, *v1.BootstrapRequest, *connect.ServerStream[v1.DeployEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.Bootstrap is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) DestroyPreview(context.Context, *v1.DestroyPreviewRequest, *connect.ServerStream[v1.DeployEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.DestroyPreview is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) DestroyProject(context.Context, *v1.DestroyProjectRequest, *connect.ServerStream[v1.DeployEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.DestroyProject is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) PlanDestroyProject(context.Context, *v1.PlanDestroyProjectRequest) (*v1.PlanDestroyProjectResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.PlanDestroyProject is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) ListEnvironments(context.Context, *v1.ListEnvironmentsRequest) (*v1.ListEnvironmentsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.ListEnvironments is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) Preflight(context.Context, *v1.PreflightRequest) (*v1.PreflightResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.Preflight is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) ListPromotions(context.Context, *v1.ListPromotionsRequest) (*v1.ListPromotionsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.ListPromotions is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) Rollback(context.Context, *v1.RollbackRequest) (*v1.RollbackResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.Rollback is not implemented"))
}

func (UnimplementedDeploymentServiceHandler) Prune(context.Context, *v1.PruneRequest, *connect.ServerStream[v1.DeployEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("deployments.v1.DeploymentService.Prune is not implemented"))
}
