name: Rust

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "crates/**"
      - ".github/workflows/rust.yml"
  workflow_dispatch:

concurrency:
  group: rust-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust:
    name: rust
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: crates
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: crates

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

      - name: cargo test
        run: cargo test --all-features
